import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getIndicatorLibraryPage = (params) => request.get('/api/indicator/page', { params })
export const addIndicatorLibrary = (data) => request.post('/api/indicator', data)
export const updateIndicatorLibrary = (data) => request.put('/api/indicator', data)
export const deleteIndicatorLibrary = (id) => request.delete(`/api/indicator/${id}`)
export const activateIndicatorLibrary = (id) => request.put(`/api/indicator/activate/${id}`)
export const finishIndicatorLibrary = (id) => request.put(`/api/indicator/finish/${id}`)
export const getDisclosureTemplatePage = (params) => request.get('/api/template/page', { params })
export const addDisclosureTemplate = (data) => request.post('/api/template', data)
export const updateDisclosureTemplate = (data) => request.put('/api/template', data)
export const deleteDisclosureTemplate = (id) => request.delete(`/api/template/${id}`)
export const activateDisclosureTemplate = (id) => request.put(`/api/template/activate/${id}`)
export const finishDisclosureTemplate = (id) => request.put(`/api/template/finish/${id}`)
export const getReportingPeriodPage = (params) => request.get('/api/period/page', { params })
export const addReportingPeriod = (data) => request.post('/api/period', data)
export const updateReportingPeriod = (data) => request.put('/api/period', data)
export const deleteReportingPeriod = (id) => request.delete(`/api/period/${id}`)
export const submitReportingPeriod = (id) => request.put(`/api/period/submit/${id}`)
export const approveReportingPeriod = (id) => request.put(`/api/period/approve/${id}`)
export const getCompanySubmissionPage = (params) => request.get('/api/submission/page', { params })
export const addCompanySubmission = (data) => request.post('/api/submission', data)
export const updateCompanySubmission = (data) => request.put('/api/submission', data)
export const deleteCompanySubmission = (id) => request.delete(`/api/submission/${id}`)
export const submitCompanySubmission = (id) => request.put(`/api/submission/submit/${id}`)
export const approveCompanySubmission = (id) => request.put(`/api/submission/approve/${id}`)
export const getIndicatorDataPage = (params) => request.get('/api/data/page', { params })
export const addIndicatorData = (data) => request.post('/api/data', data)
export const updateIndicatorData = (data) => request.put('/api/data', data)
export const deleteIndicatorData = (id) => request.delete(`/api/data/${id}`)
export const submitIndicatorData = (id) => request.put(`/api/data/submit/${id}`)
export const approveIndicatorData = (id) => request.put(`/api/data/approve/${id}`)
export const getEvidenceFilePage = (params) => request.get('/api/evidence/page', { params })
export const addEvidenceFile = (data) => request.post('/api/evidence', data)
export const updateEvidenceFile = (data) => request.put('/api/evidence', data)
export const deleteEvidenceFile = (id) => request.delete(`/api/evidence/${id}`)
export const submitEvidenceFile = (id) => request.put(`/api/evidence/submit/${id}`)
export const approveEvidenceFile = (id) => request.put(`/api/evidence/approve/${id}`)
export const getReviewTaskPage = (params) => request.get('/api/review/page', { params })
export const addReviewTask = (data) => request.post('/api/review', data)
export const updateReviewTask = (data) => request.put('/api/review', data)
export const deleteReviewTask = (id) => request.delete(`/api/review/${id}`)
export const submitReviewTask = (id) => request.put(`/api/review/submit/${id}`)
export const approveReviewTask = (id) => request.put(`/api/review/approve/${id}`)
export const getScoreModelPage = (params) => request.get('/api/model/page', { params })
export const addScoreModel = (data) => request.post('/api/model', data)
export const updateScoreModel = (data) => request.put('/api/model', data)
export const deleteScoreModel = (id) => request.delete(`/api/model/${id}`)
export const activateScoreModel = (id) => request.put(`/api/model/activate/${id}`)
export const finishScoreModel = (id) => request.put(`/api/model/finish/${id}`)
export const getEsgScorePage = (params) => request.get('/api/score/page', { params })
export const addEsgScore = (data) => request.post('/api/score', data)
export const updateEsgScore = (data) => request.put('/api/score', data)
export const deleteEsgScore = (id) => request.delete(`/api/score/${id}`)
export const activateEsgScore = (id) => request.put(`/api/score/activate/${id}`)
export const finishEsgScore = (id) => request.put(`/api/score/finish/${id}`)
export const getImprovementTaskPage = (params) => request.get('/api/improvement/page', { params })
export const addImprovementTask = (data) => request.post('/api/improvement', data)
export const updateImprovementTask = (data) => request.put('/api/improvement', data)
export const deleteImprovementTask = (id) => request.delete(`/api/improvement/${id}`)
export const processImprovementTask = (id) => request.put(`/api/improvement/process/${id}`)
export const finishImprovementTask = (id) => request.put(`/api/improvement/finish/${id}`)
export const getStakeholderFeedbackPage = (params) => request.get('/api/feedback/page', { params })
export const addStakeholderFeedback = (data) => request.post('/api/feedback', data)
export const updateStakeholderFeedback = (data) => request.put('/api/feedback', data)
export const deleteStakeholderFeedback = (id) => request.delete(`/api/feedback/${id}`)
export const processStakeholderFeedback = (id) => request.put(`/api/feedback/process/${id}`)
export const finishStakeholderFeedback = (id) => request.put(`/api/feedback/finish/${id}`)
export const getReportExportPage = (params) => request.get('/api/export/page', { params })
export const addReportExport = (data) => request.post('/api/export', data)
export const updateReportExport = (data) => request.put('/api/export', data)
export const deleteReportExport = (id) => request.delete(`/api/export/${id}`)
export const submitReportExport = (id) => request.put(`/api/export/submit/${id}`)
export const approveReportExport = (id) => request.put(`/api/export/approve/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
