import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getExamPlanPage = (params) => request.get('/api/plan/page', { params })
export const addExamPlan = (data) => request.post('/api/plan', data)
export const updateExamPlan = (data) => request.put('/api/plan', data)
export const deleteExamPlan = (id) => request.delete(`/api/plan/${id}`)
export const activateExamPlan = (id) => request.put(`/api/plan/activate/${id}`)
export const finishExamPlan = (id) => request.put(`/api/plan/finish/${id}`)
export const getInvigilatorProfilePage = (params) => request.get('/api/invigilator/page', { params })
export const addInvigilatorProfile = (data) => request.post('/api/invigilator', data)
export const updateInvigilatorProfile = (data) => request.put('/api/invigilator', data)
export const deleteInvigilatorProfile = (id) => request.delete(`/api/invigilator/${id}`)
export const activateInvigilatorProfile = (id) => request.put(`/api/invigilator/activate/${id}`)
export const finishInvigilatorProfile = (id) => request.put(`/api/invigilator/finish/${id}`)
export const getCandidateProfilePage = (params) => request.get('/api/candidate/page', { params })
export const addCandidateProfile = (data) => request.post('/api/candidate', data)
export const updateCandidateProfile = (data) => request.put('/api/candidate', data)
export const deleteCandidateProfile = (id) => request.delete(`/api/candidate/${id}`)
export const processCandidateProfile = (id) => request.put(`/api/candidate/process/${id}`)
export const finishCandidateProfile = (id) => request.put(`/api/candidate/finish/${id}`)
export const getExamSessionPage = (params) => request.get('/api/session/page', { params })
export const addExamSession = (data) => request.post('/api/session', data)
export const updateExamSession = (data) => request.put('/api/session', data)
export const deleteExamSession = (id) => request.delete(`/api/session/${id}`)
export const submitExamSession = (id) => request.put(`/api/session/submit/${id}`)
export const approveExamSession = (id) => request.put(`/api/session/approve/${id}`)
export const getSuspiciousBehaviorPage = (params) => request.get('/api/behavior/page', { params })
export const addSuspiciousBehavior = (data) => request.post('/api/behavior', data)
export const updateSuspiciousBehavior = (data) => request.put('/api/behavior', data)
export const deleteSuspiciousBehavior = (id) => request.delete(`/api/behavior/${id}`)
export const submitSuspiciousBehavior = (id) => request.put(`/api/behavior/submit/${id}`)
export const approveSuspiciousBehavior = (id) => request.put(`/api/behavior/approve/${id}`)
export const getEvidenceRecordPage = (params) => request.get('/api/evidence/page', { params })
export const addEvidenceRecord = (data) => request.post('/api/evidence', data)
export const updateEvidenceRecord = (data) => request.put('/api/evidence', data)
export const deleteEvidenceRecord = (id) => request.delete(`/api/evidence/${id}`)
export const submitEvidenceRecord = (id) => request.put(`/api/evidence/submit/${id}`)
export const approveEvidenceRecord = (id) => request.put(`/api/evidence/approve/${id}`)
export const getReviewTaskPage = (params) => request.get('/api/task/page', { params })
export const addReviewTask = (data) => request.post('/api/task', data)
export const updateReviewTask = (data) => request.put('/api/task', data)
export const deleteReviewTask = (id) => request.delete(`/api/task/${id}`)
export const processReviewTask = (id) => request.put(`/api/task/process/${id}`)
export const finishReviewTask = (id) => request.put(`/api/task/finish/${id}`)
export const getReviewDecisionPage = (params) => request.get('/api/decision/page', { params })
export const addReviewDecision = (data) => request.post('/api/decision', data)
export const updateReviewDecision = (data) => request.put('/api/decision', data)
export const deleteReviewDecision = (id) => request.delete(`/api/decision/${id}`)
export const activateReviewDecision = (id) => request.put(`/api/decision/activate/${id}`)
export const finishReviewDecision = (id) => request.put(`/api/decision/finish/${id}`)
export const getWarningRulePage = (params) => request.get('/api/rule/page', { params })
export const addWarningRule = (data) => request.post('/api/rule', data)
export const updateWarningRule = (data) => request.put('/api/rule', data)
export const deleteWarningRule = (id) => request.delete(`/api/rule/${id}`)
export const activateWarningRule = (id) => request.put(`/api/rule/activate/${id}`)
export const finishWarningRule = (id) => request.put(`/api/rule/finish/${id}`)
export const getDeviceMonitorPage = (params) => request.get('/api/device/page', { params })
export const addDeviceMonitor = (data) => request.post('/api/device', data)
export const updateDeviceMonitor = (data) => request.put('/api/device', data)
export const deleteDeviceMonitor = (id) => request.delete(`/api/device/${id}`)
export const activateDeviceMonitor = (id) => request.put(`/api/device/activate/${id}`)
export const finishDeviceMonitor = (id) => request.put(`/api/device/finish/${id}`)
export const getViolationAppealPage = (params) => request.get('/api/appeal/page', { params })
export const addViolationAppeal = (data) => request.post('/api/appeal', data)
export const updateViolationAppeal = (data) => request.put('/api/appeal', data)
export const deleteViolationAppeal = (id) => request.delete(`/api/appeal/${id}`)
export const processViolationAppeal = (id) => request.put(`/api/appeal/process/${id}`)
export const finishViolationAppeal = (id) => request.put(`/api/appeal/finish/${id}`)
export const getAlertNotificationPage = (params) => request.get('/api/alert/page', { params })
export const addAlertNotification = (data) => request.post('/api/alert', data)
export const updateAlertNotification = (data) => request.put('/api/alert', data)
export const deleteAlertNotification = (id) => request.delete(`/api/alert/${id}`)
export const processAlertNotification = (id) => request.put(`/api/alert/process/${id}`)
export const finishAlertNotification = (id) => request.put(`/api/alert/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)


