import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getMerchantStorePage = (params) => request.get('/api/merchant/page', { params })
export const addMerchantStore = (data) => request.post('/api/merchant', data)
export const updateMerchantStore = (data) => request.put('/api/merchant', data)
export const deleteMerchantStore = (id) => request.delete(`/api/merchant/${id}`)
export const approveMerchantStore = (id) => request.put(`/api/merchant/approve/${id}`)
export const suspendMerchantStore = (id) => request.put(`/api/merchant/suspend/${id}`)
export const getCustomerProfilePage = (params) => request.get('/api/customer/page', { params })
export const addCustomerProfile = (data) => request.post('/api/customer', data)
export const updateCustomerProfile = (data) => request.put('/api/customer', data)
export const deleteCustomerProfile = (id) => request.delete(`/api/customer/${id}`)
export const verifyCustomerProfile = (id) => request.put(`/api/customer/verify/${id}`)
export const freezeCustomerProfile = (id) => request.put(`/api/customer/freeze/${id}`)
export const getProductSkuPage = (params) => request.get('/api/sku/page', { params })
export const addProductSku = (data) => request.post('/api/sku', data)
export const updateProductSku = (data) => request.put('/api/sku', data)
export const deleteProductSku = (id) => request.delete(`/api/sku/${id}`)
export const publishProductSku = (id) => request.put(`/api/sku/publish/${id}`)
export const disableProductSku = (id) => request.put(`/api/sku/disable/${id}`)
export const getCrossBorderOrderPage = (params) => request.get('/api/order/page', { params })
export const addCrossBorderOrder = (data) => request.post('/api/order', data)
export const updateCrossBorderOrder = (data) => request.put('/api/order', data)
export const deleteCrossBorderOrder = (id) => request.delete(`/api/order/${id}`)
export const submitCrossBorderOrder = (id) => request.put(`/api/order/submit/${id}`)
export const shipCrossBorderOrder = (id) => request.put(`/api/order/ship/${id}`)
export const closeCrossBorderOrder = (id) => request.put(`/api/order/close/${id}`)
export const getClearanceDeclarationPage = (params) => request.get('/api/declaration/page', { params })
export const addClearanceDeclaration = (data) => request.post('/api/declaration', data)
export const updateClearanceDeclaration = (data) => request.put('/api/declaration', data)
export const deleteClearanceDeclaration = (id) => request.delete(`/api/declaration/${id}`)
export const submitClearanceDeclaration = (id) => request.put(`/api/declaration/submit/${id}`)
export const releaseClearanceDeclaration = (id) => request.put(`/api/declaration/release/${id}`)
export const rejectClearanceDeclaration = (id) => request.put(`/api/declaration/reject/${id}`)
export const getCustomsDocumentPage = (params) => request.get('/api/document/page', { params })
export const addCustomsDocument = (data) => request.post('/api/document', data)
export const updateCustomsDocument = (data) => request.put('/api/document', data)
export const deleteCustomsDocument = (id) => request.delete(`/api/document/${id}`)
export const approveCustomsDocument = (id) => request.put(`/api/document/approve/${id}`)
export const rejectCustomsDocument = (id) => request.put(`/api/document/reject/${id}`)
export const getTaxFeeRecordPage = (params) => request.get('/api/tax/page', { params })
export const addTaxFeeRecord = (data) => request.post('/api/tax', data)
export const updateTaxFeeRecord = (data) => request.put('/api/tax', data)
export const deleteTaxFeeRecord = (id) => request.delete(`/api/tax/${id}`)
export const confirmTaxFeeRecord = (id) => request.put(`/api/tax/confirm/${id}`)
export const overdueTaxFeeRecord = (id) => request.put(`/api/tax/overdue/${id}`)
export const getExchangeRatePage = (params) => request.get('/api/rate/page', { params })
export const addExchangeRate = (data) => request.post('/api/rate', data)
export const updateExchangeRate = (data) => request.put('/api/rate', data)
export const deleteExchangeRate = (id) => request.delete(`/api/rate/${id}`)
export const publishExchangeRate = (id) => request.put(`/api/rate/publish/${id}`)
export const expireExchangeRate = (id) => request.put(`/api/rate/expire/${id}`)
export const getSettlementBillPage = (params) => request.get('/api/settlement/page', { params })
export const addSettlementBill = (data) => request.post('/api/settlement', data)
export const updateSettlementBill = (data) => request.put('/api/settlement', data)
export const deleteSettlementBill = (id) => request.delete(`/api/settlement/${id}`)
export const calculateSettlementBill = (id) => request.put(`/api/settlement/calculate/${id}`)
export const settleSettlementBill = (id) => request.put(`/api/settlement/settle/${id}`)
export const getPaymentRecordPage = (params) => request.get('/api/payment/page', { params })
export const addPaymentRecord = (data) => request.post('/api/payment', data)
export const updatePaymentRecord = (data) => request.put('/api/payment', data)
export const deletePaymentRecord = (id) => request.delete(`/api/payment/${id}`)
export const confirmPaymentRecord = (id) => request.put(`/api/payment/confirm/${id}`)
export const failPaymentRecord = (id) => request.put(`/api/payment/fail/${id}`)
export const getLogisticsTrackPage = (params) => request.get('/api/logistics/page', { params })
export const addLogisticsTrack = (data) => request.post('/api/logistics', data)
export const updateLogisticsTrack = (data) => request.put('/api/logistics', data)
export const deleteLogisticsTrack = (id) => request.delete(`/api/logistics/${id}`)
export const departLogisticsTrack = (id) => request.put(`/api/logistics/depart/${id}`)
export const arriveLogisticsTrack = (id) => request.put(`/api/logistics/arrive/${id}`)
export const signLogisticsTrack = (id) => request.put(`/api/logistics/sign/${id}`)
export const getReconciliationTaskPage = (params) => request.get('/api/reconciliation/page', { params })
export const addReconciliationTask = (data) => request.post('/api/reconciliation', data)
export const updateReconciliationTask = (data) => request.put('/api/reconciliation', data)
export const deleteReconciliationTask = (id) => request.delete(`/api/reconciliation/${id}`)
export const executeReconciliationTask = (id) => request.put(`/api/reconciliation/execute/${id}`)
export const passReconciliationTask = (id) => request.put(`/api/reconciliation/pass/${id}`)
export const exceptionReconciliationTask = (id) => request.put(`/api/reconciliation/exception/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
