import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getCompanyZonePage = (params) => request.get('/api/zone/page', { params })
export const addCompanyZone = (data) => request.post('/api/zone', data)
export const updateCompanyZone = (data) => request.put('/api/zone', data)
export const deleteCompanyZone = (id) => request.delete(`/api/zone/${id}`)
export const processCompanyZone = (id) => request.put(`/api/zone/process/${id}`)
export const finishCompanyZone = (id) => request.put(`/api/zone/finish/${id}`)

export const getHostEmployeePage = (params) => request.get('/api/host/page', { params })
export const addHostEmployee = (data) => request.post('/api/host', data)
export const updateHostEmployee = (data) => request.put('/api/host', data)
export const deleteHostEmployee = (id) => request.delete(`/api/host/${id}`)
export const processHostEmployee = (id) => request.put(`/api/host/process/${id}`)
export const finishHostEmployee = (id) => request.put(`/api/host/finish/${id}`)

export const getVisitorProfilePage = (params) => request.get('/api/visitor/page', { params })
export const addVisitorProfile = (data) => request.post('/api/visitor', data)
export const updateVisitorProfile = (data) => request.put('/api/visitor', data)
export const deleteVisitorProfile = (id) => request.delete(`/api/visitor/${id}`)
export const processVisitorProfile = (id) => request.put(`/api/visitor/process/${id}`)
export const finishVisitorProfile = (id) => request.put(`/api/visitor/finish/${id}`)

export const getVisitAppointmentPage = (params) => request.get('/api/appointment/page', { params })
export const addVisitAppointment = (data) => request.post('/api/appointment', data)
export const updateVisitAppointment = (data) => request.put('/api/appointment', data)
export const deleteVisitAppointment = (id) => request.delete(`/api/appointment/${id}`)
export const processVisitAppointment = (id) => request.put(`/api/appointment/process/${id}`)
export const finishVisitAppointment = (id) => request.put(`/api/appointment/finish/${id}`)

export const getApprovalRecordPage = (params) => request.get('/api/approval/page', { params })
export const addApprovalRecord = (data) => request.post('/api/approval', data)
export const updateApprovalRecord = (data) => request.put('/api/approval', data)
export const deleteApprovalRecord = (id) => request.delete(`/api/approval/${id}`)
export const processApprovalRecord = (id) => request.put(`/api/approval/process/${id}`)
export const finishApprovalRecord = (id) => request.put(`/api/approval/finish/${id}`)

export const getQrPassPage = (params) => request.get('/api/qrcode/page', { params })
export const addQrPass = (data) => request.post('/api/qrcode', data)
export const updateQrPass = (data) => request.put('/api/qrcode', data)
export const deleteQrPass = (id) => request.delete(`/api/qrcode/${id}`)
export const processQrPass = (id) => request.put(`/api/qrcode/process/${id}`)
export const finishQrPass = (id) => request.put(`/api/qrcode/finish/${id}`)

export const getGateDevicePage = (params) => request.get('/api/gate/page', { params })
export const addGateDevice = (data) => request.post('/api/gate', data)
export const updateGateDevice = (data) => request.put('/api/gate', data)
export const deleteGateDevice = (id) => request.delete(`/api/gate/${id}`)
export const processGateDevice = (id) => request.put(`/api/gate/process/${id}`)
export const finishGateDevice = (id) => request.put(`/api/gate/finish/${id}`)

export const getAccessLinkagePage = (params) => request.get('/api/linkage/page', { params })
export const addAccessLinkage = (data) => request.post('/api/linkage', data)
export const updateAccessLinkage = (data) => request.put('/api/linkage', data)
export const deleteAccessLinkage = (id) => request.delete(`/api/linkage/${id}`)
export const processAccessLinkage = (id) => request.put(`/api/linkage/process/${id}`)
export const finishAccessLinkage = (id) => request.put(`/api/linkage/finish/${id}`)

export const getEntryRecordPage = (params) => request.get('/api/entry/page', { params })
export const addEntryRecord = (data) => request.post('/api/entry', data)
export const updateEntryRecord = (data) => request.put('/api/entry', data)
export const deleteEntryRecord = (id) => request.delete(`/api/entry/${id}`)
export const processEntryRecord = (id) => request.put(`/api/entry/process/${id}`)
export const finishEntryRecord = (id) => request.put(`/api/entry/finish/${id}`)

export const getTrailRecordPage = (params) => request.get('/api/trail/page', { params })
export const addTrailRecord = (data) => request.post('/api/trail', data)
export const updateTrailRecord = (data) => request.put('/api/trail', data)
export const deleteTrailRecord = (id) => request.delete(`/api/trail/${id}`)
export const processTrailRecord = (id) => request.put(`/api/trail/process/${id}`)
export const finishTrailRecord = (id) => request.put(`/api/trail/finish/${id}`)

export const getExceptionAlertPage = (params) => request.get('/api/alert/page', { params })
export const addExceptionAlert = (data) => request.post('/api/alert', data)
export const updateExceptionAlert = (data) => request.put('/api/alert', data)
export const deleteExceptionAlert = (id) => request.delete(`/api/alert/${id}`)
export const processExceptionAlert = (id) => request.put(`/api/alert/process/${id}`)
export const finishExceptionAlert = (id) => request.put(`/api/alert/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
