import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/guidances/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getTopicReleasePage = (params) => request.get('/api/topic/page', { params })
export const addTopicRelease = (data) => request.post('/api/topic', data)
export const updateTopicRelease = (data) => request.put('/api/topic', data)
export const deleteTopicRelease = (id) => request.delete(`/api/topic/${id}`)
export const activateTopicRelease = (id) => request.put(`/api/topic/activate/${id}`)
export const finishTopicRelease = (id) => request.put(`/api/topic/finish/${id}`)
export const getTeacherProfilePage = (params) => request.get('/api/teacher/page', { params })
export const addTeacherProfile = (data) => request.post('/api/teacher', data)
export const updateTeacherProfile = (data) => request.put('/api/teacher', data)
export const deleteTeacherProfile = (id) => request.delete(`/api/teacher/${id}`)
export const activateTeacherProfile = (id) => request.put(`/api/teacher/activate/${id}`)
export const finishTeacherProfile = (id) => request.put(`/api/teacher/finish/${id}`)
export const getStudentProfilePage = (params) => request.get('/api/student/page', { params })
export const addStudentProfile = (data) => request.post('/api/student', data)
export const updateStudentProfile = (data) => request.put('/api/student', data)
export const deleteStudentProfile = (id) => request.delete(`/api/student/${id}`)
export const processStudentProfile = (id) => request.put(`/api/student/process/${id}`)
export const finishStudentProfile = (id) => request.put(`/api/student/finish/${id}`)
export const getTopicApplicationPage = (params) => request.get('/api/application/page', { params })
export const addTopicApplication = (data) => request.post('/api/application', data)
export const updateTopicApplication = (data) => request.put('/api/application', data)
export const deleteTopicApplication = (id) => request.delete(`/api/application/${id}`)
export const submitTopicApplication = (id) => request.put(`/api/application/submit/${id}`)
export const approveTopicApplication = (id) => request.put(`/api/application/approve/${id}`)
export const getSelectionReviewPage = (params) => request.get('/api/review/page', { params })
export const addSelectionReview = (data) => request.post('/api/review', data)
export const updateSelectionReview = (data) => request.put('/api/review', data)
export const deleteSelectionReview = (id) => request.delete(`/api/review/${id}`)
export const submitSelectionReview = (id) => request.put(`/api/review/submit/${id}`)
export const approveSelectionReview = (id) => request.put(`/api/review/approve/${id}`)
export const getMutualSelectionPage = (params) => request.get('/api/selection/page', { params })
export const addMutualSelection = (data) => request.post('/api/selection', data)
export const updateMutualSelection = (data) => request.put('/api/selection', data)
export const deleteMutualSelection = (id) => request.delete(`/api/selection/${id}`)
export const submitMutualSelection = (id) => request.put(`/api/selection/submit/${id}`)
export const approveMutualSelection = (id) => request.put(`/api/selection/approve/${id}`)
export const getTaskBookPage = (params) => request.get('/api/taskbook/page', { params })
export const addTaskBook = (data) => request.post('/api/taskbook', data)
export const updateTaskBook = (data) => request.put('/api/taskbook', data)
export const deleteTaskBook = (id) => request.delete(`/api/taskbook/${id}`)
export const processTaskBook = (id) => request.put(`/api/taskbook/process/${id}`)
export const finishTaskBook = (id) => request.put(`/api/taskbook/finish/${id}`)
export const getProposalRecordPage = (params) => request.get('/api/proposal/page', { params })
export const addProposalRecord = (data) => request.post('/api/proposal', data)
export const updateProposalRecord = (data) => request.put('/api/proposal', data)
export const deleteProposalRecord = (id) => request.delete(`/api/proposal/${id}`)
export const activateProposalRecord = (id) => request.put(`/api/proposal/activate/${id}`)
export const finishProposalRecord = (id) => request.put(`/api/proposal/finish/${id}`)
export const getOpeningDefensePage = (params) => request.get('/api/defense/page', { params })
export const addOpeningDefense = (data) => request.post('/api/defense', data)
export const updateOpeningDefense = (data) => request.put('/api/defense', data)
export const deleteOpeningDefense = (id) => request.delete(`/api/defense/${id}`)
export const activateOpeningDefense = (id) => request.put(`/api/defense/activate/${id}`)
export const finishOpeningDefense = (id) => request.put(`/api/defense/finish/${id}`)
export const getMidtermCheckPage = (params) => request.get('/api/midterm/page', { params })
export const addMidtermCheck = (data) => request.post('/api/midterm', data)
export const updateMidtermCheck = (data) => request.put('/api/midterm', data)
export const deleteMidtermCheck = (id) => request.delete(`/api/midterm/${id}`)
export const activateMidtermCheck = (id) => request.put(`/api/midterm/activate/${id}`)
export const finishMidtermCheck = (id) => request.put(`/api/midterm/finish/${id}`)
export const getGuidanceMeetingPage = (params) => request.get('/api/guidance/page', { params })
export const addGuidanceMeeting = (data) => request.post('/api/guidance', data)
export const updateGuidanceMeeting = (data) => request.put('/api/guidance', data)
export const deleteGuidanceMeeting = (id) => request.delete(`/api/guidance/${id}`)
export const processGuidanceMeeting = (id) => request.put(`/api/guidance/process/${id}`)
export const finishGuidanceMeeting = (id) => request.put(`/api/guidance/finish/${id}`)
export const getMilestoneNoticePage = (params) => request.get('/api/notice/page', { params })
export const addMilestoneNotice = (data) => request.post('/api/notice', data)
export const updateMilestoneNotice = (data) => request.put('/api/notice', data)
export const deleteMilestoneNotice = (id) => request.delete(`/api/notice/${id}`)
export const processMilestoneNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishMilestoneNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)

