import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getDeviceAssetPage = (params) => request.get('/api/device/page', { params })
export const addDeviceAsset = (data) => request.post('/api/device', data)
export const updateDeviceAsset = (data) => request.put('/api/device', data)
export const deleteDeviceAsset = (id) => request.delete(`/api/device/${id}`)
export const approveDeviceAsset = (id) => request.put(`/api/device/approve/${id}`)
export const blockDeviceAsset = (id) => request.put(`/api/device/block/${id}`)
export const retireDeviceAsset = (id) => request.put(`/api/device/retire/${id}`)
export const getEmployeeAccountPage = (params) => request.get('/api/employee/page', { params })
export const addEmployeeAccount = (data) => request.post('/api/employee', data)
export const updateEmployeeAccount = (data) => request.put('/api/employee', data)
export const deleteEmployeeAccount = (id) => request.delete(`/api/employee/${id}`)
export const enableEmployeeAccount = (id) => request.put(`/api/employee/enable/${id}`)
export const disableEmployeeAccount = (id) => request.put(`/api/employee/disable/${id}`)
export const getIdentityProviderPage = (params) => request.get('/api/idp/page', { params })
export const addIdentityProvider = (data) => request.post('/api/idp', data)
export const updateIdentityProvider = (data) => request.put('/api/idp', data)
export const deleteIdentityProvider = (id) => request.delete(`/api/idp/${id}`)
export const connectIdentityProvider = (id) => request.put(`/api/idp/connect/${id}`)
export const disableIdentityProvider = (id) => request.put(`/api/idp/disable/${id}`)
export const getRiskModelPage = (params) => request.get('/api/risk-model/page', { params })
export const addRiskModel = (data) => request.post('/api/risk-model', data)
export const updateRiskModel = (data) => request.put('/api/risk-model', data)
export const deleteRiskModel = (id) => request.delete(`/api/risk-model/${id}`)
export const publishRiskModel = (id) => request.put(`/api/risk-model/publish/${id}`)
export const archiveRiskModel = (id) => request.put(`/api/risk-model/archive/${id}`)
export const getRiskAssessmentPage = (params) => request.get('/api/assessment/page', { params })
export const addRiskAssessment = (data) => request.post('/api/assessment', data)
export const updateRiskAssessment = (data) => request.put('/api/assessment', data)
export const deleteRiskAssessment = (id) => request.delete(`/api/assessment/${id}`)
export const reviewRiskAssessment = (id) => request.put(`/api/assessment/review/${id}`)
export const clearRiskAssessment = (id) => request.put(`/api/assessment/clear/${id}`)
export const blockRiskAssessment = (id) => request.put(`/api/assessment/block/${id}`)
export const getAccessPolicyPage = (params) => request.get('/api/policy/page', { params })
export const addAccessPolicy = (data) => request.post('/api/policy', data)
export const updateAccessPolicy = (data) => request.put('/api/policy', data)
export const deleteAccessPolicy = (id) => request.delete(`/api/policy/${id}`)
export const enableAccessPolicy = (id) => request.put(`/api/policy/enable/${id}`)
export const disableAccessPolicy = (id) => request.put(`/api/policy/disable/${id}`)
export const getPolicyRulePage = (params) => request.get('/api/rule/page', { params })
export const addPolicyRule = (data) => request.post('/api/rule', data)
export const updatePolicyRule = (data) => request.put('/api/rule', data)
export const deletePolicyRule = (id) => request.delete(`/api/rule/${id}`)
export const getAccessApplicationPage = (params) => request.get('/api/application/page', { params })
export const addAccessApplication = (data) => request.post('/api/application', data)
export const updateAccessApplication = (data) => request.put('/api/application', data)
export const deleteAccessApplication = (id) => request.delete(`/api/application/${id}`)
export const submitAccessApplication = (id) => request.put(`/api/application/submit/${id}`)
export const approveAccessApplication = (id) => request.put(`/api/application/approve/${id}`)
export const rejectAccessApplication = (id) => request.put(`/api/application/reject/${id}`)
export const getAccessSessionPage = (params) => request.get('/api/session/page', { params })
export const addAccessSession = (data) => request.post('/api/session', data)
export const updateAccessSession = (data) => request.put('/api/session', data)
export const deleteAccessSession = (id) => request.delete(`/api/session/${id}`)
export const terminateAccessSession = (id) => request.put(`/api/session/terminate/${id}`)
export const expireAccessSession = (id) => request.put(`/api/session/expire/${id}`)
export const getNetworkSegmentPage = (params) => request.get('/api/segment/page', { params })
export const addNetworkSegment = (data) => request.post('/api/segment', data)
export const updateNetworkSegment = (data) => request.put('/api/segment', data)
export const deleteNetworkSegment = (id) => request.delete(`/api/segment/${id}`)
export const getDeviceCertificatePage = (params) => request.get('/api/certificate/page', { params })
export const addDeviceCertificate = (data) => request.post('/api/certificate', data)
export const updateDeviceCertificate = (data) => request.put('/api/certificate', data)
export const deleteDeviceCertificate = (id) => request.delete(`/api/certificate/${id}`)
export const revokeDeviceCertificate = (id) => request.put(`/api/certificate/revoke/${id}`)
export const renewDeviceCertificate = (id) => request.put(`/api/certificate/renew/${id}`)
export const getAuditEventPage = (params) => request.get('/api/audit-event/page', { params })
export const addAuditEvent = (data) => request.post('/api/audit-event', data)
export const updateAuditEvent = (data) => request.put('/api/audit-event', data)
export const deleteAuditEvent = (id) => request.delete(`/api/audit-event/${id}`)
export const ackAuditEvent = (id) => request.put(`/api/audit-event/ack/${id}`)
export const closeAuditEvent = (id) => request.put(`/api/audit-event/close/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
