import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getServiceItemPage = (params) => request.get('/api/item/page', { params })
export const addServiceItem = (data) => request.post('/api/item', data)
export const updateServiceItem = (data) => request.put('/api/item', data)
export const deleteServiceItem = (id) => request.delete(`/api/item/${id}`)
export const processServiceItem = (id) => request.put(`/api/item/process/${id}`)
export const finishServiceItem = (id) => request.put(`/api/item/finish/${id}`)

export const getWindowProfilePage = (params) => request.get('/api/window/page', { params })
export const addWindowProfile = (data) => request.post('/api/window', data)
export const updateWindowProfile = (data) => request.put('/api/window', data)
export const deleteWindowProfile = (id) => request.delete(`/api/window/${id}`)
export const processWindowProfile = (id) => request.put(`/api/window/process/${id}`)
export const finishWindowProfile = (id) => request.put(`/api/window/finish/${id}`)

export const getClerkRosterPage = (params) => request.get('/api/roster/page', { params })
export const addClerkRoster = (data) => request.post('/api/roster', data)
export const updateClerkRoster = (data) => request.put('/api/roster', data)
export const deleteClerkRoster = (id) => request.delete(`/api/roster/${id}`)
export const processClerkRoster = (id) => request.put(`/api/roster/process/${id}`)
export const finishClerkRoster = (id) => request.put(`/api/roster/finish/${id}`)

export const getAppointmentBookingPage = (params) => request.get('/api/appointment/page', { params })
export const addAppointmentBooking = (data) => request.post('/api/appointment', data)
export const updateAppointmentBooking = (data) => request.put('/api/appointment', data)
export const deleteAppointmentBooking = (id) => request.delete(`/api/appointment/${id}`)
export const processAppointmentBooking = (id) => request.put(`/api/appointment/process/${id}`)
export const finishAppointmentBooking = (id) => request.put(`/api/appointment/finish/${id}`)

export const getQueueCallPage = (params) => request.get('/api/queue/page', { params })
export const addQueueCall = (data) => request.post('/api/queue', data)
export const updateQueueCall = (data) => request.put('/api/queue', data)
export const deleteQueueCall = (id) => request.delete(`/api/queue/${id}`)
export const processQueueCall = (id) => request.put(`/api/queue/process/${id}`)
export const finishQueueCall = (id) => request.put(`/api/queue/finish/${id}`)

export const getMaterialReviewPage = (params) => request.get('/api/review/page', { params })
export const addMaterialReview = (data) => request.post('/api/review', data)
export const updateMaterialReview = (data) => request.put('/api/review', data)
export const deleteMaterialReview = (id) => request.delete(`/api/review/${id}`)
export const processMaterialReview = (id) => request.put(`/api/review/process/${id}`)
export const finishMaterialReview = (id) => request.put(`/api/review/finish/${id}`)

export const getProcessProgressPage = (params) => request.get('/api/progress/page', { params })
export const addProcessProgress = (data) => request.post('/api/progress', data)
export const updateProcessProgress = (data) => request.put('/api/progress', data)
export const deleteProcessProgress = (id) => request.delete(`/api/progress/${id}`)
export const processProcessProgress = (id) => request.put(`/api/progress/process/${id}`)
export const finishProcessProgress = (id) => request.put(`/api/progress/finish/${id}`)

export const getMessageNoticePage = (params) => request.get('/api/notice/page', { params })
export const addMessageNotice = (data) => request.post('/api/notice', data)
export const updateMessageNotice = (data) => request.put('/api/notice', data)
export const deleteMessageNotice = (id) => request.delete(`/api/notice/${id}`)
export const processMessageNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishMessageNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getServiceEvaluationPage = (params) => request.get('/api/evaluation/page', { params })
export const addServiceEvaluation = (data) => request.post('/api/evaluation', data)
export const updateServiceEvaluation = (data) => request.put('/api/evaluation', data)
export const deleteServiceEvaluation = (id) => request.delete(`/api/evaluation/${id}`)
export const processServiceEvaluation = (id) => request.put(`/api/evaluation/process/${id}`)
export const finishServiceEvaluation = (id) => request.put(`/api/evaluation/finish/${id}`)

export const getComplaintHandlingPage = (params) => request.get('/api/complaint/page', { params })
export const addComplaintHandling = (data) => request.post('/api/complaint', data)
export const updateComplaintHandling = (data) => request.put('/api/complaint', data)
export const deleteComplaintHandling = (id) => request.delete(`/api/complaint/${id}`)
export const processComplaintHandling = (id) => request.put(`/api/complaint/process/${id}`)
export const finishComplaintHandling = (id) => request.put(`/api/complaint/finish/${id}`)

export const getPerformanceArchivePage = (params) => request.get('/api/performance/page', { params })
export const addPerformanceArchive = (data) => request.post('/api/performance', data)
export const updatePerformanceArchive = (data) => request.put('/api/performance', data)
export const deletePerformanceArchive = (id) => request.delete(`/api/performance/${id}`)
export const processPerformanceArchive = (id) => request.put(`/api/performance/process/${id}`)
export const finishPerformanceArchive = (id) => request.put(`/api/performance/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
