spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cinema_member_system_091_verify?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
