import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getCounselCasePage = (params) => request.get('/api/case/page', { params })
export const addCounselCase = (data) => request.post('/api/case', data)
export const updateCounselCase = (data) => request.put('/api/case', data)
export const deleteCounselCase = (id) => request.delete(`/api/case/${id}`)
export const activateCounselCase = (id) => request.put(`/api/case/activate/${id}`)
export const finishCounselCase = (id) => request.put(`/api/case/finish/${id}`)
export const getCounselRoomPage = (params) => request.get('/api/room/page', { params })
export const addCounselRoom = (data) => request.post('/api/room', data)
export const updateCounselRoom = (data) => request.put('/api/room', data)
export const deleteCounselRoom = (id) => request.delete(`/api/room/${id}`)
export const activateCounselRoom = (id) => request.put(`/api/room/activate/${id}`)
export const finishCounselRoom = (id) => request.put(`/api/room/finish/${id}`)
export const getStudentProfilePage = (params) => request.get('/api/student/page', { params })
export const addStudentProfile = (data) => request.post('/api/student', data)
export const updateStudentProfile = (data) => request.put('/api/student', data)
export const deleteStudentProfile = (id) => request.delete(`/api/student/${id}`)
export const activateStudentProfile = (id) => request.put(`/api/student/activate/${id}`)
export const finishStudentProfile = (id) => request.put(`/api/student/finish/${id}`)
export const getDutySchedulePage = (params) => request.get('/api/duty/page', { params })
export const addDutySchedule = (data) => request.post('/api/duty', data)
export const updateDutySchedule = (data) => request.put('/api/duty', data)
export const deleteDutySchedule = (id) => request.delete(`/api/duty/${id}`)
export const processDutySchedule = (id) => request.put(`/api/duty/process/${id}`)
export const finishDutySchedule = (id) => request.put(`/api/duty/finish/${id}`)
export const getAppointmentRequestPage = (params) => request.get('/api/appointment/page', { params })
export const addAppointmentRequest = (data) => request.post('/api/appointment', data)
export const updateAppointmentRequest = (data) => request.put('/api/appointment', data)
export const deleteAppointmentRequest = (id) => request.delete(`/api/appointment/${id}`)
export const submitAppointmentRequest = (id) => request.put(`/api/appointment/submit/${id}`)
export const approveAppointmentRequest = (id) => request.put(`/api/appointment/approve/${id}`)
export const getCounselRecordPage = (params) => request.get('/api/record/page', { params })
export const addCounselRecord = (data) => request.post('/api/record', data)
export const updateCounselRecord = (data) => request.put('/api/record', data)
export const deleteCounselRecord = (id) => request.delete(`/api/record/${id}`)
export const submitCounselRecord = (id) => request.put(`/api/record/submit/${id}`)
export const approveCounselRecord = (id) => request.put(`/api/record/approve/${id}`)
export const getAssessmentQuestionnairePage = (params) => request.get('/api/questionnaire/page', { params })
export const addAssessmentQuestionnaire = (data) => request.post('/api/questionnaire', data)
export const updateAssessmentQuestionnaire = (data) => request.put('/api/questionnaire', data)
export const deleteAssessmentQuestionnaire = (id) => request.delete(`/api/questionnaire/${id}`)
export const processAssessmentQuestionnaire = (id) => request.put(`/api/questionnaire/process/${id}`)
export const finishAssessmentQuestionnaire = (id) => request.put(`/api/questionnaire/finish/${id}`)
export const getRiskAssessmentPage = (params) => request.get('/api/risk/page', { params })
export const addRiskAssessment = (data) => request.post('/api/risk', data)
export const updateRiskAssessment = (data) => request.put('/api/risk', data)
export const deleteRiskAssessment = (id) => request.delete(`/api/risk/${id}`)
export const submitRiskAssessment = (id) => request.put(`/api/risk/submit/${id}`)
export const approveRiskAssessment = (id) => request.put(`/api/risk/approve/${id}`)
export const getCrisisInterventionPage = (params) => request.get('/api/intervention/page', { params })
export const addCrisisIntervention = (data) => request.post('/api/intervention', data)
export const updateCrisisIntervention = (data) => request.put('/api/intervention', data)
export const deleteCrisisIntervention = (id) => request.delete(`/api/intervention/${id}`)
export const submitCrisisIntervention = (id) => request.put(`/api/intervention/submit/${id}`)
export const approveCrisisIntervention = (id) => request.put(`/api/intervention/approve/${id}`)
export const getFamilyCommunicationPage = (params) => request.get('/api/family/page', { params })
export const addFamilyCommunication = (data) => request.post('/api/family', data)
export const updateFamilyCommunication = (data) => request.put('/api/family', data)
export const deleteFamilyCommunication = (id) => request.delete(`/api/family/${id}`)
export const processFamilyCommunication = (id) => request.put(`/api/family/process/${id}`)
export const finishFamilyCommunication = (id) => request.put(`/api/family/finish/${id}`)
export const getFollowUpPlanPage = (params) => request.get('/api/followup/page', { params })
export const addFollowUpPlan = (data) => request.post('/api/followup', data)
export const updateFollowUpPlan = (data) => request.put('/api/followup', data)
export const deleteFollowUpPlan = (id) => request.delete(`/api/followup/${id}`)
export const activateFollowUpPlan = (id) => request.put(`/api/followup/activate/${id}`)
export const finishFollowUpPlan = (id) => request.put(`/api/followup/finish/${id}`)
export const getSystemNoticePage = (params) => request.get('/api/notice/page', { params })
export const addSystemNotice = (data) => request.post('/api/notice', data)
export const updateSystemNotice = (data) => request.put('/api/notice', data)
export const deleteSystemNotice = (id) => request.delete(`/api/notice/${id}`)
export const processSystemNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishSystemNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)








