spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dream_donation
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never

logging:
  level:
    com.xiaou.dreamdonation: debug
    org.hibernate.SQL: debug
