import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getConstructionProjectPage = (params) => request.get('/api/project/page', { params })
export const addConstructionProject = (data) => request.post('/api/project', data)
export const updateConstructionProject = (data) => request.put('/api/project', data)
export const deleteConstructionProject = (id) => request.delete(`/api/project/${id}`)
export const enableConstructionProject = (id) => request.put(`/api/project/enable/${id}`)
export const disableConstructionProject = (id) => request.put(`/api/project/disable/${id}`)
export const getWorkTeamPage = (params) => request.get('/api/team/page', { params })
export const addWorkTeam = (data) => request.post('/api/team', data)
export const updateWorkTeam = (data) => request.put('/api/team', data)
export const deleteWorkTeam = (id) => request.delete(`/api/team/${id}`)
export const enableWorkTeam = (id) => request.put(`/api/team/enable/${id}`)
export const disableWorkTeam = (id) => request.put(`/api/team/disable/${id}`)
export const getSafetyInspectorPage = (params) => request.get('/api/inspector/page', { params })
export const addSafetyInspector = (data) => request.post('/api/inspector', data)
export const updateSafetyInspector = (data) => request.put('/api/inspector', data)
export const deleteSafetyInspector = (id) => request.delete(`/api/inspector/${id}`)
export const enableSafetyInspector = (id) => request.put(`/api/inspector/enable/${id}`)
export const disableSafetyInspector = (id) => request.put(`/api/inspector/disable/${id}`)
export const getInspectionPlanPage = (params) => request.get('/api/plan/page', { params })
export const addInspectionPlan = (data) => request.post('/api/plan', data)
export const updateInspectionPlan = (data) => request.put('/api/plan', data)
export const deleteInspectionPlan = (id) => request.delete(`/api/plan/${id}`)
export const publishInspectionPlan = (id) => request.put(`/api/plan/publish/${id}`)
export const closeInspectionPlan = (id) => request.put(`/api/plan/close/${id}`)
export const getInspectionTaskPage = (params) => request.get('/api/task/page', { params })
export const addInspectionTask = (data) => request.post('/api/task', data)
export const updateInspectionTask = (data) => request.put('/api/task', data)
export const deleteInspectionTask = (id) => request.delete(`/api/task/${id}`)
export const startInspectionTask = (id) => request.put(`/api/task/start/${id}`)
export const finishInspectionTask = (id) => request.put(`/api/task/finish/${id}`)
export const getHazardReportPage = (params) => request.get('/api/hazard/page', { params })
export const addHazardReport = (data) => request.post('/api/hazard', data)
export const updateHazardReport = (data) => request.put('/api/hazard', data)
export const deleteHazardReport = (id) => request.delete(`/api/hazard/${id}`)
export const confirmHazardReport = (id) => request.put(`/api/hazard/confirm/${id}`)
export const closeHazardReport = (id) => request.put(`/api/hazard/close/${id}`)
export const getRectificationOrderPage = (params) => request.get('/api/rectify/page', { params })
export const addRectificationOrder = (data) => request.post('/api/rectify', data)
export const updateRectificationOrder = (data) => request.put('/api/rectify', data)
export const deleteRectificationOrder = (id) => request.delete(`/api/rectify/${id}`)
export const submitRectificationOrder = (id) => request.put(`/api/rectify/submit/${id}`)
export const finishRectificationOrder = (id) => request.put(`/api/rectify/finish/${id}`)
export const getAcceptanceRecordPage = (params) => request.get('/api/acceptance/page', { params })
export const addAcceptanceRecord = (data) => request.post('/api/acceptance', data)
export const updateAcceptanceRecord = (data) => request.put('/api/acceptance', data)
export const deleteAcceptanceRecord = (id) => request.delete(`/api/acceptance/${id}`)
export const passAcceptanceRecord = (id) => request.put(`/api/acceptance/pass/${id}`)
export const failAcceptanceRecord = (id) => request.put(`/api/acceptance/fail/${id}`)
export const getSafetyTrainingPage = (params) => request.get('/api/training/page', { params })
export const addSafetyTraining = (data) => request.post('/api/training', data)
export const updateSafetyTraining = (data) => request.put('/api/training', data)
export const deleteSafetyTraining = (id) => request.delete(`/api/training/${id}`)
export const publishSafetyTraining = (id) => request.put(`/api/training/publish/${id}`)
export const finishSafetyTraining = (id) => request.put(`/api/training/finish/${id}`)
export const getEquipmentCheckPage = (params) => request.get('/api/equipment/page', { params })
export const addEquipmentCheck = (data) => request.post('/api/equipment', data)
export const updateEquipmentCheck = (data) => request.put('/api/equipment', data)
export const deleteEquipmentCheck = (id) => request.delete(`/api/equipment/${id}`)
export const passEquipmentCheck = (id) => request.put(`/api/equipment/pass/${id}`)
export const warnEquipmentCheck = (id) => request.put(`/api/equipment/warn/${id}`)
export const getProtectiveSupplyPage = (params) => request.get('/api/supply/page', { params })
export const addProtectiveSupply = (data) => request.post('/api/supply', data)
export const updateProtectiveSupply = (data) => request.put('/api/supply', data)
export const deleteProtectiveSupply = (id) => request.delete(`/api/supply/${id}`)
export const enableProtectiveSupply = (id) => request.put(`/api/supply/enable/${id}`)
export const warnProtectiveSupply = (id) => request.put(`/api/supply/warn/${id}`)
export const getRiskWarningPage = (params) => request.get('/api/warning/page', { params })
export const addRiskWarning = (data) => request.post('/api/warning', data)
export const updateRiskWarning = (data) => request.put('/api/warning', data)
export const deleteRiskWarning = (id) => request.delete(`/api/warning/${id}`)
export const assignRiskWarning = (id) => request.put(`/api/warning/assign/${id}`)
export const closeRiskWarning = (id) => request.put(`/api/warning/close/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
