import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getWasteSourcePage = (params) => request.get('/api/waste/page', { params })
export const addWasteSource = (data) => request.post('/api/waste', data)
export const updateWasteSource = (data) => request.put('/api/waste', data)
export const deleteWasteSource = (id) => request.delete(`/api/waste/${id}`)
export const processWasteSource = (id) => request.put(`/api/waste/process/${id}`)
export const finishWasteSource = (id) => request.put(`/api/waste/finish/${id}`)

export const getWasteCategoryPage = (params) => request.get('/api/category/page', { params })
export const addWasteCategory = (data) => request.post('/api/category', data)
export const updateWasteCategory = (data) => request.put('/api/category', data)
export const deleteWasteCategory = (id) => request.delete(`/api/category/${id}`)
export const processWasteCategory = (id) => request.put(`/api/category/process/${id}`)
export const finishWasteCategory = (id) => request.put(`/api/category/finish/${id}`)

export const getWastePackagePage = (params) => request.get('/api/package/page', { params })
export const addWastePackage = (data) => request.post('/api/package', data)
export const updateWastePackage = (data) => request.put('/api/package', data)
export const deleteWastePackage = (id) => request.delete(`/api/package/${id}`)
export const processWastePackage = (id) => request.put(`/api/package/process/${id}`)
export const finishWastePackage = (id) => request.put(`/api/package/finish/${id}`)

export const getCollectionOrderPage = (params) => request.get('/api/order/page', { params })
export const addCollectionOrder = (data) => request.post('/api/order', data)
export const updateCollectionOrder = (data) => request.put('/api/order', data)
export const deleteCollectionOrder = (id) => request.delete(`/api/order/${id}`)
export const processCollectionOrder = (id) => request.put(`/api/order/process/${id}`)
export const finishCollectionOrder = (id) => request.put(`/api/order/finish/${id}`)

export const getWeighingRecordPage = (params) => request.get('/api/weighing/page', { params })
export const addWeighingRecord = (data) => request.post('/api/weighing', data)
export const updateWeighingRecord = (data) => request.put('/api/weighing', data)
export const deleteWeighingRecord = (id) => request.delete(`/api/weighing/${id}`)
export const processWeighingRecord = (id) => request.put(`/api/weighing/process/${id}`)
export const finishWeighingRecord = (id) => request.put(`/api/weighing/finish/${id}`)

export const getStorageHandoverPage = (params) => request.get('/api/storage/page', { params })
export const addStorageHandover = (data) => request.post('/api/storage', data)
export const updateStorageHandover = (data) => request.put('/api/storage', data)
export const deleteStorageHandover = (id) => request.delete(`/api/storage/${id}`)
export const processStorageHandover = (id) => request.put(`/api/storage/process/${id}`)
export const finishStorageHandover = (id) => request.put(`/api/storage/finish/${id}`)

export const getTransferManifestPage = (params) => request.get('/api/manifest/page', { params })
export const addTransferManifest = (data) => request.post('/api/manifest', data)
export const updateTransferManifest = (data) => request.put('/api/manifest', data)
export const deleteTransferManifest = (id) => request.delete(`/api/manifest/${id}`)
export const processTransferManifest = (id) => request.put(`/api/manifest/process/${id}`)
export const finishTransferManifest = (id) => request.put(`/api/manifest/finish/${id}`)

export const getTransportTrackPage = (params) => request.get('/api/track/page', { params })
export const addTransportTrack = (data) => request.post('/api/track', data)
export const updateTransportTrack = (data) => request.put('/api/track', data)
export const deleteTransportTrack = (id) => request.delete(`/api/track/${id}`)
export const processTransportTrack = (id) => request.put(`/api/track/process/${id}`)
export const finishTransportTrack = (id) => request.put(`/api/track/finish/${id}`)

export const getDisposalConfirmPage = (params) => request.get('/api/disposal/page', { params })
export const addDisposalConfirm = (data) => request.post('/api/disposal', data)
export const updateDisposalConfirm = (data) => request.put('/api/disposal', data)
export const deleteDisposalConfirm = (id) => request.delete(`/api/disposal/${id}`)
export const processDisposalConfirm = (id) => request.put(`/api/disposal/process/${id}`)
export const finishDisposalConfirm = (id) => request.put(`/api/disposal/finish/${id}`)

export const getExceptionTracePage = (params) => request.get('/api/exception/page', { params })
export const addExceptionTrace = (data) => request.post('/api/exception', data)
export const updateExceptionTrace = (data) => request.put('/api/exception', data)
export const deleteExceptionTrace = (id) => request.delete(`/api/exception/${id}`)
export const processExceptionTrace = (id) => request.put(`/api/exception/process/${id}`)
export const finishExceptionTrace = (id) => request.put(`/api/exception/finish/${id}`)

export const getComplianceAuditPage = (params) => request.get('/api/audit/page', { params })
export const addComplianceAudit = (data) => request.post('/api/audit', data)
export const updateComplianceAudit = (data) => request.put('/api/audit', data)
export const deleteComplianceAudit = (id) => request.delete(`/api/audit/${id}`)
export const processComplianceAudit = (id) => request.put(`/api/audit/process/${id}`)
export const finishComplianceAudit = (id) => request.put(`/api/audit/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
