import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getAccessibleRoutePage = (params) => request.get('/api/route/page', { params })
export const addAccessibleRoute = (data) => request.post('/api/route', data)
export const updateAccessibleRoute = (data) => request.put('/api/route', data)
export const deleteAccessibleRoute = (id) => request.delete(`/api/route/${id}`)
export const activateAccessibleRoute = (id) => request.put(`/api/route/activate/${id}`)
export const finishAccessibleRoute = (id) => request.put(`/api/route/finish/${id}`)
export const getFacilityPointPage = (params) => request.get('/api/facility/page', { params })
export const addFacilityPoint = (data) => request.post('/api/facility', data)
export const updateFacilityPoint = (data) => request.put('/api/facility', data)
export const deleteFacilityPoint = (id) => request.delete(`/api/facility/${id}`)
export const activateFacilityPoint = (id) => request.put(`/api/facility/activate/${id}`)
export const finishFacilityPoint = (id) => request.put(`/api/facility/finish/${id}`)
export const getTravelerProfilePage = (params) => request.get('/api/traveler/page', { params })
export const addTravelerProfile = (data) => request.post('/api/traveler', data)
export const updateTravelerProfile = (data) => request.put('/api/traveler', data)
export const deleteTravelerProfile = (id) => request.delete(`/api/traveler/${id}`)
export const processTravelerProfile = (id) => request.put(`/api/traveler/process/${id}`)
export const finishTravelerProfile = (id) => request.put(`/api/traveler/finish/${id}`)
export const getAssistRequestPage = (params) => request.get('/api/request/page', { params })
export const addAssistRequest = (data) => request.post('/api/request', data)
export const updateAssistRequest = (data) => request.put('/api/request', data)
export const deleteAssistRequest = (id) => request.delete(`/api/request/${id}`)
export const submitAssistRequest = (id) => request.put(`/api/request/submit/${id}`)
export const approveAssistRequest = (id) => request.put(`/api/request/approve/${id}`)
export const getVolunteerProfilePage = (params) => request.get('/api/volunteer/page', { params })
export const addVolunteerProfile = (data) => request.post('/api/volunteer', data)
export const updateVolunteerProfile = (data) => request.put('/api/volunteer', data)
export const deleteVolunteerProfile = (id) => request.delete(`/api/volunteer/${id}`)
export const submitVolunteerProfile = (id) => request.put(`/api/volunteer/submit/${id}`)
export const approveVolunteerProfile = (id) => request.put(`/api/volunteer/approve/${id}`)
export const getRoutePlanPage = (params) => request.get('/api/plan/page', { params })
export const addRoutePlan = (data) => request.post('/api/plan', data)
export const updateRoutePlan = (data) => request.put('/api/plan', data)
export const deleteRoutePlan = (id) => request.delete(`/api/plan/${id}`)
export const submitRoutePlan = (id) => request.put(`/api/plan/submit/${id}`)
export const approveRoutePlan = (id) => request.put(`/api/plan/approve/${id}`)
export const getAssistTaskPage = (params) => request.get('/api/task/page', { params })
export const addAssistTask = (data) => request.post('/api/task', data)
export const updateAssistTask = (data) => request.put('/api/task', data)
export const deleteAssistTask = (id) => request.delete(`/api/task/${id}`)
export const processAssistTask = (id) => request.put(`/api/task/process/${id}`)
export const finishAssistTask = (id) => request.put(`/api/task/finish/${id}`)
export const getServiceCheckinPage = (params) => request.get('/api/checkin/page', { params })
export const addServiceCheckin = (data) => request.post('/api/checkin', data)
export const updateServiceCheckin = (data) => request.put('/api/checkin', data)
export const deleteServiceCheckin = (id) => request.delete(`/api/checkin/${id}`)
export const activateServiceCheckin = (id) => request.put(`/api/checkin/activate/${id}`)
export const finishServiceCheckin = (id) => request.put(`/api/checkin/finish/${id}`)
export const getFeedbackReviewPage = (params) => request.get('/api/feedback/page', { params })
export const addFeedbackReview = (data) => request.post('/api/feedback', data)
export const updateFeedbackReview = (data) => request.put('/api/feedback', data)
export const deleteFeedbackReview = (id) => request.delete(`/api/feedback/${id}`)
export const activateFeedbackReview = (id) => request.put(`/api/feedback/activate/${id}`)
export const finishFeedbackReview = (id) => request.put(`/api/feedback/finish/${id}`)
export const getEmergencyContactPage = (params) => request.get('/api/contact/page', { params })
export const addEmergencyContact = (data) => request.post('/api/contact', data)
export const updateEmergencyContact = (data) => request.put('/api/contact', data)
export const deleteEmergencyContact = (id) => request.delete(`/api/contact/${id}`)
export const activateEmergencyContact = (id) => request.put(`/api/contact/activate/${id}`)
export const finishEmergencyContact = (id) => request.put(`/api/contact/finish/${id}`)
export const getTripRecordPage = (params) => request.get('/api/trip/page', { params })
export const addTripRecord = (data) => request.post('/api/trip', data)
export const updateTripRecord = (data) => request.put('/api/trip', data)
export const deleteTripRecord = (id) => request.delete(`/api/trip/${id}`)
export const processTripRecord = (id) => request.put(`/api/trip/process/${id}`)
export const finishTripRecord = (id) => request.put(`/api/trip/finish/${id}`)
export const getMessageNoticePage = (params) => request.get('/api/notice/page', { params })
export const addMessageNotice = (data) => request.post('/api/notice', data)
export const updateMessageNotice = (data) => request.put('/api/notice', data)
export const deleteMessageNotice = (id) => request.delete(`/api/notice/${id}`)
export const processMessageNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishMessageNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)






