import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getRehabCenterPage = (params) => request.get('/api/center/page', { params })
export const addRehabCenter = (data) => request.post('/api/center', data)
export const updateRehabCenter = (data) => request.put('/api/center', data)
export const deleteRehabCenter = (id) => request.delete(`/api/center/${id}`)
export const processRehabCenter = (id) => request.put(`/api/center/process/${id}`)
export const finishRehabCenter = (id) => request.put(`/api/center/finish/${id}`)

export const getMemberProfilePage = (params) => request.get('/api/member/page', { params })
export const addMemberProfile = (data) => request.post('/api/member', data)
export const updateMemberProfile = (data) => request.put('/api/member', data)
export const deleteMemberProfile = (id) => request.delete(`/api/member/${id}`)
export const processMemberProfile = (id) => request.put(`/api/member/process/${id}`)
export const finishMemberProfile = (id) => request.put(`/api/member/finish/${id}`)

export const getCoachProfilePage = (params) => request.get('/api/coach/page', { params })
export const addCoachProfile = (data) => request.post('/api/coach', data)
export const updateCoachProfile = (data) => request.put('/api/coach', data)
export const deleteCoachProfile = (id) => request.delete(`/api/coach/${id}`)
export const processCoachProfile = (id) => request.put(`/api/coach/process/${id}`)
export const finishCoachProfile = (id) => request.put(`/api/coach/finish/${id}`)

export const getAssessmentItemPage = (params) => request.get('/api/item/page', { params })
export const addAssessmentItem = (data) => request.post('/api/item', data)
export const updateAssessmentItem = (data) => request.put('/api/item', data)
export const deleteAssessmentItem = (id) => request.delete(`/api/item/${id}`)
export const processAssessmentItem = (id) => request.put(`/api/item/process/${id}`)
export const finishAssessmentItem = (id) => request.put(`/api/item/finish/${id}`)

export const getFitnessAssessmentPage = (params) => request.get('/api/assessment/page', { params })
export const addFitnessAssessment = (data) => request.post('/api/assessment', data)
export const updateFitnessAssessment = (data) => request.put('/api/assessment', data)
export const deleteFitnessAssessment = (id) => request.delete(`/api/assessment/${id}`)
export const processFitnessAssessment = (id) => request.put(`/api/assessment/process/${id}`)
export const finishFitnessAssessment = (id) => request.put(`/api/assessment/finish/${id}`)

export const getRiskWarningPage = (params) => request.get('/api/risk/page', { params })
export const addRiskWarning = (data) => request.post('/api/risk', data)
export const updateRiskWarning = (data) => request.put('/api/risk', data)
export const deleteRiskWarning = (id) => request.delete(`/api/risk/${id}`)
export const processRiskWarning = (id) => request.put(`/api/risk/process/${id}`)
export const finishRiskWarning = (id) => request.put(`/api/risk/finish/${id}`)

export const getTrainingPlanPage = (params) => request.get('/api/plan/page', { params })
export const addTrainingPlan = (data) => request.post('/api/plan', data)
export const updateTrainingPlan = (data) => request.put('/api/plan', data)
export const deleteTrainingPlan = (id) => request.delete(`/api/plan/${id}`)
export const processTrainingPlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishTrainingPlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getTrainingSessionPage = (params) => request.get('/api/session/page', { params })
export const addTrainingSession = (data) => request.post('/api/session', data)
export const updateTrainingSession = (data) => request.put('/api/session', data)
export const deleteTrainingSession = (id) => request.delete(`/api/session/${id}`)
export const processTrainingSession = (id) => request.put(`/api/session/process/${id}`)
export const finishTrainingSession = (id) => request.put(`/api/session/finish/${id}`)

export const getExerciseCheckinPage = (params) => request.get('/api/checkin/page', { params })
export const addExerciseCheckin = (data) => request.post('/api/checkin', data)
export const updateExerciseCheckin = (data) => request.put('/api/checkin', data)
export const deleteExerciseCheckin = (id) => request.delete(`/api/checkin/${id}`)
export const processExerciseCheckin = (id) => request.put(`/api/checkin/process/${id}`)
export const finishExerciseCheckin = (id) => request.put(`/api/checkin/finish/${id}`)

export const getRehabFeedbackPage = (params) => request.get('/api/feedback/page', { params })
export const addRehabFeedback = (data) => request.post('/api/feedback', data)
export const updateRehabFeedback = (data) => request.put('/api/feedback', data)
export const deleteRehabFeedback = (id) => request.delete(`/api/feedback/${id}`)
export const processRehabFeedback = (id) => request.put(`/api/feedback/process/${id}`)
export const finishRehabFeedback = (id) => request.put(`/api/feedback/finish/${id}`)

export const getReassessmentRecordPage = (params) => request.get('/api/reassessment/page', { params })
export const addReassessmentRecord = (data) => request.post('/api/reassessment', data)
export const updateReassessmentRecord = (data) => request.put('/api/reassessment', data)
export const deleteReassessmentRecord = (id) => request.delete(`/api/reassessment/${id}`)
export const processReassessmentRecord = (id) => request.put(`/api/reassessment/process/${id}`)
export const finishReassessmentRecord = (id) => request.put(`/api/reassessment/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
