import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getBizRecord01Page = (params) => request.get('/api/record01/page', { params })
export const addBizRecord01 = (data) => request.post('/api/record01', data)
export const updateBizRecord01 = (data) => request.put('/api/record01', data)
export const deleteBizRecord01 = (id) => request.delete(`/api/record01/${id}`)
export const processBizRecord01 = (id) => request.put(`/api/record01/process/${id}`)
export const finishBizRecord01 = (id) => request.put(`/api/record01/finish/${id}`)

export const getBizRecord02Page = (params) => request.get('/api/record02/page', { params })
export const addBizRecord02 = (data) => request.post('/api/record02', data)
export const updateBizRecord02 = (data) => request.put('/api/record02', data)
export const deleteBizRecord02 = (id) => request.delete(`/api/record02/${id}`)
export const processBizRecord02 = (id) => request.put(`/api/record02/process/${id}`)
export const finishBizRecord02 = (id) => request.put(`/api/record02/finish/${id}`)

export const getBizRecord03Page = (params) => request.get('/api/record03/page', { params })
export const addBizRecord03 = (data) => request.post('/api/record03', data)
export const updateBizRecord03 = (data) => request.put('/api/record03', data)
export const deleteBizRecord03 = (id) => request.delete(`/api/record03/${id}`)
export const processBizRecord03 = (id) => request.put(`/api/record03/process/${id}`)
export const finishBizRecord03 = (id) => request.put(`/api/record03/finish/${id}`)

export const getBizRecord04Page = (params) => request.get('/api/record04/page', { params })
export const addBizRecord04 = (data) => request.post('/api/record04', data)
export const updateBizRecord04 = (data) => request.put('/api/record04', data)
export const deleteBizRecord04 = (id) => request.delete(`/api/record04/${id}`)
export const processBizRecord04 = (id) => request.put(`/api/record04/process/${id}`)
export const finishBizRecord04 = (id) => request.put(`/api/record04/finish/${id}`)

export const getBizRecord05Page = (params) => request.get('/api/record05/page', { params })
export const addBizRecord05 = (data) => request.post('/api/record05', data)
export const updateBizRecord05 = (data) => request.put('/api/record05', data)
export const deleteBizRecord05 = (id) => request.delete(`/api/record05/${id}`)
export const processBizRecord05 = (id) => request.put(`/api/record05/process/${id}`)
export const finishBizRecord05 = (id) => request.put(`/api/record05/finish/${id}`)

export const getBizRecord06Page = (params) => request.get('/api/record06/page', { params })
export const addBizRecord06 = (data) => request.post('/api/record06', data)
export const updateBizRecord06 = (data) => request.put('/api/record06', data)
export const deleteBizRecord06 = (id) => request.delete(`/api/record06/${id}`)
export const processBizRecord06 = (id) => request.put(`/api/record06/process/${id}`)
export const finishBizRecord06 = (id) => request.put(`/api/record06/finish/${id}`)

export const getBizRecord07Page = (params) => request.get('/api/record07/page', { params })
export const addBizRecord07 = (data) => request.post('/api/record07', data)
export const updateBizRecord07 = (data) => request.put('/api/record07', data)
export const deleteBizRecord07 = (id) => request.delete(`/api/record07/${id}`)
export const processBizRecord07 = (id) => request.put(`/api/record07/process/${id}`)
export const finishBizRecord07 = (id) => request.put(`/api/record07/finish/${id}`)

export const getBizRecord08Page = (params) => request.get('/api/record08/page', { params })
export const addBizRecord08 = (data) => request.post('/api/record08', data)
export const updateBizRecord08 = (data) => request.put('/api/record08', data)
export const deleteBizRecord08 = (id) => request.delete(`/api/record08/${id}`)
export const processBizRecord08 = (id) => request.put(`/api/record08/process/${id}`)
export const finishBizRecord08 = (id) => request.put(`/api/record08/finish/${id}`)

export const getBizRecord09Page = (params) => request.get('/api/record09/page', { params })
export const addBizRecord09 = (data) => request.post('/api/record09', data)
export const updateBizRecord09 = (data) => request.put('/api/record09', data)
export const deleteBizRecord09 = (id) => request.delete(`/api/record09/${id}`)
export const processBizRecord09 = (id) => request.put(`/api/record09/process/${id}`)
export const finishBizRecord09 = (id) => request.put(`/api/record09/finish/${id}`)

export const getBizRecord10Page = (params) => request.get('/api/record10/page', { params })
export const addBizRecord10 = (data) => request.post('/api/record10', data)
export const updateBizRecord10 = (data) => request.put('/api/record10', data)
export const deleteBizRecord10 = (id) => request.delete(`/api/record10/${id}`)
export const processBizRecord10 = (id) => request.put(`/api/record10/process/${id}`)
export const finishBizRecord10 = (id) => request.put(`/api/record10/finish/${id}`)

export const getBizRecord11Page = (params) => request.get('/api/record11/page', { params })
export const addBizRecord11 = (data) => request.post('/api/record11', data)
export const updateBizRecord11 = (data) => request.put('/api/record11', data)
export const deleteBizRecord11 = (id) => request.delete(`/api/record11/${id}`)
export const processBizRecord11 = (id) => request.put(`/api/record11/process/${id}`)
export const finishBizRecord11 = (id) => request.put(`/api/record11/finish/${id}`)

export const getBizRecord12Page = (params) => request.get('/api/record12/page', { params })
export const addBizRecord12 = (data) => request.post('/api/record12', data)
export const updateBizRecord12 = (data) => request.put('/api/record12', data)
export const deleteBizRecord12 = (id) => request.delete(`/api/record12/${id}`)
export const processBizRecord12 = (id) => request.put(`/api/record12/process/${id}`)
export const finishBizRecord12 = (id) => request.put(`/api/record12/finish/${id}`)
