import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getInsurancePolicyPage = (params) => request.get('/api/policy/page', { params })
export const addInsurancePolicy = (data) => request.post('/api/policy', data)
export const updateInsurancePolicy = (data) => request.put('/api/policy', data)
export const deleteInsurancePolicy = (id) => request.delete(`/api/policy/${id}`)
export const activateInsurancePolicy = (id) => request.put(`/api/policy/activate/${id}`)
export const finishInsurancePolicy = (id) => request.put(`/api/policy/finish/${id}`)
export const getVehicleProfilePage = (params) => request.get('/api/vehicle/page', { params })
export const addVehicleProfile = (data) => request.post('/api/vehicle', data)
export const updateVehicleProfile = (data) => request.put('/api/vehicle', data)
export const deleteVehicleProfile = (id) => request.delete(`/api/vehicle/${id}`)
export const activateVehicleProfile = (id) => request.put(`/api/vehicle/activate/${id}`)
export const finishVehicleProfile = (id) => request.put(`/api/vehicle/finish/${id}`)
export const getCustomerProfilePage = (params) => request.get('/api/customer/page', { params })
export const addCustomerProfile = (data) => request.post('/api/customer', data)
export const updateCustomerProfile = (data) => request.put('/api/customer', data)
export const deleteCustomerProfile = (id) => request.delete(`/api/customer/${id}`)
export const activateCustomerProfile = (id) => request.put(`/api/customer/activate/${id}`)
export const finishCustomerProfile = (id) => request.put(`/api/customer/finish/${id}`)
export const getClaimApplicationPage = (params) => request.get('/api/claim/page', { params })
export const addClaimApplication = (data) => request.post('/api/claim', data)
export const updateClaimApplication = (data) => request.put('/api/claim', data)
export const deleteClaimApplication = (id) => request.delete(`/api/claim/${id}`)
export const submitClaimApplication = (id) => request.put(`/api/claim/submit/${id}`)
export const approveClaimApplication = (id) => request.put(`/api/claim/approve/${id}`)
export const getAccidentReportPage = (params) => request.get('/api/accident/page', { params })
export const addAccidentReport = (data) => request.post('/api/accident', data)
export const updateAccidentReport = (data) => request.put('/api/accident', data)
export const deleteAccidentReport = (id) => request.delete(`/api/accident/${id}`)
export const submitAccidentReport = (id) => request.put(`/api/accident/submit/${id}`)
export const approveAccidentReport = (id) => request.put(`/api/accident/approve/${id}`)
export const getMaterialChecklistPage = (params) => request.get('/api/material/page', { params })
export const addMaterialChecklist = (data) => request.post('/api/material', data)
export const updateMaterialChecklist = (data) => request.put('/api/material', data)
export const deleteMaterialChecklist = (id) => request.delete(`/api/material/${id}`)
export const submitMaterialChecklist = (id) => request.put(`/api/material/submit/${id}`)
export const approveMaterialChecklist = (id) => request.put(`/api/material/approve/${id}`)
export const getMaterialReviewPage = (params) => request.get('/api/review/page', { params })
export const addMaterialReview = (data) => request.post('/api/review', data)
export const updateMaterialReview = (data) => request.put('/api/review', data)
export const deleteMaterialReview = (id) => request.delete(`/api/review/${id}`)
export const processMaterialReview = (id) => request.put(`/api/review/process/${id}`)
export const finishMaterialReview = (id) => request.put(`/api/review/finish/${id}`)
export const getLossAssessmentPage = (params) => request.get('/api/assessment/page', { params })
export const addLossAssessment = (data) => request.post('/api/assessment', data)
export const updateLossAssessment = (data) => request.put('/api/assessment', data)
export const deleteLossAssessment = (id) => request.delete(`/api/assessment/${id}`)
export const activateLossAssessment = (id) => request.put(`/api/assessment/activate/${id}`)
export const finishLossAssessment = (id) => request.put(`/api/assessment/finish/${id}`)
export const getCompensationRecordPage = (params) => request.get('/api/compensation/page', { params })
export const addCompensationRecord = (data) => request.post('/api/compensation', data)
export const updateCompensationRecord = (data) => request.put('/api/compensation', data)
export const deleteCompensationRecord = (id) => request.delete(`/api/compensation/${id}`)
export const activateCompensationRecord = (id) => request.put(`/api/compensation/activate/${id}`)
export const finishCompensationRecord = (id) => request.put(`/api/compensation/finish/${id}`)
export const getProgressTrackPage = (params) => request.get('/api/progress/page', { params })
export const addProgressTrack = (data) => request.post('/api/progress', data)
export const updateProgressTrack = (data) => request.put('/api/progress', data)
export const deleteProgressTrack = (id) => request.delete(`/api/progress/${id}`)
export const activateProgressTrack = (id) => request.put(`/api/progress/activate/${id}`)
export const finishProgressTrack = (id) => request.put(`/api/progress/finish/${id}`)
export const getFollowUpRecordPage = (params) => request.get('/api/followup/page', { params })
export const addFollowUpRecord = (data) => request.post('/api/followup', data)
export const updateFollowUpRecord = (data) => request.put('/api/followup', data)
export const deleteFollowUpRecord = (id) => request.delete(`/api/followup/${id}`)
export const processFollowUpRecord = (id) => request.put(`/api/followup/process/${id}`)
export const finishFollowUpRecord = (id) => request.put(`/api/followup/finish/${id}`)
export const getClaimNoticePage = (params) => request.get('/api/notice/page', { params })
export const addClaimNotice = (data) => request.post('/api/notice', data)
export const updateClaimNotice = (data) => request.put('/api/notice', data)
export const deleteClaimNotice = (id) => request.delete(`/api/notice/${id}`)
export const processClaimNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishClaimNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)

