import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getPlacementSitePage = (params) => request.get('/api/site/page', { params })
export const addPlacementSite = (data) => request.post('/api/site', data)
export const updatePlacementSite = (data) => request.put('/api/site', data)
export const deletePlacementSite = (id) => request.delete(`/api/site/${id}`)
export const processPlacementSite = (id) => request.put(`/api/site/process/${id}`)
export const finishPlacementSite = (id) => request.put(`/api/site/finish/${id}`)

export const getCabinetProfilePage = (params) => request.get('/api/cabinet/page', { params })
export const addCabinetProfile = (data) => request.post('/api/cabinet', data)
export const updateCabinetProfile = (data) => request.put('/api/cabinet', data)
export const deleteCabinetProfile = (id) => request.delete(`/api/cabinet/${id}`)
export const processCabinetProfile = (id) => request.put(`/api/cabinet/process/${id}`)
export const finishCabinetProfile = (id) => request.put(`/api/cabinet/finish/${id}`)

export const getPowerBankDevicePage = (params) => request.get('/api/device/page', { params })
export const addPowerBankDevice = (data) => request.post('/api/device', data)
export const updatePowerBankDevice = (data) => request.put('/api/device', data)
export const deletePowerBankDevice = (id) => request.delete(`/api/device/${id}`)
export const processPowerBankDevice = (id) => request.put(`/api/device/process/${id}`)
export const finishPowerBankDevice = (id) => request.put(`/api/device/finish/${id}`)

export const getPlacementPlanPage = (params) => request.get('/api/plan/page', { params })
export const addPlacementPlan = (data) => request.post('/api/plan', data)
export const updatePlacementPlan = (data) => request.put('/api/plan', data)
export const deletePlacementPlan = (id) => request.delete(`/api/plan/${id}`)
export const processPlacementPlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishPlacementPlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getInspectionTaskPage = (params) => request.get('/api/inspection/page', { params })
export const addInspectionTask = (data) => request.post('/api/inspection', data)
export const updateInspectionTask = (data) => request.put('/api/inspection', data)
export const deleteInspectionTask = (id) => request.delete(`/api/inspection/${id}`)
export const processInspectionTask = (id) => request.put(`/api/inspection/process/${id}`)
export const finishInspectionTask = (id) => request.put(`/api/inspection/finish/${id}`)

export const getFaultRepairPage = (params) => request.get('/api/repair/page', { params })
export const addFaultRepair = (data) => request.post('/api/repair', data)
export const updateFaultRepair = (data) => request.put('/api/repair', data)
export const deleteFaultRepair = (id) => request.delete(`/api/repair/${id}`)
export const processFaultRepair = (id) => request.put(`/api/repair/process/${id}`)
export const finishFaultRepair = (id) => request.put(`/api/repair/finish/${id}`)

export const getAbnormalRecyclePage = (params) => request.get('/api/recycle/page', { params })
export const addAbnormalRecycle = (data) => request.post('/api/recycle', data)
export const updateAbnormalRecycle = (data) => request.put('/api/recycle', data)
export const deleteAbnormalRecycle = (id) => request.delete(`/api/recycle/${id}`)
export const processAbnormalRecycle = (id) => request.put(`/api/recycle/process/${id}`)
export const finishAbnormalRecycle = (id) => request.put(`/api/recycle/finish/${id}`)

export const getLeaseOrderPage = (params) => request.get('/api/order/page', { params })
export const addLeaseOrder = (data) => request.post('/api/order', data)
export const updateLeaseOrder = (data) => request.put('/api/order', data)
export const deleteLeaseOrder = (id) => request.delete(`/api/order/${id}`)
export const processLeaseOrder = (id) => request.put(`/api/order/process/${id}`)
export const finishLeaseOrder = (id) => request.put(`/api/order/finish/${id}`)

export const getMerchantIncomePage = (params) => request.get('/api/income/page', { params })
export const addMerchantIncome = (data) => request.post('/api/income', data)
export const updateMerchantIncome = (data) => request.put('/api/income', data)
export const deleteMerchantIncome = (id) => request.delete(`/api/income/${id}`)
export const processMerchantIncome = (id) => request.put(`/api/income/process/${id}`)
export const finishMerchantIncome = (id) => request.put(`/api/income/finish/${id}`)

export const getSettlementRecordPage = (params) => request.get('/api/settlement/page', { params })
export const addSettlementRecord = (data) => request.post('/api/settlement', data)
export const updateSettlementRecord = (data) => request.put('/api/settlement', data)
export const deleteSettlementRecord = (id) => request.delete(`/api/settlement/${id}`)
export const processSettlementRecord = (id) => request.put(`/api/settlement/process/${id}`)
export const finishSettlementRecord = (id) => request.put(`/api/settlement/finish/${id}`)

export const getInventoryTransferPage = (params) => request.get('/api/transfer/page', { params })
export const addInventoryTransfer = (data) => request.post('/api/transfer', data)
export const updateInventoryTransfer = (data) => request.put('/api/transfer', data)
export const deleteInventoryTransfer = (id) => request.delete(`/api/transfer/${id}`)
export const processInventoryTransfer = (id) => request.put(`/api/transfer/process/${id}`)
export const finishInventoryTransfer = (id) => request.put(`/api/transfer/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
