-- 创建所有项目数据库
-- 从application.yml中提取的数据库名称

CREATE DATABASE IF NOT EXISTS campus_affairs DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS course_selection_system DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS chat_system DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS volunteer_activity DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS campus_express DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS campus_video DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS lost_and_found DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS pharmacy_care_196 DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS heritage_workshop_200 DEFAULT CHARACTER SET utf8mb4;
-- 更多数据库会在验证时自动创建
