import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getOrganizationTeamPage = (params) => request.get('/api/team/page', { params })
export const addOrganizationTeam = (data) => request.post('/api/team', data)
export const updateOrganizationTeam = (data) => request.put('/api/team', data)
export const deleteOrganizationTeam = (id) => request.delete(`/api/team/${id}`)
export const getProjectRepositoryPage = (params) => request.get('/api/repository/page', { params })
export const addProjectRepository = (data) => request.post('/api/repository', data)
export const updateProjectRepository = (data) => request.put('/api/repository', data)
export const deleteProjectRepository = (id) => request.delete(`/api/repository/${id}`)
export const archiveProjectRepository = (id) => request.put(`/api/repository/archive/${id}`)
export const activateProjectRepository = (id) => request.put(`/api/repository/activate/${id}`)
export const getRepositoryBranchPage = (params) => request.get('/api/branch/page', { params })
export const addRepositoryBranch = (data) => request.post('/api/branch', data)
export const updateRepositoryBranch = (data) => request.put('/api/branch', data)
export const deleteRepositoryBranch = (id) => request.delete(`/api/branch/${id}`)
export const getDependencyPackagePage = (params) => request.get('/api/dependency/page', { params })
export const addDependencyPackage = (data) => request.post('/api/dependency', data)
export const updateDependencyPackage = (data) => request.put('/api/dependency', data)
export const deleteDependencyPackage = (id) => request.delete(`/api/dependency/${id}`)
export const getLicensePolicyPage = (params) => request.get('/api/policy/page', { params })
export const addLicensePolicy = (data) => request.post('/api/policy', data)
export const updateLicensePolicy = (data) => request.put('/api/policy', data)
export const deleteLicensePolicy = (id) => request.delete(`/api/policy/${id}`)
export const getComplianceBaselinePage = (params) => request.get('/api/baseline/page', { params })
export const addComplianceBaseline = (data) => request.post('/api/baseline', data)
export const updateComplianceBaseline = (data) => request.put('/api/baseline', data)
export const deleteComplianceBaseline = (id) => request.delete(`/api/baseline/${id}`)
export const getScanTaskPage = (params) => request.get('/api/scan-task/page', { params })
export const addScanTask = (data) => request.post('/api/scan-task', data)
export const updateScanTask = (data) => request.put('/api/scan-task', data)
export const deleteScanTask = (id) => request.delete(`/api/scan-task/${id}`)
export const startScanTask = (id) => request.put(`/api/scan-task/start/${id}`)
export const finishScanTask = (id) => request.put(`/api/scan-task/finish/${id}`)
export const failScanTask = (id) => request.put(`/api/scan-task/fail/${id}`)
export const getScanResultPage = (params) => request.get('/api/scan-result/page', { params })
export const addScanResult = (data) => request.post('/api/scan-result', data)
export const updateScanResult = (data) => request.put('/api/scan-result', data)
export const deleteScanResult = (id) => request.delete(`/api/scan-result/${id}`)
export const getRiskIssuePage = (params) => request.get('/api/issue/page', { params })
export const addRiskIssue = (data) => request.post('/api/issue', data)
export const updateRiskIssue = (data) => request.put('/api/issue', data)
export const deleteRiskIssue = (id) => request.delete(`/api/issue/${id}`)
export const confirmRiskIssue = (id) => request.put(`/api/issue/confirm/${id}`)
export const ignoreRiskIssue = (id) => request.put(`/api/issue/ignore/${id}`)
export const getRectificationTaskPage = (params) => request.get('/api/rectification/page', { params })
export const addRectificationTask = (data) => request.post('/api/rectification', data)
export const updateRectificationTask = (data) => request.put('/api/rectification', data)
export const deleteRectificationTask = (id) => request.delete(`/api/rectification/${id}`)
export const assignRectificationTask = (id) => request.put(`/api/rectification/assign/${id}`)
export const finishRectificationTask = (id) => request.put(`/api/rectification/finish/${id}`)
export const reopenRectificationTask = (id) => request.put(`/api/rectification/reopen/${id}`)
export const getAuditReportPage = (params) => request.get('/api/report/page', { params })
export const addAuditReport = (data) => request.post('/api/report', data)
export const updateAuditReport = (data) => request.put('/api/report', data)
export const deleteAuditReport = (id) => request.delete(`/api/report/${id}`)
export const publishAuditReport = (id) => request.put(`/api/report/publish/${id}`)
export const archiveAuditReport = (id) => request.put(`/api/report/archive/${id}`)
export const getApprovalRecordPage = (params) => request.get('/api/approval/page', { params })
export const addApprovalRecord = (data) => request.post('/api/approval', data)
export const updateApprovalRecord = (data) => request.put('/api/approval', data)
export const deleteApprovalRecord = (id) => request.delete(`/api/approval/${id}`)
export const approveApprovalRecord = (id) => request.put(`/api/approval/approve/${id}`)
export const rejectApprovalRecord = (id) => request.put(`/api/approval/reject/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
