import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getEquipmentAssetPage = (params) => request.get('/api/asset/page', { params })
export const addEquipmentAsset = (data) => request.post('/api/asset', data)
export const updateEquipmentAsset = (data) => request.put('/api/asset', data)
export const deleteEquipmentAsset = (id) => request.delete(`/api/asset/${id}`)
export const runEquipmentAsset = (id) => request.put(`/api/asset/run/${id}`)
export const stopEquipmentAsset = (id) => request.put(`/api/asset/stop/${id}`)
export const getSparePartCatalogPage = (params) => request.get('/api/catalog/page', { params })
export const addSparePartCatalog = (data) => request.post('/api/catalog', data)
export const updateSparePartCatalog = (data) => request.put('/api/catalog', data)
export const deleteSparePartCatalog = (id) => request.delete(`/api/catalog/${id}`)
export const enableSparePartCatalog = (id) => request.put(`/api/catalog/enable/${id}`)
export const disableSparePartCatalog = (id) => request.put(`/api/catalog/disable/${id}`)
export const getSparePartStockPage = (params) => request.get('/api/stock/page', { params })
export const addSparePartStock = (data) => request.post('/api/stock', data)
export const updateSparePartStock = (data) => request.put('/api/stock', data)
export const deleteSparePartStock = (id) => request.delete(`/api/stock/${id}`)
export const freezeSparePartStock = (id) => request.put(`/api/stock/freeze/${id}`)
export const releaseSparePartStock = (id) => request.put(`/api/stock/release/${id}`)
export const getSparePartInboundPage = (params) => request.get('/api/inbound/page', { params })
export const addSparePartInbound = (data) => request.post('/api/inbound', data)
export const updateSparePartInbound = (data) => request.put('/api/inbound', data)
export const deleteSparePartInbound = (id) => request.delete(`/api/inbound/${id}`)
export const checkSparePartInbound = (id) => request.put(`/api/inbound/check/${id}`)
export const finishSparePartInbound = (id) => request.put(`/api/inbound/finish/${id}`)
export const getSparePartOutboundPage = (params) => request.get('/api/outbound/page', { params })
export const addSparePartOutbound = (data) => request.post('/api/outbound', data)
export const updateSparePartOutbound = (data) => request.put('/api/outbound', data)
export const deleteSparePartOutbound = (id) => request.delete(`/api/outbound/${id}`)
export const approveSparePartOutbound = (id) => request.put(`/api/outbound/approve/${id}`)
export const issueSparePartOutbound = (id) => request.put(`/api/outbound/issue/${id}`)
export const getUsageRecordPage = (params) => request.get('/api/usage/page', { params })
export const addUsageRecord = (data) => request.post('/api/usage', data)
export const updateUsageRecord = (data) => request.put('/api/usage', data)
export const deleteUsageRecord = (id) => request.delete(`/api/usage/${id}`)
export const replaceUsageRecord = (id) => request.put(`/api/usage/replace/${id}`)
export const scrapUsageRecord = (id) => request.put(`/api/usage/scrap/${id}`)
export const getSensorMetricPage = (params) => request.get('/api/metric/page', { params })
export const addSensorMetric = (data) => request.post('/api/metric', data)
export const updateSensorMetric = (data) => request.put('/api/metric', data)
export const deleteSensorMetric = (id) => request.delete(`/api/metric/${id}`)
export const warnSensorMetric = (id) => request.put(`/api/metric/warn/${id}`)
export const recoverSensorMetric = (id) => request.put(`/api/metric/recover/${id}`)
export const getFailureRecordPage = (params) => request.get('/api/failure/page', { params })
export const addFailureRecord = (data) => request.post('/api/failure', data)
export const updateFailureRecord = (data) => request.put('/api/failure', data)
export const deleteFailureRecord = (id) => request.delete(`/api/failure/${id}`)
export const handleFailureRecord = (id) => request.put(`/api/failure/handle/${id}`)
export const closeFailureRecord = (id) => request.put(`/api/failure/close/${id}`)
export const getLifePredictionPage = (params) => request.get('/api/prediction/page', { params })
export const addLifePrediction = (data) => request.post('/api/prediction', data)
export const updateLifePrediction = (data) => request.put('/api/prediction', data)
export const deleteLifePrediction = (id) => request.delete(`/api/prediction/${id}`)
export const confirmLifePrediction = (id) => request.put(`/api/prediction/confirm/${id}`)
export const archiveLifePrediction = (id) => request.put(`/api/prediction/archive/${id}`)
export const getMaintenancePlanPage = (params) => request.get('/api/plan/page', { params })
export const addMaintenancePlan = (data) => request.post('/api/plan', data)
export const updateMaintenancePlan = (data) => request.put('/api/plan', data)
export const deleteMaintenancePlan = (id) => request.delete(`/api/plan/${id}`)
export const startMaintenancePlan = (id) => request.put(`/api/plan/start/${id}`)
export const finishMaintenancePlan = (id) => request.put(`/api/plan/finish/${id}`)
export const getProcurementRequestPage = (params) => request.get('/api/purchase/page', { params })
export const addProcurementRequest = (data) => request.post('/api/purchase', data)
export const updateProcurementRequest = (data) => request.put('/api/purchase', data)
export const deleteProcurementRequest = (id) => request.delete(`/api/purchase/${id}`)
export const approveProcurementRequest = (id) => request.put(`/api/purchase/approve/${id}`)
export const rejectProcurementRequest = (id) => request.put(`/api/purchase/reject/${id}`)
export const getRiskWarningPage = (params) => request.get('/api/warning/page', { params })
export const addRiskWarning = (data) => request.post('/api/warning', data)
export const updateRiskWarning = (data) => request.put('/api/warning', data)
export const deleteRiskWarning = (id) => request.delete(`/api/warning/${id}`)
export const assignRiskWarning = (id) => request.put(`/api/warning/assign/${id}`)
export const closeRiskWarning = (id) => request.put(`/api/warning/close/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
