import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const register = (data) => request.post('/api/auth/register', data)
export const getUserInfo = () => request.get('/api/auth/info')
export const updatePassword = (data) => request.put('/api/auth/password', data)
export const logout = () => request.post('/api/auth/logout')

export const getUserPage = (params) => request.get('/api/user/page', { params })
export const addUser = (data) => request.post('/api/user', data)
export const updateUser = (data) => request.put('/api/user', data)
export const updateUserStatus = (data) => request.put('/api/user/status', data)
export const updateProfile = (data) => request.put('/api/user/profile', data)
export const deleteUser = (id) => request.delete(`/api/user/${id}`)

export const getSubjectList = () => request.get('/api/subject/list')
export const getSubjectPage = (params) => request.get('/api/subject/page', { params })
export const addSubject = (data) => request.post('/api/subject', data)
export const updateSubject = (data) => request.put('/api/subject', data)
export const updateSubjectStatus = (data) => request.put('/api/subject/status', data)
export const deleteSubject = (id) => request.delete(`/api/subject/${id}`)

export const getClassList = () => request.get('/api/class/list')
export const getClassPage = (params) => request.get('/api/class/page', { params })
export const addClass = (data) => request.post('/api/class', data)
export const updateClass = (data) => request.put('/api/class', data)
export const updateClassStatus = (data) => request.put('/api/class/status', data)
export const deleteClass = (id) => request.delete(`/api/class/${id}`)

export const getTeacherList = () => request.get('/api/teacher/list')
export const getTeacherPage = (params) => request.get('/api/teacher/page', { params })
export const addTeacher = (data) => request.post('/api/teacher', data)
export const updateTeacher = (data) => request.put('/api/teacher', data)
export const updateTeacherStatus = (data) => request.put('/api/teacher/status', data)
export const deleteTeacher = (id) => request.delete(`/api/teacher/${id}`)

export const getIndicatorList = () => request.get('/api/indicator/list')
export const getIndicatorPage = (params) => request.get('/api/indicator/page', { params })
export const addIndicator = (data) => request.post('/api/indicator', data)
export const updateIndicator = (data) => request.put('/api/indicator', data)
export const updateIndicatorStatus = (data) => request.put('/api/indicator/status', data)
export const deleteIndicator = (id) => request.delete(`/api/indicator/${id}`)

export const getTaskPage = (params) => request.get('/api/task/page', { params })
export const getMyTaskPage = (params) => request.get('/api/task/my-page', { params })
export const addTask = (data) => request.post('/api/task', data)
export const updateTask = (data) => request.put('/api/task', data)
export const updateTaskStatus = (data) => request.put('/api/task/status', data)
export const deleteTask = (id) => request.delete(`/api/task/${id}`)

export const getRecordPage = (params) => request.get('/api/record/page', { params })
export const getMyRecordPage = (params) => request.get('/api/record/my-page', { params })
export const addRecord = (data) => request.post('/api/record', data)
export const deleteRecord = (id) => request.delete(`/api/record/${id}`)

export const getAppealPage = (params) => request.get('/api/appeal/page', { params })
export const getMyAppealPage = (params) => request.get('/api/appeal/my-page', { params })
export const addAppeal = (data) => request.post('/api/appeal', data)
export const handleAppeal = (data) => request.put('/api/appeal/handle', data)

export const getNoticeList = () => request.get('/api/notice/list')
export const getNoticePage = (params) => request.get('/api/notice/page', { params })
export const addNotice = (data) => request.post('/api/notice', data)
export const updateNotice = (data) => request.put('/api/notice', data)
export const updateNoticeStatus = (data) => request.put('/api/notice/status', data)
export const deleteNotice = (id) => request.delete(`/api/notice/${id}`)

export const getDashboardStats = () => request.get('/api/dashboard/stats')
export const getDashboardTrend = () => request.get('/api/dashboard/trend')
