import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getTrainingCoursePage = (params) => request.get('/api/course/page', { params })
export const addTrainingCourse = (data) => request.post('/api/course', data)
export const updateTrainingCourse = (data) => request.put('/api/course', data)
export const deleteTrainingCourse = (id) => request.delete(`/api/course/${id}`)
export const processTrainingCourse = (id) => request.put(`/api/course/process/${id}`)
export const finishTrainingCourse = (id) => request.put(`/api/course/finish/${id}`)

export const getTraineeProfilePage = (params) => request.get('/api/trainee/page', { params })
export const addTraineeProfile = (data) => request.post('/api/trainee', data)
export const updateTraineeProfile = (data) => request.put('/api/trainee', data)
export const deleteTraineeProfile = (id) => request.delete(`/api/trainee/${id}`)
export const processTraineeProfile = (id) => request.put(`/api/trainee/process/${id}`)
export const finishTraineeProfile = (id) => request.put(`/api/trainee/finish/${id}`)

export const getInstructorProfilePage = (params) => request.get('/api/instructor/page', { params })
export const addInstructorProfile = (data) => request.post('/api/instructor', data)
export const updateInstructorProfile = (data) => request.put('/api/instructor', data)
export const deleteInstructorProfile = (id) => request.delete(`/api/instructor/${id}`)
export const processInstructorProfile = (id) => request.put(`/api/instructor/process/${id}`)
export const finishInstructorProfile = (id) => request.put(`/api/instructor/finish/${id}`)

export const getCourseEnrollmentPage = (params) => request.get('/api/enrollment/page', { params })
export const addCourseEnrollment = (data) => request.post('/api/enrollment', data)
export const updateCourseEnrollment = (data) => request.put('/api/enrollment', data)
export const deleteCourseEnrollment = (id) => request.delete(`/api/enrollment/${id}`)
export const processCourseEnrollment = (id) => request.put(`/api/enrollment/process/${id}`)
export const finishCourseEnrollment = (id) => request.put(`/api/enrollment/finish/${id}`)

export const getLearningProgressPage = (params) => request.get('/api/progress/page', { params })
export const addLearningProgress = (data) => request.post('/api/progress', data)
export const updateLearningProgress = (data) => request.put('/api/progress', data)
export const deleteLearningProgress = (id) => request.delete(`/api/progress/${id}`)
export const processLearningProgress = (id) => request.put(`/api/progress/process/${id}`)
export const finishLearningProgress = (id) => request.put(`/api/progress/finish/${id}`)

export const getExamPlanPage = (params) => request.get('/api/exam/page', { params })
export const addExamPlan = (data) => request.post('/api/exam', data)
export const updateExamPlan = (data) => request.put('/api/exam', data)
export const deleteExamPlan = (id) => request.delete(`/api/exam/${id}`)
export const processExamPlan = (id) => request.put(`/api/exam/process/${id}`)
export const finishExamPlan = (id) => request.put(`/api/exam/finish/${id}`)

export const getExamScorePage = (params) => request.get('/api/score/page', { params })
export const addExamScore = (data) => request.post('/api/score', data)
export const updateExamScore = (data) => request.put('/api/score', data)
export const deleteExamScore = (id) => request.delete(`/api/score/${id}`)
export const processExamScore = (id) => request.put(`/api/score/process/${id}`)
export const finishExamScore = (id) => request.put(`/api/score/finish/${id}`)

export const getCertificateIssuePage = (params) => request.get('/api/certificate/page', { params })
export const addCertificateIssue = (data) => request.post('/api/certificate', data)
export const updateCertificateIssue = (data) => request.put('/api/certificate', data)
export const deleteCertificateIssue = (id) => request.delete(`/api/certificate/${id}`)
export const processCertificateIssue = (id) => request.put(`/api/certificate/process/${id}`)
export const finishCertificateIssue = (id) => request.put(`/api/certificate/finish/${id}`)

export const getCertificateLedgerPage = (params) => request.get('/api/ledger/page', { params })
export const addCertificateLedger = (data) => request.post('/api/ledger', data)
export const updateCertificateLedger = (data) => request.put('/api/ledger', data)
export const deleteCertificateLedger = (id) => request.delete(`/api/ledger/${id}`)
export const processCertificateLedger = (id) => request.put(`/api/ledger/process/${id}`)
export const finishCertificateLedger = (id) => request.put(`/api/ledger/finish/${id}`)

export const getRenewalApplicationPage = (params) => request.get('/api/renewal/page', { params })
export const addRenewalApplication = (data) => request.post('/api/renewal', data)
export const updateRenewalApplication = (data) => request.put('/api/renewal', data)
export const deleteRenewalApplication = (id) => request.delete(`/api/renewal/${id}`)
export const processRenewalApplication = (id) => request.put(`/api/renewal/process/${id}`)
export const finishRenewalApplication = (id) => request.put(`/api/renewal/finish/${id}`)

export const getReminderNoticePage = (params) => request.get('/api/reminder/page', { params })
export const addReminderNotice = (data) => request.post('/api/reminder', data)
export const updateReminderNotice = (data) => request.put('/api/reminder', data)
export const deleteReminderNotice = (id) => request.delete(`/api/reminder/${id}`)
export const processReminderNotice = (id) => request.put(`/api/reminder/process/${id}`)
export const finishReminderNotice = (id) => request.put(`/api/reminder/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
