import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getExamItemPage = (params) => request.get('/api/checkin/page', { params })
export const addExamItem = (data) => request.post('/api/checkin', data)
export const updateExamItem = (data) => request.put('/api/checkin', data)
export const deleteExamItem = (id) => request.delete(`/api/checkin/${id}`)
export const activateExamItem = (id) => request.put(`/api/checkin/activate/${id}`)
export const finishExamItem = (id) => request.put(`/api/checkin/finish/${id}`)
export const getPatientProfilePage = (params) => request.get('/api/patient/page', { params })
export const addPatientProfile = (data) => request.post('/api/patient', data)
export const updatePatientProfile = (data) => request.put('/api/patient', data)
export const deletePatientProfile = (id) => request.delete(`/api/patient/${id}`)
export const activatePatientProfile = (id) => request.put(`/api/patient/activate/${id}`)
export const finishPatientProfile = (id) => request.put(`/api/patient/finish/${id}`)
export const getDoctorProfilePage = (params) => request.get('/api/doctor/page', { params })
export const addDoctorProfile = (data) => request.post('/api/doctor', data)
export const updateDoctorProfile = (data) => request.put('/api/doctor', data)
export const deleteDoctorProfile = (id) => request.delete(`/api/doctor/${id}`)
export const processDoctorProfile = (id) => request.put(`/api/doctor/process/${id}`)
export const finishDoctorProfile = (id) => request.put(`/api/doctor/finish/${id}`)
export const getExamAppointmentPage = (params) => request.get('/api/report/page', { params })
export const addExamAppointment = (data) => request.post('/api/report', data)
export const updateExamAppointment = (data) => request.put('/api/report', data)
export const deleteExamAppointment = (id) => request.delete(`/api/report/${id}`)
export const submitExamAppointment = (id) => request.put(`/api/report/submit/${id}`)
export const approveExamAppointment = (id) => request.put(`/api/report/approve/${id}`)
export const getExamDepartmentPage = (params) => request.get('/api/department/page', { params })
export const addExamDepartment = (data) => request.post('/api/department', data)
export const updateExamDepartment = (data) => request.put('/api/department', data)
export const deleteExamDepartment = (id) => request.delete(`/api/department/${id}`)
export const submitExamDepartment = (id) => request.put(`/api/department/submit/${id}`)
export const approveExamDepartment = (id) => request.put(`/api/department/approve/${id}`)
export const getCheckinRecordPage = (params) => request.get('/api/checkin/page', { params })
export const addCheckinRecord = (data) => request.post('/api/checkin', data)
export const updateCheckinRecord = (data) => request.put('/api/checkin', data)
export const deleteCheckinRecord = (id) => request.delete(`/api/checkin/${id}`)
export const submitCheckinRecord = (id) => request.put(`/api/checkin/submit/${id}`)
export const approveCheckinRecord = (id) => request.put(`/api/checkin/approve/${id}`)
export const getExamReportPage = (params) => request.get('/api/report/page', { params })
export const addExamReport = (data) => request.post('/api/report', data)
export const updateExamReport = (data) => request.put('/api/report', data)
export const deleteExamReport = (id) => request.delete(`/api/report/${id}`)
export const processExamReport = (id) => request.put(`/api/report/process/${id}`)
export const finishExamReport = (id) => request.put(`/api/report/finish/${id}`)
export const getAbnormalAlertPage = (params) => request.get('/api/queue/page', { params })
export const addAbnormalAlert = (data) => request.post('/api/queue', data)
export const updateAbnormalAlert = (data) => request.put('/api/queue', data)
export const deleteAbnormalAlert = (id) => request.delete(`/api/queue/${id}`)
export const activateAbnormalAlert = (id) => request.put(`/api/queue/activate/${id}`)
export const finishAbnormalAlert = (id) => request.put(`/api/queue/finish/${id}`)
export const getReportDeliveryPage = (params) => request.get('/api/delivery/page', { params })
export const addReportDelivery = (data) => request.post('/api/delivery', data)
export const updateReportDelivery = (data) => request.put('/api/delivery', data)
export const deleteReportDelivery = (id) => request.delete(`/api/delivery/${id}`)
export const activateReportDelivery = (id) => request.put(`/api/delivery/activate/${id}`)
export const finishReportDelivery = (id) => request.put(`/api/delivery/finish/${id}`)
export const getRevisitAdvicePage = (params) => request.get('/api/advice/page', { params })
export const addRevisitAdvice = (data) => request.post('/api/advice', data)
export const updateRevisitAdvice = (data) => request.put('/api/advice', data)
export const deleteRevisitAdvice = (id) => request.delete(`/api/advice/${id}`)
export const activateRevisitAdvice = (id) => request.put(`/api/advice/activate/${id}`)
export const finishRevisitAdvice = (id) => request.put(`/api/advice/finish/${id}`)
export const getQueueCallPage = (params) => request.get('/api/queue/page', { params })
export const addQueueCall = (data) => request.post('/api/queue', data)
export const updateQueueCall = (data) => request.put('/api/queue', data)
export const deleteQueueCall = (id) => request.delete(`/api/queue/${id}`)
export const processQueueCall = (id) => request.put(`/api/queue/process/${id}`)
export const finishQueueCall = (id) => request.put(`/api/queue/finish/${id}`)
export const getHospitalNoticePage = (params) => request.get('/api/notice/page', { params })
export const addHospitalNotice = (data) => request.post('/api/notice', data)
export const updateHospitalNotice = (data) => request.put('/api/notice', data)
export const deleteHospitalNotice = (id) => request.delete(`/api/notice/${id}`)
export const processHospitalNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishHospitalNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)









