import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getInnovationProgramPage = (params) => request.get('/api/program/page', { params })
export const addInnovationProgram = (data) => request.post('/api/program', data)
export const updateInnovationProgram = (data) => request.put('/api/program', data)
export const deleteInnovationProgram = (id) => request.delete(`/api/program/${id}`)
export const processInnovationProgram = (id) => request.put(`/api/program/process/${id}`)
export const finishInnovationProgram = (id) => request.put(`/api/program/finish/${id}`)

export const getStudentProfilePage = (params) => request.get('/api/student/page', { params })
export const addStudentProfile = (data) => request.post('/api/student', data)
export const updateStudentProfile = (data) => request.put('/api/student', data)
export const deleteStudentProfile = (id) => request.delete(`/api/student/${id}`)
export const processStudentProfile = (id) => request.put(`/api/student/process/${id}`)
export const finishStudentProfile = (id) => request.put(`/api/student/finish/${id}`)

export const getMentorProfilePage = (params) => request.get('/api/mentor/page', { params })
export const addMentorProfile = (data) => request.post('/api/mentor', data)
export const updateMentorProfile = (data) => request.put('/api/mentor', data)
export const deleteMentorProfile = (id) => request.delete(`/api/mentor/${id}`)
export const processMentorProfile = (id) => request.put(`/api/mentor/process/${id}`)
export const finishMentorProfile = (id) => request.put(`/api/mentor/finish/${id}`)

export const getSelectionNoticePage = (params) => request.get('/api/notice/page', { params })
export const addSelectionNotice = (data) => request.post('/api/notice', data)
export const updateSelectionNotice = (data) => request.put('/api/notice', data)
export const deleteSelectionNotice = (id) => request.delete(`/api/notice/${id}`)
export const processSelectionNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishSelectionNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getApplicationRegistrationPage = (params) => request.get('/api/application/page', { params })
export const addApplicationRegistration = (data) => request.post('/api/application', data)
export const updateApplicationRegistration = (data) => request.put('/api/application', data)
export const deleteApplicationRegistration = (id) => request.delete(`/api/application/${id}`)
export const processApplicationRegistration = (id) => request.put(`/api/application/process/${id}`)
export const finishApplicationRegistration = (id) => request.put(`/api/application/finish/${id}`)

export const getSelectionReviewPage = (params) => request.get('/api/review/page', { params })
export const addSelectionReview = (data) => request.post('/api/review', data)
export const updateSelectionReview = (data) => request.put('/api/review', data)
export const deleteSelectionReview = (id) => request.delete(`/api/review/${id}`)
export const processSelectionReview = (id) => request.put(`/api/review/process/${id}`)
export const finishSelectionReview = (id) => request.put(`/api/review/finish/${id}`)

export const getInterviewAssessmentPage = (params) => request.get('/api/interview/page', { params })
export const addInterviewAssessment = (data) => request.post('/api/interview', data)
export const updateInterviewAssessment = (data) => request.put('/api/interview', data)
export const deleteInterviewAssessment = (id) => request.delete(`/api/interview/${id}`)
export const processInterviewAssessment = (id) => request.put(`/api/interview/process/${id}`)
export const finishInterviewAssessment = (id) => request.put(`/api/interview/finish/${id}`)

export const getMentorMatchPage = (params) => request.get('/api/match/page', { params })
export const addMentorMatch = (data) => request.post('/api/match', data)
export const updateMentorMatch = (data) => request.put('/api/match', data)
export const deleteMentorMatch = (id) => request.delete(`/api/match/${id}`)
export const processMentorMatch = (id) => request.put(`/api/match/process/${id}`)
export const finishMentorMatch = (id) => request.put(`/api/match/finish/${id}`)

export const getTrainingPlanPage = (params) => request.get('/api/plan/page', { params })
export const addTrainingPlan = (data) => request.post('/api/plan', data)
export const updateTrainingPlan = (data) => request.put('/api/plan', data)
export const deleteTrainingPlan = (id) => request.delete(`/api/plan/${id}`)
export const processTrainingPlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishTrainingPlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getProcessTrackingPage = (params) => request.get('/api/tracking/page', { params })
export const addProcessTracking = (data) => request.post('/api/tracking', data)
export const updateProcessTracking = (data) => request.put('/api/tracking', data)
export const deleteProcessTracking = (id) => request.delete(`/api/tracking/${id}`)
export const processProcessTracking = (id) => request.put(`/api/tracking/process/${id}`)
export const finishProcessTracking = (id) => request.put(`/api/tracking/finish/${id}`)

export const getAchievementArchivePage = (params) => request.get('/api/achievement/page', { params })
export const addAchievementArchive = (data) => request.post('/api/achievement', data)
export const updateAchievementArchive = (data) => request.put('/api/achievement', data)
export const deleteAchievementArchive = (id) => request.delete(`/api/achievement/${id}`)
export const processAchievementArchive = (id) => request.put(`/api/achievement/process/${id}`)
export const finishAchievementArchive = (id) => request.put(`/api/achievement/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
