DROP TABLE IF EXISTS blog_notice;
DROP TABLE IF EXISTS blog_comment;
DROP TABLE IF EXISTS blog_post_tag;
DROP TABLE IF EXISTS blog_post;
DROP TABLE IF EXISTS blog_tag;
DROP TABLE IF EXISTS blog_category;
DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    nickname VARCHAR(50),
    avatar VARCHAR(255),
    email VARCHAR(100),
    role VARCHAR(20) DEFAULT 'USER',
    status INT DEFAULT 1,
    last_login_time TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blog_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    sort INT DEFAULT 0,
    status INT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blog_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    status INT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blog_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    summary VARCHAR(300),
    content CLOB NOT NULL,
    cover VARCHAR(255),
    category_id BIGINT,
    author_id BIGINT NOT NULL,
    status INT DEFAULT 0,
    is_top INT DEFAULT 0,
    view_count BIGINT DEFAULT 0,
    comment_count INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_post_category ON blog_post(category_id);
CREATE INDEX idx_post_author ON blog_post(author_id);
CREATE INDEX idx_post_status ON blog_post(status);

CREATE TABLE blog_post_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT uk_post_tag UNIQUE(post_id, tag_id)
);
CREATE INDEX idx_pt_post ON blog_post_tag(post_id);
CREATE INDEX idx_pt_tag ON blog_post_tag(tag_id);

CREATE TABLE blog_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content VARCHAR(500) NOT NULL,
    status INT DEFAULT 0,
    reply_content VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_comment_post ON blog_comment(post_id);
CREATE INDEX idx_comment_user ON blog_comment(user_id);
CREATE INDEX idx_comment_status ON blog_comment(status);

CREATE TABLE blog_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content CLOB NOT NULL,
    status INT DEFAULT 1,
    admin_id BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
