import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getAnimalRoomPage = (params) => request.get('/api/room/page', { params })
export const addAnimalRoom = (data) => request.post('/api/room', data)
export const updateAnimalRoom = (data) => request.put('/api/room', data)
export const deleteAnimalRoom = (id) => request.delete(`/api/room/${id}`)
export const processAnimalRoom = (id) => request.put(`/api/room/process/${id}`)
export const finishAnimalRoom = (id) => request.put(`/api/room/finish/${id}`)

export const getAnimalProfilePage = (params) => request.get('/api/animal/page', { params })
export const addAnimalProfile = (data) => request.post('/api/animal', data)
export const updateAnimalProfile = (data) => request.put('/api/animal', data)
export const deleteAnimalProfile = (id) => request.delete(`/api/animal/${id}`)
export const processAnimalProfile = (id) => request.put(`/api/animal/process/${id}`)
export const finishAnimalProfile = (id) => request.put(`/api/animal/finish/${id}`)

export const getFeedingSchedulePage = (params) => request.get('/api/schedule/page', { params })
export const addFeedingSchedule = (data) => request.post('/api/schedule', data)
export const updateFeedingSchedule = (data) => request.put('/api/schedule', data)
export const deleteFeedingSchedule = (id) => request.delete(`/api/schedule/${id}`)
export const processFeedingSchedule = (id) => request.put(`/api/schedule/process/${id}`)
export const finishFeedingSchedule = (id) => request.put(`/api/schedule/finish/${id}`)

export const getFeedingRecordPage = (params) => request.get('/api/feeding/page', { params })
export const addFeedingRecord = (data) => request.post('/api/feeding', data)
export const updateFeedingRecord = (data) => request.put('/api/feeding', data)
export const deleteFeedingRecord = (id) => request.delete(`/api/feeding/${id}`)
export const processFeedingRecord = (id) => request.put(`/api/feeding/process/${id}`)
export const finishFeedingRecord = (id) => request.put(`/api/feeding/finish/${id}`)

export const getEthicsApplicationPage = (params) => request.get('/api/ethics/page', { params })
export const addEthicsApplication = (data) => request.post('/api/ethics', data)
export const updateEthicsApplication = (data) => request.put('/api/ethics', data)
export const deleteEthicsApplication = (id) => request.delete(`/api/ethics/${id}`)
export const processEthicsApplication = (id) => request.put(`/api/ethics/process/${id}`)
export const finishEthicsApplication = (id) => request.put(`/api/ethics/finish/${id}`)

export const getEthicsReviewPage = (params) => request.get('/api/review/page', { params })
export const addEthicsReview = (data) => request.post('/api/review', data)
export const updateEthicsReview = (data) => request.put('/api/review', data)
export const deleteEthicsReview = (id) => request.delete(`/api/review/${id}`)
export const processEthicsReview = (id) => request.put(`/api/review/process/${id}`)
export const finishEthicsReview = (id) => request.put(`/api/review/finish/${id}`)

export const getExperimentRegistrationPage = (params) => request.get('/api/experiment/page', { params })
export const addExperimentRegistration = (data) => request.post('/api/experiment', data)
export const updateExperimentRegistration = (data) => request.put('/api/experiment', data)
export const deleteExperimentRegistration = (id) => request.delete(`/api/experiment/${id}`)
export const processExperimentRegistration = (id) => request.put(`/api/experiment/process/${id}`)
export const finishExperimentRegistration = (id) => request.put(`/api/experiment/finish/${id}`)

export const getHealthInspectionPage = (params) => request.get('/api/health/page', { params })
export const addHealthInspection = (data) => request.post('/api/health', data)
export const updateHealthInspection = (data) => request.put('/api/health', data)
export const deleteHealthInspection = (id) => request.delete(`/api/health/${id}`)
export const processHealthInspection = (id) => request.put(`/api/health/process/${id}`)
export const finishHealthInspection = (id) => request.put(`/api/health/finish/${id}`)

export const getAbnormalAlertPage = (params) => request.get('/api/alert/page', { params })
export const addAbnormalAlert = (data) => request.post('/api/alert', data)
export const updateAbnormalAlert = (data) => request.put('/api/alert', data)
export const deleteAbnormalAlert = (id) => request.delete(`/api/alert/${id}`)
export const processAbnormalAlert = (id) => request.put(`/api/alert/process/${id}`)
export const finishAbnormalAlert = (id) => request.put(`/api/alert/finish/${id}`)

export const getVeterinaryTreatmentPage = (params) => request.get('/api/treatment/page', { params })
export const addVeterinaryTreatment = (data) => request.post('/api/treatment', data)
export const updateVeterinaryTreatment = (data) => request.put('/api/treatment', data)
export const deleteVeterinaryTreatment = (id) => request.delete(`/api/treatment/${id}`)
export const processVeterinaryTreatment = (id) => request.put(`/api/treatment/process/${id}`)
export const finishVeterinaryTreatment = (id) => request.put(`/api/treatment/finish/${id}`)

export const getMaterialUsagePage = (params) => request.get('/api/material/page', { params })
export const addMaterialUsage = (data) => request.post('/api/material', data)
export const updateMaterialUsage = (data) => request.put('/api/material', data)
export const deleteMaterialUsage = (id) => request.delete(`/api/material/${id}`)
export const processMaterialUsage = (id) => request.put(`/api/material/process/${id}`)
export const finishMaterialUsage = (id) => request.put(`/api/material/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
