import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getClinicRoomPage = (params) => request.get('/api/room/page', { params })
export const addClinicRoom = (data) => request.post('/api/room', data)
export const updateClinicRoom = (data) => request.put('/api/room', data)
export const deleteClinicRoom = (id) => request.delete(`/api/room/${id}`)
export const processClinicRoom = (id) => request.put(`/api/room/process/${id}`)
export const finishClinicRoom = (id) => request.put(`/api/room/finish/${id}`)

export const getDentistProfilePage = (params) => request.get('/api/dentist/page', { params })
export const addDentistProfile = (data) => request.post('/api/dentist', data)
export const updateDentistProfile = (data) => request.put('/api/dentist', data)
export const deleteDentistProfile = (id) => request.delete(`/api/dentist/${id}`)
export const processDentistProfile = (id) => request.put(`/api/dentist/process/${id}`)
export const finishDentistProfile = (id) => request.put(`/api/dentist/finish/${id}`)

export const getPatientProfilePage = (params) => request.get('/api/patient/page', { params })
export const addPatientProfile = (data) => request.post('/api/patient', data)
export const updatePatientProfile = (data) => request.put('/api/patient', data)
export const deletePatientProfile = (id) => request.delete(`/api/patient/${id}`)
export const processPatientProfile = (id) => request.put(`/api/patient/process/${id}`)
export const finishPatientProfile = (id) => request.put(`/api/patient/finish/${id}`)

export const getTreatmentCatalogPage = (params) => request.get('/api/treatment/page', { params })
export const addTreatmentCatalog = (data) => request.post('/api/treatment', data)
export const updateTreatmentCatalog = (data) => request.put('/api/treatment', data)
export const deleteTreatmentCatalog = (id) => request.delete(`/api/treatment/${id}`)
export const processTreatmentCatalog = (id) => request.put(`/api/treatment/process/${id}`)
export const finishTreatmentCatalog = (id) => request.put(`/api/treatment/finish/${id}`)

export const getAppointmentOrderPage = (params) => request.get('/api/appointment/page', { params })
export const addAppointmentOrder = (data) => request.post('/api/appointment', data)
export const updateAppointmentOrder = (data) => request.put('/api/appointment', data)
export const deleteAppointmentOrder = (id) => request.delete(`/api/appointment/${id}`)
export const processAppointmentOrder = (id) => request.put(`/api/appointment/process/${id}`)
export const finishAppointmentOrder = (id) => request.put(`/api/appointment/finish/${id}`)

export const getCheckinTriagePage = (params) => request.get('/api/triage/page', { params })
export const addCheckinTriage = (data) => request.post('/api/triage', data)
export const updateCheckinTriage = (data) => request.put('/api/triage', data)
export const deleteCheckinTriage = (id) => request.delete(`/api/triage/${id}`)
export const processCheckinTriage = (id) => request.put(`/api/triage/process/${id}`)
export const finishCheckinTriage = (id) => request.put(`/api/triage/finish/${id}`)

export const getTreatmentRecordPage = (params) => request.get('/api/treatment-record/page', { params })
export const addTreatmentRecord = (data) => request.post('/api/treatment-record', data)
export const updateTreatmentRecord = (data) => request.put('/api/treatment-record', data)
export const deleteTreatmentRecord = (id) => request.delete(`/api/treatment-record/${id}`)
export const processTreatmentRecord = (id) => request.put(`/api/treatment-record/process/${id}`)
export const finishTreatmentRecord = (id) => request.put(`/api/treatment-record/finish/${id}`)

export const getConsumableCatalogPage = (params) => request.get('/api/consumable/page', { params })
export const addConsumableCatalog = (data) => request.post('/api/consumable', data)
export const updateConsumableCatalog = (data) => request.put('/api/consumable', data)
export const deleteConsumableCatalog = (id) => request.delete(`/api/consumable/${id}`)
export const processConsumableCatalog = (id) => request.put(`/api/consumable/process/${id}`)
export const finishConsumableCatalog = (id) => request.put(`/api/consumable/finish/${id}`)

export const getConsumableStockPage = (params) => request.get('/api/stock/page', { params })
export const addConsumableStock = (data) => request.post('/api/stock', data)
export const updateConsumableStock = (data) => request.put('/api/stock', data)
export const deleteConsumableStock = (id) => request.delete(`/api/stock/${id}`)
export const processConsumableStock = (id) => request.put(`/api/stock/process/${id}`)
export const finishConsumableStock = (id) => request.put(`/api/stock/finish/${id}`)

export const getConsumableUsagePage = (params) => request.get('/api/usage/page', { params })
export const addConsumableUsage = (data) => request.post('/api/usage', data)
export const updateConsumableUsage = (data) => request.put('/api/usage', data)
export const deleteConsumableUsage = (id) => request.delete(`/api/usage/${id}`)
export const processConsumableUsage = (id) => request.put(`/api/usage/process/${id}`)
export const finishConsumableUsage = (id) => request.put(`/api/usage/finish/${id}`)

export const getBillingRecordPage = (params) => request.get('/api/billing/page', { params })
export const addBillingRecord = (data) => request.post('/api/billing', data)
export const updateBillingRecord = (data) => request.put('/api/billing', data)
export const deleteBillingRecord = (id) => request.delete(`/api/billing/${id}`)
export const processBillingRecord = (id) => request.put(`/api/billing/process/${id}`)
export const finishBillingRecord = (id) => request.put(`/api/billing/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
