import request from './request'

export const login = data => request.post('/auth/login', data)
export const register = data => request.post('/auth/register', data)
export const getInfo = () => request.get('/auth/info')
export const updatePassword = data => request.put('/auth/password', data)
export const logout = () => request.post('/auth/logout')

export const getUserList = params => request.get('/user/list', { params })
export const getUserDetail = id => request.get(`/user/${id}`)
export const saveUser = data => request.post('/user/save', data)
export const updateUserStatus = (id, status) => request.put(`/user/status/${id}/${status}`)
export const deleteUser = id => request.delete(`/user/${id}`)
export const updateProfile = data => request.put('/user/profile', data)

export const getPublicMovieList = params => request.get('/movie/public/list', { params })
export const getRecommendMovieList = params => request.get('/movie/public/recommend', { params })
export const getMovieDetail = id => request.get(`/movie/public/${id}`)
export const getMovieList = params => request.get('/movie/list', { params })
export const saveMovie = data => request.post('/movie/save', data)
export const deleteMovie = id => request.delete(`/movie/${id}`)

export const getPublicCinemaList = () => request.get('/cinema/public/list')
export const getCinemaList = params => request.get('/cinema/list', { params })
export const getCinemaDetail = id => request.get(`/cinema/${id}`)
export const saveCinema = data => request.post('/cinema/save', data)
export const deleteCinema = id => request.delete(`/cinema/${id}`)

export const getPublicHallList = params => request.get('/hall/public/list', { params })
export const getHallList = params => request.get('/hall/list', { params })
export const getHallDetail = id => request.get(`/hall/${id}`)
export const saveHall = data => request.post('/hall/save', data)
export const deleteHall = id => request.delete(`/hall/${id}`)

export const getPublicShowtimeList = params => request.get('/showtime/public/list', { params })
export const getPublicShowtimeDetail = id => request.get(`/showtime/public/${id}`)
export const getShowtimeList = params => request.get('/showtime/list', { params })
export const saveShowtime = data => request.post('/showtime/save', data)
export const deleteShowtime = id => request.delete(`/showtime/${id}`)

export const getSeatList = showtimeId => request.get(`/seat/showtime/${showtimeId}`)
export const lockSeat = data => request.post('/seat/lock', data)
export const unlockSeat = data => request.post('/seat/unlock', data)

export const createOrder = data => request.post('/order/create', data)
export const getMyOrderList = params => request.get('/order/my', { params })
export const getOrderList = params => request.get('/order/list', { params })
export const getOrderDetail = id => request.get(`/order/${id}`)
export const cancelOrder = id => request.put(`/order/cancel/${id}`)
export const finishOrder = id => request.put(`/order/finish/${id}`)
export const refundOrder = id => request.put(`/order/refund/${id}`)

export const createPayment = data => request.post('/payment/create', data)
export const balancePay = data => request.post('/payment/balance', data)
export const recharge = data => request.post('/payment/recharge', data)
export const getPaymentList = params => request.get('/payment/list', { params })

export const getMyTicketList = params => request.get('/ticket/my', { params })
export const getTicketList = params => request.get('/ticket/list', { params })
export const getTicketDetail = id => request.get(`/ticket/${id}`)
export const verifyTicket = data => request.post('/ticket/verify', data)

export const getPublicCommentList = (movieId, params) => request.get(`/comment/public/movie/${movieId}`, { params })
export const getCommentList = params => request.get('/comment/list', { params })
export const addComment = data => request.post('/comment/add', data)
export const auditComment = (id, status) => request.put(`/comment/audit/${id}/${status}`)
export const deleteComment = id => request.delete(`/comment/${id}`)

export const getPublicCouponList = () => request.get('/coupon/public/list')
export const getCouponList = params => request.get('/coupon/list', { params })
export const saveCoupon = data => request.post('/coupon/save', data)
export const deleteCoupon = id => request.delete(`/coupon/${id}`)
export const receiveCoupon = id => request.post(`/coupon/receive/${id}`)
export const getMyCouponList = params => request.get('/coupon/my', { params })
export const getAvailableCouponList = params => request.get('/coupon/available', { params })

export const getDashboardStats = () => request.get('/statistics/dashboard')
export const getSalesTrend = params => request.get('/statistics/sales-trend', { params })
export const getBoxOffice = () => request.get('/statistics/box-office')
