import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getCommunityClinicPage = (params) => request.get('/api/clinic/page', { params })
export const addCommunityClinic = (data) => request.post('/api/clinic', data)
export const updateCommunityClinic = (data) => request.put('/api/clinic', data)
export const deleteCommunityClinic = (id) => request.delete(`/api/clinic/${id}`)
export const processCommunityClinic = (id) => request.put(`/api/clinic/process/${id}`)
export const finishCommunityClinic = (id) => request.put(`/api/clinic/finish/${id}`)

export const getChronicPatientPage = (params) => request.get('/api/patient/page', { params })
export const addChronicPatient = (data) => request.post('/api/patient', data)
export const updateChronicPatient = (data) => request.put('/api/patient', data)
export const deleteChronicPatient = (id) => request.delete(`/api/patient/${id}`)
export const processChronicPatient = (id) => request.put(`/api/patient/process/${id}`)
export const finishChronicPatient = (id) => request.put(`/api/patient/finish/${id}`)

export const getDoctorTeamPage = (params) => request.get('/api/team/page', { params })
export const addDoctorTeam = (data) => request.post('/api/team', data)
export const updateDoctorTeam = (data) => request.put('/api/team', data)
export const deleteDoctorTeam = (id) => request.delete(`/api/team/${id}`)
export const processDoctorTeam = (id) => request.put(`/api/team/process/${id}`)
export const finishDoctorTeam = (id) => request.put(`/api/team/finish/${id}`)

export const getDiseaseArchivePage = (params) => request.get('/api/disease/page', { params })
export const addDiseaseArchive = (data) => request.post('/api/disease', data)
export const updateDiseaseArchive = (data) => request.put('/api/disease', data)
export const deleteDiseaseArchive = (id) => request.delete(`/api/disease/${id}`)
export const processDiseaseArchive = (id) => request.put(`/api/disease/process/${id}`)
export const finishDiseaseArchive = (id) => request.put(`/api/disease/finish/${id}`)

export const getFollowupPlanPage = (params) => request.get('/api/plan/page', { params })
export const addFollowupPlan = (data) => request.post('/api/plan', data)
export const updateFollowupPlan = (data) => request.put('/api/plan', data)
export const deleteFollowupPlan = (id) => request.delete(`/api/plan/${id}`)
export const processFollowupPlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishFollowupPlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getFollowupRecordPage = (params) => request.get('/api/followup/page', { params })
export const addFollowupRecord = (data) => request.post('/api/followup', data)
export const updateFollowupRecord = (data) => request.put('/api/followup', data)
export const deleteFollowupRecord = (id) => request.delete(`/api/followup/${id}`)
export const processFollowupRecord = (id) => request.put(`/api/followup/process/${id}`)
export const finishFollowupRecord = (id) => request.put(`/api/followup/finish/${id}`)

export const getMedicationPlanPage = (params) => request.get('/api/medication/page', { params })
export const addMedicationPlan = (data) => request.post('/api/medication', data)
export const updateMedicationPlan = (data) => request.put('/api/medication', data)
export const deleteMedicationPlan = (id) => request.delete(`/api/medication/${id}`)
export const processMedicationPlan = (id) => request.put(`/api/medication/process/${id}`)
export const finishMedicationPlan = (id) => request.put(`/api/medication/finish/${id}`)

export const getMedicationAdherencePage = (params) => request.get('/api/adherence/page', { params })
export const addMedicationAdherence = (data) => request.post('/api/adherence', data)
export const updateMedicationAdherence = (data) => request.put('/api/adherence', data)
export const deleteMedicationAdherence = (id) => request.delete(`/api/adherence/${id}`)
export const processMedicationAdherence = (id) => request.put(`/api/adherence/process/${id}`)
export const finishMedicationAdherence = (id) => request.put(`/api/adherence/finish/${id}`)

export const getHealthIndicatorPage = (params) => request.get('/api/indicator/page', { params })
export const addHealthIndicator = (data) => request.post('/api/indicator', data)
export const updateHealthIndicator = (data) => request.put('/api/indicator', data)
export const deleteHealthIndicator = (id) => request.delete(`/api/indicator/${id}`)
export const processHealthIndicator = (id) => request.put(`/api/indicator/process/${id}`)
export const finishHealthIndicator = (id) => request.put(`/api/indicator/finish/${id}`)

export const getRiskStratificationPage = (params) => request.get('/api/risk/page', { params })
export const addRiskStratification = (data) => request.post('/api/risk', data)
export const updateRiskStratification = (data) => request.put('/api/risk', data)
export const deleteRiskStratification = (id) => request.delete(`/api/risk/${id}`)
export const processRiskStratification = (id) => request.put(`/api/risk/process/${id}`)
export const finishRiskStratification = (id) => request.put(`/api/risk/finish/${id}`)

export const getReminderNoticePage = (params) => request.get('/api/notice/page', { params })
export const addReminderNotice = (data) => request.post('/api/notice', data)
export const updateReminderNotice = (data) => request.put('/api/notice', data)
export const deleteReminderNotice = (id) => request.delete(`/api/notice/${id}`)
export const processReminderNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishReminderNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
