import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getTrainingProgramPage = (params) => request.get('/api/program/page', { params })
export const addTrainingProgram = (data) => request.post('/api/program', data)
export const updateTrainingProgram = (data) => request.put('/api/program', data)
export const deleteTrainingProgram = (id) => request.delete(`/api/program/${id}`)
export const activateTrainingProgram = (id) => request.put(`/api/program/activate/${id}`)
export const finishTrainingProgram = (id) => request.put(`/api/program/finish/${id}`)
export const getCourseCatalogPage = (params) => request.get('/api/course/page', { params })
export const addCourseCatalog = (data) => request.post('/api/course', data)
export const updateCourseCatalog = (data) => request.put('/api/course', data)
export const deleteCourseCatalog = (id) => request.delete(`/api/course/${id}`)
export const activateCourseCatalog = (id) => request.put(`/api/course/activate/${id}`)
export const finishCourseCatalog = (id) => request.put(`/api/course/finish/${id}`)
export const getLearnerProfilePage = (params) => request.get('/api/learner/page', { params })
export const addLearnerProfile = (data) => request.post('/api/learner', data)
export const updateLearnerProfile = (data) => request.put('/api/learner', data)
export const deleteLearnerProfile = (id) => request.delete(`/api/learner/${id}`)
export const activateLearnerProfile = (id) => request.put(`/api/learner/activate/${id}`)
export const finishLearnerProfile = (id) => request.put(`/api/learner/finish/${id}`)
export const getLearningPathPlanPage = (params) => request.get('/api/path/page', { params })
export const addLearningPathPlan = (data) => request.post('/api/path', data)
export const updateLearningPathPlan = (data) => request.put('/api/path', data)
export const deleteLearningPathPlan = (id) => request.delete(`/api/path/${id}`)
export const processLearningPathPlan = (id) => request.put(`/api/path/process/${id}`)
export const finishLearningPathPlan = (id) => request.put(`/api/path/finish/${id}`)
export const getStudyTaskPage = (params) => request.get('/api/task/page', { params })
export const addStudyTask = (data) => request.post('/api/task', data)
export const updateStudyTask = (data) => request.put('/api/task', data)
export const deleteStudyTask = (id) => request.delete(`/api/task/${id}`)
export const submitStudyTask = (id) => request.put(`/api/task/submit/${id}`)
export const approveStudyTask = (id) => request.put(`/api/task/approve/${id}`)
export const getCourseEnrollmentPage = (params) => request.get('/api/enroll/page', { params })
export const addCourseEnrollment = (data) => request.post('/api/enroll', data)
export const updateCourseEnrollment = (data) => request.put('/api/enroll', data)
export const deleteCourseEnrollment = (id) => request.delete(`/api/enroll/${id}`)
export const submitCourseEnrollment = (id) => request.put(`/api/enroll/submit/${id}`)
export const approveCourseEnrollment = (id) => request.put(`/api/enroll/approve/${id}`)
export const getAssessmentExamPage = (params) => request.get('/api/exam/page', { params })
export const addAssessmentExam = (data) => request.post('/api/exam', data)
export const updateAssessmentExam = (data) => request.put('/api/exam', data)
export const deleteAssessmentExam = (id) => request.delete(`/api/exam/${id}`)
export const processAssessmentExam = (id) => request.put(`/api/exam/process/${id}`)
export const finishAssessmentExam = (id) => request.put(`/api/exam/finish/${id}`)
export const getExamScorePage = (params) => request.get('/api/score/page', { params })
export const addExamScore = (data) => request.post('/api/score', data)
export const updateExamScore = (data) => request.put('/api/score', data)
export const deleteExamScore = (id) => request.delete(`/api/score/${id}`)
export const submitExamScore = (id) => request.put(`/api/score/submit/${id}`)
export const approveExamScore = (id) => request.put(`/api/score/approve/${id}`)
export const getSkillTagPage = (params) => request.get('/api/skill/page', { params })
export const addSkillTag = (data) => request.post('/api/skill', data)
export const updateSkillTag = (data) => request.put('/api/skill', data)
export const deleteSkillTag = (id) => request.delete(`/api/skill/${id}`)
export const submitSkillTag = (id) => request.put(`/api/skill/submit/${id}`)
export const approveSkillTag = (id) => request.put(`/api/skill/approve/${id}`)
export const getCompetencyProfilePage = (params) => request.get('/api/profile/page', { params })
export const addCompetencyProfile = (data) => request.post('/api/profile', data)
export const updateCompetencyProfile = (data) => request.put('/api/profile', data)
export const deleteCompetencyProfile = (id) => request.delete(`/api/profile/${id}`)
export const processCompetencyProfile = (id) => request.put(`/api/profile/process/${id}`)
export const finishCompetencyProfile = (id) => request.put(`/api/profile/finish/${id}`)
export const getCertificationRecordPage = (params) => request.get('/api/cert/page', { params })
export const addCertificationRecord = (data) => request.post('/api/cert', data)
export const updateCertificationRecord = (data) => request.put('/api/cert', data)
export const deleteCertificationRecord = (id) => request.delete(`/api/cert/${id}`)
export const activateCertificationRecord = (id) => request.put(`/api/cert/activate/${id}`)
export const finishCertificationRecord = (id) => request.put(`/api/cert/finish/${id}`)
export const getLearningReminderPage = (params) => request.get('/api/reminder/page', { params })
export const addLearningReminder = (data) => request.post('/api/reminder', data)
export const updateLearningReminder = (data) => request.put('/api/reminder', data)
export const deleteLearningReminder = (id) => request.delete(`/api/reminder/${id}`)
export const processLearningReminder = (id) => request.put(`/api/reminder/process/${id}`)
export const finishLearningReminder = (id) => request.put(`/api/reminder/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)




