import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getPharmacyStorePage = (params) => request.get('/api/store/page', { params })
export const addPharmacyStore = (data) => request.post('/api/store', data)
export const updatePharmacyStore = (data) => request.put('/api/store', data)
export const deletePharmacyStore = (id) => request.delete(`/api/store/${id}`)
export const processPharmacyStore = (id) => request.put(`/api/store/process/${id}`)
export const finishPharmacyStore = (id) => request.put(`/api/store/finish/${id}`)

export const getCustomerProfilePage = (params) => request.get('/api/customer/page', { params })
export const addCustomerProfile = (data) => request.post('/api/customer', data)
export const updateCustomerProfile = (data) => request.put('/api/customer', data)
export const deleteCustomerProfile = (id) => request.delete(`/api/customer/${id}`)
export const processCustomerProfile = (id) => request.put(`/api/customer/process/${id}`)
export const finishCustomerProfile = (id) => request.put(`/api/customer/finish/${id}`)

export const getMedicineCatalogPage = (params) => request.get('/api/medicine/page', { params })
export const addMedicineCatalog = (data) => request.post('/api/medicine', data)
export const updateMedicineCatalog = (data) => request.put('/api/medicine', data)
export const deleteMedicineCatalog = (id) => request.delete(`/api/medicine/${id}`)
export const processMedicineCatalog = (id) => request.put(`/api/medicine/process/${id}`)
export const finishMedicineCatalog = (id) => request.put(`/api/medicine/finish/${id}`)

export const getPrescriptionRecordPage = (params) => request.get('/api/prescription/page', { params })
export const addPrescriptionRecord = (data) => request.post('/api/prescription', data)
export const updatePrescriptionRecord = (data) => request.put('/api/prescription', data)
export const deletePrescriptionRecord = (id) => request.delete(`/api/prescription/${id}`)
export const processPrescriptionRecord = (id) => request.put(`/api/prescription/process/${id}`)
export const finishPrescriptionRecord = (id) => request.put(`/api/prescription/finish/${id}`)

export const getPrescriptionReviewPage = (params) => request.get('/api/review/page', { params })
export const addPrescriptionReview = (data) => request.post('/api/review', data)
export const updatePrescriptionReview = (data) => request.put('/api/review', data)
export const deletePrescriptionReview = (id) => request.delete(`/api/review/${id}`)
export const processPrescriptionReview = (id) => request.put(`/api/review/process/${id}`)
export const finishPrescriptionReview = (id) => request.put(`/api/review/finish/${id}`)

export const getRiskCheckPage = (params) => request.get('/api/risk/page', { params })
export const addRiskCheck = (data) => request.post('/api/risk', data)
export const updateRiskCheck = (data) => request.put('/api/risk', data)
export const deleteRiskCheck = (id) => request.delete(`/api/risk/${id}`)
export const processRiskCheck = (id) => request.put(`/api/risk/process/${id}`)
export const finishRiskCheck = (id) => request.put(`/api/risk/finish/${id}`)

export const getPurchaseRecordPage = (params) => request.get('/api/purchase/page', { params })
export const addPurchaseRecord = (data) => request.post('/api/purchase', data)
export const updatePurchaseRecord = (data) => request.put('/api/purchase', data)
export const deletePurchaseRecord = (id) => request.delete(`/api/purchase/${id}`)
export const processPurchaseRecord = (id) => request.put(`/api/purchase/process/${id}`)
export const finishPurchaseRecord = (id) => request.put(`/api/purchase/finish/${id}`)

export const getMedicationGuidePage = (params) => request.get('/api/guide/page', { params })
export const addMedicationGuide = (data) => request.post('/api/guide', data)
export const updateMedicationGuide = (data) => request.put('/api/guide', data)
export const deleteMedicationGuide = (id) => request.delete(`/api/guide/${id}`)
export const processMedicationGuide = (id) => request.put(`/api/guide/process/${id}`)
export const finishMedicationGuide = (id) => request.put(`/api/guide/finish/${id}`)

export const getChronicPlanPage = (params) => request.get('/api/plan/page', { params })
export const addChronicPlan = (data) => request.post('/api/plan', data)
export const updateChronicPlan = (data) => request.put('/api/plan', data)
export const deleteChronicPlan = (id) => request.delete(`/api/plan/${id}`)
export const processChronicPlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishChronicPlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getRenewalReminderPage = (params) => request.get('/api/reminder/page', { params })
export const addRenewalReminder = (data) => request.post('/api/reminder', data)
export const updateRenewalReminder = (data) => request.put('/api/reminder', data)
export const deleteRenewalReminder = (id) => request.delete(`/api/reminder/${id}`)
export const processRenewalReminder = (id) => request.put(`/api/reminder/process/${id}`)
export const finishRenewalReminder = (id) => request.put(`/api/reminder/finish/${id}`)

export const getFollowupRecordPage = (params) => request.get('/api/followup/page', { params })
export const addFollowupRecord = (data) => request.post('/api/followup', data)
export const updateFollowupRecord = (data) => request.put('/api/followup', data)
export const deleteFollowupRecord = (id) => request.delete(`/api/followup/${id}`)
export const processFollowupRecord = (id) => request.put(`/api/followup/process/${id}`)
export const finishFollowupRecord = (id) => request.put(`/api/followup/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
