import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getWorkAreaPage = (params) => request.get('/api/area/page', { params })
export const addWorkArea = (data) => request.post('/api/area', data)
export const updateWorkArea = (data) => request.put('/api/area', data)
export const deleteWorkArea = (id) => request.delete(`/api/area/${id}`)
export const processWorkArea = (id) => request.put(`/api/area/process/${id}`)
export const finishWorkArea = (id) => request.put(`/api/area/finish/${id}`)

export const getHazardSourcePage = (params) => request.get('/api/hazard/page', { params })
export const addHazardSource = (data) => request.post('/api/hazard', data)
export const updateHazardSource = (data) => request.put('/api/hazard', data)
export const deleteHazardSource = (id) => request.delete(`/api/hazard/${id}`)
export const processHazardSource = (id) => request.put(`/api/hazard/process/${id}`)
export const finishHazardSource = (id) => request.put(`/api/hazard/finish/${id}`)

export const getWorkerProfilePage = (params) => request.get('/api/worker/page', { params })
export const addWorkerProfile = (data) => request.post('/api/worker', data)
export const updateWorkerProfile = (data) => request.put('/api/worker', data)
export const deleteWorkerProfile = (id) => request.delete(`/api/worker/${id}`)
export const processWorkerProfile = (id) => request.put(`/api/worker/process/${id}`)
export const finishWorkerProfile = (id) => request.put(`/api/worker/finish/${id}`)

export const getWorkPermitPage = (params) => request.get('/api/work-ticket/page', { params })
export const addWorkPermit = (data) => request.post('/api/work-ticket', data)
export const updateWorkPermit = (data) => request.put('/api/work-ticket', data)
export const deleteWorkPermit = (id) => request.delete(`/api/work-ticket/${id}`)
export const processWorkPermit = (id) => request.put(`/api/work-ticket/process/${id}`)
export const finishWorkPermit = (id) => request.put(`/api/work-ticket/finish/${id}`)

export const getPermitApprovalPage = (params) => request.get('/api/approval/page', { params })
export const addPermitApproval = (data) => request.post('/api/approval', data)
export const updatePermitApproval = (data) => request.put('/api/approval', data)
export const deletePermitApproval = (id) => request.delete(`/api/approval/${id}`)
export const processPermitApproval = (id) => request.put(`/api/approval/process/${id}`)
export const finishPermitApproval = (id) => request.put(`/api/approval/finish/${id}`)

export const getSafetyBriefingPage = (params) => request.get('/api/briefing/page', { params })
export const addSafetyBriefing = (data) => request.post('/api/briefing', data)
export const updateSafetyBriefing = (data) => request.put('/api/briefing', data)
export const deleteSafetyBriefing = (id) => request.delete(`/api/briefing/${id}`)
export const processSafetyBriefing = (id) => request.put(`/api/briefing/process/${id}`)
export const finishSafetyBriefing = (id) => request.put(`/api/briefing/finish/${id}`)

export const getGuardianAssignmentPage = (params) => request.get('/api/guardian/page', { params })
export const addGuardianAssignment = (data) => request.post('/api/guardian', data)
export const updateGuardianAssignment = (data) => request.put('/api/guardian', data)
export const deleteGuardianAssignment = (id) => request.delete(`/api/guardian/${id}`)
export const processGuardianAssignment = (id) => request.put(`/api/guardian/process/${id}`)
export const finishGuardianAssignment = (id) => request.put(`/api/guardian/finish/${id}`)

export const getMonitorRecordPage = (params) => request.get('/api/monitor/page', { params })
export const addMonitorRecord = (data) => request.post('/api/monitor', data)
export const updateMonitorRecord = (data) => request.put('/api/monitor', data)
export const deleteMonitorRecord = (id) => request.delete(`/api/monitor/${id}`)
export const processMonitorRecord = (id) => request.put(`/api/monitor/process/${id}`)
export const finishMonitorRecord = (id) => request.put(`/api/monitor/finish/${id}`)

export const getHiddenDangerPage = (params) => request.get('/api/danger/page', { params })
export const addHiddenDanger = (data) => request.post('/api/danger', data)
export const updateHiddenDanger = (data) => request.put('/api/danger', data)
export const deleteHiddenDanger = (id) => request.delete(`/api/danger/${id}`)
export const processHiddenDanger = (id) => request.put(`/api/danger/process/${id}`)
export const finishHiddenDanger = (id) => request.put(`/api/danger/finish/${id}`)

export const getGasDetectionPage = (params) => request.get('/api/gas/page', { params })
export const addGasDetection = (data) => request.post('/api/gas', data)
export const updateGasDetection = (data) => request.put('/api/gas', data)
export const deleteGasDetection = (id) => request.delete(`/api/gas/${id}`)
export const processGasDetection = (id) => request.put(`/api/gas/process/${id}`)
export const finishGasDetection = (id) => request.put(`/api/gas/finish/${id}`)

export const getEmergencyPlanPage = (params) => request.get('/api/plan/page', { params })
export const addEmergencyPlan = (data) => request.post('/api/plan', data)
export const updateEmergencyPlan = (data) => request.put('/api/plan', data)
export const deleteEmergencyPlan = (id) => request.delete(`/api/plan/${id}`)
export const processEmergencyPlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishEmergencyPlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
