DROP TABLE IF EXISTS announcement;
DROP TABLE IF EXISTS parking_slot;
DROP TABLE IF EXISTS visitor_record;
DROP TABLE IF EXISTS complaint;
DROP TABLE IF EXISTS repair_order;
DROP TABLE IF EXISTS fee_order;
DROP TABLE IF EXISTS house;
DROP TABLE IF EXISTS building;
DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    nickname VARCHAR(50),
    phone VARCHAR(20),
    email VARCHAR(100),
    role VARCHAR(20) DEFAULT 'OWNER',
    status INT DEFAULT 1,
    last_login_time TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE building (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    floors INT DEFAULT 0,
    status INT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE house (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id BIGINT NOT NULL,
    unit_no VARCHAR(20) NOT NULL,
    room_no VARCHAR(20) NOT NULL,
    area DECIMAL(10,2) DEFAULT 0,
    owner_id BIGINT,
    status INT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_house_building ON house(building_id);
CREATE INDEX idx_house_owner ON house(owner_id);
CREATE INDEX idx_house_status ON house(status);

CREATE TABLE fee_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    house_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    fee_month VARCHAR(20) NOT NULL,
    status INT DEFAULT 0,
    pay_time TIMESTAMP,
    remark VARCHAR(255),
    creator_id BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_fee_house ON fee_order(house_id);
CREATE INDEX idx_fee_owner ON fee_order(owner_id);
CREATE INDEX idx_fee_status ON fee_order(status);

CREATE TABLE repair_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    house_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    content VARCHAR(500) NOT NULL,
    status INT DEFAULT 0,
    assignee_id BIGINT,
    reply VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_repair_house ON repair_order(house_id);
CREATE INDEX idx_repair_owner ON repair_order(owner_id);
CREATE INDEX idx_repair_status ON repair_order(status);

CREATE TABLE complaint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    owner_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    content VARCHAR(500) NOT NULL,
    status INT DEFAULT 0,
    reply VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_complaint_owner ON complaint(owner_id);
CREATE INDEX idx_complaint_status ON complaint(status);

CREATE TABLE visitor_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    owner_id BIGINT NOT NULL,
    visitor_name VARCHAR(50) NOT NULL,
    visitor_phone VARCHAR(20) NOT NULL,
    visit_time TIMESTAMP NOT NULL,
    status INT DEFAULT 0,
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_visitor_owner ON visitor_record(owner_id);
CREATE INDEX idx_visitor_status ON visitor_record(status);

CREATE TABLE parking_slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_no VARCHAR(50) NOT NULL UNIQUE,
    location VARCHAR(100),
    owner_id BIGINT,
    status INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_slot_owner ON parking_slot(owner_id);
CREATE INDEX idx_slot_status ON parking_slot(status);

CREATE TABLE announcement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content CLOB NOT NULL,
    admin_id BIGINT,
    status INT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
