import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getCommunityAreaPage = (params) => request.get('/api/area/page', { params })
export const addCommunityArea = (data) => request.post('/api/area', data)
export const updateCommunityArea = (data) => request.put('/api/area', data)
export const deleteCommunityArea = (id) => request.delete(`/api/area/${id}`)
export const processCommunityArea = (id) => request.put(`/api/area/process/${id}`)
export const finishCommunityArea = (id) => request.put(`/api/area/finish/${id}`)

export const getOwnerProfilePage = (params) => request.get('/api/owner/page', { params })
export const addOwnerProfile = (data) => request.post('/api/owner', data)
export const updateOwnerProfile = (data) => request.put('/api/owner', data)
export const deleteOwnerProfile = (id) => request.delete(`/api/owner/${id}`)
export const processOwnerProfile = (id) => request.put(`/api/owner/process/${id}`)
export const finishOwnerProfile = (id) => request.put(`/api/owner/finish/${id}`)

export const getRepairCategoryPage = (params) => request.get('/api/category/page', { params })
export const addRepairCategory = (data) => request.post('/api/category', data)
export const updateRepairCategory = (data) => request.put('/api/category', data)
export const deleteRepairCategory = (id) => request.delete(`/api/category/${id}`)
export const processRepairCategory = (id) => request.put(`/api/category/process/${id}`)
export const finishRepairCategory = (id) => request.put(`/api/category/finish/${id}`)

export const getRepairOrderPage = (params) => request.get('/api/repair/page', { params })
export const addRepairOrder = (data) => request.post('/api/repair', data)
export const updateRepairOrder = (data) => request.put('/api/repair', data)
export const deleteRepairOrder = (id) => request.delete(`/api/repair/${id}`)
export const processRepairOrder = (id) => request.put(`/api/repair/process/${id}`)
export const finishRepairOrder = (id) => request.put(`/api/repair/finish/${id}`)

export const getDispatchAssignmentPage = (params) => request.get('/api/dispatch/page', { params })
export const addDispatchAssignment = (data) => request.post('/api/dispatch', data)
export const updateDispatchAssignment = (data) => request.put('/api/dispatch', data)
export const deleteDispatchAssignment = (id) => request.delete(`/api/dispatch/${id}`)
export const processDispatchAssignment = (id) => request.put(`/api/dispatch/process/${id}`)
export const finishDispatchAssignment = (id) => request.put(`/api/dispatch/finish/${id}`)

export const getDoorServicePage = (params) => request.get('/api/service/page', { params })
export const addDoorService = (data) => request.post('/api/service', data)
export const updateDoorService = (data) => request.put('/api/service', data)
export const deleteDoorService = (id) => request.delete(`/api/service/${id}`)
export const processDoorService = (id) => request.put(`/api/service/process/${id}`)
export const finishDoorService = (id) => request.put(`/api/service/finish/${id}`)

export const getMaterialUsagePage = (params) => request.get('/api/material/page', { params })
export const addMaterialUsage = (data) => request.post('/api/material', data)
export const updateMaterialUsage = (data) => request.put('/api/material', data)
export const deleteMaterialUsage = (id) => request.delete(`/api/material/${id}`)
export const processMaterialUsage = (id) => request.put(`/api/material/process/${id}`)
export const finishMaterialUsage = (id) => request.put(`/api/material/finish/${id}`)

export const getFeeRegistrationPage = (params) => request.get('/api/fee/page', { params })
export const addFeeRegistration = (data) => request.post('/api/fee', data)
export const updateFeeRegistration = (data) => request.put('/api/fee', data)
export const deleteFeeRegistration = (id) => request.delete(`/api/fee/${id}`)
export const processFeeRegistration = (id) => request.put(`/api/fee/process/${id}`)
export const finishFeeRegistration = (id) => request.put(`/api/fee/finish/${id}`)

export const getPaymentRecordPage = (params) => request.get('/api/payment/page', { params })
export const addPaymentRecord = (data) => request.post('/api/payment', data)
export const updatePaymentRecord = (data) => request.put('/api/payment', data)
export const deletePaymentRecord = (id) => request.delete(`/api/payment/${id}`)
export const processPaymentRecord = (id) => request.put(`/api/payment/process/${id}`)
export const finishPaymentRecord = (id) => request.put(`/api/payment/finish/${id}`)

export const getSatisfactionReviewPage = (params) => request.get('/api/review/page', { params })
export const addSatisfactionReview = (data) => request.post('/api/review', data)
export const updateSatisfactionReview = (data) => request.put('/api/review', data)
export const deleteSatisfactionReview = (id) => request.delete(`/api/review/${id}`)
export const processSatisfactionReview = (id) => request.put(`/api/review/process/${id}`)
export const finishSatisfactionReview = (id) => request.put(`/api/review/finish/${id}`)

export const getComplaintFollowupPage = (params) => request.get('/api/complaint/page', { params })
export const addComplaintFollowup = (data) => request.post('/api/complaint', data)
export const updateComplaintFollowup = (data) => request.put('/api/complaint', data)
export const deleteComplaintFollowup = (id) => request.delete(`/api/complaint/${id}`)
export const processComplaintFollowup = (id) => request.put(`/api/complaint/process/${id}`)
export const finishComplaintFollowup = (id) => request.put(`/api/complaint/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
