import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getCollegeMajorPage = (params) => request.get('/api/major/page', { params })
export const addCollegeMajor = (data) => request.post('/api/major', data)
export const updateCollegeMajor = (data) => request.put('/api/major', data)
export const deleteCollegeMajor = (id) => request.delete(`/api/major/${id}`)
export const processCollegeMajor = (id) => request.put(`/api/major/process/${id}`)
export const finishCollegeMajor = (id) => request.put(`/api/major/finish/${id}`)

export const getGraduateProfilePage = (params) => request.get('/api/graduate/page', { params })
export const addGraduateProfile = (data) => request.post('/api/graduate', data)
export const updateGraduateProfile = (data) => request.put('/api/graduate', data)
export const deleteGraduateProfile = (id) => request.delete(`/api/graduate/${id}`)
export const processGraduateProfile = (id) => request.put(`/api/graduate/process/${id}`)
export const finishGraduateProfile = (id) => request.put(`/api/graduate/finish/${id}`)

export const getEmployerProfilePage = (params) => request.get('/api/employer/page', { params })
export const addEmployerProfile = (data) => request.post('/api/employer', data)
export const updateEmployerProfile = (data) => request.put('/api/employer', data)
export const deleteEmployerProfile = (id) => request.delete(`/api/employer/${id}`)
export const processEmployerProfile = (id) => request.put(`/api/employer/process/${id}`)
export const finishEmployerProfile = (id) => request.put(`/api/employer/finish/${id}`)

export const getJobPositionPage = (params) => request.get('/api/job/page', { params })
export const addJobPosition = (data) => request.post('/api/job', data)
export const updateJobPosition = (data) => request.put('/api/job', data)
export const deleteJobPosition = (id) => request.delete(`/api/job/${id}`)
export const processJobPosition = (id) => request.put(`/api/job/process/${id}`)
export const finishJobPosition = (id) => request.put(`/api/job/finish/${id}`)

export const getDestinationReportPage = (params) => request.get('/api/destination/page', { params })
export const addDestinationReport = (data) => request.post('/api/destination', data)
export const updateDestinationReport = (data) => request.put('/api/destination', data)
export const deleteDestinationReport = (id) => request.delete(`/api/destination/${id}`)
export const processDestinationReport = (id) => request.put(`/api/destination/process/${id}`)
export const finishDestinationReport = (id) => request.put(`/api/destination/finish/${id}`)

export const getContractArchivePage = (params) => request.get('/api/contract/page', { params })
export const addContractArchive = (data) => request.post('/api/contract', data)
export const updateContractArchive = (data) => request.put('/api/contract', data)
export const deleteContractArchive = (id) => request.delete(`/api/contract/${id}`)
export const processContractArchive = (id) => request.put(`/api/contract/process/${id}`)
export const finishContractArchive = (id) => request.put(`/api/contract/finish/${id}`)

export const getMaterialReviewPage = (params) => request.get('/api/review/page', { params })
export const addMaterialReview = (data) => request.post('/api/review', data)
export const updateMaterialReview = (data) => request.put('/api/review', data)
export const deleteMaterialReview = (id) => request.delete(`/api/review/${id}`)
export const processMaterialReview = (id) => request.put(`/api/review/process/${id}`)
export const finishMaterialReview = (id) => request.put(`/api/review/finish/${id}`)

export const getAssistanceRecordPage = (params) => request.get('/api/assistance/page', { params })
export const addAssistanceRecord = (data) => request.post('/api/assistance', data)
export const updateAssistanceRecord = (data) => request.put('/api/assistance', data)
export const deleteAssistanceRecord = (id) => request.delete(`/api/assistance/${id}`)
export const processAssistanceRecord = (id) => request.put(`/api/assistance/process/${id}`)
export const finishAssistanceRecord = (id) => request.put(`/api/assistance/finish/${id}`)

export const getJobRecommendationPage = (params) => request.get('/api/recommendation/page', { params })
export const addJobRecommendation = (data) => request.post('/api/recommendation', data)
export const updateJobRecommendation = (data) => request.put('/api/recommendation', data)
export const deleteJobRecommendation = (id) => request.delete(`/api/recommendation/${id}`)
export const processJobRecommendation = (id) => request.put(`/api/recommendation/process/${id}`)
export const finishJobRecommendation = (id) => request.put(`/api/recommendation/finish/${id}`)

export const getFollowupRecordPage = (params) => request.get('/api/followup/page', { params })
export const addFollowupRecord = (data) => request.post('/api/followup', data)
export const updateFollowupRecord = (data) => request.put('/api/followup', data)
export const deleteFollowupRecord = (id) => request.delete(`/api/followup/${id}`)
export const processFollowupRecord = (id) => request.put(`/api/followup/process/${id}`)
export const finishFollowupRecord = (id) => request.put(`/api/followup/finish/${id}`)

export const getEmploymentStatisticsPage = (params) => request.get('/api/statistics/page', { params })
export const addEmploymentStatistics = (data) => request.post('/api/statistics', data)
export const updateEmploymentStatistics = (data) => request.put('/api/statistics', data)
export const deleteEmploymentStatistics = (id) => request.delete(`/api/statistics/${id}`)
export const processEmploymentStatistics = (id) => request.put(`/api/statistics/process/${id}`)
export const finishEmploymentStatistics = (id) => request.put(`/api/statistics/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
