import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getScenicAreaPage = (params) => request.get('/api/area/page', { params })
export const addScenicArea = (data) => request.post('/api/area', data)
export const updateScenicArea = (data) => request.put('/api/area', data)
export const deleteScenicArea = (id) => request.delete(`/api/area/${id}`)
export const processScenicArea = (id) => request.put(`/api/area/process/${id}`)
export const finishScenicArea = (id) => request.put(`/api/area/finish/${id}`)

export const getLostItemPage = (params) => request.get('/api/lost/page', { params })
export const addLostItem = (data) => request.post('/api/lost', data)
export const updateLostItem = (data) => request.put('/api/lost', data)
export const deleteLostItem = (id) => request.delete(`/api/lost/${id}`)
export const processLostItem = (id) => request.put(`/api/lost/process/${id}`)
export const finishLostItem = (id) => request.put(`/api/lost/finish/${id}`)

export const getFoundReportPage = (params) => request.get('/api/found/page', { params })
export const addFoundReport = (data) => request.post('/api/found', data)
export const updateFoundReport = (data) => request.put('/api/found', data)
export const deleteFoundReport = (id) => request.delete(`/api/found/${id}`)
export const processFoundReport = (id) => request.put(`/api/found/process/${id}`)
export const finishFoundReport = (id) => request.put(`/api/found/finish/${id}`)

export const getClaimApplicationPage = (params) => request.get('/api/claim/page', { params })
export const addClaimApplication = (data) => request.post('/api/claim', data)
export const updateClaimApplication = (data) => request.put('/api/claim', data)
export const deleteClaimApplication = (id) => request.delete(`/api/claim/${id}`)
export const processClaimApplication = (id) => request.put(`/api/claim/process/${id}`)
export const finishClaimApplication = (id) => request.put(`/api/claim/finish/${id}`)

export const getIdentityVerifyPage = (params) => request.get('/api/verify/page', { params })
export const addIdentityVerify = (data) => request.post('/api/verify', data)
export const updateIdentityVerify = (data) => request.put('/api/verify', data)
export const deleteIdentityVerify = (id) => request.delete(`/api/verify/${id}`)
export const processIdentityVerify = (id) => request.put(`/api/verify/process/${id}`)
export const finishIdentityVerify = (id) => request.put(`/api/verify/finish/${id}`)

export const getLocationTracePage = (params) => request.get('/api/trace/page', { params })
export const addLocationTrace = (data) => request.post('/api/trace', data)
export const updateLocationTrace = (data) => request.put('/api/trace', data)
export const deleteLocationTrace = (id) => request.delete(`/api/trace/${id}`)
export const processLocationTrace = (id) => request.put(`/api/trace/process/${id}`)
export const finishLocationTrace = (id) => request.put(`/api/trace/finish/${id}`)

export const getCustodyRecordPage = (params) => request.get('/api/custody/page', { params })
export const addCustodyRecord = (data) => request.post('/api/custody', data)
export const updateCustodyRecord = (data) => request.put('/api/custody', data)
export const deleteCustodyRecord = (id) => request.delete(`/api/custody/${id}`)
export const processCustodyRecord = (id) => request.put(`/api/custody/process/${id}`)
export const finishCustodyRecord = (id) => request.put(`/api/custody/finish/${id}`)

export const getNoticeBroadcastPage = (params) => request.get('/api/notice/page', { params })
export const addNoticeBroadcast = (data) => request.post('/api/notice', data)
export const updateNoticeBroadcast = (data) => request.put('/api/notice', data)
export const deleteNoticeBroadcast = (id) => request.delete(`/api/notice/${id}`)
export const processNoticeBroadcast = (id) => request.put(`/api/notice/process/${id}`)
export const finishNoticeBroadcast = (id) => request.put(`/api/notice/finish/${id}`)

export const getHandoverRecordPage = (params) => request.get('/api/handover/page', { params })
export const addHandoverRecord = (data) => request.post('/api/handover', data)
export const updateHandoverRecord = (data) => request.put('/api/handover', data)
export const deleteHandoverRecord = (id) => request.delete(`/api/handover/${id}`)
export const processHandoverRecord = (id) => request.put(`/api/handover/process/${id}`)
export const finishHandoverRecord = (id) => request.put(`/api/handover/finish/${id}`)

export const getSearchTaskPage = (params) => request.get('/api/search/page', { params })
export const addSearchTask = (data) => request.post('/api/search', data)
export const updateSearchTask = (data) => request.put('/api/search', data)
export const deleteSearchTask = (id) => request.delete(`/api/search/${id}`)
export const processSearchTask = (id) => request.put(`/api/search/process/${id}`)
export const finishSearchTask = (id) => request.put(`/api/search/finish/${id}`)

export const getFeedbackRecordPage = (params) => request.get('/api/feedback/page', { params })
export const addFeedbackRecord = (data) => request.post('/api/feedback', data)
export const updateFeedbackRecord = (data) => request.put('/api/feedback', data)
export const deleteFeedbackRecord = (id) => request.delete(`/api/feedback/${id}`)
export const processFeedbackRecord = (id) => request.put(`/api/feedback/process/${id}`)
export const finishFeedbackRecord = (id) => request.put(`/api/feedback/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
