import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getServiceStationPage = (params) => request.get('/api/station/page', { params })
export const addServiceStation = (data) => request.post('/api/station', data)
export const updateServiceStation = (data) => request.put('/api/station', data)
export const deleteServiceStation = (id) => request.delete(`/api/station/${id}`)
export const processServiceStation = (id) => request.put(`/api/station/process/${id}`)
export const finishServiceStation = (id) => request.put(`/api/station/finish/${id}`)

export const getMachineAssetPage = (params) => request.get('/api/machine/page', { params })
export const addMachineAsset = (data) => request.post('/api/machine', data)
export const updateMachineAsset = (data) => request.put('/api/machine', data)
export const deleteMachineAsset = (id) => request.delete(`/api/machine/${id}`)
export const processMachineAsset = (id) => request.put(`/api/machine/process/${id}`)
export const finishMachineAsset = (id) => request.put(`/api/machine/finish/${id}`)

export const getFarmerProfilePage = (params) => request.get('/api/farmer/page', { params })
export const addFarmerProfile = (data) => request.post('/api/farmer', data)
export const updateFarmerProfile = (data) => request.put('/api/farmer', data)
export const deleteFarmerProfile = (id) => request.delete(`/api/farmer/${id}`)
export const processFarmerProfile = (id) => request.put(`/api/farmer/process/${id}`)
export const finishFarmerProfile = (id) => request.put(`/api/farmer/finish/${id}`)

export const getDriverProfilePage = (params) => request.get('/api/driver/page', { params })
export const addDriverProfile = (data) => request.post('/api/driver', data)
export const updateDriverProfile = (data) => request.put('/api/driver', data)
export const deleteDriverProfile = (id) => request.delete(`/api/driver/${id}`)
export const processDriverProfile = (id) => request.put(`/api/driver/process/${id}`)
export const finishDriverProfile = (id) => request.put(`/api/driver/finish/${id}`)

export const getOperationBookingPage = (params) => request.get('/api/booking/page', { params })
export const addOperationBooking = (data) => request.post('/api/booking', data)
export const updateOperationBooking = (data) => request.put('/api/booking', data)
export const deleteOperationBooking = (id) => request.delete(`/api/booking/${id}`)
export const processOperationBooking = (id) => request.put(`/api/booking/process/${id}`)
export const finishOperationBooking = (id) => request.put(`/api/booking/finish/${id}`)

export const getDispatchSchedulePage = (params) => request.get('/api/dispatch/page', { params })
export const addDispatchSchedule = (data) => request.post('/api/dispatch', data)
export const updateDispatchSchedule = (data) => request.put('/api/dispatch', data)
export const deleteDispatchSchedule = (id) => request.delete(`/api/dispatch/${id}`)
export const processDispatchSchedule = (id) => request.put(`/api/dispatch/process/${id}`)
export const finishDispatchSchedule = (id) => request.put(`/api/dispatch/finish/${id}`)

export const getFieldWorkOrderPage = (params) => request.get('/api/workorder/page', { params })
export const addFieldWorkOrder = (data) => request.post('/api/workorder', data)
export const updateFieldWorkOrder = (data) => request.put('/api/workorder', data)
export const deleteFieldWorkOrder = (id) => request.delete(`/api/workorder/${id}`)
export const processFieldWorkOrder = (id) => request.put(`/api/workorder/process/${id}`)
export const finishFieldWorkOrder = (id) => request.put(`/api/workorder/finish/${id}`)

export const getWorkCompletionPage = (params) => request.get('/api/completion/page', { params })
export const addWorkCompletion = (data) => request.post('/api/completion', data)
export const updateWorkCompletion = (data) => request.put('/api/completion', data)
export const deleteWorkCompletion = (id) => request.delete(`/api/completion/${id}`)
export const processWorkCompletion = (id) => request.put(`/api/completion/process/${id}`)
export const finishWorkCompletion = (id) => request.put(`/api/completion/finish/${id}`)

export const getMaintenanceRecordPage = (params) => request.get('/api/maintenance/page', { params })
export const addMaintenanceRecord = (data) => request.post('/api/maintenance', data)
export const updateMaintenanceRecord = (data) => request.put('/api/maintenance', data)
export const deleteMaintenanceRecord = (id) => request.delete(`/api/maintenance/${id}`)
export const processMaintenanceRecord = (id) => request.put(`/api/maintenance/process/${id}`)
export const finishMaintenanceRecord = (id) => request.put(`/api/maintenance/finish/${id}`)

export const getRepairFollowupPage = (params) => request.get('/api/repair/page', { params })
export const addRepairFollowup = (data) => request.post('/api/repair', data)
export const updateRepairFollowup = (data) => request.put('/api/repair', data)
export const deleteRepairFollowup = (id) => request.delete(`/api/repair/${id}`)
export const processRepairFollowup = (id) => request.put(`/api/repair/process/${id}`)
export const finishRepairFollowup = (id) => request.put(`/api/repair/finish/${id}`)

export const getSeasonalStatisticsPage = (params) => request.get('/api/season/page', { params })
export const addSeasonalStatistics = (data) => request.post('/api/season', data)
export const updateSeasonalStatistics = (data) => request.put('/api/season', data)
export const deleteSeasonalStatistics = (id) => request.delete(`/api/season/${id}`)
export const processSeasonalStatistics = (id) => request.put(`/api/season/process/${id}`)
export const finishSeasonalStatistics = (id) => request.put(`/api/season/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
