DROP TABLE IF EXISTS collection;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS creator_auth;
DROP TABLE IF EXISTS recipe_ingredient;
DROP TABLE IF EXISTS ingredient_taboo;
DROP TABLE IF EXISTS health_profile;
DROP TABLE IF EXISTS topic;
DROP TABLE IF EXISTS recipe;
DROP TABLE IF EXISTS ingredient;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    avatar VARCHAR(255),
    nickname VARCHAR(50),
    bio CLOB,
    user_type TINYINT DEFAULT 0,
    status TINYINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE health_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    constitution VARCHAR(50),
    allergies CLOB,
    health_goals CLOB,
    dietary_restrictions CLOB,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_health_profile_user UNIQUE (user_id),
    CONSTRAINT fk_health_profile_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(50),
    nature VARCHAR(50),
    taste VARCHAR(100),
    efficacy CLOB,
    nutrition CLOB,
    image VARCHAR(255),
    status TINYINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description CLOB,
    author_id BIGINT NOT NULL,
    cover_image VARCHAR(255),
    efficacy CLOB,
    nutrition CLOB,
    difficulty TINYINT,
    cook_time INT,
    servings INT,
    applicable_people VARCHAR(255),
    seasons VARCHAR(255),
    status TINYINT DEFAULT 0,
    views INT DEFAULT 0,
    likes INT DEFAULT 0,
    collects INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipe_author FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE ingredient_taboo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id1 BIGINT NOT NULL,
    ingredient_id2 BIGINT NOT NULL,
    reason CLOB,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ingredient_taboo UNIQUE (ingredient_id1, ingredient_id2),
    CONSTRAINT fk_ingredient_taboo_1 FOREIGN KEY (ingredient_id1) REFERENCES ingredient (id) ON DELETE CASCADE,
    CONSTRAINT fk_ingredient_taboo_2 FOREIGN KEY (ingredient_id2) REFERENCES ingredient (id) ON DELETE CASCADE
);

CREATE TABLE recipe_ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    quantity DECIMAL(10, 2),
    unit VARCHAR(20),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipe_ingredient_recipe FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ingredient_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) ON DELETE CASCADE
);

CREATE TABLE topic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content CLOB,
    author_id BIGINT NOT NULL,
    category VARCHAR(50),
    tags CLOB,
    views INT DEFAULT 0,
    replies INT DEFAULT 0,
    status TINYINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_topic_author FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type TINYINT NOT NULL,
    target_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content CLOB,
    rating TINYINT,
    image_urls CLOB,
    likes INT DEFAULT 0,
    status TINYINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    target_type TINYINT NOT NULL,
    target_id BIGINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_collection UNIQUE (user_id, target_type, target_id),
    CONSTRAINT fk_collection_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE creator_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    auth_type VARCHAR(50),
    credentials CLOB,
    status TINYINT DEFAULT 0,
    auth_time TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_creator_auth_user UNIQUE (user_id),
    CONSTRAINT fk_creator_auth_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_username ON user (username);
CREATE INDEX idx_health_profile_user_id ON health_profile (user_id);
CREATE INDEX idx_ingredient_category ON ingredient (category);
CREATE INDEX idx_recipe_author_id ON recipe (author_id);
CREATE INDEX idx_recipe_status ON recipe (status);
CREATE INDEX idx_recipe_ingredient_recipe_id ON recipe_ingredient (recipe_id);
CREATE INDEX idx_topic_author_id ON topic (author_id);
CREATE INDEX idx_topic_status ON topic (status);
CREATE INDEX idx_comment_target ON comment (target_type, target_id);
CREATE INDEX idx_comment_user_id ON comment (user_id);
CREATE INDEX idx_collection_user_target ON collection (user_id, target_type);
CREATE INDEX idx_creator_auth_status ON creator_auth (status);
