import request from './request'

export const login = (data) => request.post('/auth/login', data)
export const getInfo = () => request.get('/auth/info')
export const logout = () => request.post('/auth/logout')
export const updatePassword = (data) => request.put('/auth/password', data)

export const getAdminPage = (params) => request.get('/admin/page', { params })
export const addAdmin = (data) => request.post('/admin', data)
export const updateAdmin = (data) => request.put('/admin', data)
export const deleteAdmin = (id) => request.delete(`/admin/${id}`)

export const getDepartmentPage = (params) => request.get('/department/page', { params })
export const getDepartmentList = () => request.get('/department/list')
export const addDepartment = (data) => request.post('/department', data)
export const updateDepartment = (data) => request.put('/department', data)
export const deleteDepartment = (id) => request.delete(`/department/${id}`)

export const getMajorPage = (params) => request.get('/major/page', { params })
export const getMajorList = () => request.get('/major/list')
export const getMajorByDept = (deptId) => request.get(`/major/list/${deptId}`)
export const addMajor = (data) => request.post('/major', data)
export const updateMajor = (data) => request.put('/major', data)
export const deleteMajor = (id) => request.delete(`/major/${id}`)

export const getPlanPage = (params) => request.get('/plan/page', { params })
export const getPlanByYear = (year) => request.get(`/plan/list/${year}`)
export const addPlan = (data) => request.post('/plan', data)
export const updatePlan = (data) => request.put('/plan', data)
export const deletePlan = (id) => request.delete(`/plan/${id}`)
export const publishPlan = (id) => request.put(`/plan/publish/${id}`)
export const closePlan = (id) => request.put(`/plan/close/${id}`)

export const getStudentPage = (params) => request.get('/student/page', { params })
export const getStudent = (id) => request.get(`/student/${id}`)
export const getStudentList = () => request.get('/student/list')
export const addStudent = (data) => request.post('/student', data)
export const updateStudent = (data) => request.put('/student', data)
export const deleteStudent = (id) => request.delete(`/student/${id}`)
export const auditStudent = (id, status) => request.put(`/student/audit/${id}`, null, { params: { status } })

export const getApplicationPage = (params) => request.get('/application/page', { params })
export const addApplication = (data) => request.post('/application', data)
export const updateApplication = (data) => request.put('/application', data)
export const deleteApplication = (id) => request.delete(`/application/${id}`)
export const auditApplication = (id, data) => request.put(`/application/audit/${id}`, data)

export const getScorePage = (params) => request.get('/score/page', { params })
export const addScore = (data) => request.post('/score', data)
export const updateScore = (data) => request.put('/score', data)
export const deleteScore = (id) => request.delete(`/score/${id}`)
export const importScore = (data) => request.post('/score/import', data)

export const getAdmissionPage = (params) => request.get('/admission/page', { params })
export const addAdmission = (data) => request.post('/admission', data)
export const updateAdmission = (data) => request.put('/admission', data)
export const deleteAdmission = (id) => request.delete(`/admission/${id}`)
export const confirmAdmission = (id) => request.put(`/admission/confirm/${id}`)
export const batchAdmission = (data) => request.post('/admission/batch', data)

export const getScoreLinePage = (params) => request.get('/scoreline/page', { params })
export const addScoreLine = (data) => request.post('/scoreline', data)
export const updateScoreLine = (data) => request.put('/scoreline', data)
export const deleteScoreLine = (id) => request.delete(`/scoreline/${id}`)

export const getNoticePage = (params) => request.get('/notice/page', { params })
export const getNotice = (id) => request.get(`/notice/${id}`)
export const addNotice = (data) => request.post('/notice', data)
export const updateNotice = (data) => request.put('/notice', data)
export const deleteNotice = (id) => request.delete(`/notice/${id}`)
export const publishNotice = (id) => request.put(`/notice/publish/${id}`)

export const getDashboard = () => request.get('/stats/dashboard')
export const getApplicationStats = () => request.get('/stats/application')
export const getAdmissionStats = () => request.get('/stats/admission')
export const getMajorStats = () => request.get('/stats/major')
export const getProvinceStats = () => request.get('/stats/province')
