import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getComplaintTicketPage = (params) => request.get('/api/complaint/page', { params })
export const addComplaintTicket = (data) => request.post('/api/complaint', data)
export const updateComplaintTicket = (data) => request.put('/api/complaint', data)
export const deleteComplaintTicket = (id) => request.delete(`/api/complaint/${id}`)
export const activateComplaintTicket = (id) => request.put(`/api/complaint/activate/${id}`)
export const finishComplaintTicket = (id) => request.put(`/api/complaint/finish/${id}`)
export const getMonitoringSitePage = (params) => request.get('/api/site/page', { params })
export const addMonitoringSite = (data) => request.post('/api/site', data)
export const updateMonitoringSite = (data) => request.put('/api/site', data)
export const deleteMonitoringSite = (id) => request.delete(`/api/site/${id}`)
export const activateMonitoringSite = (id) => request.put(`/api/site/activate/${id}`)
export const finishMonitoringSite = (id) => request.put(`/api/site/finish/${id}`)
export const getNoiseSourcePage = (params) => request.get('/api/source/page', { params })
export const addNoiseSource = (data) => request.post('/api/source', data)
export const updateNoiseSource = (data) => request.put('/api/source', data)
export const deleteNoiseSource = (id) => request.delete(`/api/source/${id}`)
export const activateNoiseSource = (id) => request.put(`/api/source/activate/${id}`)
export const finishNoiseSource = (id) => request.put(`/api/source/finish/${id}`)
export const getOfficerProfilePage = (params) => request.get('/api/officer/page', { params })
export const addOfficerProfile = (data) => request.post('/api/officer', data)
export const updateOfficerProfile = (data) => request.put('/api/officer', data)
export const deleteOfficerProfile = (id) => request.delete(`/api/officer/${id}`)
export const processOfficerProfile = (id) => request.put(`/api/officer/process/${id}`)
export const finishOfficerProfile = (id) => request.put(`/api/officer/finish/${id}`)
export const getHandlingTaskPage = (params) => request.get('/api/task/page', { params })
export const addHandlingTask = (data) => request.post('/api/task', data)
export const updateHandlingTask = (data) => request.put('/api/task', data)
export const deleteHandlingTask = (id) => request.delete(`/api/task/${id}`)
export const submitHandlingTask = (id) => request.put(`/api/task/submit/${id}`)
export const approveHandlingTask = (id) => request.put(`/api/task/approve/${id}`)
export const getPatrolRecordPage = (params) => request.get('/api/patrol/page', { params })
export const addPatrolRecord = (data) => request.post('/api/patrol', data)
export const updatePatrolRecord = (data) => request.put('/api/patrol', data)
export const deletePatrolRecord = (id) => request.delete(`/api/patrol/${id}`)
export const submitPatrolRecord = (id) => request.put(`/api/patrol/submit/${id}`)
export const approvePatrolRecord = (id) => request.put(`/api/patrol/approve/${id}`)
export const getRectificationNoticePage = (params) => request.get('/api/rectify/page', { params })
export const addRectificationNotice = (data) => request.post('/api/rectify', data)
export const updateRectificationNotice = (data) => request.put('/api/rectify', data)
export const deleteRectificationNotice = (id) => request.delete(`/api/rectify/${id}`)
export const processRectificationNotice = (id) => request.put(`/api/rectify/process/${id}`)
export const finishRectificationNotice = (id) => request.put(`/api/rectify/finish/${id}`)
export const getRetestRecordPage = (params) => request.get('/api/retest/page', { params })
export const addRetestRecord = (data) => request.post('/api/retest', data)
export const updateRetestRecord = (data) => request.put('/api/retest', data)
export const deleteRetestRecord = (id) => request.delete(`/api/retest/${id}`)
export const submitRetestRecord = (id) => request.put(`/api/retest/submit/${id}`)
export const approveRetestRecord = (id) => request.put(`/api/retest/approve/${id}`)
export const getPenaltyDecisionPage = (params) => request.get('/api/penalty/page', { params })
export const addPenaltyDecision = (data) => request.post('/api/penalty', data)
export const updatePenaltyDecision = (data) => request.put('/api/penalty', data)
export const deletePenaltyDecision = (id) => request.delete(`/api/penalty/${id}`)
export const submitPenaltyDecision = (id) => request.put(`/api/penalty/submit/${id}`)
export const approvePenaltyDecision = (id) => request.put(`/api/penalty/approve/${id}`)
export const getPublicFeedbackPage = (params) => request.get('/api/feedback/page', { params })
export const addPublicFeedback = (data) => request.post('/api/feedback', data)
export const updatePublicFeedback = (data) => request.put('/api/feedback', data)
export const deletePublicFeedback = (id) => request.delete(`/api/feedback/${id}`)
export const processPublicFeedback = (id) => request.put(`/api/feedback/process/${id}`)
export const finishPublicFeedback = (id) => request.put(`/api/feedback/finish/${id}`)
export const getWarningRulePage = (params) => request.get('/api/rule/page', { params })
export const addWarningRule = (data) => request.post('/api/rule', data)
export const updateWarningRule = (data) => request.put('/api/rule', data)
export const deleteWarningRule = (id) => request.delete(`/api/rule/${id}`)
export const activateWarningRule = (id) => request.put(`/api/rule/activate/${id}`)
export const finishWarningRule = (id) => request.put(`/api/rule/finish/${id}`)
export const getPublicNoticePage = (params) => request.get('/api/notice/page', { params })
export const addPublicNotice = (data) => request.post('/api/notice', data)
export const updatePublicNotice = (data) => request.put('/api/notice', data)
export const deletePublicNotice = (id) => request.delete(`/api/notice/${id}`)
export const processPublicNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishPublicNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)







