import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getPartyBranchPage = (params) => request.get('/api/branch/page', { params })
export const addPartyBranch = (data) => request.post('/api/branch', data)
export const updatePartyBranch = (data) => request.put('/api/branch', data)
export const deletePartyBranch = (id) => request.delete(`/api/branch/${id}`)
export const processPartyBranch = (id) => request.put(`/api/branch/process/${id}`)
export const finishPartyBranch = (id) => request.put(`/api/branch/finish/${id}`)

export const getMemberProfilePage = (params) => request.get('/api/member/page', { params })
export const addMemberProfile = (data) => request.post('/api/member', data)
export const updateMemberProfile = (data) => request.put('/api/member', data)
export const deleteMemberProfile = (id) => request.delete(`/api/member/${id}`)
export const processMemberProfile = (id) => request.put(`/api/member/process/${id}`)
export const finishMemberProfile = (id) => request.put(`/api/member/finish/${id}`)

export const getPartyActivityPage = (params) => request.get('/api/activity/page', { params })
export const addPartyActivity = (data) => request.post('/api/activity', data)
export const updatePartyActivity = (data) => request.put('/api/activity', data)
export const deletePartyActivity = (id) => request.delete(`/api/activity/${id}`)
export const processPartyActivity = (id) => request.put(`/api/activity/process/${id}`)
export const finishPartyActivity = (id) => request.put(`/api/activity/finish/${id}`)

export const getActivityRegistrationPage = (params) => request.get('/api/registration/page', { params })
export const addActivityRegistration = (data) => request.post('/api/registration', data)
export const updateActivityRegistration = (data) => request.put('/api/registration', data)
export const deleteActivityRegistration = (id) => request.delete(`/api/registration/${id}`)
export const processActivityRegistration = (id) => request.put(`/api/registration/process/${id}`)
export const finishActivityRegistration = (id) => request.put(`/api/registration/finish/${id}`)

export const getAttendanceRecordPage = (params) => request.get('/api/attendance/page', { params })
export const addAttendanceRecord = (data) => request.post('/api/attendance', data)
export const updateAttendanceRecord = (data) => request.put('/api/attendance', data)
export const deleteAttendanceRecord = (id) => request.delete(`/api/attendance/${id}`)
export const processAttendanceRecord = (id) => request.put(`/api/attendance/process/${id}`)
export const finishAttendanceRecord = (id) => request.put(`/api/attendance/finish/${id}`)

export const getVolunteerTaskPage = (params) => request.get('/api/task/page', { params })
export const addVolunteerTask = (data) => request.post('/api/task', data)
export const updateVolunteerTask = (data) => request.put('/api/task', data)
export const deleteVolunteerTask = (id) => request.delete(`/api/task/${id}`)
export const processVolunteerTask = (id) => request.put(`/api/task/process/${id}`)
export const finishVolunteerTask = (id) => request.put(`/api/task/finish/${id}`)

export const getPointRecordPage = (params) => request.get('/api/points/page', { params })
export const addPointRecord = (data) => request.post('/api/points', data)
export const updatePointRecord = (data) => request.put('/api/points', data)
export const deletePointRecord = (id) => request.delete(`/api/points/${id}`)
export const processPointRecord = (id) => request.put(`/api/points/process/${id}`)
export const finishPointRecord = (id) => request.put(`/api/points/finish/${id}`)

export const getPointExchangePage = (params) => request.get('/api/exchange/page', { params })
export const addPointExchange = (data) => request.post('/api/exchange', data)
export const updatePointExchange = (data) => request.put('/api/exchange', data)
export const deletePointExchange = (id) => request.delete(`/api/exchange/${id}`)
export const processPointExchange = (id) => request.put(`/api/exchange/process/${id}`)
export const finishPointExchange = (id) => request.put(`/api/exchange/finish/${id}`)

export const getOrganizationTransferPage = (params) => request.get('/api/transfer/page', { params })
export const addOrganizationTransfer = (data) => request.post('/api/transfer', data)
export const updateOrganizationTransfer = (data) => request.put('/api/transfer', data)
export const deleteOrganizationTransfer = (id) => request.delete(`/api/transfer/${id}`)
export const processOrganizationTransfer = (id) => request.put(`/api/transfer/process/${id}`)
export const finishOrganizationTransfer = (id) => request.put(`/api/transfer/finish/${id}`)

export const getHonorRankingPage = (params) => request.get('/api/ranking/page', { params })
export const addHonorRanking = (data) => request.post('/api/ranking', data)
export const updateHonorRanking = (data) => request.put('/api/ranking', data)
export const deleteHonorRanking = (id) => request.delete(`/api/ranking/${id}`)
export const processHonorRanking = (id) => request.put(`/api/ranking/process/${id}`)
export const finishHonorRanking = (id) => request.put(`/api/ranking/finish/${id}`)

export const getNoticeBoardPage = (params) => request.get('/api/notice/page', { params })
export const addNoticeBoard = (data) => request.post('/api/notice', data)
export const updateNoticeBoard = (data) => request.put('/api/notice', data)
export const deleteNoticeBoard = (id) => request.delete(`/api/notice/${id}`)
export const processNoticeBoard = (id) => request.put(`/api/notice/process/${id}`)
export const finishNoticeBoard = (id) => request.put(`/api/notice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
