import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getLiveChannelPage = (params) => request.get('/api/channel/page', { params })
export const addLiveChannel = (data) => request.post('/api/channel', data)
export const updateLiveChannel = (data) => request.put('/api/channel', data)
export const deleteLiveChannel = (id) => request.delete(`/api/channel/${id}`)
export const approveLiveChannel = (id) => request.put(`/api/channel/approve/${id}`)
export const suspendLiveChannel = (id) => request.put(`/api/channel/suspend/${id}`)
export const getAnchorProfilePage = (params) => request.get('/api/anchor/page', { params })
export const addAnchorProfile = (data) => request.post('/api/anchor', data)
export const updateAnchorProfile = (data) => request.put('/api/anchor', data)
export const deleteAnchorProfile = (id) => request.delete(`/api/anchor/${id}`)
export const certifyAnchorProfile = (id) => request.put(`/api/anchor/certify/${id}`)
export const freezeAnchorProfile = (id) => request.put(`/api/anchor/freeze/${id}`)
export const getSupplierBrandPage = (params) => request.get('/api/supplier/page', { params })
export const addSupplierBrand = (data) => request.post('/api/supplier', data)
export const updateSupplierBrand = (data) => request.put('/api/supplier', data)
export const deleteSupplierBrand = (id) => request.delete(`/api/supplier/${id}`)
export const approveSupplierBrand = (id) => request.put(`/api/supplier/approve/${id}`)
export const disableSupplierBrand = (id) => request.put(`/api/supplier/disable/${id}`)
export const getProductSelectionPage = (params) => request.get('/api/selection/page', { params })
export const addProductSelection = (data) => request.post('/api/selection', data)
export const updateProductSelection = (data) => request.put('/api/selection', data)
export const deleteProductSelection = (id) => request.delete(`/api/selection/${id}`)
export const shortlistProductSelection = (id) => request.put(`/api/selection/shortlist/${id}`)
export const approveProductSelection = (id) => request.put(`/api/selection/approve/${id}`)
export const rejectProductSelection = (id) => request.put(`/api/selection/reject/${id}`)
export const getLiveSessionPage = (params) => request.get('/api/session/page', { params })
export const addLiveSession = (data) => request.post('/api/session', data)
export const updateLiveSession = (data) => request.put('/api/session', data)
export const deleteLiveSession = (id) => request.delete(`/api/session/${id}`)
export const scheduleLiveSession = (id) => request.put(`/api/session/schedule/${id}`)
export const startLiveSession = (id) => request.put(`/api/session/start/${id}`)
export const finishLiveSession = (id) => request.put(`/api/session/finish/${id}`)
export const getSchedulePlanPage = (params) => request.get('/api/schedule/page', { params })
export const addSchedulePlan = (data) => request.post('/api/schedule', data)
export const updateSchedulePlan = (data) => request.put('/api/schedule', data)
export const deleteSchedulePlan = (id) => request.delete(`/api/schedule/${id}`)
export const confirmSchedulePlan = (id) => request.put(`/api/schedule/confirm/${id}`)
export const cancelSchedulePlan = (id) => request.put(`/api/schedule/cancel/${id}`)
export const getSampleRequestPage = (params) => request.get('/api/sample/page', { params })
export const addSampleRequest = (data) => request.post('/api/sample', data)
export const updateSampleRequest = (data) => request.put('/api/sample', data)
export const deleteSampleRequest = (id) => request.delete(`/api/sample/${id}`)
export const sendSampleRequest = (id) => request.put(`/api/sample/send/${id}`)
export const receiveSampleRequest = (id) => request.put(`/api/sample/receive/${id}`)
export const getPromotionScriptPage = (params) => request.get('/api/script/page', { params })
export const addPromotionScript = (data) => request.post('/api/script', data)
export const updatePromotionScript = (data) => request.put('/api/script', data)
export const deletePromotionScript = (id) => request.delete(`/api/script/${id}`)
export const approvePromotionScript = (id) => request.put(`/api/script/approve/${id}`)
export const archivePromotionScript = (id) => request.put(`/api/script/archive/${id}`)
export const getLiveOrderPage = (params) => request.get('/api/order/page', { params })
export const addLiveOrder = (data) => request.post('/api/order', data)
export const updateLiveOrder = (data) => request.put('/api/order', data)
export const deleteLiveOrder = (id) => request.delete(`/api/order/${id}`)
export const shipLiveOrder = (id) => request.put(`/api/order/ship/${id}`)
export const completeLiveOrder = (id) => request.put(`/api/order/complete/${id}`)
export const getAfterSaleTicketPage = (params) => request.get('/api/ticket/page', { params })
export const addAfterSaleTicket = (data) => request.post('/api/ticket', data)
export const updateAfterSaleTicket = (data) => request.put('/api/ticket', data)
export const deleteAfterSaleTicket = (id) => request.delete(`/api/ticket/${id}`)
export const assignAfterSaleTicket = (id) => request.put(`/api/ticket/assign/${id}`)
export const resolveAfterSaleTicket = (id) => request.put(`/api/ticket/resolve/${id}`)
export const closeAfterSaleTicket = (id) => request.put(`/api/ticket/close/${id}`)
export const getRefundRecordPage = (params) => request.get('/api/refund/page', { params })
export const addRefundRecord = (data) => request.post('/api/refund', data)
export const updateRefundRecord = (data) => request.put('/api/refund', data)
export const deleteRefundRecord = (id) => request.delete(`/api/refund/${id}`)
export const approveRefundRecord = (id) => request.put(`/api/refund/approve/${id}`)
export const payRefundRecord = (id) => request.put(`/api/refund/pay/${id}`)
export const rejectRefundRecord = (id) => request.put(`/api/refund/reject/${id}`)
export const getAnchorPerformancePage = (params) => request.get('/api/performance/page', { params })
export const addAnchorPerformance = (data) => request.post('/api/performance', data)
export const updateAnchorPerformance = (data) => request.put('/api/performance', data)
export const deleteAnchorPerformance = (id) => request.delete(`/api/performance/${id}`)
export const confirmAnchorPerformance = (id) => request.put(`/api/performance/confirm/${id}`)
export const archiveAnchorPerformance = (id) => request.put(`/api/performance/archive/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
