import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getAgencyInfoPage = (params) => request.get('/api/agency/page', { params })
export const addAgencyInfo = (data) => request.post('/api/agency', data)
export const updateAgencyInfo = (data) => request.put('/api/agency', data)
export const deleteAgencyInfo = (id) => request.delete(`/api/agency/${id}`)
export const processAgencyInfo = (id) => request.put(`/api/agency/process/${id}`)
export const finishAgencyInfo = (id) => request.put(`/api/agency/finish/${id}`)

export const getTeamProfilePage = (params) => request.get('/api/team/page', { params })
export const addTeamProfile = (data) => request.post('/api/team', data)
export const updateTeamProfile = (data) => request.put('/api/team', data)
export const deleteTeamProfile = (id) => request.delete(`/api/team/${id}`)
export const processTeamProfile = (id) => request.put(`/api/team/process/${id}`)
export const finishTeamProfile = (id) => request.put(`/api/team/finish/${id}`)

export const getTripPlanPage = (params) => request.get('/api/trip/page', { params })
export const addTripPlan = (data) => request.post('/api/trip', data)
export const updateTripPlan = (data) => request.put('/api/trip', data)
export const deleteTripPlan = (id) => request.delete(`/api/trip/${id}`)
export const processTripPlan = (id) => request.put(`/api/trip/process/${id}`)
export const finishTripPlan = (id) => request.put(`/api/trip/finish/${id}`)

export const getSignupRegistrationPage = (params) => request.get('/api/signup/page', { params })
export const addSignupRegistration = (data) => request.post('/api/signup', data)
export const updateSignupRegistration = (data) => request.put('/api/signup', data)
export const deleteSignupRegistration = (id) => request.delete(`/api/signup/${id}`)
export const processSignupRegistration = (id) => request.put(`/api/signup/process/${id}`)
export const finishSignupRegistration = (id) => request.put(`/api/signup/finish/${id}`)

export const getMemberConfirmationPage = (params) => request.get('/api/confirmation/page', { params })
export const addMemberConfirmation = (data) => request.post('/api/confirmation', data)
export const updateMemberConfirmation = (data) => request.put('/api/confirmation', data)
export const deleteMemberConfirmation = (id) => request.delete(`/api/confirmation/${id}`)
export const processMemberConfirmation = (id) => request.put(`/api/confirmation/process/${id}`)
export const finishMemberConfirmation = (id) => request.put(`/api/confirmation/finish/${id}`)

export const getCostBudgetPage = (params) => request.get('/api/budget/page', { params })
export const addCostBudget = (data) => request.post('/api/budget', data)
export const updateCostBudget = (data) => request.put('/api/budget', data)
export const deleteCostBudget = (id) => request.delete(`/api/budget/${id}`)
export const processCostBudget = (id) => request.put(`/api/budget/process/${id}`)
export const finishCostBudget = (id) => request.put(`/api/budget/finish/${id}`)

export const getCostSharePage = (params) => request.get('/api/share/page', { params })
export const addCostShare = (data) => request.post('/api/share', data)
export const updateCostShare = (data) => request.put('/api/share', data)
export const deleteCostShare = (id) => request.delete(`/api/share/${id}`)
export const processCostShare = (id) => request.put(`/api/share/process/${id}`)
export const finishCostShare = (id) => request.put(`/api/share/finish/${id}`)

export const getPaymentRecordPage = (params) => request.get('/api/payment/page', { params })
export const addPaymentRecord = (data) => request.post('/api/payment', data)
export const updatePaymentRecord = (data) => request.put('/api/payment', data)
export const deletePaymentRecord = (id) => request.delete(`/api/payment/${id}`)
export const processPaymentRecord = (id) => request.put(`/api/payment/process/${id}`)
export const finishPaymentRecord = (id) => request.put(`/api/payment/finish/${id}`)

export const getNoticeSyncPage = (params) => request.get('/api/notice/page', { params })
export const addNoticeSync = (data) => request.post('/api/notice', data)
export const updateNoticeSync = (data) => request.put('/api/notice', data)
export const deleteNoticeSync = (id) => request.delete(`/api/notice/${id}`)
export const processNoticeSync = (id) => request.put(`/api/notice/process/${id}`)
export const finishNoticeSync = (id) => request.put(`/api/notice/finish/${id}`)

export const getTravelFeedbackPage = (params) => request.get('/api/feedback/page', { params })
export const addTravelFeedback = (data) => request.post('/api/feedback', data)
export const updateTravelFeedback = (data) => request.put('/api/feedback', data)
export const deleteTravelFeedback = (id) => request.delete(`/api/feedback/${id}`)
export const processTravelFeedback = (id) => request.put(`/api/feedback/process/${id}`)
export const finishTravelFeedback = (id) => request.put(`/api/feedback/finish/${id}`)

export const getInvoiceRecordPage = (params) => request.get('/api/invoice/page', { params })
export const addInvoiceRecord = (data) => request.post('/api/invoice', data)
export const updateInvoiceRecord = (data) => request.put('/api/invoice', data)
export const deleteInvoiceRecord = (id) => request.delete(`/api/invoice/${id}`)
export const processInvoiceRecord = (id) => request.put(`/api/invoice/process/${id}`)
export const finishInvoiceRecord = (id) => request.put(`/api/invoice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
