import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getEquipmentAssetPage = (params) => request.get('/api/asset/page', { params })
export const addEquipmentAsset = (data) => request.post('/api/asset', data)
export const updateEquipmentAsset = (data) => request.put('/api/asset', data)
export const deleteEquipmentAsset = (id) => request.delete(`/api/asset/${id}`)
export const activateEquipmentAsset = (id) => request.put(`/api/asset/activate/${id}`)
export const finishEquipmentAsset = (id) => request.put(`/api/asset/finish/${id}`)
export const getLaboratoryRoomPage = (params) => request.get('/api/lab/page', { params })
export const addLaboratoryRoom = (data) => request.post('/api/lab', data)
export const updateLaboratoryRoom = (data) => request.put('/api/lab', data)
export const deleteLaboratoryRoom = (id) => request.delete(`/api/lab/${id}`)
export const activateLaboratoryRoom = (id) => request.put(`/api/lab/activate/${id}`)
export const finishLaboratoryRoom = (id) => request.put(`/api/lab/finish/${id}`)
export const getEquipmentCategoryPage = (params) => request.get('/api/category/page', { params })
export const addEquipmentCategory = (data) => request.post('/api/category', data)
export const updateEquipmentCategory = (data) => request.put('/api/category', data)
export const deleteEquipmentCategory = (id) => request.delete(`/api/category/${id}`)
export const activateEquipmentCategory = (id) => request.put(`/api/category/activate/${id}`)
export const finishEquipmentCategory = (id) => request.put(`/api/category/finish/${id}`)
export const getBorrowUserPage = (params) => request.get('/api/borrow-user/page', { params })
export const addBorrowUser = (data) => request.post('/api/borrow-user', data)
export const updateBorrowUser = (data) => request.put('/api/borrow-user', data)
export const deleteBorrowUser = (id) => request.delete(`/api/borrow-user/${id}`)
export const processBorrowUser = (id) => request.put(`/api/borrow-user/process/${id}`)
export const finishBorrowUser = (id) => request.put(`/api/borrow-user/finish/${id}`)
export const getReservationRequestPage = (params) => request.get('/api/reservation/page', { params })
export const addReservationRequest = (data) => request.post('/api/reservation', data)
export const updateReservationRequest = (data) => request.put('/api/reservation', data)
export const deleteReservationRequest = (id) => request.delete(`/api/reservation/${id}`)
export const submitReservationRequest = (id) => request.put(`/api/reservation/submit/${id}`)
export const approveReservationRequest = (id) => request.put(`/api/reservation/approve/${id}`)
export const getBorrowRecordPage = (params) => request.get('/api/borrow-record/page', { params })
export const addBorrowRecord = (data) => request.post('/api/borrow-record', data)
export const updateBorrowRecord = (data) => request.put('/api/borrow-record', data)
export const deleteBorrowRecord = (id) => request.delete(`/api/borrow-record/${id}`)
export const submitBorrowRecord = (id) => request.put(`/api/borrow-record/submit/${id}`)
export const approveBorrowRecord = (id) => request.put(`/api/borrow-record/approve/${id}`)
export const getUsageRegistrationPage = (params) => request.get('/api/usage/page', { params })
export const addUsageRegistration = (data) => request.post('/api/usage', data)
export const updateUsageRegistration = (data) => request.put('/api/usage', data)
export const deleteUsageRegistration = (id) => request.delete(`/api/usage/${id}`)
export const processUsageRegistration = (id) => request.put(`/api/usage/process/${id}`)
export const finishUsageRegistration = (id) => request.put(`/api/usage/finish/${id}`)
export const getViolationRecordPage = (params) => request.get('/api/violation/page', { params })
export const addViolationRecord = (data) => request.post('/api/violation', data)
export const updateViolationRecord = (data) => request.put('/api/violation', data)
export const deleteViolationRecord = (id) => request.delete(`/api/violation/${id}`)
export const submitViolationRecord = (id) => request.put(`/api/violation/submit/${id}`)
export const approveViolationRecord = (id) => request.put(`/api/violation/approve/${id}`)
export const getMaintenanceWorkOrderPage = (params) => request.get('/api/maintenance/page', { params })
export const addMaintenanceWorkOrder = (data) => request.post('/api/maintenance', data)
export const updateMaintenanceWorkOrder = (data) => request.put('/api/maintenance', data)
export const deleteMaintenanceWorkOrder = (id) => request.delete(`/api/maintenance/${id}`)
export const submitMaintenanceWorkOrder = (id) => request.put(`/api/maintenance/submit/${id}`)
export const approveMaintenanceWorkOrder = (id) => request.put(`/api/maintenance/approve/${id}`)
export const getReturnConfirmationPage = (params) => request.get('/api/return-confirm/page', { params })
export const addReturnConfirmation = (data) => request.post('/api/return-confirm', data)
export const updateReturnConfirmation = (data) => request.put('/api/return-confirm', data)
export const deleteReturnConfirmation = (id) => request.delete(`/api/return-confirm/${id}`)
export const processReturnConfirmation = (id) => request.put(`/api/return-confirm/process/${id}`)
export const finishReturnConfirmation = (id) => request.put(`/api/return-confirm/finish/${id}`)
export const getInspectionPlanPage = (params) => request.get('/api/inspection/page', { params })
export const addInspectionPlan = (data) => request.post('/api/inspection', data)
export const updateInspectionPlan = (data) => request.put('/api/inspection', data)
export const deleteInspectionPlan = (id) => request.delete(`/api/inspection/${id}`)
export const activateInspectionPlan = (id) => request.put(`/api/inspection/activate/${id}`)
export const finishInspectionPlan = (id) => request.put(`/api/inspection/finish/${id}`)
export const getSystemNoticePage = (params) => request.get('/api/notice/page', { params })
export const addSystemNotice = (data) => request.post('/api/notice', data)
export const updateSystemNotice = (data) => request.put('/api/notice', data)
export const deleteSystemNotice = (id) => request.delete(`/api/notice/${id}`)
export const processSystemNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishSystemNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)









