CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(100),
    real_name VARCHAR(50),
    id_card VARCHAR(20),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    balance DECIMAL(10, 2) DEFAULT 0.00,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stadium (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(200) NOT NULL,
    city VARCHAR(50) NOT NULL,
    capacity INT NOT NULL,
    description CLOB,
    facilities VARCHAR(500),
    image_url VARCHAR(500),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    logo_url VARCHAR(500),
    country VARCHAR(50),
    city VARCHAR(50),
    founded_year INT,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "match" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,
    stadium_id BIGINT NOT NULL,
    match_date TIMESTAMP NOT NULL,
    match_type VARCHAR(50),
    league VARCHAR(100),
    season VARCHAR(50),
    description CLOB,
    poster_url VARCHAR(500),
    status VARCHAR(20) DEFAULT 'UPCOMING',
    home_score INT,
    away_score INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_match_home_team FOREIGN KEY (home_team_id) REFERENCES team (id),
    CONSTRAINT fk_match_away_team FOREIGN KEY (away_team_id) REFERENCES team (id),
    CONSTRAINT fk_match_stadium FOREIGN KEY (stadium_id) REFERENCES stadium (id)
);

CREATE TABLE IF NOT EXISTS seat_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stadium_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(200),
    total_seats INT NOT NULL,
    row_count INT NOT NULL,
    column_count INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_category_stadium FOREIGN KEY (stadium_id) REFERENCES stadium (id)
);

CREATE TABLE IF NOT EXISTS match_pricing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    available_seats INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pricing_match FOREIGN KEY (match_id) REFERENCES "match" (id),
    CONSTRAINT fk_pricing_category FOREIGN KEY (category_id) REFERENCES seat_category (id),
    CONSTRAINT uk_match_category UNIQUE (match_id, category_id)
);

CREATE TABLE IF NOT EXISTS seat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    row_number VARCHAR(10) NOT NULL,
    seat_number VARCHAR(10) NOT NULL,
    status VARCHAR(20) DEFAULT 'AVAILABLE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_seat_category FOREIGN KEY (category_id) REFERENCES seat_category (id),
    CONSTRAINT uk_seat UNIQUE (category_id, row_number, seat_number)
);

CREATE TABLE IF NOT EXISTS ticket_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    match_id BIGINT NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    payment_amount DECIMAL(10, 2) NOT NULL,
    discount_amount DECIMAL(10, 2) DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    payment_method VARCHAR(20),
    payment_time TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES "user" (id),
    CONSTRAINT fk_order_match FOREIGN KEY (match_id) REFERENCES "match" (id)
);

CREATE TABLE IF NOT EXISTS ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_no VARCHAR(50) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL,
    match_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'VALID',
    qr_code VARCHAR(500),
    check_in_time TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ticket_order FOREIGN KEY (order_id) REFERENCES ticket_order (id),
    CONSTRAINT fk_ticket_match FOREIGN KEY (match_id) REFERENCES "match" (id),
    CONSTRAINT fk_ticket_seat FOREIGN KEY (seat_id) REFERENCES seat (id),
    CONSTRAINT fk_ticket_category FOREIGN KEY (category_id) REFERENCES seat_category (id)
);

CREATE TABLE IF NOT EXISTS user_favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES "user" (id),
    CONSTRAINT fk_favorite_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT uk_user_team UNIQUE (user_id, team_id)
);

CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    type VARCHAR(50),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES "user" (id)
);

CREATE INDEX IF NOT EXISTS idx_user_username ON "user" (username);
CREATE INDEX IF NOT EXISTS idx_user_phone ON "user" (phone);
CREATE INDEX IF NOT EXISTS idx_stadium_city ON stadium (city);
CREATE INDEX IF NOT EXISTS idx_stadium_name ON stadium (name);
CREATE INDEX IF NOT EXISTS idx_team_name ON team (name);
CREATE INDEX IF NOT EXISTS idx_match_date ON "match" (match_date);
CREATE INDEX IF NOT EXISTS idx_match_status ON "match" (status);
CREATE INDEX IF NOT EXISTS idx_category_stadium ON seat_category (stadium_id);
CREATE INDEX IF NOT EXISTS idx_pricing_match ON match_pricing (match_id);
CREATE INDEX IF NOT EXISTS idx_seat_category ON seat (category_id);
CREATE INDEX IF NOT EXISTS idx_order_user ON ticket_order (user_id);
CREATE INDEX IF NOT EXISTS idx_order_no ON ticket_order (order_no);
CREATE INDEX IF NOT EXISTS idx_order_status ON ticket_order (status);
CREATE INDEX IF NOT EXISTS idx_ticket_order ON ticket (order_id);
CREATE INDEX IF NOT EXISTS idx_ticket_no ON ticket (ticket_no);
CREATE INDEX IF NOT EXISTS idx_ticket_match_category ON ticket (match_id, category_id);
CREATE INDEX IF NOT EXISTS idx_notification_user ON notification (user_id);
