import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getConferenceInfoPage = (params) => request.get('/api/conference/page', { params })
export const addConferenceInfo = (data) => request.post('/api/conference', data)
export const updateConferenceInfo = (data) => request.put('/api/conference', data)
export const deleteConferenceInfo = (id) => request.delete(`/api/conference/${id}`)
export const activateConferenceInfo = (id) => request.put(`/api/conference/activate/${id}`)
export const finishConferenceInfo = (id) => request.put(`/api/conference/finish/${id}`)
export const getCallForPaperPage = (params) => request.get('/api/call/page', { params })
export const addCallForPaper = (data) => request.post('/api/call', data)
export const updateCallForPaper = (data) => request.put('/api/call', data)
export const deleteCallForPaper = (id) => request.delete(`/api/call/${id}`)
export const activateCallForPaper = (id) => request.put(`/api/call/activate/${id}`)
export const finishCallForPaper = (id) => request.put(`/api/call/finish/${id}`)
export const getAuthorProfilePage = (params) => request.get('/api/author/page', { params })
export const addAuthorProfile = (data) => request.post('/api/author', data)
export const updateAuthorProfile = (data) => request.put('/api/author', data)
export const deleteAuthorProfile = (id) => request.delete(`/api/author/${id}`)
export const activateAuthorProfile = (id) => request.put(`/api/author/activate/${id}`)
export const finishAuthorProfile = (id) => request.put(`/api/author/finish/${id}`)
export const getPaperSubmissionPage = (params) => request.get('/api/paper/page', { params })
export const addPaperSubmission = (data) => request.post('/api/paper', data)
export const updatePaperSubmission = (data) => request.put('/api/paper', data)
export const deletePaperSubmission = (id) => request.delete(`/api/paper/${id}`)
export const processPaperSubmission = (id) => request.put(`/api/paper/process/${id}`)
export const finishPaperSubmission = (id) => request.put(`/api/paper/finish/${id}`)
export const getReviewerProfilePage = (params) => request.get('/api/reviewer/page', { params })
export const addReviewerProfile = (data) => request.post('/api/reviewer', data)
export const updateReviewerProfile = (data) => request.put('/api/reviewer', data)
export const deleteReviewerProfile = (id) => request.delete(`/api/reviewer/${id}`)
export const submitReviewerProfile = (id) => request.put(`/api/reviewer/submit/${id}`)
export const approveReviewerProfile = (id) => request.put(`/api/reviewer/approve/${id}`)
export const getReviewAssignmentPage = (params) => request.get('/api/assignment/page', { params })
export const addReviewAssignment = (data) => request.post('/api/assignment', data)
export const updateReviewAssignment = (data) => request.put('/api/assignment', data)
export const deleteReviewAssignment = (id) => request.delete(`/api/assignment/${id}`)
export const submitReviewAssignment = (id) => request.put(`/api/assignment/submit/${id}`)
export const approveReviewAssignment = (id) => request.put(`/api/assignment/approve/${id}`)
export const getBlindReviewPage = (params) => request.get('/api/review/page', { params })
export const addBlindReview = (data) => request.post('/api/review', data)
export const updateBlindReview = (data) => request.put('/api/review', data)
export const deleteBlindReview = (id) => request.delete(`/api/review/${id}`)
export const processBlindReview = (id) => request.put(`/api/review/process/${id}`)
export const finishBlindReview = (id) => request.put(`/api/review/finish/${id}`)
export const getAcceptanceNoticePage = (params) => request.get('/api/notice/page', { params })
export const addAcceptanceNotice = (data) => request.post('/api/notice', data)
export const updateAcceptanceNotice = (data) => request.put('/api/notice', data)
export const deleteAcceptanceNotice = (id) => request.delete(`/api/notice/${id}`)
export const submitAcceptanceNotice = (id) => request.put(`/api/notice/submit/${id}`)
export const approveAcceptanceNotice = (id) => request.put(`/api/notice/approve/${id}`)
export const getGuestRegistrationPage = (params) => request.get('/api/guest/page', { params })
export const addGuestRegistration = (data) => request.post('/api/guest', data)
export const updateGuestRegistration = (data) => request.put('/api/guest', data)
export const deleteGuestRegistration = (id) => request.delete(`/api/guest/${id}`)
export const submitGuestRegistration = (id) => request.put(`/api/guest/submit/${id}`)
export const approveGuestRegistration = (id) => request.put(`/api/guest/approve/${id}`)
export const getVenueRoomPage = (params) => request.get('/api/venue/page', { params })
export const addVenueRoom = (data) => request.post('/api/venue', data)
export const updateVenueRoom = (data) => request.put('/api/venue', data)
export const deleteVenueRoom = (id) => request.delete(`/api/venue/${id}`)
export const processVenueRoom = (id) => request.put(`/api/venue/process/${id}`)
export const finishVenueRoom = (id) => request.put(`/api/venue/finish/${id}`)
export const getAgendaSchedulePage = (params) => request.get('/api/agenda/page', { params })
export const addAgendaSchedule = (data) => request.post('/api/agenda', data)
export const updateAgendaSchedule = (data) => request.put('/api/agenda', data)
export const deleteAgendaSchedule = (id) => request.delete(`/api/agenda/${id}`)
export const activateAgendaSchedule = (id) => request.put(`/api/agenda/activate/${id}`)
export const finishAgendaSchedule = (id) => request.put(`/api/agenda/finish/${id}`)
export const getCheckinRecordPage = (params) => request.get('/api/venuein/page', { params })
export const addCheckinRecord = (data) => request.post('/api/venuein', data)
export const updateCheckinRecord = (data) => request.put('/api/venuein', data)
export const deleteCheckinRecord = (id) => request.delete(`/api/venuein/${id}`)
export const processCheckinRecord = (id) => request.put(`/api/venuein/process/${id}`)
export const finishCheckinRecord = (id) => request.put(`/api/venuein/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)

