DROP TABLE IF EXISTS notification;
DROP TABLE IF EXISTS balance_log;
DROP TABLE IF EXISTS points_log;
DROP TABLE IF EXISTS schedule;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS appointment;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS hairdresser;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(11) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(50),
    avatar VARCHAR(255) DEFAULT 'https://via.placeholder.com/150',
    gender TINYINT DEFAULT 0,
    points INT DEFAULT 0,
    level VARCHAR(20) DEFAULT '普通会员',
    balance DECIMAL(10, 2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    open_time TIME NOT NULL DEFAULT '09:00:00',
    close_time TIME NOT NULL DEFAULT '21:00:00',
    intro CLOB,
    images CLOB,
    rating DECIMAL(3, 2) DEFAULT 5.00,
    longitude DECIMAL(10, 7),
    latitude DECIMAL(10, 7),
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hairdresser (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    gender TINYINT DEFAULT 1,
    work_no VARCHAR(20) NOT NULL UNIQUE,
    avatar VARCHAR(255) DEFAULT 'https://via.placeholder.com/150',
    skills VARCHAR(500),
    work_years INT DEFAULT 0,
    intro CLOB,
    rating DECIMAL(3, 2) DEFAULT 5.00,
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hairdresser_store FOREIGN KEY (store_id) REFERENCES store (id)
);

CREATE TABLE service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    category VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    duration INT NOT NULL DEFAULT 30,
    description CLOB,
    image VARCHAR(255),
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_store FOREIGN KEY (store_id) REFERENCES store (id)
);

CREATE TABLE appointment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    hairdresser_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    status VARCHAR(20) DEFAULT '待确认',
    cancel_reason VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appointment_user FOREIGN KEY (user_id) REFERENCES user (id),
    CONSTRAINT fk_appointment_store FOREIGN KEY (store_id) REFERENCES store (id),
    CONSTRAINT fk_appointment_hairdresser FOREIGN KEY (hairdresser_id) REFERENCES hairdresser (id),
    CONSTRAINT fk_appointment_service FOREIGN KEY (service_id) REFERENCES service (id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL UNIQUE,
    appointment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    hairdresser_id BIGINT NOT NULL,
    service_name VARCHAR(100) NOT NULL,
    original_price DECIMAL(10, 2) NOT NULL,
    discount DECIMAL(3, 2) DEFAULT 1.00,
    actual_price DECIMAL(10, 2) NOT NULL,
    pay_type VARCHAR(20),
    pay_status TINYINT DEFAULT 0,
    pay_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_appointment FOREIGN KEY (appointment_id) REFERENCES appointment (id),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    hairdresser_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    rating TINYINT NOT NULL,
    content CLOB,
    images CLOB,
    tags VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES user (id),
    CONSTRAINT fk_review_hairdresser FOREIGN KEY (hairdresser_id) REFERENCES hairdresser (id)
);

CREATE TABLE schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hairdresser_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_schedule UNIQUE (hairdresser_id, work_date),
    CONSTRAINT fk_schedule_hairdresser FOREIGN KEY (hairdresser_id) REFERENCES hairdresser (id)
);

CREATE TABLE points_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    points INT NOT NULL,
    reason VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_points_log_user FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE balance_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    type VARCHAR(20) NOT NULL,
    reason VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_balance_log_user FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content CLOB NOT NULL,
    is_read TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'ADMIN',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_phone ON user (phone);
CREATE INDEX idx_store_status ON store (status);
CREATE INDEX idx_hairdresser_store ON hairdresser (store_id);
CREATE INDEX idx_hairdresser_status ON hairdresser (status);
CREATE INDEX idx_service_store ON service (store_id);
CREATE INDEX idx_service_category ON service (category);
CREATE INDEX idx_appointment_user ON appointment (user_id);
CREATE INDEX idx_appointment_hairdresser_slot ON appointment (hairdresser_id, appointment_date, appointment_time);
CREATE INDEX idx_orders_user ON orders (user_id);
CREATE INDEX idx_review_hairdresser ON review (hairdresser_id);
