DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS repair;
DROP TABLE IF EXISTS bill;
DROP TABLE IF EXISTS contract;
DROP TABLE IF EXISTS appointment;
DROP TABLE IF EXISTS house_favorite;
DROP TABLE IF EXISTS house;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'tenant',
    real_name VARCHAR(50),
    phone VARCHAR(20),
    id_card VARCHAR(20),
    avatar VARCHAR(255),
    balance DECIMAL(10,2) DEFAULT 0.00,
    status TINYINT NOT NULL DEFAULT 1,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0,
    CONSTRAINT uk_user_username UNIQUE (username)
);

CREATE TABLE house (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    landlord_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    province VARCHAR(50),
    city VARCHAR(50),
    district VARCHAR(50),
    address VARCHAR(200),
    price DECIMAL(10,2) NOT NULL,
    deposit DECIMAL(10,2),
    area DECIMAL(10,2),
    room_type VARCHAR(50),
    floor INT,
    total_floor INT,
    orientation VARCHAR(20),
    decoration VARCHAR(20),
    facilities VARCHAR(500),
    images TEXT,
    status TINYINT NOT NULL DEFAULT 0,
    view_count INT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0
);

CREATE INDEX idx_house_landlord_id ON house(landlord_id);
CREATE INDEX idx_house_status ON house(status);
CREATE INDEX idx_house_city ON house(city);

CREATE TABLE house_favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    house_id BIGINT NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_house_favorite_user_house UNIQUE (user_id, house_id)
);

CREATE INDEX idx_house_favorite_user_id ON house_favorite(user_id);
CREATE INDEX idx_house_favorite_house_id ON house_favorite(house_id);

CREATE TABLE appointment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    landlord_id BIGINT NOT NULL,
    appointment_time DATETIME NOT NULL,
    contact_phone VARCHAR(20),
    remark VARCHAR(500),
    status TINYINT NOT NULL DEFAULT 0,
    reject_reason VARCHAR(200),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_appointment_tenant_id ON appointment(tenant_id);
CREATE INDEX idx_appointment_landlord_id ON appointment(landlord_id);
CREATE INDEX idx_appointment_house_id ON appointment(house_id);

CREATE TABLE contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_no VARCHAR(50) NOT NULL,
    house_id BIGINT NOT NULL,
    landlord_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    monthly_rent DECIMAL(10,2) NOT NULL,
    deposit DECIMAL(10,2),
    payment_day INT DEFAULT 1,
    payment_method VARCHAR(20) DEFAULT '月付',
    terms TEXT,
    status TINYINT NOT NULL DEFAULT 0,
    sign_time DATETIME,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_contract_no UNIQUE (contract_no)
);

CREATE INDEX idx_contract_tenant_id ON contract(tenant_id);
CREATE INDEX idx_contract_landlord_id ON contract(landlord_id);
CREATE INDEX idx_contract_house_id ON contract(house_id);

CREATE TABLE bill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_no VARCHAR(50) NOT NULL,
    contract_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    landlord_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    bill_month VARCHAR(10) NOT NULL,
    due_date DATE NOT NULL,
    paid_amount DECIMAL(10,2) DEFAULT 0.00,
    paid_time DATETIME,
    status TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_bill_no UNIQUE (bill_no)
);

CREATE INDEX idx_bill_contract_id ON bill(contract_id);
CREATE INDEX idx_bill_tenant_id ON bill(tenant_id);
CREATE INDEX idx_bill_landlord_id ON bill(landlord_id);

CREATE TABLE repair (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id BIGINT NOT NULL,
    contract_id BIGINT,
    tenant_id BIGINT NOT NULL,
    landlord_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    description TEXT,
    images TEXT,
    status TINYINT NOT NULL DEFAULT 0,
    result VARCHAR(500),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_repair_tenant_id ON repair(tenant_id);
CREATE INDEX idx_repair_landlord_id ON repair(landlord_id);
CREATE INDEX idx_repair_house_id ON repair(house_id);

CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id BIGINT NOT NULL,
    contract_id BIGINT,
    tenant_id BIGINT NOT NULL,
    landlord_id BIGINT NOT NULL,
    house_score INT NOT NULL DEFAULT 5,
    service_score INT NOT NULL DEFAULT 5,
    facility_score INT NOT NULL DEFAULT 5,
    content TEXT,
    images TEXT,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_review_house_id ON review(house_id);
CREATE INDEX idx_review_tenant_id ON review(tenant_id);

CREATE TABLE message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT,
    type VARCHAR(50),
    is_read TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_message_user_id ON message(user_id);
CREATE INDEX idx_message_is_read ON message(is_read);
