import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getServiceProjectPage = (params) => request.get('/api/project/page', { params })
export const addServiceProject = (data) => request.post('/api/project', data)
export const updateServiceProject = (data) => request.put('/api/project', data)
export const deleteServiceProject = (id) => request.delete(`/api/project/${id}`)
export const activateServiceProject = (id) => request.put(`/api/project/activate/${id}`)
export const finishServiceProject = (id) => request.put(`/api/project/finish/${id}`)
export const getServiceCategoryPage = (params) => request.get('/api/category/page', { params })
export const addServiceCategory = (data) => request.post('/api/category', data)
export const updateServiceCategory = (data) => request.put('/api/category', data)
export const deleteServiceCategory = (id) => request.delete(`/api/category/${id}`)
export const activateServiceCategory = (id) => request.put(`/api/category/activate/${id}`)
export const finishServiceCategory = (id) => request.put(`/api/category/finish/${id}`)
export const getResidentProfilePage = (params) => request.get('/api/resident/page', { params })
export const addResidentProfile = (data) => request.post('/api/resident', data)
export const updateResidentProfile = (data) => request.put('/api/resident', data)
export const deleteResidentProfile = (id) => request.delete(`/api/resident/${id}`)
export const activateResidentProfile = (id) => request.put(`/api/resident/activate/${id}`)
export const finishResidentProfile = (id) => request.put(`/api/resident/finish/${id}`)
export const getVolunteerProfilePage = (params) => request.get('/api/volunteer/page', { params })
export const addVolunteerProfile = (data) => request.post('/api/volunteer', data)
export const updateVolunteerProfile = (data) => request.put('/api/volunteer', data)
export const deleteVolunteerProfile = (id) => request.delete(`/api/volunteer/${id}`)
export const processVolunteerProfile = (id) => request.put(`/api/volunteer/process/${id}`)
export const finishVolunteerProfile = (id) => request.put(`/api/volunteer/finish/${id}`)
export const getServiceBookingPage = (params) => request.get('/api/booking/page', { params })
export const addServiceBooking = (data) => request.post('/api/booking', data)
export const updateServiceBooking = (data) => request.put('/api/booking', data)
export const deleteServiceBooking = (id) => request.delete(`/api/booking/${id}`)
export const submitServiceBooking = (id) => request.put(`/api/booking/submit/${id}`)
export const approveServiceBooking = (id) => request.put(`/api/booking/approve/${id}`)
export const getServiceCheckinPage = (params) => request.get('/api/checkin/page', { params })
export const addServiceCheckin = (data) => request.post('/api/checkin', data)
export const updateServiceCheckin = (data) => request.put('/api/checkin', data)
export const deleteServiceCheckin = (id) => request.delete(`/api/checkin/${id}`)
export const submitServiceCheckin = (id) => request.put(`/api/checkin/submit/${id}`)
export const approveServiceCheckin = (id) => request.put(`/api/checkin/approve/${id}`)
export const getTimeAccountPage = (params) => request.get('/api/account/page', { params })
export const addTimeAccount = (data) => request.post('/api/account', data)
export const updateTimeAccount = (data) => request.put('/api/account', data)
export const deleteTimeAccount = (id) => request.delete(`/api/account/${id}`)
export const processTimeAccount = (id) => request.put(`/api/account/process/${id}`)
export const finishTimeAccount = (id) => request.put(`/api/account/finish/${id}`)
export const getTimeExchangePage = (params) => request.get('/api/exchange/page', { params })
export const addTimeExchange = (data) => request.post('/api/exchange', data)
export const updateTimeExchange = (data) => request.put('/api/exchange', data)
export const deleteTimeExchange = (id) => request.delete(`/api/exchange/${id}`)
export const submitTimeExchange = (id) => request.put(`/api/exchange/submit/${id}`)
export const approveTimeExchange = (id) => request.put(`/api/exchange/approve/${id}`)
export const getFeedbackReviewPage = (params) => request.get('/api/feedback/page', { params })
export const addFeedbackReview = (data) => request.post('/api/feedback', data)
export const updateFeedbackReview = (data) => request.put('/api/feedback', data)
export const deleteFeedbackReview = (id) => request.delete(`/api/feedback/${id}`)
export const submitFeedbackReview = (id) => request.put(`/api/feedback/submit/${id}`)
export const approveFeedbackReview = (id) => request.put(`/api/feedback/approve/${id}`)
export const getCommunityActivityPage = (params) => request.get('/api/activity/page', { params })
export const addCommunityActivity = (data) => request.post('/api/activity', data)
export const updateCommunityActivity = (data) => request.put('/api/activity', data)
export const deleteCommunityActivity = (id) => request.delete(`/api/activity/${id}`)
export const processCommunityActivity = (id) => request.put(`/api/activity/process/${id}`)
export const finishCommunityActivity = (id) => request.put(`/api/activity/finish/${id}`)
export const getPointRulePage = (params) => request.get('/api/rule/page', { params })
export const addPointRule = (data) => request.post('/api/rule', data)
export const updatePointRule = (data) => request.put('/api/rule', data)
export const deletePointRule = (id) => request.delete(`/api/rule/${id}`)
export const activatePointRule = (id) => request.put(`/api/rule/activate/${id}`)
export const finishPointRule = (id) => request.put(`/api/rule/finish/${id}`)
export const getSiteNoticePage = (params) => request.get('/api/notice/page', { params })
export const addSiteNotice = (data) => request.post('/api/notice', data)
export const updateSiteNotice = (data) => request.put('/api/notice', data)
export const deleteSiteNotice = (id) => request.delete(`/api/notice/${id}`)
export const processSiteNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishSiteNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)






