import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getCareAreaPage = (params) => request.get('/api/area/page', { params })
export const addCareArea = (data) => request.post('/api/area', data)
export const updateCareArea = (data) => request.put('/api/area', data)
export const deleteCareArea = (id) => request.delete(`/api/area/${id}`)
export const processCareArea = (id) => request.put(`/api/area/process/${id}`)
export const finishCareArea = (id) => request.put(`/api/area/finish/${id}`)

export const getRoomProfilePage = (params) => request.get('/api/room/page', { params })
export const addRoomProfile = (data) => request.post('/api/room', data)
export const updateRoomProfile = (data) => request.put('/api/room', data)
export const deleteRoomProfile = (id) => request.delete(`/api/room/${id}`)
export const processRoomProfile = (id) => request.put(`/api/room/process/${id}`)
export const finishRoomProfile = (id) => request.put(`/api/room/finish/${id}`)

export const getBedProfilePage = (params) => request.get('/api/bed/page', { params })
export const addBedProfile = (data) => request.post('/api/bed', data)
export const updateBedProfile = (data) => request.put('/api/bed', data)
export const deleteBedProfile = (id) => request.delete(`/api/bed/${id}`)
export const processBedProfile = (id) => request.put(`/api/bed/process/${id}`)
export const finishBedProfile = (id) => request.put(`/api/bed/finish/${id}`)

export const getElderProfilePage = (params) => request.get('/api/elder/page', { params })
export const addElderProfile = (data) => request.post('/api/elder', data)
export const updateElderProfile = (data) => request.put('/api/elder', data)
export const deleteElderProfile = (id) => request.delete(`/api/elder/${id}`)
export const processElderProfile = (id) => request.put(`/api/elder/process/${id}`)
export const finishElderProfile = (id) => request.put(`/api/elder/finish/${id}`)

export const getFamilyProfilePage = (params) => request.get('/api/family/page', { params })
export const addFamilyProfile = (data) => request.post('/api/family', data)
export const updateFamilyProfile = (data) => request.put('/api/family', data)
export const deleteFamilyProfile = (id) => request.delete(`/api/family/${id}`)
export const processFamilyProfile = (id) => request.put(`/api/family/process/${id}`)
export const finishFamilyProfile = (id) => request.put(`/api/family/finish/${id}`)

export const getCheckinAssessmentPage = (params) => request.get('/api/assessment/page', { params })
export const addCheckinAssessment = (data) => request.post('/api/assessment', data)
export const updateCheckinAssessment = (data) => request.put('/api/assessment', data)
export const deleteCheckinAssessment = (id) => request.delete(`/api/assessment/${id}`)
export const processCheckinAssessment = (id) => request.put(`/api/assessment/process/${id}`)
export const finishCheckinAssessment = (id) => request.put(`/api/assessment/finish/${id}`)

export const getBedAllocationPage = (params) => request.get('/api/allocation/page', { params })
export const addBedAllocation = (data) => request.post('/api/allocation', data)
export const updateBedAllocation = (data) => request.put('/api/allocation', data)
export const deleteBedAllocation = (id) => request.delete(`/api/allocation/${id}`)
export const processBedAllocation = (id) => request.put(`/api/allocation/process/${id}`)
export const finishBedAllocation = (id) => request.put(`/api/allocation/finish/${id}`)

export const getCarePlanPage = (params) => request.get('/api/plan/page', { params })
export const addCarePlan = (data) => request.post('/api/plan', data)
export const updateCarePlan = (data) => request.put('/api/plan', data)
export const deleteCarePlan = (id) => request.delete(`/api/plan/${id}`)
export const processCarePlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishCarePlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getCareRecordPage = (params) => request.get('/api/care/page', { params })
export const addCareRecord = (data) => request.post('/api/care', data)
export const updateCareRecord = (data) => request.put('/api/care', data)
export const deleteCareRecord = (id) => request.delete(`/api/care/${id}`)
export const processCareRecord = (id) => request.put(`/api/care/process/${id}`)
export const finishCareRecord = (id) => request.put(`/api/care/finish/${id}`)

export const getFamilyQueryPage = (params) => request.get('/api/query/page', { params })
export const addFamilyQuery = (data) => request.post('/api/query', data)
export const updateFamilyQuery = (data) => request.put('/api/query', data)
export const deleteFamilyQuery = (id) => request.delete(`/api/query/${id}`)
export const processFamilyQuery = (id) => request.put(`/api/query/process/${id}`)
export const finishFamilyQuery = (id) => request.put(`/api/query/finish/${id}`)

export const getExceptionReportPage = (params) => request.get('/api/exception/page', { params })
export const addExceptionReport = (data) => request.post('/api/exception', data)
export const updateExceptionReport = (data) => request.put('/api/exception', data)
export const deleteExceptionReport = (id) => request.delete(`/api/exception/${id}`)
export const processExceptionReport = (id) => request.put(`/api/exception/process/${id}`)
export const finishExceptionReport = (id) => request.put(`/api/exception/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
