import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getParkEnterprisePage = (params) => request.get('/api/enterprise/page', { params })
export const addParkEnterprise = (data) => request.post('/api/enterprise', data)
export const updateParkEnterprise = (data) => request.put('/api/enterprise', data)
export const deleteParkEnterprise = (id) => request.delete(`/api/enterprise/${id}`)
export const processParkEnterprise = (id) => request.put(`/api/enterprise/process/${id}`)
export const finishParkEnterprise = (id) => request.put(`/api/enterprise/finish/${id}`)

export const getWasteCategoryPage = (params) => request.get('/api/waste/page', { params })
export const addWasteCategory = (data) => request.post('/api/waste', data)
export const updateWasteCategory = (data) => request.put('/api/waste', data)
export const deleteWasteCategory = (id) => request.delete(`/api/waste/${id}`)
export const processWasteCategory = (id) => request.put(`/api/waste/process/${id}`)
export const finishWasteCategory = (id) => request.put(`/api/waste/finish/${id}`)

export const getStorageFacilityPage = (params) => request.get('/api/facility/page', { params })
export const addStorageFacility = (data) => request.post('/api/facility', data)
export const updateStorageFacility = (data) => request.put('/api/facility', data)
export const deleteStorageFacility = (id) => request.delete(`/api/facility/${id}`)
export const processStorageFacility = (id) => request.put(`/api/facility/process/${id}`)
export const finishStorageFacility = (id) => request.put(`/api/facility/finish/${id}`)

export const getStorageInboundPage = (params) => request.get('/api/inbound/page', { params })
export const addStorageInbound = (data) => request.post('/api/inbound', data)
export const updateStorageInbound = (data) => request.put('/api/inbound', data)
export const deleteStorageInbound = (id) => request.delete(`/api/inbound/${id}`)
export const processStorageInbound = (id) => request.put(`/api/inbound/process/${id}`)
export const finishStorageInbound = (id) => request.put(`/api/inbound/finish/${id}`)

export const getStorageCheckPage = (params) => request.get('/api/check/page', { params })
export const addStorageCheck = (data) => request.post('/api/check', data)
export const updateStorageCheck = (data) => request.put('/api/check', data)
export const deleteStorageCheck = (id) => request.delete(`/api/check/${id}`)
export const processStorageCheck = (id) => request.put(`/api/check/process/${id}`)
export const finishStorageCheck = (id) => request.put(`/api/check/finish/${id}`)

export const getTransferOrderPage = (params) => request.get('/api/transfer/page', { params })
export const addTransferOrder = (data) => request.post('/api/transfer', data)
export const updateTransferOrder = (data) => request.put('/api/transfer', data)
export const deleteTransferOrder = (id) => request.delete(`/api/transfer/${id}`)
export const processTransferOrder = (id) => request.put(`/api/transfer/process/${id}`)
export const finishTransferOrder = (id) => request.put(`/api/transfer/finish/${id}`)

export const getVehicleDispatchPage = (params) => request.get('/api/dispatch/page', { params })
export const addVehicleDispatch = (data) => request.post('/api/dispatch', data)
export const updateVehicleDispatch = (data) => request.put('/api/dispatch', data)
export const deleteVehicleDispatch = (id) => request.delete(`/api/dispatch/${id}`)
export const processVehicleDispatch = (id) => request.put(`/api/dispatch/process/${id}`)
export const finishVehicleDispatch = (id) => request.put(`/api/dispatch/finish/${id}`)

export const getWeighingRecordPage = (params) => request.get('/api/weighing/page', { params })
export const addWeighingRecord = (data) => request.post('/api/weighing', data)
export const updateWeighingRecord = (data) => request.put('/api/weighing', data)
export const deleteWeighingRecord = (id) => request.delete(`/api/weighing/${id}`)
export const processWeighingRecord = (id) => request.put(`/api/weighing/process/${id}`)
export const finishWeighingRecord = (id) => request.put(`/api/weighing/finish/${id}`)

export const getDisposalHandoverPage = (params) => request.get('/api/handover/page', { params })
export const addDisposalHandover = (data) => request.post('/api/handover', data)
export const updateDisposalHandover = (data) => request.put('/api/handover', data)
export const deleteDisposalHandover = (id) => request.delete(`/api/handover/${id}`)
export const processDisposalHandover = (id) => request.put(`/api/handover/process/${id}`)
export const finishDisposalHandover = (id) => request.put(`/api/handover/finish/${id}`)

export const getRiskWarningPage = (params) => request.get('/api/warning/page', { params })
export const addRiskWarning = (data) => request.post('/api/warning', data)
export const updateRiskWarning = (data) => request.put('/api/warning', data)
export const deleteRiskWarning = (id) => request.delete(`/api/warning/${id}`)
export const processRiskWarning = (id) => request.put(`/api/warning/process/${id}`)
export const finishRiskWarning = (id) => request.put(`/api/warning/finish/${id}`)

export const getLedgerAuditPage = (params) => request.get('/api/audit/page', { params })
export const addLedgerAudit = (data) => request.post('/api/audit', data)
export const updateLedgerAudit = (data) => request.put('/api/audit', data)
export const deleteLedgerAudit = (id) => request.delete(`/api/audit/${id}`)
export const processLedgerAudit = (id) => request.put(`/api/audit/process/${id}`)
export const finishLedgerAudit = (id) => request.put(`/api/audit/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
