import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getServiceStationPage = (params) => request.get('/api/station/page', { params })
export const addServiceStation = (data) => request.post('/api/station', data)
export const updateServiceStation = (data) => request.put('/api/station', data)
export const deleteServiceStation = (id) => request.delete(`/api/station/${id}`)
export const processServiceStation = (id) => request.put(`/api/station/process/${id}`)
export const finishServiceStation = (id) => request.put(`/api/station/finish/${id}`)

export const getResidentProfilePage = (params) => request.get('/api/resident/page', { params })
export const addResidentProfile = (data) => request.post('/api/resident', data)
export const updateResidentProfile = (data) => request.put('/api/resident', data)
export const deleteResidentProfile = (id) => request.delete(`/api/resident/${id}`)
export const processResidentProfile = (id) => request.put(`/api/resident/process/${id}`)
export const finishResidentProfile = (id) => request.put(`/api/resident/finish/${id}`)

export const getWorkerProfilePage = (params) => request.get('/api/worker/page', { params })
export const addWorkerProfile = (data) => request.post('/api/worker', data)
export const updateWorkerProfile = (data) => request.put('/api/worker', data)
export const deleteWorkerProfile = (id) => request.delete(`/api/worker/${id}`)
export const processWorkerProfile = (id) => request.put(`/api/worker/process/${id}`)
export const finishWorkerProfile = (id) => request.put(`/api/worker/finish/${id}`)

export const getServiceCatalogPage = (params) => request.get('/api/service/page', { params })
export const addServiceCatalog = (data) => request.post('/api/service', data)
export const updateServiceCatalog = (data) => request.put('/api/service', data)
export const deleteServiceCatalog = (id) => request.delete(`/api/service/${id}`)
export const processServiceCatalog = (id) => request.put(`/api/service/process/${id}`)
export const finishServiceCatalog = (id) => request.put(`/api/service/finish/${id}`)

export const getServiceBookingPage = (params) => request.get('/api/booking/page', { params })
export const addServiceBooking = (data) => request.post('/api/booking', data)
export const updateServiceBooking = (data) => request.put('/api/booking', data)
export const deleteServiceBooking = (id) => request.delete(`/api/booking/${id}`)
export const processServiceBooking = (id) => request.put(`/api/booking/process/${id}`)
export const finishServiceBooking = (id) => request.put(`/api/booking/finish/${id}`)

export const getBookingReviewPage = (params) => request.get('/api/review/page', { params })
export const addBookingReview = (data) => request.post('/api/review', data)
export const updateBookingReview = (data) => request.put('/api/review', data)
export const deleteBookingReview = (id) => request.delete(`/api/review/${id}`)
export const processBookingReview = (id) => request.put(`/api/review/process/${id}`)
export const finishBookingReview = (id) => request.put(`/api/review/finish/${id}`)

export const getScheduleDispatchPage = (params) => request.get('/api/dispatch/page', { params })
export const addScheduleDispatch = (data) => request.post('/api/dispatch', data)
export const updateScheduleDispatch = (data) => request.put('/api/dispatch', data)
export const deleteScheduleDispatch = (id) => request.delete(`/api/dispatch/${id}`)
export const processScheduleDispatch = (id) => request.put(`/api/dispatch/process/${id}`)
export const finishScheduleDispatch = (id) => request.put(`/api/dispatch/finish/${id}`)

export const getServiceRecordPage = (params) => request.get('/api/record/page', { params })
export const addServiceRecord = (data) => request.post('/api/record', data)
export const updateServiceRecord = (data) => request.put('/api/record', data)
export const deleteServiceRecord = (id) => request.delete(`/api/record/${id}`)
export const processServiceRecord = (id) => request.put(`/api/record/process/${id}`)
export const finishServiceRecord = (id) => request.put(`/api/record/finish/${id}`)

export const getCreditEvaluationPage = (params) => request.get('/api/evaluation/page', { params })
export const addCreditEvaluation = (data) => request.post('/api/evaluation', data)
export const updateCreditEvaluation = (data) => request.put('/api/evaluation', data)
export const deleteCreditEvaluation = (id) => request.delete(`/api/evaluation/${id}`)
export const processCreditEvaluation = (id) => request.put(`/api/evaluation/process/${id}`)
export const finishCreditEvaluation = (id) => request.put(`/api/evaluation/finish/${id}`)

export const getComplaintHandlingPage = (params) => request.get('/api/complaint/page', { params })
export const addComplaintHandling = (data) => request.post('/api/complaint', data)
export const updateComplaintHandling = (data) => request.put('/api/complaint', data)
export const deleteComplaintHandling = (id) => request.delete(`/api/complaint/${id}`)
export const processComplaintHandling = (id) => request.put(`/api/complaint/process/${id}`)
export const finishComplaintHandling = (id) => request.put(`/api/complaint/finish/${id}`)

export const getSettlementRecordPage = (params) => request.get('/api/settlement/page', { params })
export const addSettlementRecord = (data) => request.post('/api/settlement', data)
export const updateSettlementRecord = (data) => request.put('/api/settlement', data)
export const deleteSettlementRecord = (id) => request.delete(`/api/settlement/${id}`)
export const processSettlementRecord = (id) => request.put(`/api/settlement/process/${id}`)
export const finishSettlementRecord = (id) => request.put(`/api/settlement/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
