import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getFarmBasePage = (params) => request.get('/api/farm/page', { params })
export const addFarmBase = (data) => request.post('/api/farm', data)
export const updateFarmBase = (data) => request.put('/api/farm', data)
export const deleteFarmBase = (id) => request.delete(`/api/farm/${id}`)
export const certifyFarmBase = (id) => request.put(`/api/farm/certify/${id}`)
export const suspendFarmBase = (id) => request.put(`/api/farm/suspend/${id}`)
export const getFarmerProfilePage = (params) => request.get('/api/farmer/page', { params })
export const addFarmerProfile = (data) => request.post('/api/farmer', data)
export const updateFarmerProfile = (data) => request.put('/api/farmer', data)
export const deleteFarmerProfile = (id) => request.delete(`/api/farmer/${id}`)
export const activateFarmerProfile = (id) => request.put(`/api/farmer/activate/${id}`)
export const freezeFarmerProfile = (id) => request.put(`/api/farmer/freeze/${id}`)
export const getProductCategoryPage = (params) => request.get('/api/category/page', { params })
export const addProductCategory = (data) => request.post('/api/category', data)
export const updateProductCategory = (data) => request.put('/api/category', data)
export const deleteProductCategory = (id) => request.delete(`/api/category/${id}`)
export const enableProductCategory = (id) => request.put(`/api/category/enable/${id}`)
export const disableProductCategory = (id) => request.put(`/api/category/disable/${id}`)
export const getProductBatchPage = (params) => request.get('/api/batch/page', { params })
export const addProductBatch = (data) => request.post('/api/batch', data)
export const updateProductBatch = (data) => request.put('/api/batch', data)
export const deleteProductBatch = (id) => request.delete(`/api/batch/${id}`)
export const submitProductBatch = (id) => request.put(`/api/batch/submit/${id}`)
export const chainProductBatch = (id) => request.put(`/api/batch/chain/${id}`)
export const closeProductBatch = (id) => request.put(`/api/batch/close/${id}`)
export const getPlantingRecordPage = (params) => request.get('/api/planting/page', { params })
export const addPlantingRecord = (data) => request.post('/api/planting', data)
export const updatePlantingRecord = (data) => request.put('/api/planting', data)
export const deletePlantingRecord = (id) => request.delete(`/api/planting/${id}`)
export const confirmPlantingRecord = (id) => request.put(`/api/planting/confirm/${id}`)
export const chainPlantingRecord = (id) => request.put(`/api/planting/chain/${id}`)
export const getInputMaterialPage = (params) => request.get('/api/material/page', { params })
export const addInputMaterial = (data) => request.post('/api/material', data)
export const updateInputMaterial = (data) => request.put('/api/material', data)
export const deleteInputMaterial = (id) => request.delete(`/api/material/${id}`)
export const approveInputMaterial = (id) => request.put(`/api/material/approve/${id}`)
export const rejectInputMaterial = (id) => request.put(`/api/material/reject/${id}`)
export const getQualityInspectionPage = (params) => request.get('/api/inspection/page', { params })
export const addQualityInspection = (data) => request.post('/api/inspection', data)
export const updateQualityInspection = (data) => request.put('/api/inspection', data)
export const deleteQualityInspection = (id) => request.delete(`/api/inspection/${id}`)
export const publishQualityInspection = (id) => request.put(`/api/inspection/publish/${id}`)
export const failQualityInspection = (id) => request.put(`/api/inspection/fail/${id}`)
export const getChainBlockPage = (params) => request.get('/api/block/page', { params })
export const addChainBlock = (data) => request.post('/api/block', data)
export const updateChainBlock = (data) => request.put('/api/block', data)
export const deleteChainBlock = (id) => request.delete(`/api/block/${id}`)
export const confirmChainBlock = (id) => request.put(`/api/block/confirm/${id}`)
export const failChainBlock = (id) => request.put(`/api/block/fail/${id}`)
export const getTraceNodePage = (params) => request.get('/api/node/page', { params })
export const addTraceNode = (data) => request.post('/api/node', data)
export const updateTraceNode = (data) => request.put('/api/node', data)
export const deleteTraceNode = (id) => request.delete(`/api/node/${id}`)
export const enableTraceNode = (id) => request.put(`/api/node/enable/${id}`)
export const disableTraceNode = (id) => request.put(`/api/node/disable/${id}`)
export const getLogisticsRecordPage = (params) => request.get('/api/logistics/page', { params })
export const addLogisticsRecord = (data) => request.post('/api/logistics', data)
export const updateLogisticsRecord = (data) => request.put('/api/logistics', data)
export const deleteLogisticsRecord = (id) => request.delete(`/api/logistics/${id}`)
export const departLogisticsRecord = (id) => request.put(`/api/logistics/depart/${id}`)
export const arriveLogisticsRecord = (id) => request.put(`/api/logistics/arrive/${id}`)
export const signLogisticsRecord = (id) => request.put(`/api/logistics/sign/${id}`)
export const getRecallEventPage = (params) => request.get('/api/recall/page', { params })
export const addRecallEvent = (data) => request.post('/api/recall', data)
export const updateRecallEvent = (data) => request.put('/api/recall', data)
export const deleteRecallEvent = (id) => request.delete(`/api/recall/${id}`)
export const processRecallEvent = (id) => request.put(`/api/recall/process/${id}`)
export const closeRecallEvent = (id) => request.put(`/api/recall/close/${id}`)
export const getRegulationCheckPage = (params) => request.get('/api/regulation/page', { params })
export const addRegulationCheck = (data) => request.post('/api/regulation', data)
export const updateRegulationCheck = (data) => request.put('/api/regulation', data)
export const deleteRegulationCheck = (id) => request.delete(`/api/regulation/${id}`)
export const publishRegulationCheck = (id) => request.put(`/api/regulation/publish/${id}`)
export const rectifyRegulationCheck = (id) => request.put(`/api/regulation/rectify/${id}`)
export const closeRegulationCheck = (id) => request.put(`/api/regulation/close/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
