import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getHomeProfilePage = (params) => request.get('/api/home/page', { params })
export const addHomeProfile = (data) => request.post('/api/home', data)
export const updateHomeProfile = (data) => request.put('/api/home', data)
export const deleteHomeProfile = (id) => request.delete(`/api/home/${id}`)
export const enableHomeProfile = (id) => request.put(`/api/home/enable/${id}`)
export const disableHomeProfile = (id) => request.put(`/api/home/disable/${id}`)
export const getFamilyMemberPage = (params) => request.get('/api/member/page', { params })
export const addFamilyMember = (data) => request.post('/api/member', data)
export const updateFamilyMember = (data) => request.put('/api/member', data)
export const deleteFamilyMember = (id) => request.delete(`/api/member/${id}`)
export const enableFamilyMember = (id) => request.put(`/api/member/enable/${id}`)
export const disableFamilyMember = (id) => request.put(`/api/member/disable/${id}`)
export const getSmartMeterPage = (params) => request.get('/api/meter/page', { params })
export const addSmartMeter = (data) => request.post('/api/meter', data)
export const updateSmartMeter = (data) => request.put('/api/meter', data)
export const deleteSmartMeter = (id) => request.delete(`/api/meter/${id}`)
export const onlineSmartMeter = (id) => request.put(`/api/meter/online/${id}`)
export const warnSmartMeter = (id) => request.put(`/api/meter/warn/${id}`)
export const getElectricDevicePage = (params) => request.get('/api/device/page', { params })
export const addElectricDevice = (data) => request.post('/api/device', data)
export const updateElectricDevice = (data) => request.put('/api/device', data)
export const deleteElectricDevice = (id) => request.delete(`/api/device/${id}`)
export const enableElectricDevice = (id) => request.put(`/api/device/enable/${id}`)
export const disableElectricDevice = (id) => request.put(`/api/device/disable/${id}`)
export const getEnergyReadingPage = (params) => request.get('/api/reading/page', { params })
export const addEnergyReading = (data) => request.post('/api/reading', data)
export const updateEnergyReading = (data) => request.put('/api/reading', data)
export const deleteEnergyReading = (id) => request.delete(`/api/reading/${id}`)
export const warnEnergyReading = (id) => request.put(`/api/reading/warn/${id}`)
export const recoverEnergyReading = (id) => request.put(`/api/reading/recover/${id}`)
export const getElectricityBillPage = (params) => request.get('/api/bill/page', { params })
export const addElectricityBill = (data) => request.post('/api/bill', data)
export const updateElectricityBill = (data) => request.put('/api/bill', data)
export const deleteElectricityBill = (id) => request.delete(`/api/bill/${id}`)
export const payElectricityBill = (id) => request.put(`/api/bill/pay/${id}`)
export const closeElectricityBill = (id) => request.put(`/api/bill/close/${id}`)
export const getDeviceUsagePage = (params) => request.get('/api/usage/page', { params })
export const addDeviceUsage = (data) => request.post('/api/usage', data)
export const updateDeviceUsage = (data) => request.put('/api/usage', data)
export const deleteDeviceUsage = (id) => request.delete(`/api/usage/${id}`)
export const warnDeviceUsage = (id) => request.put(`/api/usage/warn/${id}`)
export const recoverDeviceUsage = (id) => request.put(`/api/usage/recover/${id}`)
export const getEnergyBudgetPage = (params) => request.get('/api/budget/page', { params })
export const addEnergyBudget = (data) => request.post('/api/budget', data)
export const updateEnergyBudget = (data) => request.put('/api/budget', data)
export const deleteEnergyBudget = (id) => request.delete(`/api/budget/${id}`)
export const enableEnergyBudget = (id) => request.put(`/api/budget/enable/${id}`)
export const overEnergyBudget = (id) => request.put(`/api/budget/over/${id}`)
export const getSavingSuggestionPage = (params) => request.get('/api/suggestion/page', { params })
export const addSavingSuggestion = (data) => request.post('/api/suggestion', data)
export const updateSavingSuggestion = (data) => request.put('/api/suggestion', data)
export const deleteSavingSuggestion = (id) => request.delete(`/api/suggestion/${id}`)
export const publishSavingSuggestion = (id) => request.put(`/api/suggestion/publish/${id}`)
export const closeSavingSuggestion = (id) => request.put(`/api/suggestion/close/${id}`)
export const getAbnormalAlertPage = (params) => request.get('/api/alert/page', { params })
export const addAbnormalAlert = (data) => request.post('/api/alert', data)
export const updateAbnormalAlert = (data) => request.put('/api/alert', data)
export const deleteAbnormalAlert = (id) => request.delete(`/api/alert/${id}`)
export const assignAbnormalAlert = (id) => request.put(`/api/alert/assign/${id}`)
export const closeAbnormalAlert = (id) => request.put(`/api/alert/close/${id}`)
export const getCarbonStatisticPage = (params) => request.get('/api/carbon/page', { params })
export const addCarbonStatistic = (data) => request.post('/api/carbon', data)
export const updateCarbonStatistic = (data) => request.put('/api/carbon', data)
export const deleteCarbonStatistic = (id) => request.delete(`/api/carbon/${id}`)
export const confirmCarbonStatistic = (id) => request.put(`/api/carbon/confirm/${id}`)
export const publishCarbonStatistic = (id) => request.put(`/api/carbon/publish/${id}`)
export const getMaintenanceTicketPage = (params) => request.get('/api/ticket/page', { params })
export const addMaintenanceTicket = (data) => request.post('/api/ticket', data)
export const updateMaintenanceTicket = (data) => request.put('/api/ticket', data)
export const deleteMaintenanceTicket = (id) => request.delete(`/api/ticket/${id}`)
export const assignMaintenanceTicket = (id) => request.put(`/api/ticket/assign/${id}`)
export const finishMaintenanceTicket = (id) => request.put(`/api/ticket/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
