import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getAssetInfoPage = (params) => request.get('/api/asset/page', { params })
export const addAssetInfo = (data) => request.post('/api/asset', data)
export const updateAssetInfo = (data) => request.put('/api/asset', data)
export const deleteAssetInfo = (id) => request.delete(`/api/asset/${id}`)
export const activateAssetInfo = (id) => request.put(`/api/asset/activate/${id}`)
export const finishAssetInfo = (id) => request.put(`/api/asset/finish/${id}`)
export const getAssetCategoryPage = (params) => request.get('/api/category/page', { params })
export const addAssetCategory = (data) => request.post('/api/category', data)
export const updateAssetCategory = (data) => request.put('/api/category', data)
export const deleteAssetCategory = (id) => request.delete(`/api/category/${id}`)
export const activateAssetCategory = (id) => request.put(`/api/category/activate/${id}`)
export const finishAssetCategory = (id) => request.put(`/api/category/finish/${id}`)
export const getRfidTagPage = (params) => request.get('/api/tag/page', { params })
export const addRfidTag = (data) => request.post('/api/tag', data)
export const updateRfidTag = (data) => request.put('/api/tag', data)
export const deleteRfidTag = (id) => request.delete(`/api/tag/${id}`)
export const activateRfidTag = (id) => request.put(`/api/tag/activate/${id}`)
export const finishRfidTag = (id) => request.put(`/api/tag/finish/${id}`)
export const getStorageLocationPage = (params) => request.get('/api/location/page', { params })
export const addStorageLocation = (data) => request.post('/api/location', data)
export const updateStorageLocation = (data) => request.put('/api/location', data)
export const deleteStorageLocation = (id) => request.delete(`/api/location/${id}`)
export const processStorageLocation = (id) => request.put(`/api/location/process/${id}`)
export const finishStorageLocation = (id) => request.put(`/api/location/finish/${id}`)
export const getInventoryTaskPage = (params) => request.get('/api/inventory-task/page', { params })
export const addInventoryTask = (data) => request.post('/api/inventory-task', data)
export const updateInventoryTask = (data) => request.put('/api/inventory-task', data)
export const deleteInventoryTask = (id) => request.delete(`/api/inventory-task/${id}`)
export const submitInventoryTask = (id) => request.put(`/api/inventory-task/submit/${id}`)
export const approveInventoryTask = (id) => request.put(`/api/inventory-task/approve/${id}`)
export const getInventoryRecordPage = (params) => request.get('/api/inventory-record/page', { params })
export const addInventoryRecord = (data) => request.post('/api/inventory-record', data)
export const updateInventoryRecord = (data) => request.put('/api/inventory-record', data)
export const deleteInventoryRecord = (id) => request.delete(`/api/inventory-record/${id}`)
export const submitInventoryRecord = (id) => request.put(`/api/inventory-record/submit/${id}`)
export const approveInventoryRecord = (id) => request.put(`/api/inventory-record/approve/${id}`)
export const getBorrowApplicationPage = (params) => request.get('/api/borrow-apply/page', { params })
export const addBorrowApplication = (data) => request.post('/api/borrow-apply', data)
export const updateBorrowApplication = (data) => request.put('/api/borrow-apply', data)
export const deleteBorrowApplication = (id) => request.delete(`/api/borrow-apply/${id}`)
export const processBorrowApplication = (id) => request.put(`/api/borrow-apply/process/${id}`)
export const finishBorrowApplication = (id) => request.put(`/api/borrow-apply/finish/${id}`)
export const getReturnRecordPage = (params) => request.get('/api/return-record/page', { params })
export const addReturnRecord = (data) => request.post('/api/return-record', data)
export const updateReturnRecord = (data) => request.put('/api/return-record', data)
export const deleteReturnRecord = (id) => request.delete(`/api/return-record/${id}`)
export const submitReturnRecord = (id) => request.put(`/api/return-record/submit/${id}`)
export const approveReturnRecord = (id) => request.put(`/api/return-record/approve/${id}`)
export const getRepairRecordPage = (params) => request.get('/api/repair/page', { params })
export const addRepairRecord = (data) => request.post('/api/repair', data)
export const updateRepairRecord = (data) => request.put('/api/repair', data)
export const deleteRepairRecord = (id) => request.delete(`/api/repair/${id}`)
export const submitRepairRecord = (id) => request.put(`/api/repair/submit/${id}`)
export const approveRepairRecord = (id) => request.put(`/api/repair/approve/${id}`)
export const getDepreciationRecordPage = (params) => request.get('/api/depreciation/page', { params })
export const addDepreciationRecord = (data) => request.post('/api/depreciation', data)
export const updateDepreciationRecord = (data) => request.put('/api/depreciation', data)
export const deleteDepreciationRecord = (id) => request.delete(`/api/depreciation/${id}`)
export const processDepreciationRecord = (id) => request.put(`/api/depreciation/process/${id}`)
export const finishDepreciationRecord = (id) => request.put(`/api/depreciation/finish/${id}`)
export const getDisposalRecordPage = (params) => request.get('/api/disposal/page', { params })
export const addDisposalRecord = (data) => request.post('/api/disposal', data)
export const updateDisposalRecord = (data) => request.put('/api/disposal', data)
export const deleteDisposalRecord = (id) => request.delete(`/api/disposal/${id}`)
export const activateDisposalRecord = (id) => request.put(`/api/disposal/activate/${id}`)
export const finishDisposalRecord = (id) => request.put(`/api/disposal/finish/${id}`)
export const getWarningNoticePage = (params) => request.get('/api/notice/page', { params })
export const addWarningNotice = (data) => request.post('/api/notice', data)
export const updateWarningNotice = (data) => request.put('/api/notice', data)
export const deleteWarningNotice = (id) => request.delete(`/api/notice/${id}`)
export const processWarningNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishWarningNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)





