import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getResearchProjectPage = (params) => request.get('/api/project/page', { params })
export const addResearchProject = (data) => request.post('/api/project', data)
export const updateResearchProject = (data) => request.put('/api/project', data)
export const deleteResearchProject = (id) => request.delete(`/api/project/${id}`)
export const activateResearchProject = (id) => request.put(`/api/project/activate/${id}`)
export const finishResearchProject = (id) => request.put(`/api/project/finish/${id}`)
export const getBudgetCategoryPage = (params) => request.get('/api/category/page', { params })
export const addBudgetCategory = (data) => request.post('/api/category', data)
export const updateBudgetCategory = (data) => request.put('/api/category', data)
export const deleteBudgetCategory = (id) => request.delete(`/api/category/${id}`)
export const activateBudgetCategory = (id) => request.put(`/api/category/activate/${id}`)
export const finishBudgetCategory = (id) => request.put(`/api/category/finish/${id}`)
export const getBudgetAllocationPage = (params) => request.get('/api/budget/page', { params })
export const addBudgetAllocation = (data) => request.post('/api/budget', data)
export const updateBudgetAllocation = (data) => request.put('/api/budget', data)
export const deleteBudgetAllocation = (id) => request.delete(`/api/budget/${id}`)
export const processBudgetAllocation = (id) => request.put(`/api/budget/process/${id}`)
export const finishBudgetAllocation = (id) => request.put(`/api/budget/finish/${id}`)
export const getExpenseClaimPage = (params) => request.get('/api/claim/page', { params })
export const addExpenseClaim = (data) => request.post('/api/claim', data)
export const updateExpenseClaim = (data) => request.put('/api/claim', data)
export const deleteExpenseClaim = (id) => request.delete(`/api/claim/${id}`)
export const submitExpenseClaim = (id) => request.put(`/api/claim/submit/${id}`)
export const approveExpenseClaim = (id) => request.put(`/api/claim/approve/${id}`)
export const getInvoiceRecordPage = (params) => request.get('/api/invoice/page', { params })
export const addInvoiceRecord = (data) => request.post('/api/invoice', data)
export const updateInvoiceRecord = (data) => request.put('/api/invoice', data)
export const deleteInvoiceRecord = (id) => request.delete(`/api/invoice/${id}`)
export const submitInvoiceRecord = (id) => request.put(`/api/invoice/submit/${id}`)
export const approveInvoiceRecord = (id) => request.put(`/api/invoice/approve/${id}`)
export const getApprovalTaskPage = (params) => request.get('/api/approval/page', { params })
export const addApprovalTask = (data) => request.post('/api/approval', data)
export const updateApprovalTask = (data) => request.put('/api/approval', data)
export const deleteApprovalTask = (id) => request.delete(`/api/approval/${id}`)
export const submitApprovalTask = (id) => request.put(`/api/approval/submit/${id}`)
export const approveApprovalTask = (id) => request.put(`/api/approval/approve/${id}`)
export const getPaymentRecordPage = (params) => request.get('/api/payment/page', { params })
export const addPaymentRecord = (data) => request.post('/api/payment', data)
export const updatePaymentRecord = (data) => request.put('/api/payment', data)
export const deletePaymentRecord = (id) => request.delete(`/api/payment/${id}`)
export const processPaymentRecord = (id) => request.put(`/api/payment/process/${id}`)
export const finishPaymentRecord = (id) => request.put(`/api/payment/finish/${id}`)
export const getResearchAchievementPage = (params) => request.get('/api/achievement/page', { params })
export const addResearchAchievement = (data) => request.post('/api/achievement', data)
export const updateResearchAchievement = (data) => request.put('/api/achievement', data)
export const deleteResearchAchievement = (id) => request.delete(`/api/achievement/${id}`)
export const activateResearchAchievement = (id) => request.put(`/api/achievement/activate/${id}`)
export const finishResearchAchievement = (id) => request.put(`/api/achievement/finish/${id}`)
export const getPaperRecordPage = (params) => request.get('/api/paper/page', { params })
export const addPaperRecord = (data) => request.post('/api/paper', data)
export const updatePaperRecord = (data) => request.put('/api/paper', data)
export const deletePaperRecord = (id) => request.delete(`/api/paper/${id}`)
export const activatePaperRecord = (id) => request.put(`/api/paper/activate/${id}`)
export const finishPaperRecord = (id) => request.put(`/api/paper/finish/${id}`)
export const getPatentRecordPage = (params) => request.get('/api/patent/page', { params })
export const addPatentRecord = (data) => request.post('/api/patent', data)
export const updatePatentRecord = (data) => request.put('/api/patent', data)
export const deletePatentRecord = (id) => request.delete(`/api/patent/${id}`)
export const activatePatentRecord = (id) => request.put(`/api/patent/activate/${id}`)
export const finishPatentRecord = (id) => request.put(`/api/patent/finish/${id}`)
export const getPerformanceStatisticPage = (params) => request.get('/api/statistic/page', { params })
export const addPerformanceStatistic = (data) => request.post('/api/statistic', data)
export const updatePerformanceStatistic = (data) => request.put('/api/statistic', data)
export const deletePerformanceStatistic = (id) => request.delete(`/api/statistic/${id}`)
export const processPerformanceStatistic = (id) => request.put(`/api/statistic/process/${id}`)
export const finishPerformanceStatistic = (id) => request.put(`/api/statistic/finish/${id}`)
export const getRiskWarningPage = (params) => request.get('/api/risk/page', { params })
export const addRiskWarning = (data) => request.post('/api/risk', data)
export const updateRiskWarning = (data) => request.put('/api/risk', data)
export const deleteRiskWarning = (id) => request.delete(`/api/risk/${id}`)
export const processRiskWarning = (id) => request.put(`/api/risk/process/${id}`)
export const finishRiskWarning = (id) => request.put(`/api/risk/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
