import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getInspectionPlanPage = (params) => request.get('/api/sample/page', { params })
export const addInspectionPlan = (data) => request.post('/api/sample', data)
export const updateInspectionPlan = (data) => request.put('/api/sample', data)
export const deleteInspectionPlan = (id) => request.delete(`/api/sample/${id}`)
export const activateInspectionPlan = (id) => request.put(`/api/sample/activate/${id}`)
export const finishInspectionPlan = (id) => request.put(`/api/sample/finish/${id}`)
export const getFoodItemPage = (params) => request.get('/api/food/page', { params })
export const addFoodItem = (data) => request.post('/api/food', data)
export const updateFoodItem = (data) => request.put('/api/food', data)
export const deleteFoodItem = (id) => request.delete(`/api/food/${id}`)
export const activateFoodItem = (id) => request.put(`/api/food/activate/${id}`)
export const finishFoodItem = (id) => request.put(`/api/food/finish/${id}`)
export const getMerchantProfilePage = (params) => request.get('/api/merchant/page', { params })
export const addMerchantProfile = (data) => request.post('/api/merchant', data)
export const updateMerchantProfile = (data) => request.put('/api/merchant', data)
export const deleteMerchantProfile = (id) => request.delete(`/api/merchant/${id}`)
export const processMerchantProfile = (id) => request.put(`/api/merchant/process/${id}`)
export const finishMerchantProfile = (id) => request.put(`/api/merchant/finish/${id}`)
export const getSamplingTaskPage = (params) => request.get('/api/result/page', { params })
export const addSamplingTask = (data) => request.post('/api/result', data)
export const updateSamplingTask = (data) => request.put('/api/result', data)
export const deleteSamplingTask = (id) => request.delete(`/api/result/${id}`)
export const submitSamplingTask = (id) => request.put(`/api/result/submit/${id}`)
export const approveSamplingTask = (id) => request.put(`/api/result/approve/${id}`)
export const getAgencyProfilePage = (params) => request.get('/api/agency/page', { params })
export const addAgencyProfile = (data) => request.post('/api/agency', data)
export const updateAgencyProfile = (data) => request.put('/api/agency', data)
export const deleteAgencyProfile = (id) => request.delete(`/api/agency/${id}`)
export const submitAgencyProfile = (id) => request.put(`/api/agency/submit/${id}`)
export const approveAgencyProfile = (id) => request.put(`/api/agency/approve/${id}`)
export const getSampleRecordPage = (params) => request.get('/api/sample/page', { params })
export const addSampleRecord = (data) => request.post('/api/sample', data)
export const updateSampleRecord = (data) => request.put('/api/sample', data)
export const deleteSampleRecord = (id) => request.delete(`/api/sample/${id}`)
export const submitSampleRecord = (id) => request.put(`/api/sample/submit/${id}`)
export const approveSampleRecord = (id) => request.put(`/api/sample/approve/${id}`)
export const getTestResultPage = (params) => request.get('/api/result/page', { params })
export const addTestResult = (data) => request.post('/api/result', data)
export const updateTestResult = (data) => request.put('/api/result', data)
export const deleteTestResult = (id) => request.delete(`/api/result/${id}`)
export const processTestResult = (id) => request.put(`/api/result/process/${id}`)
export const finishTestResult = (id) => request.put(`/api/result/finish/${id}`)
export const getRecheckApplicationPage = (params) => request.get('/api/recheck/page', { params })
export const addRecheckApplication = (data) => request.post('/api/recheck', data)
export const updateRecheckApplication = (data) => request.put('/api/recheck', data)
export const deleteRecheckApplication = (id) => request.delete(`/api/recheck/${id}`)
export const activateRecheckApplication = (id) => request.put(`/api/recheck/activate/${id}`)
export const finishRecheckApplication = (id) => request.put(`/api/recheck/finish/${id}`)
export const getDisposalRecordPage = (params) => request.get('/api/disposal/page', { params })
export const addDisposalRecord = (data) => request.post('/api/disposal', data)
export const updateDisposalRecord = (data) => request.put('/api/disposal', data)
export const deleteDisposalRecord = (id) => request.delete(`/api/disposal/${id}`)
export const activateDisposalRecord = (id) => request.put(`/api/disposal/activate/${id}`)
export const finishDisposalRecord = (id) => request.put(`/api/disposal/finish/${id}`)
export const getPublicReportPage = (params) => request.get('/api/report/page', { params })
export const addPublicReport = (data) => request.post('/api/report', data)
export const updatePublicReport = (data) => request.put('/api/report', data)
export const deletePublicReport = (id) => request.delete(`/api/report/${id}`)
export const activatePublicReport = (id) => request.put(`/api/report/activate/${id}`)
export const finishPublicReport = (id) => request.put(`/api/report/finish/${id}`)
export const getRiskWarningPage = (params) => request.get('/api/warning/page', { params })
export const addRiskWarning = (data) => request.post('/api/warning', data)
export const updateRiskWarning = (data) => request.put('/api/warning', data)
export const deleteRiskWarning = (id) => request.delete(`/api/warning/${id}`)
export const processRiskWarning = (id) => request.put(`/api/warning/process/${id}`)
export const finishRiskWarning = (id) => request.put(`/api/warning/finish/${id}`)
export const getInspectionNoticePage = (params) => request.get('/api/notice/page', { params })
export const addInspectionNotice = (data) => request.post('/api/notice', data)
export const updateInspectionNotice = (data) => request.put('/api/notice', data)
export const deleteInspectionNotice = (id) => request.delete(`/api/notice/${id}`)
export const processInspectionNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishInspectionNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)







