import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getClubProfilePage = (params) => request.get('/api/club/page', { params })
export const addClubProfile = (data) => request.post('/api/club', data)
export const updateClubProfile = (data) => request.put('/api/club', data)
export const deleteClubProfile = (id) => request.delete(`/api/club/${id}`)
export const processClubProfile = (id) => request.put(`/api/club/process/${id}`)
export const finishClubProfile = (id) => request.put(`/api/club/finish/${id}`)

export const getMemberProfilePage = (params) => request.get('/api/member/page', { params })
export const addMemberProfile = (data) => request.post('/api/member', data)
export const updateMemberProfile = (data) => request.put('/api/member', data)
export const deleteMemberProfile = (id) => request.delete(`/api/member/${id}`)
export const processMemberProfile = (id) => request.put(`/api/member/process/${id}`)
export const finishMemberProfile = (id) => request.put(`/api/member/finish/${id}`)

export const getActivityPlanPage = (params) => request.get('/api/activity/page', { params })
export const addActivityPlan = (data) => request.post('/api/activity', data)
export const updateActivityPlan = (data) => request.put('/api/activity', data)
export const deleteActivityPlan = (id) => request.delete(`/api/activity/${id}`)
export const processActivityPlan = (id) => request.put(`/api/activity/process/${id}`)
export const finishActivityPlan = (id) => request.put(`/api/activity/finish/${id}`)

export const getBudgetRequestPage = (params) => request.get('/api/budget/page', { params })
export const addBudgetRequest = (data) => request.post('/api/budget', data)
export const updateBudgetRequest = (data) => request.put('/api/budget', data)
export const deleteBudgetRequest = (id) => request.delete(`/api/budget/${id}`)
export const processBudgetRequest = (id) => request.put(`/api/budget/process/${id}`)
export const finishBudgetRequest = (id) => request.put(`/api/budget/finish/${id}`)

export const getBudgetLineItemPage = (params) => request.get('/api/lineitem/page', { params })
export const addBudgetLineItem = (data) => request.post('/api/lineitem', data)
export const updateBudgetLineItem = (data) => request.put('/api/lineitem', data)
export const deleteBudgetLineItem = (id) => request.delete(`/api/lineitem/${id}`)
export const processBudgetLineItem = (id) => request.put(`/api/lineitem/process/${id}`)
export const finishBudgetLineItem = (id) => request.put(`/api/lineitem/finish/${id}`)

export const getApprovalRecordPage = (params) => request.get('/api/approval/page', { params })
export const addApprovalRecord = (data) => request.post('/api/approval', data)
export const updateApprovalRecord = (data) => request.put('/api/approval', data)
export const deleteApprovalRecord = (id) => request.delete(`/api/approval/${id}`)
export const processApprovalRecord = (id) => request.put(`/api/approval/process/${id}`)
export const finishApprovalRecord = (id) => request.put(`/api/approval/finish/${id}`)

export const getReimbursementClaimPage = (params) => request.get('/api/reimbursement/page', { params })
export const addReimbursementClaim = (data) => request.post('/api/reimbursement', data)
export const updateReimbursementClaim = (data) => request.put('/api/reimbursement', data)
export const deleteReimbursementClaim = (id) => request.delete(`/api/reimbursement/${id}`)
export const processReimbursementClaim = (id) => request.put(`/api/reimbursement/process/${id}`)
export const finishReimbursementClaim = (id) => request.put(`/api/reimbursement/finish/${id}`)

export const getReceiptArchivePage = (params) => request.get('/api/receipt/page', { params })
export const addReceiptArchive = (data) => request.post('/api/receipt', data)
export const updateReceiptArchive = (data) => request.put('/api/receipt', data)
export const deleteReceiptArchive = (id) => request.delete(`/api/receipt/${id}`)
export const processReceiptArchive = (id) => request.put(`/api/receipt/process/${id}`)
export const finishReceiptArchive = (id) => request.put(`/api/receipt/finish/${id}`)

export const getMaterialAssetPage = (params) => request.get('/api/asset/page', { params })
export const addMaterialAsset = (data) => request.post('/api/asset', data)
export const updateMaterialAsset = (data) => request.put('/api/asset', data)
export const deleteMaterialAsset = (id) => request.delete(`/api/asset/${id}`)
export const processMaterialAsset = (id) => request.put(`/api/asset/process/${id}`)
export const finishMaterialAsset = (id) => request.put(`/api/asset/finish/${id}`)

export const getBorrowRequestPage = (params) => request.get('/api/borrow/page', { params })
export const addBorrowRequest = (data) => request.post('/api/borrow', data)
export const updateBorrowRequest = (data) => request.put('/api/borrow', data)
export const deleteBorrowRequest = (id) => request.delete(`/api/borrow/${id}`)
export const processBorrowRequest = (id) => request.put(`/api/borrow/process/${id}`)
export const finishBorrowRequest = (id) => request.put(`/api/borrow/finish/${id}`)

export const getReturnInspectionPage = (params) => request.get('/api/returncheck/page', { params })
export const addReturnInspection = (data) => request.post('/api/returncheck', data)
export const updateReturnInspection = (data) => request.put('/api/returncheck', data)
export const deleteReturnInspection = (id) => request.delete(`/api/returncheck/${id}`)
export const processReturnInspection = (id) => request.put(`/api/returncheck/process/${id}`)
export const finishReturnInspection = (id) => request.put(`/api/returncheck/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
