import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getMealSitePage = (params) => request.get('/api/site/page', { params })
export const addMealSite = (data) => request.post('/api/site', data)
export const updateMealSite = (data) => request.put('/api/site', data)
export const deleteMealSite = (id) => request.delete(`/api/site/${id}`)
export const processMealSite = (id) => request.put(`/api/site/process/${id}`)
export const finishMealSite = (id) => request.put(`/api/site/finish/${id}`)

export const getElderProfilePage = (params) => request.get('/api/elder/page', { params })
export const addElderProfile = (data) => request.post('/api/elder', data)
export const updateElderProfile = (data) => request.put('/api/elder', data)
export const deleteElderProfile = (id) => request.delete(`/api/elder/${id}`)
export const processElderProfile = (id) => request.put(`/api/elder/process/${id}`)
export const finishElderProfile = (id) => request.put(`/api/elder/finish/${id}`)

export const getNutritionMenuPage = (params) => request.get('/api/menu/page', { params })
export const addNutritionMenu = (data) => request.post('/api/menu', data)
export const updateNutritionMenu = (data) => request.put('/api/menu', data)
export const deleteNutritionMenu = (id) => request.delete(`/api/menu/${id}`)
export const processNutritionMenu = (id) => request.put(`/api/menu/process/${id}`)
export const finishNutritionMenu = (id) => request.put(`/api/menu/finish/${id}`)

export const getMealOrderPage = (params) => request.get('/api/order/page', { params })
export const addMealOrder = (data) => request.post('/api/order', data)
export const updateMealOrder = (data) => request.put('/api/order', data)
export const deleteMealOrder = (id) => request.delete(`/api/order/${id}`)
export const processMealOrder = (id) => request.put(`/api/order/process/${id}`)
export const finishMealOrder = (id) => request.put(`/api/order/finish/${id}`)

export const getRoutePlanPage = (params) => request.get('/api/route/page', { params })
export const addRoutePlan = (data) => request.post('/api/route', data)
export const updateRoutePlan = (data) => request.put('/api/route', data)
export const deleteRoutePlan = (id) => request.delete(`/api/route/${id}`)
export const processRoutePlan = (id) => request.put(`/api/route/process/${id}`)
export const finishRoutePlan = (id) => request.put(`/api/route/finish/${id}`)

export const getDeliveryTaskPage = (params) => request.get('/api/delivery/page', { params })
export const addDeliveryTask = (data) => request.post('/api/delivery', data)
export const updateDeliveryTask = (data) => request.put('/api/delivery', data)
export const deleteDeliveryTask = (id) => request.delete(`/api/delivery/${id}`)
export const processDeliveryTask = (id) => request.put(`/api/delivery/process/${id}`)
export const finishDeliveryTask = (id) => request.put(`/api/delivery/finish/${id}`)

export const getSignReceiptPage = (params) => request.get('/api/receipt/page', { params })
export const addSignReceipt = (data) => request.post('/api/receipt', data)
export const updateSignReceipt = (data) => request.put('/api/receipt', data)
export const deleteSignReceipt = (id) => request.delete(`/api/receipt/${id}`)
export const processSignReceipt = (id) => request.put(`/api/receipt/process/${id}`)
export const finishSignReceipt = (id) => request.put(`/api/receipt/finish/${id}`)

export const getDietaryRestrictionPage = (params) => request.get('/api/restriction/page', { params })
export const addDietaryRestriction = (data) => request.post('/api/restriction', data)
export const updateDietaryRestriction = (data) => request.put('/api/restriction', data)
export const deleteDietaryRestriction = (id) => request.delete(`/api/restriction/${id}`)
export const processDietaryRestriction = (id) => request.put(`/api/restriction/process/${id}`)
export const finishDietaryRestriction = (id) => request.put(`/api/restriction/finish/${id}`)

export const getNutritionAnalysisPage = (params) => request.get('/api/analysis/page', { params })
export const addNutritionAnalysis = (data) => request.post('/api/analysis', data)
export const updateNutritionAnalysis = (data) => request.put('/api/analysis', data)
export const deleteNutritionAnalysis = (id) => request.delete(`/api/analysis/${id}`)
export const processNutritionAnalysis = (id) => request.put(`/api/analysis/process/${id}`)
export const finishNutritionAnalysis = (id) => request.put(`/api/analysis/finish/${id}`)

export const getSubsidyRecordPage = (params) => request.get('/api/subsidy/page', { params })
export const addSubsidyRecord = (data) => request.post('/api/subsidy', data)
export const updateSubsidyRecord = (data) => request.put('/api/subsidy', data)
export const deleteSubsidyRecord = (id) => request.delete(`/api/subsidy/${id}`)
export const processSubsidyRecord = (id) => request.put(`/api/subsidy/process/${id}`)
export const finishSubsidyRecord = (id) => request.put(`/api/subsidy/finish/${id}`)

export const getVisitFollowupPage = (params) => request.get('/api/followup/page', { params })
export const addVisitFollowup = (data) => request.post('/api/followup', data)
export const updateVisitFollowup = (data) => request.put('/api/followup', data)
export const deleteVisitFollowup = (id) => request.delete(`/api/followup/${id}`)
export const processVisitFollowup = (id) => request.put(`/api/followup/process/${id}`)
export const finishVisitFollowup = (id) => request.put(`/api/followup/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
