import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getWaterLevelPointPage = (params) => request.get('/api/point/page', { params })
export const addWaterLevelPoint = (data) => request.post('/api/point', data)
export const updateWaterLevelPoint = (data) => request.put('/api/point', data)
export const deleteWaterLevelPoint = (id) => request.delete(`/api/point/${id}`)
export const enableWaterLevelPoint = (id) => request.put(`/api/point/enable/${id}`)
export const disableWaterLevelPoint = (id) => request.put(`/api/point/disable/${id}`)
export const getRainGaugeStationPage = (params) => request.get('/api/rainstation/page', { params })
export const addRainGaugeStation = (data) => request.post('/api/rainstation', data)
export const updateRainGaugeStation = (data) => request.put('/api/rainstation', data)
export const deleteRainGaugeStation = (id) => request.delete(`/api/rainstation/${id}`)
export const enableRainGaugeStation = (id) => request.put(`/api/rainstation/enable/${id}`)
export const disableRainGaugeStation = (id) => request.put(`/api/rainstation/disable/${id}`)
export const getDrainagePumpPage = (params) => request.get('/api/pump/page', { params })
export const addDrainagePump = (data) => request.post('/api/pump', data)
export const updateDrainagePump = (data) => request.put('/api/pump', data)
export const deleteDrainagePump = (id) => request.delete(`/api/pump/${id}`)
export const runDrainagePump = (id) => request.put(`/api/pump/run/${id}`)
export const warnDrainagePump = (id) => request.put(`/api/pump/warn/${id}`)
export const getWaterLevelDataPage = (params) => request.get('/api/waterdata/page', { params })
export const addWaterLevelData = (data) => request.post('/api/waterdata', data)
export const updateWaterLevelData = (data) => request.put('/api/waterdata', data)
export const deleteWaterLevelData = (id) => request.delete(`/api/waterdata/${id}`)
export const warnWaterLevelData = (id) => request.put(`/api/waterdata/warn/${id}`)
export const recoverWaterLevelData = (id) => request.put(`/api/waterdata/recover/${id}`)
export const getRainfallDataPage = (params) => request.get('/api/raindata/page', { params })
export const addRainfallData = (data) => request.post('/api/raindata', data)
export const updateRainfallData = (data) => request.put('/api/raindata', data)
export const deleteRainfallData = (id) => request.delete(`/api/raindata/${id}`)
export const warnRainfallData = (id) => request.put(`/api/raindata/warn/${id}`)
export const recoverRainfallData = (id) => request.put(`/api/raindata/recover/${id}`)
export const getWarningRulePage = (params) => request.get('/api/rule/page', { params })
export const addWarningRule = (data) => request.post('/api/rule', data)
export const updateWarningRule = (data) => request.put('/api/rule', data)
export const deleteWarningRule = (id) => request.delete(`/api/rule/${id}`)
export const enableWarningRule = (id) => request.put(`/api/rule/enable/${id}`)
export const disableWarningRule = (id) => request.put(`/api/rule/disable/${id}`)
export const getFloodWarningPage = (params) => request.get('/api/warning/page', { params })
export const addFloodWarning = (data) => request.post('/api/warning', data)
export const updateFloodWarning = (data) => request.put('/api/warning', data)
export const deleteFloodWarning = (id) => request.delete(`/api/warning/${id}`)
export const assignFloodWarning = (id) => request.put(`/api/warning/assign/${id}`)
export const closeFloodWarning = (id) => request.put(`/api/warning/close/${id}`)
export const getEmergencyPlanPage = (params) => request.get('/api/plan/page', { params })
export const addEmergencyPlan = (data) => request.post('/api/plan', data)
export const updateEmergencyPlan = (data) => request.put('/api/plan', data)
export const deleteEmergencyPlan = (id) => request.delete(`/api/plan/${id}`)
export const publishEmergencyPlan = (id) => request.put(`/api/plan/publish/${id}`)
export const disableEmergencyPlan = (id) => request.put(`/api/plan/disable/${id}`)
export const getDispatchTaskPage = (params) => request.get('/api/task/page', { params })
export const addDispatchTask = (data) => request.post('/api/task', data)
export const updateDispatchTask = (data) => request.put('/api/task', data)
export const deleteDispatchTask = (id) => request.delete(`/api/task/${id}`)
export const startDispatchTask = (id) => request.put(`/api/task/start/${id}`)
export const finishDispatchTask = (id) => request.put(`/api/task/finish/${id}`)
export const getRescueTeamPage = (params) => request.get('/api/team/page', { params })
export const addRescueTeam = (data) => request.post('/api/team', data)
export const updateRescueTeam = (data) => request.put('/api/team', data)
export const deleteRescueTeam = (id) => request.delete(`/api/team/${id}`)
export const enableRescueTeam = (id) => request.put(`/api/team/enable/${id}`)
export const disableRescueTeam = (id) => request.put(`/api/team/disable/${id}`)
export const getMaterialReservePage = (params) => request.get('/api/material/page', { params })
export const addMaterialReserve = (data) => request.post('/api/material', data)
export const updateMaterialReserve = (data) => request.put('/api/material', data)
export const deleteMaterialReserve = (id) => request.delete(`/api/material/${id}`)
export const enableMaterialReserve = (id) => request.put(`/api/material/enable/${id}`)
export const warnMaterialReserve = (id) => request.put(`/api/material/warn/${id}`)
export const getShelterSitePage = (params) => request.get('/api/shelter/page', { params })
export const addShelterSite = (data) => request.post('/api/shelter', data)
export const updateShelterSite = (data) => request.put('/api/shelter', data)
export const deleteShelterSite = (id) => request.delete(`/api/shelter/${id}`)
export const openShelterSite = (id) => request.put(`/api/shelter/open/${id}`)
export const closeShelterSite = (id) => request.put(`/api/shelter/close/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
