import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getDormBuildingPage = (params) => request.get('/api/building/page', { params })
export const addDormBuilding = (data) => request.post('/api/building', data)
export const updateDormBuilding = (data) => request.put('/api/building', data)
export const deleteDormBuilding = (id) => request.delete(`/api/building/${id}`)
export const processDormBuilding = (id) => request.put(`/api/building/process/${id}`)
export const finishDormBuilding = (id) => request.put(`/api/building/finish/${id}`)

export const getDormRoomPage = (params) => request.get('/api/room/page', { params })
export const addDormRoom = (data) => request.post('/api/room', data)
export const updateDormRoom = (data) => request.put('/api/room', data)
export const deleteDormRoom = (id) => request.delete(`/api/room/${id}`)
export const processDormRoom = (id) => request.put(`/api/room/process/${id}`)
export const finishDormRoom = (id) => request.put(`/api/room/finish/${id}`)

export const getMeterDevicePage = (params) => request.get('/api/meter/page', { params })
export const addMeterDevice = (data) => request.post('/api/meter', data)
export const updateMeterDevice = (data) => request.put('/api/meter', data)
export const deleteMeterDevice = (id) => request.delete(`/api/meter/${id}`)
export const processMeterDevice = (id) => request.put(`/api/meter/process/${id}`)
export const finishMeterDevice = (id) => request.put(`/api/meter/finish/${id}`)

export const getEnergyReadingPage = (params) => request.get('/api/reading/page', { params })
export const addEnergyReading = (data) => request.post('/api/reading', data)
export const updateEnergyReading = (data) => request.put('/api/reading', data)
export const deleteEnergyReading = (id) => request.delete(`/api/reading/${id}`)
export const processEnergyReading = (id) => request.put(`/api/reading/process/${id}`)
export const finishEnergyReading = (id) => request.put(`/api/reading/finish/${id}`)

export const getConsumptionBillPage = (params) => request.get('/api/bill/page', { params })
export const addConsumptionBill = (data) => request.post('/api/bill', data)
export const updateConsumptionBill = (data) => request.put('/api/bill', data)
export const deleteConsumptionBill = (id) => request.delete(`/api/bill/${id}`)
export const processConsumptionBill = (id) => request.put(`/api/bill/process/${id}`)
export const finishConsumptionBill = (id) => request.put(`/api/bill/finish/${id}`)

export const getAlertRulePage = (params) => request.get('/api/rule/page', { params })
export const addAlertRule = (data) => request.post('/api/rule', data)
export const updateAlertRule = (data) => request.put('/api/rule', data)
export const deleteAlertRule = (id) => request.delete(`/api/rule/${id}`)
export const processAlertRule = (id) => request.put(`/api/rule/process/${id}`)
export const finishAlertRule = (id) => request.put(`/api/rule/finish/${id}`)

export const getAbnormalAlertPage = (params) => request.get('/api/alert/page', { params })
export const addAbnormalAlert = (data) => request.post('/api/alert', data)
export const updateAbnormalAlert = (data) => request.put('/api/alert', data)
export const deleteAbnormalAlert = (id) => request.delete(`/api/alert/${id}`)
export const processAbnormalAlert = (id) => request.put(`/api/alert/process/${id}`)
export const finishAbnormalAlert = (id) => request.put(`/api/alert/finish/${id}`)

export const getSavingTaskPage = (params) => request.get('/api/task/page', { params })
export const addSavingTask = (data) => request.post('/api/task', data)
export const updateSavingTask = (data) => request.put('/api/task', data)
export const deleteSavingTask = (id) => request.delete(`/api/task/${id}`)
export const processSavingTask = (id) => request.put(`/api/task/process/${id}`)
export const finishSavingTask = (id) => request.put(`/api/task/finish/${id}`)

export const getSavingRankingPage = (params) => request.get('/api/ranking/page', { params })
export const addSavingRanking = (data) => request.post('/api/ranking', data)
export const updateSavingRanking = (data) => request.put('/api/ranking', data)
export const deleteSavingRanking = (id) => request.delete(`/api/ranking/${id}`)
export const processSavingRanking = (id) => request.put(`/api/ranking/process/${id}`)
export const finishSavingRanking = (id) => request.put(`/api/ranking/finish/${id}`)

export const getInspectionRecordPage = (params) => request.get('/api/inspection/page', { params })
export const addInspectionRecord = (data) => request.post('/api/inspection', data)
export const updateInspectionRecord = (data) => request.put('/api/inspection', data)
export const deleteInspectionRecord = (id) => request.delete(`/api/inspection/${id}`)
export const processInspectionRecord = (id) => request.put(`/api/inspection/process/${id}`)
export const finishInspectionRecord = (id) => request.put(`/api/inspection/finish/${id}`)

export const getEnergyNoticePage = (params) => request.get('/api/notice/page', { params })
export const addEnergyNotice = (data) => request.post('/api/notice', data)
export const updateEnergyNotice = (data) => request.put('/api/notice', data)
export const deleteEnergyNotice = (id) => request.delete(`/api/notice/${id}`)
export const processEnergyNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishEnergyNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
