import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getCampusBranchPage = (params) => request.get('/api/branch/page', { params })
export const addCampusBranch = (data) => request.post('/api/branch', data)
export const updateCampusBranch = (data) => request.put('/api/branch', data)
export const deleteCampusBranch = (id) => request.delete(`/api/branch/${id}`)
export const processCampusBranch = (id) => request.put(`/api/branch/process/${id}`)
export const finishCampusBranch = (id) => request.put(`/api/branch/finish/${id}`)

export const getCourseCatalogPage = (params) => request.get('/api/course/page', { params })
export const addCourseCatalog = (data) => request.post('/api/course', data)
export const updateCourseCatalog = (data) => request.put('/api/course', data)
export const deleteCourseCatalog = (id) => request.delete(`/api/course/${id}`)
export const processCourseCatalog = (id) => request.put(`/api/course/process/${id}`)
export const finishCourseCatalog = (id) => request.put(`/api/course/finish/${id}`)

export const getStudentProfilePage = (params) => request.get('/api/student/page', { params })
export const addStudentProfile = (data) => request.post('/api/student', data)
export const updateStudentProfile = (data) => request.put('/api/student', data)
export const deleteStudentProfile = (id) => request.delete(`/api/student/${id}`)
export const processStudentProfile = (id) => request.put(`/api/student/process/${id}`)
export const finishStudentProfile = (id) => request.put(`/api/student/finish/${id}`)

export const getTeacherProfilePage = (params) => request.get('/api/teacher/page', { params })
export const addTeacherProfile = (data) => request.post('/api/teacher', data)
export const updateTeacherProfile = (data) => request.put('/api/teacher', data)
export const deleteTeacherProfile = (id) => request.delete(`/api/teacher/${id}`)
export const processTeacherProfile = (id) => request.put(`/api/teacher/process/${id}`)
export const finishTeacherProfile = (id) => request.put(`/api/teacher/finish/${id}`)

export const getClassGroupPage = (params) => request.get('/api/classgroup/page', { params })
export const addClassGroup = (data) => request.post('/api/classgroup', data)
export const updateClassGroup = (data) => request.put('/api/classgroup', data)
export const deleteClassGroup = (id) => request.delete(`/api/classgroup/${id}`)
export const processClassGroup = (id) => request.put(`/api/classgroup/process/${id}`)
export const finishClassGroup = (id) => request.put(`/api/classgroup/finish/${id}`)

export const getLessonSchedulePage = (params) => request.get('/api/schedule/page', { params })
export const addLessonSchedule = (data) => request.post('/api/schedule', data)
export const updateLessonSchedule = (data) => request.put('/api/schedule', data)
export const deleteLessonSchedule = (id) => request.delete(`/api/schedule/${id}`)
export const processLessonSchedule = (id) => request.put(`/api/schedule/process/${id}`)
export const finishLessonSchedule = (id) => request.put(`/api/schedule/finish/${id}`)

export const getAttendanceRecordPage = (params) => request.get('/api/attendance/page', { params })
export const addAttendanceRecord = (data) => request.post('/api/attendance', data)
export const updateAttendanceRecord = (data) => request.put('/api/attendance', data)
export const deleteAttendanceRecord = (id) => request.delete(`/api/attendance/${id}`)
export const processAttendanceRecord = (id) => request.put(`/api/attendance/process/${id}`)
export const finishAttendanceRecord = (id) => request.put(`/api/attendance/finish/${id}`)

export const getConsumptionRecordPage = (params) => request.get('/api/consumption/page', { params })
export const addConsumptionRecord = (data) => request.post('/api/consumption', data)
export const updateConsumptionRecord = (data) => request.put('/api/consumption', data)
export const deleteConsumptionRecord = (id) => request.delete(`/api/consumption/${id}`)
export const processConsumptionRecord = (id) => request.put(`/api/consumption/process/${id}`)
export const finishConsumptionRecord = (id) => request.put(`/api/consumption/finish/${id}`)

export const getRefundApplicationPage = (params) => request.get('/api/refund/page', { params })
export const addRefundApplication = (data) => request.post('/api/refund', data)
export const updateRefundApplication = (data) => request.put('/api/refund', data)
export const deleteRefundApplication = (id) => request.delete(`/api/refund/${id}`)
export const processRefundApplication = (id) => request.put(`/api/refund/process/${id}`)
export const finishRefundApplication = (id) => request.put(`/api/refund/finish/${id}`)

export const getRefundApprovalPage = (params) => request.get('/api/approval/page', { params })
export const addRefundApproval = (data) => request.post('/api/approval', data)
export const updateRefundApproval = (data) => request.put('/api/approval', data)
export const deleteRefundApproval = (id) => request.delete(`/api/approval/${id}`)
export const processRefundApproval = (id) => request.put(`/api/approval/process/${id}`)
export const finishRefundApproval = (id) => request.put(`/api/approval/finish/${id}`)

export const getFinanceLedgerPage = (params) => request.get('/api/ledger/page', { params })
export const addFinanceLedger = (data) => request.post('/api/ledger', data)
export const updateFinanceLedger = (data) => request.put('/api/ledger', data)
export const deleteFinanceLedger = (id) => request.delete(`/api/ledger/${id}`)
export const processFinanceLedger = (id) => request.put(`/api/ledger/process/${id}`)
export const finishFinanceLedger = (id) => request.put(`/api/ledger/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
