import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getExamItemPage = (params) => request.get('/api/item/page', { params })
export const addExamItem = (data) => request.post('/api/item', data)
export const updateExamItem = (data) => request.put('/api/item', data)
export const deleteExamItem = (id) => request.delete(`/api/item/${id}`)
export const activateExamItem = (id) => request.put(`/api/item/activate/${id}`)
export const disableExamItem = (id) => request.put(`/api/item/disable/${id}`)

export const getPatientProfilePage = (params) => request.get('/api/patient/page', { params })
export const addPatientProfile = (data) => request.post('/api/patient', data)
export const updatePatientProfile = (data) => request.put('/api/patient', data)
export const deletePatientProfile = (id) => request.delete(`/api/patient/${id}`)
export const activatePatientProfile = (id) => request.put(`/api/patient/activate/${id}`)
export const disablePatientProfile = (id) => request.put(`/api/patient/disable/${id}`)

export const getDoctorProfilePage = (params) => request.get('/api/doctor/page', { params })
export const addDoctorProfile = (data) => request.post('/api/doctor', data)
export const updateDoctorProfile = (data) => request.put('/api/doctor', data)
export const deleteDoctorProfile = (id) => request.delete(`/api/doctor/${id}`)
export const activateDoctorProfile = (id) => request.put(`/api/doctor/activate/${id}`)
export const disableDoctorProfile = (id) => request.put(`/api/doctor/disable/${id}`)

export const getExamAppointmentPage = (params) => request.get('/api/appointment/page', { params })
export const addExamAppointment = (data) => request.post('/api/appointment', data)
export const updateExamAppointment = (data) => request.put('/api/appointment', data)
export const deleteExamAppointment = (id) => request.delete(`/api/appointment/${id}`)
export const submitExamAppointment = (id) => request.put(`/api/appointment/submit/${id}`)
export const approveExamAppointment = (id) => request.put(`/api/appointment/approve/${id}`)

export const getExamDepartmentPage = (params) => request.get('/api/department/page', { params })
export const addExamDepartment = (data) => request.post('/api/department', data)
export const updateExamDepartment = (data) => request.put('/api/department', data)
export const deleteExamDepartment = (id) => request.delete(`/api/department/${id}`)
export const activateExamDepartment = (id) => request.put(`/api/department/activate/${id}`)
export const disableExamDepartment = (id) => request.put(`/api/department/disable/${id}`)

export const getCheckinRecordPage = (params) => request.get('/api/checkin/page', { params })
export const addCheckinRecord = (data) => request.post('/api/checkin', data)
export const updateCheckinRecord = (data) => request.put('/api/checkin', data)
export const deleteCheckinRecord = (id) => request.delete(`/api/checkin/${id}`)
export const submitCheckinRecord = (id) => request.put(`/api/checkin/submit/${id}`)
export const approveCheckinRecord = (id) => request.put(`/api/checkin/approve/${id}`)

export const getExamReportPage = (params) => request.get('/api/report/page', { params })
export const addExamReport = (data) => request.post('/api/report', data)
export const updateExamReport = (data) => request.put('/api/report', data)
export const deleteExamReport = (id) => request.delete(`/api/report/${id}`)
export const processExamReport = (id) => request.put(`/api/report/process/${id}`)
export const finishExamReport = (id) => request.put(`/api/report/finish/${id}`)

export const getAbnormalAlertPage = (params) => request.get('/api/alert/page', { params })
export const addAbnormalAlert = (data) => request.post('/api/alert', data)
export const updateAbnormalAlert = (data) => request.put('/api/alert', data)
export const deleteAbnormalAlert = (id) => request.delete(`/api/alert/${id}`)
export const processAbnormalAlert = (id) => request.put(`/api/alert/process/${id}`)
export const finishAbnormalAlert = (id) => request.put(`/api/alert/finish/${id}`)

export const getReportDeliveryPage = (params) => request.get('/api/delivery/page', { params })
export const addReportDelivery = (data) => request.post('/api/delivery', data)
export const updateReportDelivery = (data) => request.put('/api/delivery', data)
export const deleteReportDelivery = (id) => request.delete(`/api/delivery/${id}`)
export const processReportDelivery = (id) => request.put(`/api/delivery/process/${id}`)
export const finishReportDelivery = (id) => request.put(`/api/delivery/finish/${id}`)

export const getRevisitAdvicePage = (params) => request.get('/api/advice/page', { params })
export const addRevisitAdvice = (data) => request.post('/api/advice', data)
export const updateRevisitAdvice = (data) => request.put('/api/advice', data)
export const deleteRevisitAdvice = (id) => request.delete(`/api/advice/${id}`)
export const publishRevisitAdvice = (id) => request.put(`/api/advice/publish/${id}`)
export const finishRevisitAdvice = (id) => request.put(`/api/advice/finish/${id}`)

export const getQueueCallPage = (params) => request.get('/api/queue/page', { params })
export const addQueueCall = (data) => request.post('/api/queue', data)
export const updateQueueCall = (data) => request.put('/api/queue', data)
export const deleteQueueCall = (id) => request.delete(`/api/queue/${id}`)
export const processQueueCall = (id) => request.put(`/api/queue/process/${id}`)
export const finishQueueCall = (id) => request.put(`/api/queue/finish/${id}`)

export const getHospitalNoticePage = (params) => request.get('/api/notice/page', { params })
export const addHospitalNotice = (data) => request.post('/api/notice', data)
export const updateHospitalNotice = (data) => request.put('/api/notice', data)
export const deleteHospitalNotice = (id) => request.delete(`/api/notice/${id}`)
export const publishHospitalNotice = (id) => request.put(`/api/notice/publish/${id}`)
export const finishHospitalNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
