import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getServiceCenterPage = (params) => request.get('/api/center/page', { params })
export const addServiceCenter = (data) => request.post('/api/center', data)
export const updateServiceCenter = (data) => request.put('/api/center', data)
export const deleteServiceCenter = (id) => request.delete(`/api/center/${id}`)
export const processServiceCenter = (id) => request.put(`/api/center/process/${id}`)
export const finishServiceCenter = (id) => request.put(`/api/center/finish/${id}`)

export const getResidentProfilePage = (params) => request.get('/api/resident/page', { params })
export const addResidentProfile = (data) => request.post('/api/resident', data)
export const updateResidentProfile = (data) => request.put('/api/resident', data)
export const deleteResidentProfile = (id) => request.delete(`/api/resident/${id}`)
export const processResidentProfile = (id) => request.put(`/api/resident/process/${id}`)
export const finishResidentProfile = (id) => request.put(`/api/resident/finish/${id}`)

export const getAssistiveDevicePage = (params) => request.get('/api/device/page', { params })
export const addAssistiveDevice = (data) => request.post('/api/device', data)
export const updateAssistiveDevice = (data) => request.put('/api/device', data)
export const deleteAssistiveDevice = (id) => request.delete(`/api/device/${id}`)
export const processAssistiveDevice = (id) => request.put(`/api/device/process/${id}`)
export const finishAssistiveDevice = (id) => request.put(`/api/device/finish/${id}`)

export const getBorrowApplicationPage = (params) => request.get('/api/borrow/page', { params })
export const addBorrowApplication = (data) => request.post('/api/borrow', data)
export const updateBorrowApplication = (data) => request.put('/api/borrow', data)
export const deleteBorrowApplication = (id) => request.delete(`/api/borrow/${id}`)
export const processBorrowApplication = (id) => request.put(`/api/borrow/process/${id}`)
export const finishBorrowApplication = (id) => request.put(`/api/borrow/finish/${id}`)

export const getBorrowApprovalPage = (params) => request.get('/api/approval/page', { params })
export const addBorrowApproval = (data) => request.post('/api/approval', data)
export const updateBorrowApproval = (data) => request.put('/api/approval', data)
export const deleteBorrowApproval = (id) => request.delete(`/api/approval/${id}`)
export const processBorrowApproval = (id) => request.put(`/api/approval/process/${id}`)
export const finishBorrowApproval = (id) => request.put(`/api/approval/finish/${id}`)

export const getDeviceDeliveryPage = (params) => request.get('/api/delivery/page', { params })
export const addDeviceDelivery = (data) => request.post('/api/delivery', data)
export const updateDeviceDelivery = (data) => request.put('/api/delivery', data)
export const deleteDeviceDelivery = (id) => request.delete(`/api/delivery/${id}`)
export const processDeviceDelivery = (id) => request.put(`/api/delivery/process/${id}`)
export const finishDeviceDelivery = (id) => request.put(`/api/delivery/finish/${id}`)

export const getRehabPlanPage = (params) => request.get('/api/plan/page', { params })
export const addRehabPlan = (data) => request.post('/api/plan', data)
export const updateRehabPlan = (data) => request.put('/api/plan', data)
export const deleteRehabPlan = (id) => request.delete(`/api/plan/${id}`)
export const processRehabPlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishRehabPlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getRehabTrainingPage = (params) => request.get('/api/training/page', { params })
export const addRehabTraining = (data) => request.post('/api/training', data)
export const updateRehabTraining = (data) => request.put('/api/training', data)
export const deleteRehabTraining = (id) => request.delete(`/api/training/${id}`)
export const processRehabTraining = (id) => request.put(`/api/training/process/${id}`)
export const finishRehabTraining = (id) => request.put(`/api/training/finish/${id}`)

export const getFollowupRecordPage = (params) => request.get('/api/followup/page', { params })
export const addFollowupRecord = (data) => request.post('/api/followup', data)
export const updateFollowupRecord = (data) => request.put('/api/followup', data)
export const deleteFollowupRecord = (id) => request.delete(`/api/followup/${id}`)
export const processFollowupRecord = (id) => request.put(`/api/followup/process/${id}`)
export const finishFollowupRecord = (id) => request.put(`/api/followup/finish/${id}`)

export const getRecoveryReminderPage = (params) => request.get('/api/reminder/page', { params })
export const addRecoveryReminder = (data) => request.post('/api/reminder', data)
export const updateRecoveryReminder = (data) => request.put('/api/reminder', data)
export const deleteRecoveryReminder = (id) => request.delete(`/api/reminder/${id}`)
export const processRecoveryReminder = (id) => request.put(`/api/reminder/process/${id}`)
export const finishRecoveryReminder = (id) => request.put(`/api/reminder/finish/${id}`)

export const getDeviceMaintenancePage = (params) => request.get('/api/maintenance/page', { params })
export const addDeviceMaintenance = (data) => request.post('/api/maintenance', data)
export const updateDeviceMaintenance = (data) => request.put('/api/maintenance', data)
export const deleteDeviceMaintenance = (id) => request.delete(`/api/maintenance/${id}`)
export const processDeviceMaintenance = (id) => request.put(`/api/maintenance/process/${id}`)
export const finishDeviceMaintenance = (id) => request.put(`/api/maintenance/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
