import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getDepartmentProfilePage = (params) => request.get('/api/department/page', { params })
export const addDepartmentProfile = (data) => request.post('/api/department', data)
export const updateDepartmentProfile = (data) => request.put('/api/department', data)
export const deleteDepartmentProfile = (id) => request.delete(`/api/department/${id}`)
export const processDepartmentProfile = (id) => request.put(`/api/department/process/${id}`)
export const finishDepartmentProfile = (id) => request.put(`/api/department/finish/${id}`)

export const getStudentProfilePage = (params) => request.get('/api/student/page', { params })
export const addStudentProfile = (data) => request.post('/api/student', data)
export const updateStudentProfile = (data) => request.put('/api/student', data)
export const deleteStudentProfile = (id) => request.delete(`/api/student/${id}`)
export const processStudentProfile = (id) => request.put(`/api/student/process/${id}`)
export const finishStudentProfile = (id) => request.put(`/api/student/finish/${id}`)

export const getTeacherProfilePage = (params) => request.get('/api/teacher/page', { params })
export const addTeacherProfile = (data) => request.post('/api/teacher', data)
export const updateTeacherProfile = (data) => request.put('/api/teacher', data)
export const deleteTeacherProfile = (id) => request.delete(`/api/teacher/${id}`)
export const processTeacherProfile = (id) => request.put(`/api/teacher/process/${id}`)
export const finishTeacherProfile = (id) => request.put(`/api/teacher/finish/${id}`)

export const getRotationPlanPage = (params) => request.get('/api/rotation/page', { params })
export const addRotationPlan = (data) => request.post('/api/rotation', data)
export const updateRotationPlan = (data) => request.put('/api/rotation', data)
export const deleteRotationPlan = (id) => request.delete(`/api/rotation/${id}`)
export const processRotationPlan = (id) => request.put(`/api/rotation/process/${id}`)
export const finishRotationPlan = (id) => request.put(`/api/rotation/finish/${id}`)

export const getCaseLibraryPage = (params) => request.get('/api/case/page', { params })
export const addCaseLibrary = (data) => request.post('/api/case', data)
export const updateCaseLibrary = (data) => request.put('/api/case', data)
export const deleteCaseLibrary = (id) => request.delete(`/api/case/${id}`)
export const processCaseLibrary = (id) => request.put(`/api/case/process/${id}`)
export const finishCaseLibrary = (id) => request.put(`/api/case/finish/${id}`)

export const getStudyRecordPage = (params) => request.get('/api/study/page', { params })
export const addStudyRecord = (data) => request.post('/api/study', data)
export const updateStudyRecord = (data) => request.put('/api/study', data)
export const deleteStudyRecord = (id) => request.delete(`/api/study/${id}`)
export const processStudyRecord = (id) => request.put(`/api/study/process/${id}`)
export const finishStudyRecord = (id) => request.put(`/api/study/finish/${id}`)

export const getTeachingRoundPage = (params) => request.get('/api/round/page', { params })
export const addTeachingRound = (data) => request.post('/api/round', data)
export const updateTeachingRound = (data) => request.put('/api/round', data)
export const deleteTeachingRound = (id) => request.delete(`/api/round/${id}`)
export const processTeachingRound = (id) => request.put(`/api/round/process/${id}`)
export const finishTeachingRound = (id) => request.put(`/api/round/finish/${id}`)

export const getSkillTrainingPage = (params) => request.get('/api/skill/page', { params })
export const addSkillTraining = (data) => request.post('/api/skill', data)
export const updateSkillTraining = (data) => request.put('/api/skill', data)
export const deleteSkillTraining = (id) => request.delete(`/api/skill/${id}`)
export const processSkillTraining = (id) => request.put(`/api/skill/process/${id}`)
export const finishSkillTraining = (id) => request.put(`/api/skill/finish/${id}`)

export const getTeachingScorePage = (params) => request.get('/api/score/page', { params })
export const addTeachingScore = (data) => request.post('/api/score', data)
export const updateTeachingScore = (data) => request.put('/api/score', data)
export const deleteTeachingScore = (id) => request.delete(`/api/score/${id}`)
export const processTeachingScore = (id) => request.put(`/api/score/process/${id}`)
export const finishTeachingScore = (id) => request.put(`/api/score/finish/${id}`)

export const getExitExamPage = (params) => request.get('/api/exam/page', { params })
export const addExitExam = (data) => request.post('/api/exam', data)
export const updateExitExam = (data) => request.put('/api/exam', data)
export const deleteExitExam = (id) => request.delete(`/api/exam/${id}`)
export const processExitExam = (id) => request.put(`/api/exam/process/${id}`)
export const finishExitExam = (id) => request.put(`/api/exam/finish/${id}`)

export const getFeedbackReviewPage = (params) => request.get('/api/feedback/page', { params })
export const addFeedbackReview = (data) => request.post('/api/feedback', data)
export const updateFeedbackReview = (data) => request.put('/api/feedback', data)
export const deleteFeedbackReview = (id) => request.delete(`/api/feedback/${id}`)
export const processFeedbackReview = (id) => request.put(`/api/feedback/process/${id}`)
export const finishFeedbackReview = (id) => request.put(`/api/feedback/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
