import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getCareClassPage = (params) => request.get('/api/classroom/page', { params })
export const addCareClass = (data) => request.post('/api/classroom', data)
export const updateCareClass = (data) => request.put('/api/classroom', data)
export const deleteCareClass = (id) => request.delete(`/api/classroom/${id}`)
export const processCareClass = (id) => request.put(`/api/classroom/process/${id}`)
export const finishCareClass = (id) => request.put(`/api/classroom/finish/${id}`)

export const getChildProfilePage = (params) => request.get('/api/child/page', { params })
export const addChildProfile = (data) => request.post('/api/child', data)
export const updateChildProfile = (data) => request.put('/api/child', data)
export const deleteChildProfile = (id) => request.delete(`/api/child/${id}`)
export const processChildProfile = (id) => request.put(`/api/child/process/${id}`)
export const finishChildProfile = (id) => request.put(`/api/child/finish/${id}`)

export const getGuardianProfilePage = (params) => request.get('/api/guardian/page', { params })
export const addGuardianProfile = (data) => request.post('/api/guardian', data)
export const updateGuardianProfile = (data) => request.put('/api/guardian', data)
export const deleteGuardianProfile = (id) => request.delete(`/api/guardian/${id}`)
export const processGuardianProfile = (id) => request.put(`/api/guardian/process/${id}`)
export const finishGuardianProfile = (id) => request.put(`/api/guardian/finish/${id}`)

export const getAttendanceCheckinPage = (params) => request.get('/api/checkin/page', { params })
export const addAttendanceCheckin = (data) => request.post('/api/checkin', data)
export const updateAttendanceCheckin = (data) => request.put('/api/checkin', data)
export const deleteAttendanceCheckin = (id) => request.delete(`/api/checkin/${id}`)
export const processAttendanceCheckin = (id) => request.put(`/api/checkin/process/${id}`)
export const finishAttendanceCheckin = (id) => request.put(`/api/checkin/finish/${id}`)

export const getPickupAuthorizationPage = (params) => request.get('/api/authorization/page', { params })
export const addPickupAuthorization = (data) => request.post('/api/authorization', data)
export const updatePickupAuthorization = (data) => request.put('/api/authorization', data)
export const deletePickupAuthorization = (id) => request.delete(`/api/authorization/${id}`)
export const processPickupAuthorization = (id) => request.put(`/api/authorization/process/${id}`)
export const finishPickupAuthorization = (id) => request.put(`/api/authorization/finish/${id}`)

export const getPickupRecordPage = (params) => request.get('/api/pickup/page', { params })
export const addPickupRecord = (data) => request.post('/api/pickup', data)
export const updatePickupRecord = (data) => request.put('/api/pickup', data)
export const deletePickupRecord = (id) => request.delete(`/api/pickup/${id}`)
export const processPickupRecord = (id) => request.put(`/api/pickup/process/${id}`)
export const finishPickupRecord = (id) => request.put(`/api/pickup/finish/${id}`)

export const getSafetyAlertPage = (params) => request.get('/api/alert/page', { params })
export const addSafetyAlert = (data) => request.post('/api/alert', data)
export const updateSafetyAlert = (data) => request.put('/api/alert', data)
export const deleteSafetyAlert = (id) => request.delete(`/api/alert/${id}`)
export const processSafetyAlert = (id) => request.put(`/api/alert/process/${id}`)
export const finishSafetyAlert = (id) => request.put(`/api/alert/finish/${id}`)

export const getHealthCheckPage = (params) => request.get('/api/health/page', { params })
export const addHealthCheck = (data) => request.post('/api/health', data)
export const updateHealthCheck = (data) => request.put('/api/health', data)
export const deleteHealthCheck = (id) => request.delete(`/api/health/${id}`)
export const processHealthCheck = (id) => request.put(`/api/health/process/${id}`)
export const finishHealthCheck = (id) => request.put(`/api/health/finish/${id}`)

export const getActivitySchedulePage = (params) => request.get('/api/activity/page', { params })
export const addActivitySchedule = (data) => request.post('/api/activity', data)
export const updateActivitySchedule = (data) => request.put('/api/activity', data)
export const deleteActivitySchedule = (id) => request.delete(`/api/activity/${id}`)
export const processActivitySchedule = (id) => request.put(`/api/activity/process/${id}`)
export const finishActivitySchedule = (id) => request.put(`/api/activity/finish/${id}`)

export const getParentNoticePage = (params) => request.get('/api/notice/page', { params })
export const addParentNotice = (data) => request.post('/api/notice', data)
export const updateParentNotice = (data) => request.put('/api/notice', data)
export const deleteParentNotice = (id) => request.delete(`/api/notice/${id}`)
export const processParentNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishParentNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getIncidentFollowupPage = (params) => request.get('/api/incident/page', { params })
export const addIncidentFollowup = (data) => request.post('/api/incident', data)
export const updateIncidentFollowup = (data) => request.put('/api/incident', data)
export const deleteIncidentFollowup = (id) => request.delete(`/api/incident/${id}`)
export const processIncidentFollowup = (id) => request.put(`/api/incident/process/${id}`)
export const finishIncidentFollowup = (id) => request.put(`/api/incident/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
