import request from './request'

export const login = data => request.post('/auth/login', data)
export const register = data => request.post('/auth/register', data)

export const getSpotList = params => request.get('/spots/list', { params })
export const getSpotDetail = id => request.get(`/spots/detail/${id}`)
export const getAllSpots = () => request.get('/spots/all')
export const getTop10Spots = () => request.get('/spots/top10')
export const addSpot = data => request.post('/spots', data)
export const updateSpot = data => request.put('/spots', data)
export const deleteSpot = id => request.delete(`/spots/${id}`)

export const getRouteList = params => request.get('/routes/list', { params })
export const getRouteDetail = id => request.get(`/routes/detail/${id}`)
export const addRoute = data => request.post('/routes', data)
export const updateRoute = data => request.put('/routes', data)
export const deleteRoute = id => request.delete(`/routes/${id}`)
export const likeRoute = id => request.post(`/routes/like/${id}`)

export const getTicketTypes = spotId => request.get(`/tickets/types/${spotId}`)
export const addTicketType = data => request.post('/tickets/types', data)
export const updateTicketType = data => request.put('/tickets/types', data)
export const deleteTicketType = id => request.delete(`/tickets/types/${id}`)
export const createTicketOrder = data => request.post('/tickets/order', data)
export const getMyOrders = params => request.get('/tickets/orders/my', { params })
export const getAllOrders = params => request.get('/tickets/orders', { params })
export const getOrderDetail = id => request.get(`/tickets/orders/${id}`)
export const refundOrder = id => request.post(`/tickets/orders/${id}/refund`)
export const updateOrderStatus = (id, data) => request.put(`/tickets/orders/${id}/status`, data)

export const getHotelList = params => request.get('/hotels/list', { params })
export const getHotelById = id => request.get(`/hotels/${id}`)
export const getAllHotels = () => request.get('/hotels/all')
export const addHotel = data => request.post('/hotels', data)
export const updateHotel = data => request.put('/hotels', data)
export const deleteHotel = id => request.delete(`/hotels/${id}`)

export const getRestaurantList = params => request.get('/restaurants/list', { params })
export const getRestaurantById = id => request.get(`/restaurants/${id}`)
export const getAllRestaurants = () => request.get('/restaurants/all')
export const addRestaurant = data => request.post('/restaurants', data)
export const updateRestaurant = data => request.put('/restaurants', data)
export const deleteRestaurant = id => request.delete(`/restaurants/${id}`)

export const getActivityList = params => request.get('/activities/list', { params })
export const getActivityById = id => request.get(`/activities/${id}`)
export const addActivity = data => request.post('/activities', data)
export const updateActivity = data => request.put('/activities', data)
export const deleteActivity = id => request.delete(`/activities/${id}`)
export const registerActivity = id => request.post(`/activities/${id}/register`)
export const cancelRegistration = id => request.post(`/activities/${id}/cancel`)
export const getMyRegistrations = () => request.get('/activities/registrations/my')
export const checkRegistered = id => request.get(`/activities/${id}/registered`)

export const getNoteList = params => request.get('/notes/list', { params })
export const getMyNotes = params => request.get('/notes/my', { params })
export const getNoteDetail = id => request.get(`/notes/detail/${id}`)
export const addNote = data => request.post('/notes', data)
export const updateNote = data => request.put('/notes', data)
export const deleteNote = id => request.delete(`/notes/${id}`)
export const likeNote = id => request.post(`/notes/like/${id}`)
export const auditNote = (id, data) => request.put(`/notes/audit/${id}`, data)

export const getReviewList = params => request.get('/reviews/list', { params })
export const getReviewsByTarget = params => request.get('/reviews/target', { params })
export const addReview = data => request.post('/reviews', data)
export const deleteReview = id => request.delete(`/reviews/${id}`)
export const updateReviewStatus = (id, data) => request.put(`/reviews/${id}/status`, data)

export const getAnnouncementList = params => request.get('/announcements/list', { params })
export const getTopAnnouncements = () => request.get('/announcements/top')
export const getAnnouncementById = id => request.get(`/announcements/${id}`)
export const addAnnouncement = data => request.post('/announcements', data)
export const updateAnnouncement = data => request.put('/announcements', data)
export const deleteAnnouncement = id => request.delete(`/announcements/${id}`)

export const getUserInfo = () => request.get('/user/info')
export const updateUserInfo = data => request.put('/user/info', data)
export const recharge = data => request.post('/user/recharge', data)
export const getUserList = params => request.get('/user/list', { params })
export const updateUserStatus = (id, data) => request.put(`/user/${id}/status`, data)

export const addFavorite = data => request.post('/user/favorite', data)
export const removeFavorite = params => request.delete('/user/favorite', { params })
export const checkFavorite = params => request.get('/user/favorite/check', { params })
export const getFavorites = params => request.get('/user/favorites', { params })

export const getStatistics = () => request.get('/admin/statistics')
export const getSpotRanking = () => request.get('/admin/spot-ranking')
