import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getWarehouseZonePage = (params) => request.get('/api/zone/page', { params })
export const addWarehouseZone = (data) => request.post('/api/zone', data)
export const updateWarehouseZone = (data) => request.put('/api/zone', data)
export const deleteWarehouseZone = (id) => request.delete(`/api/zone/${id}`)
export const enableWarehouseZone = (id) => request.put(`/api/zone/enable/${id}`)
export const disableWarehouseZone = (id) => request.put(`/api/zone/disable/${id}`)
export const getStorageLocationPage = (params) => request.get('/api/location/page', { params })
export const addStorageLocation = (data) => request.post('/api/location', data)
export const updateStorageLocation = (data) => request.put('/api/location', data)
export const deleteStorageLocation = (id) => request.delete(`/api/location/${id}`)
export const reserveStorageLocation = (id) => request.put(`/api/location/reserve/${id}`)
export const releaseStorageLocation = (id) => request.put(`/api/location/release/${id}`)
export const lockStorageLocation = (id) => request.put(`/api/location/lock/${id}`)
export const getAgvVehiclePage = (params) => request.get('/api/agv/page', { params })
export const addAgvVehicle = (data) => request.post('/api/agv', data)
export const updateAgvVehicle = (data) => request.put('/api/agv', data)
export const deleteAgvVehicle = (id) => request.delete(`/api/agv/${id}`)
export const onlineAgvVehicle = (id) => request.put(`/api/agv/online/${id}`)
export const dispatchAgvVehicle = (id) => request.put(`/api/agv/dispatch/${id}`)
export const offlineAgvVehicle = (id) => request.put(`/api/agv/offline/${id}`)
export const getChargingStationPage = (params) => request.get('/api/station/page', { params })
export const addChargingStation = (data) => request.post('/api/station', data)
export const updateChargingStation = (data) => request.put('/api/station', data)
export const deleteChargingStation = (id) => request.delete(`/api/station/${id}`)
export const enableChargingStation = (id) => request.put(`/api/station/enable/${id}`)
export const maintainChargingStation = (id) => request.put(`/api/station/maintain/${id}`)
export const getInventoryItemPage = (params) => request.get('/api/inventory/page', { params })
export const addInventoryItem = (data) => request.post('/api/inventory', data)
export const updateInventoryItem = (data) => request.put('/api/inventory', data)
export const deleteInventoryItem = (id) => request.delete(`/api/inventory/${id}`)
export const freezeInventoryItem = (id) => request.put(`/api/inventory/freeze/${id}`)
export const releaseInventoryItem = (id) => request.put(`/api/inventory/release/${id}`)
export const getInboundOrderPage = (params) => request.get('/api/inbound/page', { params })
export const addInboundOrder = (data) => request.post('/api/inbound', data)
export const updateInboundOrder = (data) => request.put('/api/inbound', data)
export const deleteInboundOrder = (id) => request.delete(`/api/inbound/${id}`)
export const assignInboundOrder = (id) => request.put(`/api/inbound/assign/${id}`)
export const receiveInboundOrder = (id) => request.put(`/api/inbound/receive/${id}`)
export const finishInboundOrder = (id) => request.put(`/api/inbound/finish/${id}`)
export const getOutboundOrderPage = (params) => request.get('/api/outbound/page', { params })
export const addOutboundOrder = (data) => request.post('/api/outbound', data)
export const updateOutboundOrder = (data) => request.put('/api/outbound', data)
export const deleteOutboundOrder = (id) => request.delete(`/api/outbound/${id}`)
export const allocateOutboundOrder = (id) => request.put(`/api/outbound/allocate/${id}`)
export const pickOutboundOrder = (id) => request.put(`/api/outbound/pick/${id}`)
export const shipOutboundOrder = (id) => request.put(`/api/outbound/ship/${id}`)
export const getAgvTaskPage = (params) => request.get('/api/task/page', { params })
export const addAgvTask = (data) => request.post('/api/task', data)
export const updateAgvTask = (data) => request.put('/api/task', data)
export const deleteAgvTask = (id) => request.delete(`/api/task/${id}`)
export const dispatchAgvTask = (id) => request.put(`/api/task/dispatch/${id}`)
export const executeAgvTask = (id) => request.put(`/api/task/execute/${id}`)
export const completeAgvTask = (id) => request.put(`/api/task/complete/${id}`)
export const cancelAgvTask = (id) => request.put(`/api/task/cancel/${id}`)
export const getTaskRoutePage = (params) => request.get('/api/route/page', { params })
export const addTaskRoute = (data) => request.post('/api/route', data)
export const updateTaskRoute = (data) => request.put('/api/route', data)
export const deleteTaskRoute = (id) => request.delete(`/api/route/${id}`)
export const enableTaskRoute = (id) => request.put(`/api/route/enable/${id}`)
export const disableTaskRoute = (id) => request.put(`/api/route/disable/${id}`)
export const getLocationRecommendationPage = (params) => request.get('/api/recommendation/page', { params })
export const addLocationRecommendation = (data) => request.post('/api/recommendation', data)
export const updateLocationRecommendation = (data) => request.put('/api/recommendation', data)
export const deleteLocationRecommendation = (id) => request.delete(`/api/recommendation/${id}`)
export const applyLocationRecommendation = (id) => request.put(`/api/recommendation/apply/${id}`)
export const rejectLocationRecommendation = (id) => request.put(`/api/recommendation/reject/${id}`)
export const getDeviceMaintenancePage = (params) => request.get('/api/maintenance/page', { params })
export const addDeviceMaintenance = (data) => request.post('/api/maintenance', data)
export const updateDeviceMaintenance = (data) => request.put('/api/maintenance', data)
export const deleteDeviceMaintenance = (id) => request.delete(`/api/maintenance/${id}`)
export const startDeviceMaintenance = (id) => request.put(`/api/maintenance/start/${id}`)
export const finishDeviceMaintenance = (id) => request.put(`/api/maintenance/finish/${id}`)
export const getExceptionAlertPage = (params) => request.get('/api/alert/page', { params })
export const addExceptionAlert = (data) => request.post('/api/alert', data)
export const updateExceptionAlert = (data) => request.put('/api/alert', data)
export const deleteExceptionAlert = (id) => request.delete(`/api/alert/${id}`)
export const handleExceptionAlert = (id) => request.put(`/api/alert/handle/${id}`)
export const closeExceptionAlert = (id) => request.put(`/api/alert/close/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
