import request from './request'

export const login = data => request.post('/auth/login', data)
export const register = data => request.post('/auth/register', data)
export const getInfo = () => request.get('/auth/info')
export const updatePassword = data => request.put('/auth/password', data)

export const getUserPage = params => request.get('/user/page', { params })
export const updateUserStatus = (id, data) => request.put(`/user/status/${id}`, data)
export const updateProfile = data => request.put('/user/profile', data)

export const applyMerchant = data => request.post('/merchant/apply', data)
export const getMerchantPage = params => request.get('/merchant/page', { params })
export const auditMerchant = (id, data) => request.put(`/merchant/audit/${id}`, data)
export const getMerchantInfo = () => request.get('/merchant/info')
export const updateMerchant = data => request.put('/merchant/update', data)

export const getCategoryList = () => request.get('/category/list')
export const getCategoryTree = () => request.get('/category/tree')
export const addCategory = data => request.post('/category/add', data)
export const updateCategory = data => request.put('/category/update', data)
export const deleteCategory = id => request.delete(`/category/delete/${id}`)

export const getProductPage = params => request.get('/product/page', { params })
export const getProductDetail = id => request.get(`/product/detail/${id}`)
export const addProduct = data => request.post('/product/add', data)
export const updateProduct = data => request.put('/product/update', data)
export const updateProductStatus = (id, data) => request.put(`/product/status/${id}`, data)
export const deleteProduct = id => request.delete(`/product/delete/${id}`)

export const getActivityPage = params => request.get('/activity/page', { params })
export const getActivityDetail = id => request.get(`/activity/detail/${id}`)
export const addActivity = data => request.post('/activity/add', data)
export const updateActivity = data => request.put('/activity/update', data)
export const endActivity = id => request.put(`/activity/end/${id}`)
export const getActivityHome = params => request.get('/activity/home', { params })

export const createGroup = data => request.post('/group/create', data)
export const joinGroup = data => request.post('/group/join', data)
export const getGroupDetail = id => request.get(`/group/detail/${id}`)
export const getMyGroups = params => request.get('/group/my', { params })
export const getOngoingGroups = activityId => request.get(`/group/ongoing/${activityId}`)

export const createOrder = data => request.post('/order/create', data)
export const getOrderPage = params => request.get('/order/page', { params })
export const getOrderDetail = id => request.get(`/order/detail/${id}`)
export const payOrder = id => request.put(`/order/pay/${id}`)
export const shipOrder = id => request.put(`/order/ship/${id}`)
export const receiveOrder = id => request.put(`/order/receive/${id}`)
export const cancelOrder = id => request.put(`/order/cancel/${id}`)
export const applyRefund = (id, data) => request.put(`/order/refund/${id}`, data)
export const handleRefund = (id, data) => request.put(`/order/refund/handle/${id}`, data)

export const getAddressList = () => request.get('/address/list')
export const addAddress = data => request.post('/address/add', data)
export const updateAddress = data => request.put('/address/update', data)
export const deleteAddress = id => request.delete(`/address/delete/${id}`)
export const setDefaultAddress = id => request.put(`/address/default/${id}`)

export const getCartList = () => request.get('/cart/list')
export const addCart = data => request.post('/cart/add', data)
export const updateCartQuantity = data => request.put('/cart/quantity', data)
export const deleteCart = id => request.delete(`/cart/delete/${id}`)
export const clearCart = () => request.delete('/cart/clear')

export const addReview = data => request.post('/review/add', data)
export const getReviewPage = params => request.get('/review/page', { params })
export const auditReview = (id, data) => request.put(`/review/audit/${id}`, data)
export const getProductReviews = (productId, params) => request.get(`/review/product/${productId}`, { params })

export const getNoticePage = params => request.get('/notice/page', { params })
export const getNoticeDetail = id => request.get(`/notice/detail/${id}`)
export const addNotice = data => request.post('/notice/add', data)
export const updateNotice = data => request.put('/notice/update', data)
export const deleteNotice = id => request.delete(`/notice/delete/${id}`)
export const getFrontNotice = () => request.get('/notice/front')

export const getStatsOverview = () => request.get('/stats/overview')
export const getStatsSales = params => request.get('/stats/sales', { params })
export const getHotProducts = params => request.get('/stats/hot-products', { params })
export const getMerchantStats = params => request.get('/stats/merchant', { params })
