import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getBuildingProfilePage = (params) => request.get('/api/building/page', { params })
export const addBuildingProfile = (data) => request.post('/api/building', data)
export const updateBuildingProfile = (data) => request.put('/api/building', data)
export const deleteBuildingProfile = (id) => request.delete(`/api/building/${id}`)
export const processBuildingProfile = (id) => request.put(`/api/building/process/${id}`)
export const finishBuildingProfile = (id) => request.put(`/api/building/finish/${id}`)

export const getEquipmentAssetPage = (params) => request.get('/api/equipment/page', { params })
export const addEquipmentAsset = (data) => request.post('/api/equipment', data)
export const updateEquipmentAsset = (data) => request.put('/api/equipment', data)
export const deleteEquipmentAsset = (id) => request.delete(`/api/equipment/${id}`)
export const processEquipmentAsset = (id) => request.put(`/api/equipment/process/${id}`)
export const finishEquipmentAsset = (id) => request.put(`/api/equipment/finish/${id}`)

export const getTenantProfilePage = (params) => request.get('/api/tenant/page', { params })
export const addTenantProfile = (data) => request.post('/api/tenant', data)
export const updateTenantProfile = (data) => request.put('/api/tenant', data)
export const deleteTenantProfile = (id) => request.delete(`/api/tenant/${id}`)
export const processTenantProfile = (id) => request.put(`/api/tenant/process/${id}`)
export const finishTenantProfile = (id) => request.put(`/api/tenant/finish/${id}`)

export const getVisitRepairTicketPage = (params) => request.get('/api/ticket/page', { params })
export const addVisitRepairTicket = (data) => request.post('/api/ticket', data)
export const updateVisitRepairTicket = (data) => request.put('/api/ticket', data)
export const deleteVisitRepairTicket = (id) => request.delete(`/api/ticket/${id}`)
export const processVisitRepairTicket = (id) => request.put(`/api/ticket/process/${id}`)
export const finishVisitRepairTicket = (id) => request.put(`/api/ticket/finish/${id}`)

export const getRepairDispatchPage = (params) => request.get('/api/repair/page', { params })
export const addRepairDispatch = (data) => request.post('/api/repair', data)
export const updateRepairDispatch = (data) => request.put('/api/repair', data)
export const deleteRepairDispatch = (id) => request.delete(`/api/repair/${id}`)
export const processRepairDispatch = (id) => request.put(`/api/repair/process/${id}`)
export const finishRepairDispatch = (id) => request.put(`/api/repair/finish/${id}`)

export const getMaintenancePlanPage = (params) => request.get('/api/plan/page', { params })
export const addMaintenancePlan = (data) => request.post('/api/plan', data)
export const updateMaintenancePlan = (data) => request.put('/api/plan', data)
export const deleteMaintenancePlan = (id) => request.delete(`/api/plan/${id}`)
export const processMaintenancePlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishMaintenancePlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getMaintenanceTaskPage = (params) => request.get('/api/task/page', { params })
export const addMaintenanceTask = (data) => request.post('/api/task', data)
export const updateMaintenanceTask = (data) => request.put('/api/task', data)
export const deleteMaintenanceTask = (id) => request.delete(`/api/task/${id}`)
export const processMaintenanceTask = (id) => request.put(`/api/task/process/${id}`)
export const finishMaintenanceTask = (id) => request.put(`/api/task/finish/${id}`)

export const getFaultAlertPage = (params) => request.get('/api/alert/page', { params })
export const addFaultAlert = (data) => request.post('/api/alert', data)
export const updateFaultAlert = (data) => request.put('/api/alert', data)
export const deleteFaultAlert = (id) => request.delete(`/api/alert/${id}`)
export const processFaultAlert = (id) => request.put(`/api/alert/process/${id}`)
export const finishFaultAlert = (id) => request.put(`/api/alert/finish/${id}`)

export const getInspectionRecordPage = (params) => request.get('/api/inspection/page', { params })
export const addInspectionRecord = (data) => request.post('/api/inspection', data)
export const updateInspectionRecord = (data) => request.put('/api/inspection', data)
export const deleteInspectionRecord = (id) => request.delete(`/api/inspection/${id}`)
export const processInspectionRecord = (id) => request.put(`/api/inspection/process/${id}`)
export const finishInspectionRecord = (id) => request.put(`/api/inspection/finish/${id}`)

export const getSparePartStockPage = (params) => request.get('/api/spare/page', { params })
export const addSparePartStock = (data) => request.post('/api/spare', data)
export const updateSparePartStock = (data) => request.put('/api/spare', data)
export const deleteSparePartStock = (id) => request.delete(`/api/spare/${id}`)
export const processSparePartStock = (id) => request.put(`/api/spare/process/${id}`)
export const finishSparePartStock = (id) => request.put(`/api/spare/finish/${id}`)

export const getServiceFeedbackPage = (params) => request.get('/api/feedback/page', { params })
export const addServiceFeedback = (data) => request.post('/api/feedback', data)
export const updateServiceFeedback = (data) => request.put('/api/feedback', data)
export const deleteServiceFeedback = (id) => request.delete(`/api/feedback/${id}`)
export const processServiceFeedback = (id) => request.put(`/api/feedback/process/${id}`)
export const finishServiceFeedback = (id) => request.put(`/api/feedback/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
