import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getMarketAreaPage = (params) => request.get('/api/area/page', { params })
export const addMarketArea = (data) => request.post('/api/area', data)
export const updateMarketArea = (data) => request.put('/api/area', data)
export const deleteMarketArea = (id) => request.delete(`/api/area/${id}`)
export const processMarketArea = (id) => request.put(`/api/area/process/${id}`)
export const finishMarketArea = (id) => request.put(`/api/area/finish/${id}`)

export const getStallProfilePage = (params) => request.get('/api/stall/page', { params })
export const addStallProfile = (data) => request.post('/api/stall', data)
export const updateStallProfile = (data) => request.put('/api/stall', data)
export const deleteStallProfile = (id) => request.delete(`/api/stall/${id}`)
export const processStallProfile = (id) => request.put(`/api/stall/process/${id}`)
export const finishStallProfile = (id) => request.put(`/api/stall/finish/${id}`)

export const getVendorProfilePage = (params) => request.get('/api/vendor/page', { params })
export const addVendorProfile = (data) => request.post('/api/vendor', data)
export const updateVendorProfile = (data) => request.put('/api/vendor', data)
export const deleteVendorProfile = (id) => request.delete(`/api/vendor/${id}`)
export const processVendorProfile = (id) => request.put(`/api/vendor/process/${id}`)
export const finishVendorProfile = (id) => request.put(`/api/vendor/finish/${id}`)

export const getProductTracePage = (params) => request.get('/api/product/page', { params })
export const addProductTrace = (data) => request.post('/api/product', data)
export const updateProductTrace = (data) => request.put('/api/product', data)
export const deleteProductTrace = (id) => request.delete(`/api/product/${id}`)
export const processProductTrace = (id) => request.put(`/api/product/process/${id}`)
export const finishProductTrace = (id) => request.put(`/api/product/finish/${id}`)

export const getInspectionTaskPage = (params) => request.get('/api/inspection/page', { params })
export const addInspectionTask = (data) => request.post('/api/inspection', data)
export const updateInspectionTask = (data) => request.put('/api/inspection', data)
export const deleteInspectionTask = (id) => request.delete(`/api/inspection/${id}`)
export const processInspectionTask = (id) => request.put(`/api/inspection/process/${id}`)
export const finishInspectionTask = (id) => request.put(`/api/inspection/finish/${id}`)

export const getIssueRectificationPage = (params) => request.get('/api/rectification/page', { params })
export const addIssueRectification = (data) => request.post('/api/rectification', data)
export const updateIssueRectification = (data) => request.put('/api/rectification', data)
export const deleteIssueRectification = (id) => request.delete(`/api/rectification/${id}`)
export const processIssueRectification = (id) => request.put(`/api/rectification/process/${id}`)
export const finishIssueRectification = (id) => request.put(`/api/rectification/finish/${id}`)

export const getSampleRecordPage = (params) => request.get('/api/sample/page', { params })
export const addSampleRecord = (data) => request.post('/api/sample', data)
export const updateSampleRecord = (data) => request.put('/api/sample', data)
export const deleteSampleRecord = (id) => request.delete(`/api/sample/${id}`)
export const processSampleRecord = (id) => request.put(`/api/sample/process/${id}`)
export const finishSampleRecord = (id) => request.put(`/api/sample/finish/${id}`)

export const getTestResultPage = (params) => request.get('/api/test/page', { params })
export const addTestResult = (data) => request.post('/api/test', data)
export const updateTestResult = (data) => request.put('/api/test', data)
export const deleteTestResult = (id) => request.delete(`/api/test/${id}`)
export const processTestResult = (id) => request.put(`/api/test/process/${id}`)
export const finishTestResult = (id) => request.put(`/api/test/finish/${id}`)

export const getSourceLedgerPage = (params) => request.get('/api/source/page', { params })
export const addSourceLedger = (data) => request.post('/api/source', data)
export const updateSourceLedger = (data) => request.put('/api/source', data)
export const deleteSourceLedger = (id) => request.delete(`/api/source/${id}`)
export const processSourceLedger = (id) => request.put(`/api/source/process/${id}`)
export const finishSourceLedger = (id) => request.put(`/api/source/finish/${id}`)

export const getDisposalRecordPage = (params) => request.get('/api/disposal/page', { params })
export const addDisposalRecord = (data) => request.post('/api/disposal', data)
export const updateDisposalRecord = (data) => request.put('/api/disposal', data)
export const deleteDisposalRecord = (id) => request.delete(`/api/disposal/${id}`)
export const processDisposalRecord = (id) => request.put(`/api/disposal/process/${id}`)
export const finishDisposalRecord = (id) => request.put(`/api/disposal/finish/${id}`)

export const getRiskAlertPage = (params) => request.get('/api/alert/page', { params })
export const addRiskAlert = (data) => request.post('/api/alert', data)
export const updateRiskAlert = (data) => request.put('/api/alert', data)
export const deleteRiskAlert = (id) => request.delete(`/api/alert/${id}`)
export const processRiskAlert = (id) => request.put(`/api/alert/process/${id}`)
export const finishRiskAlert = (id) => request.put(`/api/alert/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
