import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getConsumableCatalogPage = (params) => request.get('/api/catalog/page', { params })
export const addConsumableCatalog = (data) => request.post('/api/catalog', data)
export const updateConsumableCatalog = (data) => request.put('/api/catalog', data)
export const deleteConsumableCatalog = (id) => request.delete(`/api/catalog/${id}`)
export const activateConsumableCatalog = (id) => request.put(`/api/catalog/activate/${id}`)
export const finishConsumableCatalog = (id) => request.put(`/api/catalog/finish/${id}`)
export const getSupplierProfilePage = (params) => request.get('/api/supplier/page', { params })
export const addSupplierProfile = (data) => request.post('/api/supplier', data)
export const updateSupplierProfile = (data) => request.put('/api/supplier', data)
export const deleteSupplierProfile = (id) => request.delete(`/api/supplier/${id}`)
export const activateSupplierProfile = (id) => request.put(`/api/supplier/activate/${id}`)
export const finishSupplierProfile = (id) => request.put(`/api/supplier/finish/${id}`)
export const getLabRoomPage = (params) => request.get('/api/lab/page', { params })
export const addLabRoom = (data) => request.post('/api/lab', data)
export const updateLabRoom = (data) => request.put('/api/lab', data)
export const deleteLabRoom = (id) => request.delete(`/api/lab/${id}`)
export const activateLabRoom = (id) => request.put(`/api/lab/activate/${id}`)
export const finishLabRoom = (id) => request.put(`/api/lab/finish/${id}`)
export const getStockItemPage = (params) => request.get('/api/stock/page', { params })
export const addStockItem = (data) => request.post('/api/stock', data)
export const updateStockItem = (data) => request.put('/api/stock', data)
export const deleteStockItem = (id) => request.delete(`/api/stock/${id}`)
export const processStockItem = (id) => request.put(`/api/stock/process/${id}`)
export const finishStockItem = (id) => request.put(`/api/stock/finish/${id}`)
export const getPurchaseRequestPage = (params) => request.get('/api/request/page', { params })
export const addPurchaseRequest = (data) => request.post('/api/request', data)
export const updatePurchaseRequest = (data) => request.put('/api/request', data)
export const deletePurchaseRequest = (id) => request.delete(`/api/request/${id}`)
export const submitPurchaseRequest = (id) => request.put(`/api/request/submit/${id}`)
export const approvePurchaseRequest = (id) => request.put(`/api/request/approve/${id}`)
export const getPurchaseApprovalPage = (params) => request.get('/api/approval/page', { params })
export const addPurchaseApproval = (data) => request.post('/api/approval', data)
export const updatePurchaseApproval = (data) => request.put('/api/approval', data)
export const deletePurchaseApproval = (id) => request.delete(`/api/approval/${id}`)
export const submitPurchaseApproval = (id) => request.put(`/api/approval/submit/${id}`)
export const approvePurchaseApproval = (id) => request.put(`/api/approval/approve/${id}`)
export const getPurchaseOrderPage = (params) => request.get('/api/order/page', { params })
export const addPurchaseOrder = (data) => request.post('/api/order', data)
export const updatePurchaseOrder = (data) => request.put('/api/order', data)
export const deletePurchaseOrder = (id) => request.delete(`/api/order/${id}`)
export const processPurchaseOrder = (id) => request.put(`/api/order/process/${id}`)
export const finishPurchaseOrder = (id) => request.put(`/api/order/finish/${id}`)
export const getInboundRecordPage = (params) => request.get('/api/inbound/page', { params })
export const addInboundRecord = (data) => request.post('/api/inbound', data)
export const updateInboundRecord = (data) => request.put('/api/inbound', data)
export const deleteInboundRecord = (id) => request.delete(`/api/inbound/${id}`)
export const submitInboundRecord = (id) => request.put(`/api/inbound/submit/${id}`)
export const approveInboundRecord = (id) => request.put(`/api/inbound/approve/${id}`)
export const getOutboundRecordPage = (params) => request.get('/api/outbound/page', { params })
export const addOutboundRecord = (data) => request.post('/api/outbound', data)
export const updateOutboundRecord = (data) => request.put('/api/outbound', data)
export const deleteOutboundRecord = (id) => request.delete(`/api/outbound/${id}`)
export const submitOutboundRecord = (id) => request.put(`/api/outbound/submit/${id}`)
export const approveOutboundRecord = (id) => request.put(`/api/outbound/approve/${id}`)
export const getInventoryCheckPage = (params) => request.get('/api/check/page', { params })
export const addInventoryCheck = (data) => request.post('/api/check', data)
export const updateInventoryCheck = (data) => request.put('/api/check', data)
export const deleteInventoryCheck = (id) => request.delete(`/api/check/${id}`)
export const processInventoryCheck = (id) => request.put(`/api/check/process/${id}`)
export const finishInventoryCheck = (id) => request.put(`/api/check/finish/${id}`)
export const getWarningRulePage = (params) => request.get('/api/rule/page', { params })
export const addWarningRule = (data) => request.post('/api/rule', data)
export const updateWarningRule = (data) => request.put('/api/rule', data)
export const deleteWarningRule = (id) => request.delete(`/api/rule/${id}`)
export const activateWarningRule = (id) => request.put(`/api/rule/activate/${id}`)
export const finishWarningRule = (id) => request.put(`/api/rule/finish/${id}`)
export const getStockWarningPage = (params) => request.get('/api/warning/page', { params })
export const addStockWarning = (data) => request.post('/api/warning', data)
export const updateStockWarning = (data) => request.put('/api/warning', data)
export const deleteStockWarning = (id) => request.delete(`/api/warning/${id}`)
export const processStockWarning = (id) => request.put(`/api/warning/process/${id}`)
export const finishStockWarning = (id) => request.put(`/api/warning/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
