import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getCloudAccountPage = (params) => request.get('/api/account/page', { params })
export const addCloudAccount = (data) => request.post('/api/account', data)
export const updateCloudAccount = (data) => request.put('/api/account', data)
export const deleteCloudAccount = (id) => request.delete(`/api/account/${id}`)
export const activateCloudAccount = (id) => request.put(`/api/account/activate/${id}`)
export const disableCloudAccount = (id) => request.put(`/api/account/disable/${id}`)
export const getResourceNamespacePage = (params) => request.get('/api/namespace/page', { params })
export const addResourceNamespace = (data) => request.post('/api/namespace', data)
export const updateResourceNamespace = (data) => request.put('/api/namespace', data)
export const deleteResourceNamespace = (id) => request.delete(`/api/namespace/${id}`)
export const activateResourceNamespace = (id) => request.put(`/api/namespace/activate/${id}`)
export const freezeResourceNamespace = (id) => request.put(`/api/namespace/freeze/${id}`)
export const getCostBillPage = (params) => request.get('/api/bill/page', { params })
export const addCostBill = (data) => request.post('/api/bill', data)
export const updateCostBill = (data) => request.put('/api/bill', data)
export const deleteCostBill = (id) => request.delete(`/api/bill/${id}`)
export const confirmCostBill = (id) => request.put(`/api/bill/confirm/${id}`)
export const payCostBill = (id) => request.put(`/api/bill/pay/${id}`)
export const closeCostBill = (id) => request.put(`/api/bill/close/${id}`)
export const getCostItemPage = (params) => request.get('/api/cost-item/page', { params })
export const addCostItem = (data) => request.post('/api/cost-item', data)
export const updateCostItem = (data) => request.put('/api/cost-item', data)
export const deleteCostItem = (id) => request.delete(`/api/cost-item/${id}`)
export const getBudgetPolicyPage = (params) => request.get('/api/budget/page', { params })
export const addBudgetPolicy = (data) => request.post('/api/budget', data)
export const updateBudgetPolicy = (data) => request.put('/api/budget', data)
export const deleteBudgetPolicy = (id) => request.delete(`/api/budget/${id}`)
export const enableBudgetPolicy = (id) => request.put(`/api/budget/enable/${id}`)
export const archiveBudgetPolicy = (id) => request.put(`/api/budget/archive/${id}`)
export const getCostAllocationPage = (params) => request.get('/api/allocation/page', { params })
export const addCostAllocation = (data) => request.post('/api/allocation', data)
export const updateCostAllocation = (data) => request.put('/api/allocation', data)
export const deleteCostAllocation = (id) => request.delete(`/api/allocation/${id}`)
export const submitCostAllocation = (id) => request.put(`/api/allocation/submit/${id}`)
export const approveCostAllocation = (id) => request.put(`/api/allocation/approve/${id}`)
export const rejectCostAllocation = (id) => request.put(`/api/allocation/reject/${id}`)
export const getIdleResourcePage = (params) => request.get('/api/idle-resource/page', { params })
export const addIdleResource = (data) => request.post('/api/idle-resource', data)
export const updateIdleResource = (data) => request.put('/api/idle-resource', data)
export const deleteIdleResource = (id) => request.delete(`/api/idle-resource/${id}`)
export const confirmIdleResource = (id) => request.put(`/api/idle-resource/confirm/${id}`)
export const ignoreIdleResource = (id) => request.put(`/api/idle-resource/ignore/${id}`)
export const cleanIdleResource = (id) => request.put(`/api/idle-resource/clean/${id}`)
export const getOptimizationRulePage = (params) => request.get('/api/optimization-rule/page', { params })
export const addOptimizationRule = (data) => request.post('/api/optimization-rule', data)
export const updateOptimizationRule = (data) => request.put('/api/optimization-rule', data)
export const deleteOptimizationRule = (id) => request.delete(`/api/optimization-rule/${id}`)
export const enableOptimizationRule = (id) => request.put(`/api/optimization-rule/enable/${id}`)
export const pauseOptimizationRule = (id) => request.put(`/api/optimization-rule/pause/${id}`)
export const getOptimizationAdvicePage = (params) => request.get('/api/advice/page', { params })
export const addOptimizationAdvice = (data) => request.post('/api/advice', data)
export const updateOptimizationAdvice = (data) => request.put('/api/advice', data)
export const deleteOptimizationAdvice = (id) => request.delete(`/api/advice/${id}`)
export const acceptOptimizationAdvice = (id) => request.put(`/api/advice/accept/${id}`)
export const finishOptimizationAdvice = (id) => request.put(`/api/advice/finish/${id}`)
export const rejectOptimizationAdvice = (id) => request.put(`/api/advice/reject/${id}`)
export const getSavingPlanPage = (params) => request.get('/api/saving-plan/page', { params })
export const addSavingPlan = (data) => request.post('/api/saving-plan', data)
export const updateSavingPlan = (data) => request.put('/api/saving-plan', data)
export const deleteSavingPlan = (id) => request.delete(`/api/saving-plan/${id}`)
export const activateSavingPlan = (id) => request.put(`/api/saving-plan/activate/${id}`)
export const finishSavingPlan = (id) => request.put(`/api/saving-plan/finish/${id}`)
export const archiveSavingPlan = (id) => request.put(`/api/saving-plan/archive/${id}`)
export const getAnomalyEventPage = (params) => request.get('/api/anomaly/page', { params })
export const addAnomalyEvent = (data) => request.post('/api/anomaly', data)
export const updateAnomalyEvent = (data) => request.put('/api/anomaly', data)
export const deleteAnomalyEvent = (id) => request.delete(`/api/anomaly/${id}`)
export const confirmAnomalyEvent = (id) => request.put(`/api/anomaly/confirm/${id}`)
export const resolveAnomalyEvent = (id) => request.put(`/api/anomaly/resolve/${id}`)
export const closeAnomalyEvent = (id) => request.put(`/api/anomaly/close/${id}`)
export const getReportSnapshotPage = (params) => request.get('/api/report/page', { params })
export const addReportSnapshot = (data) => request.post('/api/report', data)
export const updateReportSnapshot = (data) => request.put('/api/report', data)
export const deleteReportSnapshot = (id) => request.delete(`/api/report/${id}`)
export const publishReportSnapshot = (id) => request.put(`/api/report/publish/${id}`)
export const archiveReportSnapshot = (id) => request.put(`/api/report/archive/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
