import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getParkingLotPage = (params) => request.get('/api/lot/page', { params })
export const addParkingLot = (data) => request.post('/api/lot', data)
export const updateParkingLot = (data) => request.put('/api/lot', data)
export const deleteParkingLot = (id) => request.delete(`/api/lot/${id}`)
export const enableParkingLot = (id) => request.put(`/api/lot/enable/${id}`)
export const disableParkingLot = (id) => request.put(`/api/lot/disable/${id}`)
export const getParkingAreaPage = (params) => request.get('/api/area/page', { params })
export const addParkingArea = (data) => request.post('/api/area', data)
export const updateParkingArea = (data) => request.put('/api/area', data)
export const deleteParkingArea = (id) => request.delete(`/api/area/${id}`)
export const enableParkingArea = (id) => request.put(`/api/area/enable/${id}`)
export const disableParkingArea = (id) => request.put(`/api/area/disable/${id}`)
export const getParkingSpacePage = (params) => request.get('/api/space/page', { params })
export const addParkingSpace = (data) => request.post('/api/space', data)
export const updateParkingSpace = (data) => request.put('/api/space', data)
export const deleteParkingSpace = (id) => request.delete(`/api/space/${id}`)
export const availableParkingSpace = (id) => request.put(`/api/space/available/${id}`)
export const occupyParkingSpace = (id) => request.put(`/api/space/occupy/${id}`)
export const getSpaceSensorPage = (params) => request.get('/api/sensor/page', { params })
export const addSpaceSensor = (data) => request.post('/api/sensor', data)
export const updateSpaceSensor = (data) => request.put('/api/sensor', data)
export const deleteSpaceSensor = (id) => request.delete(`/api/sensor/${id}`)
export const onlineSpaceSensor = (id) => request.put(`/api/sensor/online/${id}`)
export const warnSpaceSensor = (id) => request.put(`/api/sensor/warn/${id}`)
export const getVehicleProfilePage = (params) => request.get('/api/vehicle/page', { params })
export const addVehicleProfile = (data) => request.post('/api/vehicle', data)
export const updateVehicleProfile = (data) => request.put('/api/vehicle', data)
export const deleteVehicleProfile = (id) => request.delete(`/api/vehicle/${id}`)
export const enableVehicleProfile = (id) => request.put(`/api/vehicle/enable/${id}`)
export const disableVehicleProfile = (id) => request.put(`/api/vehicle/disable/${id}`)
export const getReservationOrderPage = (params) => request.get('/api/reservation/page', { params })
export const addReservationOrder = (data) => request.post('/api/reservation', data)
export const updateReservationOrder = (data) => request.put('/api/reservation', data)
export const deleteReservationOrder = (id) => request.delete(`/api/reservation/${id}`)
export const enterReservationOrder = (id) => request.put(`/api/reservation/enter/${id}`)
export const finishReservationOrder = (id) => request.put(`/api/reservation/finish/${id}`)
export const getParkingRecordPage = (params) => request.get('/api/record/page', { params })
export const addParkingRecord = (data) => request.post('/api/record', data)
export const updateParkingRecord = (data) => request.put('/api/record', data)
export const deleteParkingRecord = (id) => request.delete(`/api/record/${id}`)
export const leaveParkingRecord = (id) => request.put(`/api/record/leave/${id}`)
export const closeParkingRecord = (id) => request.put(`/api/record/close/${id}`)
export const getPaymentRecordPage = (params) => request.get('/api/payment/page', { params })
export const addPaymentRecord = (data) => request.post('/api/payment', data)
export const updatePaymentRecord = (data) => request.put('/api/payment', data)
export const deletePaymentRecord = (id) => request.delete(`/api/payment/${id}`)
export const refundPaymentRecord = (id) => request.put(`/api/payment/refund/${id}`)
export const finishPaymentRecord = (id) => request.put(`/api/payment/finish/${id}`)
export const getVacancyPredictionPage = (params) => request.get('/api/prediction/page', { params })
export const addVacancyPrediction = (data) => request.post('/api/prediction', data)
export const updateVacancyPrediction = (data) => request.put('/api/prediction', data)
export const deleteVacancyPrediction = (id) => request.delete(`/api/prediction/${id}`)
export const publishVacancyPrediction = (id) => request.put(`/api/prediction/publish/${id}`)
export const closeVacancyPrediction = (id) => request.put(`/api/prediction/close/${id}`)
export const getGuidanceScreenPage = (params) => request.get('/api/screen/page', { params })
export const addGuidanceScreen = (data) => request.post('/api/screen', data)
export const updateGuidanceScreen = (data) => request.put('/api/screen', data)
export const deleteGuidanceScreen = (id) => request.delete(`/api/screen/${id}`)
export const onlineGuidanceScreen = (id) => request.put(`/api/screen/online/${id}`)
export const warnGuidanceScreen = (id) => request.put(`/api/screen/warn/${id}`)
export const getNavigationRoutePage = (params) => request.get('/api/route/page', { params })
export const addNavigationRoute = (data) => request.post('/api/route', data)
export const updateNavigationRoute = (data) => request.put('/api/route', data)
export const deleteNavigationRoute = (id) => request.delete(`/api/route/${id}`)
export const publishNavigationRoute = (id) => request.put(`/api/route/publish/${id}`)
export const disableNavigationRoute = (id) => request.put(`/api/route/disable/${id}`)
export const getFaultReportPage = (params) => request.get('/api/fault/page', { params })
export const addFaultReport = (data) => request.post('/api/fault', data)
export const updateFaultReport = (data) => request.put('/api/fault', data)
export const deleteFaultReport = (id) => request.delete(`/api/fault/${id}`)
export const confirmFaultReport = (id) => request.put(`/api/fault/confirm/${id}`)
export const closeFaultReport = (id) => request.put(`/api/fault/close/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
