import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getParkBuildingPage = (params) => request.get('/api/building/page', { params })
export const addParkBuilding = (data) => request.post('/api/building', data)
export const updateParkBuilding = (data) => request.put('/api/building', data)
export const deleteParkBuilding = (id) => request.delete(`/api/building/${id}`)
export const enableParkBuilding = (id) => request.put(`/api/building/enable/${id}`)
export const disableParkBuilding = (id) => request.put(`/api/building/disable/${id}`)
export const getTwinDevicePage = (params) => request.get('/api/device/page', { params })
export const addTwinDevice = (data) => request.post('/api/device', data)
export const updateTwinDevice = (data) => request.put('/api/device', data)
export const deleteTwinDevice = (id) => request.delete(`/api/device/${id}`)
export const onlineTwinDevice = (id) => request.put(`/api/device/online/${id}`)
export const offlineTwinDevice = (id) => request.put(`/api/device/offline/${id}`)
export const getInspectionRoutePage = (params) => request.get('/api/route/page', { params })
export const addInspectionRoute = (data) => request.post('/api/route', data)
export const updateInspectionRoute = (data) => request.put('/api/route', data)
export const deleteInspectionRoute = (id) => request.delete(`/api/route/${id}`)
export const enableInspectionRoute = (id) => request.put(`/api/route/enable/${id}`)
export const disableInspectionRoute = (id) => request.put(`/api/route/disable/${id}`)
export const getInspectionPointPage = (params) => request.get('/api/point/page', { params })
export const addInspectionPoint = (data) => request.post('/api/point', data)
export const updateInspectionPoint = (data) => request.put('/api/point', data)
export const deleteInspectionPoint = (id) => request.delete(`/api/point/${id}`)
export const lockInspectionPoint = (id) => request.put(`/api/point/lock/${id}`)
export const releaseInspectionPoint = (id) => request.put(`/api/point/release/${id}`)
export const getInspectionTaskPage = (params) => request.get('/api/task/page', { params })
export const addInspectionTask = (data) => request.post('/api/task', data)
export const updateInspectionTask = (data) => request.put('/api/task', data)
export const deleteInspectionTask = (id) => request.delete(`/api/task/${id}`)
export const assignInspectionTask = (id) => request.put(`/api/task/assign/${id}`)
export const startInspectionTask = (id) => request.put(`/api/task/start/${id}`)
export const finishInspectionTask = (id) => request.put(`/api/task/finish/${id}`)
export const getInspectionRecordPage = (params) => request.get('/api/record/page', { params })
export const addInspectionRecord = (data) => request.post('/api/record', data)
export const updateInspectionRecord = (data) => request.put('/api/record', data)
export const deleteInspectionRecord = (id) => request.delete(`/api/record/${id}`)
export const reviewInspectionRecord = (id) => request.put(`/api/record/review/${id}`)
export const rejectInspectionRecord = (id) => request.put(`/api/record/reject/${id}`)
export const getDefectReportPage = (params) => request.get('/api/defect/page', { params })
export const addDefectReport = (data) => request.post('/api/defect', data)
export const updateDefectReport = (data) => request.put('/api/defect', data)
export const deleteDefectReport = (id) => request.delete(`/api/defect/${id}`)
export const confirmDefectReport = (id) => request.put(`/api/defect/confirm/${id}`)
export const closeDefectReport = (id) => request.put(`/api/defect/close/${id}`)
export const getWorkOrderPage = (params) => request.get('/api/workOrder/page', { params })
export const addWorkOrder = (data) => request.post('/api/workOrder', data)
export const updateWorkOrder = (data) => request.put('/api/workOrder', data)
export const deleteWorkOrder = (id) => request.delete(`/api/workOrder/${id}`)
export const acceptWorkOrder = (id) => request.put(`/api/workOrder/accept/${id}`)
export const finishWorkOrder = (id) => request.put(`/api/workOrder/finish/${id}`)
export const getSensorDataPage = (params) => request.get('/api/sensor/page', { params })
export const addSensorData = (data) => request.post('/api/sensor', data)
export const updateSensorData = (data) => request.put('/api/sensor', data)
export const deleteSensorData = (id) => request.delete(`/api/sensor/${id}`)
export const warnSensorData = (id) => request.put(`/api/sensor/warn/${id}`)
export const recoverSensorData = (id) => request.put(`/api/sensor/recover/${id}`)
export const getTwinModelPage = (params) => request.get('/api/model/page', { params })
export const addTwinModel = (data) => request.post('/api/model', data)
export const updateTwinModel = (data) => request.put('/api/model', data)
export const deleteTwinModel = (id) => request.delete(`/api/model/${id}`)
export const publishTwinModel = (id) => request.put(`/api/model/publish/${id}`)
export const offlineTwinModel = (id) => request.put(`/api/model/offline/${id}`)
export const getEnergyMonitorPage = (params) => request.get('/api/energy/page', { params })
export const addEnergyMonitor = (data) => request.post('/api/energy', data)
export const updateEnergyMonitor = (data) => request.put('/api/energy', data)
export const deleteEnergyMonitor = (id) => request.delete(`/api/energy/${id}`)
export const warnEnergyMonitor = (id) => request.put(`/api/energy/warn/${id}`)
export const closeEnergyMonitor = (id) => request.put(`/api/energy/close/${id}`)
export const getMaintenanceSchedulePage = (params) => request.get('/api/schedule/page', { params })
export const addMaintenanceSchedule = (data) => request.post('/api/schedule', data)
export const updateMaintenanceSchedule = (data) => request.put('/api/schedule', data)
export const deleteMaintenanceSchedule = (id) => request.delete(`/api/schedule/${id}`)
export const startMaintenanceSchedule = (id) => request.put(`/api/schedule/start/${id}`)
export const finishMaintenanceSchedule = (id) => request.put(`/api/schedule/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
