import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getServicePackagePage = (params) => request.get('/api/package/page', { params })
export const addServicePackage = (data) => request.post('/api/package', data)
export const updateServicePackage = (data) => request.put('/api/package', data)
export const deleteServicePackage = (id) => request.delete(`/api/package/${id}`)
export const activateServicePackage = (id) => request.put(`/api/package/activate/${id}`)
export const finishServicePackage = (id) => request.put(`/api/package/finish/${id}`)

export const getElderProfilePage = (params) => request.get('/api/elder/page', { params })
export const addElderProfile = (data) => request.post('/api/elder', data)
export const updateElderProfile = (data) => request.put('/api/elder', data)
export const deleteElderProfile = (id) => request.delete(`/api/elder/${id}`)
export const activateElderProfile = (id) => request.put(`/api/elder/activate/${id}`)
export const finishElderProfile = (id) => request.put(`/api/elder/finish/${id}`)

export const getCaregiverProfilePage = (params) => request.get('/api/caregiver/page', { params })
export const addCaregiverProfile = (data) => request.post('/api/caregiver', data)
export const updateCaregiverProfile = (data) => request.put('/api/caregiver', data)
export const deleteCaregiverProfile = (id) => request.delete(`/api/caregiver/${id}`)
export const processCaregiverProfile = (id) => request.put(`/api/caregiver/process/${id}`)
export const finishCaregiverProfile = (id) => request.put(`/api/caregiver/finish/${id}`)

export const getServiceOrderPage = (params) => request.get('/api/order/page', { params })
export const addServiceOrder = (data) => request.post('/api/order', data)
export const updateServiceOrder = (data) => request.put('/api/order', data)
export const deleteServiceOrder = (id) => request.delete(`/api/order/${id}`)
export const submitServiceOrder = (id) => request.put(`/api/order/submit/${id}`)
export const approveServiceOrder = (id) => request.put(`/api/order/approve/${id}`)

export const getCareTeamPage = (params) => request.get('/api/team/page', { params })
export const addCareTeam = (data) => request.post('/api/team', data)
export const updateCareTeam = (data) => request.put('/api/team', data)
export const deleteCareTeam = (id) => request.delete(`/api/team/${id}`)
export const submitCareTeam = (id) => request.put(`/api/team/submit/${id}`)
export const approveCareTeam = (id) => request.put(`/api/team/approve/${id}`)

export const getVisitCheckinPage = (params) => request.get('/api/checkin/page', { params })
export const addVisitCheckin = (data) => request.post('/api/checkin', data)
export const updateVisitCheckin = (data) => request.put('/api/checkin', data)
export const deleteVisitCheckin = (id) => request.delete(`/api/checkin/${id}`)
export const submitVisitCheckin = (id) => request.put(`/api/checkin/submit/${id}`)
export const approveVisitCheckin = (id) => request.put(`/api/checkin/approve/${id}`)

export const getServiceRecordPage = (params) => request.get('/api/record/page', { params })
export const addServiceRecord = (data) => request.post('/api/record', data)
export const updateServiceRecord = (data) => request.put('/api/record', data)
export const deleteServiceRecord = (id) => request.delete(`/api/record/${id}`)
export const processServiceRecord = (id) => request.put(`/api/record/process/${id}`)
export const finishServiceRecord = (id) => request.put(`/api/record/finish/${id}`)

export const getHealthAssessmentPage = (params) => request.get('/api/assessment/page', { params })
export const addHealthAssessment = (data) => request.post('/api/assessment', data)
export const updateHealthAssessment = (data) => request.put('/api/assessment', data)
export const deleteHealthAssessment = (id) => request.delete(`/api/assessment/${id}`)
export const activateHealthAssessment = (id) => request.put(`/api/assessment/activate/${id}`)
export const finishHealthAssessment = (id) => request.put(`/api/assessment/finish/${id}`)

export const getMedicationReminderPage = (params) => request.get('/api/reminder/page', { params })
export const addMedicationReminder = (data) => request.post('/api/reminder', data)
export const updateMedicationReminder = (data) => request.put('/api/reminder', data)
export const deleteMedicationReminder = (id) => request.delete(`/api/reminder/${id}`)
export const activateMedicationReminder = (id) => request.put(`/api/reminder/activate/${id}`)
export const finishMedicationReminder = (id) => request.put(`/api/reminder/finish/${id}`)

export const getFamilyVisitPage = (params) => request.get('/api/family/page', { params })
export const addFamilyVisit = (data) => request.post('/api/family', data)
export const updateFamilyVisit = (data) => request.put('/api/family', data)
export const deleteFamilyVisit = (id) => request.delete(`/api/family/${id}`)
export const activateFamilyVisit = (id) => request.put(`/api/family/activate/${id}`)
export const finishFamilyVisit = (id) => request.put(`/api/family/finish/${id}`)

export const getAlertEventPage = (params) => request.get('/api/alert/page', { params })
export const addAlertEvent = (data) => request.post('/api/alert', data)
export const updateAlertEvent = (data) => request.put('/api/alert', data)
export const deleteAlertEvent = (id) => request.delete(`/api/alert/${id}`)
export const processAlertEvent = (id) => request.put(`/api/alert/process/${id}`)
export const finishAlertEvent = (id) => request.put(`/api/alert/finish/${id}`)

export const getCareNoticePage = (params) => request.get('/api/notice/page', { params })
export const addCareNotice = (data) => request.post('/api/notice', data)
export const updateCareNotice = (data) => request.put('/api/notice', data)
export const deleteCareNotice = (id) => request.delete(`/api/notice/${id}`)
export const processCareNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishCareNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
