import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getDataSubjectPage = (params) => request.get('/api/subject/page', { params })
export const addDataSubject = (data) => request.post('/api/subject', data)
export const updateDataSubject = (data) => request.put('/api/subject', data)
export const deleteDataSubject = (id) => request.delete(`/api/subject/${id}`)
export const verifyDataSubject = (id) => request.put(`/api/subject/verify/${id}`)
export const disableDataSubject = (id) => request.put(`/api/subject/disable/${id}`)
export const getPersonalDataItemPage = (params) => request.get('/api/data-item/page', { params })
export const addPersonalDataItem = (data) => request.post('/api/data-item', data)
export const updatePersonalDataItem = (data) => request.put('/api/data-item', data)
export const deletePersonalDataItem = (id) => request.delete(`/api/data-item/${id}`)
export const getConsentPurposePage = (params) => request.get('/api/purpose/page', { params })
export const addConsentPurpose = (data) => request.post('/api/purpose', data)
export const updateConsentPurpose = (data) => request.put('/api/purpose', data)
export const deleteConsentPurpose = (id) => request.delete(`/api/purpose/${id}`)
export const publishConsentPurpose = (id) => request.put(`/api/purpose/publish/${id}`)
export const archiveConsentPurpose = (id) => request.put(`/api/purpose/archive/${id}`)
export const getConsentPolicyPage = (params) => request.get('/api/policy/page', { params })
export const addConsentPolicy = (data) => request.post('/api/policy', data)
export const updateConsentPolicy = (data) => request.put('/api/policy', data)
export const deleteConsentPolicy = (id) => request.delete(`/api/policy/${id}`)
export const submitConsentPolicy = (id) => request.put(`/api/policy/submit/${id}`)
export const approveConsentPolicy = (id) => request.put(`/api/policy/approve/${id}`)
export const archiveConsentPolicy = (id) => request.put(`/api/policy/archive/${id}`)
export const getAuthorizationRecordPage = (params) => request.get('/api/authorization/page', { params })
export const addAuthorizationRecord = (data) => request.post('/api/authorization', data)
export const updateAuthorizationRecord = (data) => request.put('/api/authorization', data)
export const deleteAuthorizationRecord = (id) => request.delete(`/api/authorization/${id}`)
export const activateAuthorizationRecord = (id) => request.put(`/api/authorization/activate/${id}`)
export const expireAuthorizationRecord = (id) => request.put(`/api/authorization/expire/${id}`)
export const revokeAuthorizationRecord = (id) => request.put(`/api/authorization/revoke/${id}`)
export const getAuthorizationScopePage = (params) => request.get('/api/scope/page', { params })
export const addAuthorizationScope = (data) => request.post('/api/scope', data)
export const updateAuthorizationScope = (data) => request.put('/api/scope', data)
export const deleteAuthorizationScope = (id) => request.delete(`/api/scope/${id}`)
export const getAccessApplicationPage = (params) => request.get('/api/access-application/page', { params })
export const addAccessApplication = (data) => request.post('/api/access-application', data)
export const updateAccessApplication = (data) => request.put('/api/access-application', data)
export const deleteAccessApplication = (id) => request.delete(`/api/access-application/${id}`)
export const submitAccessApplication = (id) => request.put(`/api/access-application/submit/${id}`)
export const approveAccessApplication = (id) => request.put(`/api/access-application/approve/${id}`)
export const rejectAccessApplication = (id) => request.put(`/api/access-application/reject/${id}`)
export const getAccessGrantPage = (params) => request.get('/api/grant/page', { params })
export const addAccessGrant = (data) => request.post('/api/grant', data)
export const updateAccessGrant = (data) => request.put('/api/grant', data)
export const deleteAccessGrant = (id) => request.delete(`/api/grant/${id}`)
export const activateAccessGrant = (id) => request.put(`/api/grant/activate/${id}`)
export const revokeAccessGrant = (id) => request.put(`/api/grant/revoke/${id}`)
export const getAccessLogPage = (params) => request.get('/api/access-log/page', { params })
export const addAccessLog = (data) => request.post('/api/access-log', data)
export const updateAccessLog = (data) => request.put('/api/access-log', data)
export const deleteAccessLog = (id) => request.delete(`/api/access-log/${id}`)
export const getRevocationRequestPage = (params) => request.get('/api/revocation/page', { params })
export const addRevocationRequest = (data) => request.post('/api/revocation', data)
export const updateRevocationRequest = (data) => request.put('/api/revocation', data)
export const deleteRevocationRequest = (id) => request.delete(`/api/revocation/${id}`)
export const approveRevocationRequest = (id) => request.put(`/api/revocation/approve/${id}`)
export const rejectRevocationRequest = (id) => request.put(`/api/revocation/reject/${id}`)
export const finishRevocationRequest = (id) => request.put(`/api/revocation/finish/${id}`)
export const getRiskWarningPage = (params) => request.get('/api/risk-warning/page', { params })
export const addRiskWarning = (data) => request.post('/api/risk-warning', data)
export const updateRiskWarning = (data) => request.put('/api/risk-warning', data)
export const deleteRiskWarning = (id) => request.delete(`/api/risk-warning/${id}`)
export const ackRiskWarning = (id) => request.put(`/api/risk-warning/ack/${id}`)
export const resolveRiskWarning = (id) => request.put(`/api/risk-warning/resolve/${id}`)
export const closeRiskWarning = (id) => request.put(`/api/risk-warning/close/${id}`)
export const getAuditReportPage = (params) => request.get('/api/audit-report/page', { params })
export const addAuditReport = (data) => request.post('/api/audit-report', data)
export const updateAuditReport = (data) => request.put('/api/audit-report', data)
export const deleteAuditReport = (id) => request.delete(`/api/audit-report/${id}`)
export const publishAuditReport = (id) => request.put(`/api/audit-report/publish/${id}`)
export const archiveAuditReport = (id) => request.put(`/api/audit-report/archive/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
