import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getDevopsEnvironmentPage = (params) => request.get('/api/environment/page', { params })
export const addDevopsEnvironment = (data) => request.post('/api/environment', data)
export const updateDevopsEnvironment = (data) => request.put('/api/environment', data)
export const deleteDevopsEnvironment = (id) => request.delete(`/api/environment/${id}`)
export const getApplicationServicePage = (params) => request.get('/api/service/page', { params })
export const addApplicationService = (data) => request.post('/api/service', data)
export const updateApplicationService = (data) => request.put('/api/service', data)
export const deleteApplicationService = (id) => request.delete(`/api/service/${id}`)
export const getDeployPipelinePage = (params) => request.get('/api/pipeline/page', { params })
export const addDeployPipeline = (data) => request.post('/api/pipeline', data)
export const updateDeployPipeline = (data) => request.put('/api/pipeline', data)
export const deleteDeployPipeline = (id) => request.delete(`/api/pipeline/${id}`)
export const getReleasePlanPage = (params) => request.get('/api/release-plan/page', { params })
export const addReleasePlan = (data) => request.post('/api/release-plan', data)
export const updateReleasePlan = (data) => request.put('/api/release-plan', data)
export const deleteReleasePlan = (id) => request.delete(`/api/release-plan/${id}`)
export const publishReleasePlan = (id) => request.put(`/api/release-plan/publish/${id}`)
export const archiveReleasePlan = (id) => request.put(`/api/release-plan/archive/${id}`)
export const getReleaseOrderPage = (params) => request.get('/api/release-order/page', { params })
export const addReleaseOrder = (data) => request.post('/api/release-order', data)
export const updateReleaseOrder = (data) => request.put('/api/release-order', data)
export const deleteReleaseOrder = (id) => request.delete(`/api/release-order/${id}`)
export const submitReleaseOrder = (id) => request.put(`/api/release-order/submit/${id}`)
export const approveReleaseOrder = (id) => request.put(`/api/release-order/approve/${id}`)
export const rejectReleaseOrder = (id) => request.put(`/api/release-order/reject/${id}`)
export const scheduleReleaseOrder = (id) => request.put(`/api/release-order/schedule/${id}`)
export const getApprovalFlowPage = (params) => request.get('/api/approval-flow/page', { params })
export const addApprovalFlow = (data) => request.post('/api/approval-flow', data)
export const updateApprovalFlow = (data) => request.put('/api/approval-flow', data)
export const deleteApprovalFlow = (id) => request.delete(`/api/approval-flow/${id}`)
export const getApprovalRecordPage = (params) => request.get('/api/approval-record/page', { params })
export const addApprovalRecord = (data) => request.post('/api/approval-record', data)
export const updateApprovalRecord = (data) => request.put('/api/approval-record', data)
export const deleteApprovalRecord = (id) => request.delete(`/api/approval-record/${id}`)
export const approveApprovalRecord = (id) => request.put(`/api/approval-record/approve/${id}`)
export const rejectApprovalRecord = (id) => request.put(`/api/approval-record/reject/${id}`)
export const getVersionArtifactPage = (params) => request.get('/api/artifact/page', { params })
export const addVersionArtifact = (data) => request.post('/api/artifact', data)
export const updateVersionArtifact = (data) => request.put('/api/artifact', data)
export const deleteVersionArtifact = (id) => request.delete(`/api/artifact/${id}`)
export const getDeployTaskPage = (params) => request.get('/api/deploy-task/page', { params })
export const addDeployTask = (data) => request.post('/api/deploy-task', data)
export const updateDeployTask = (data) => request.put('/api/deploy-task', data)
export const deleteDeployTask = (id) => request.delete(`/api/deploy-task/${id}`)
export const startDeployTask = (id) => request.put(`/api/deploy-task/start/${id}`)
export const finishDeployTask = (id) => request.put(`/api/deploy-task/finish/${id}`)
export const failDeployTask = (id) => request.put(`/api/deploy-task/fail/${id}`)
export const getRollbackPlanPage = (params) => request.get('/api/rollback-plan/page', { params })
export const addRollbackPlan = (data) => request.post('/api/rollback-plan', data)
export const updateRollbackPlan = (data) => request.put('/api/rollback-plan', data)
export const deleteRollbackPlan = (id) => request.delete(`/api/rollback-plan/${id}`)
export const activateRollbackPlan = (id) => request.put(`/api/rollback-plan/activate/${id}`)
export const archiveRollbackPlan = (id) => request.put(`/api/rollback-plan/archive/${id}`)
export const getRollbackRecordPage = (params) => request.get('/api/rollback-record/page', { params })
export const addRollbackRecord = (data) => request.post('/api/rollback-record', data)
export const updateRollbackRecord = (data) => request.put('/api/rollback-record', data)
export const deleteRollbackRecord = (id) => request.delete(`/api/rollback-record/${id}`)
export const startRollbackRecord = (id) => request.put(`/api/rollback-record/start/${id}`)
export const finishRollbackRecord = (id) => request.put(`/api/rollback-record/finish/${id}`)
export const failRollbackRecord = (id) => request.put(`/api/rollback-record/fail/${id}`)
export const getChangeChecklistPage = (params) => request.get('/api/checklist/page', { params })
export const addChangeChecklist = (data) => request.post('/api/checklist', data)
export const updateChangeChecklist = (data) => request.put('/api/checklist', data)
export const deleteChangeChecklist = (id) => request.delete(`/api/checklist/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
