import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getOperatingRoomPage = (params) => request.get('/api/room/page', { params })
export const addOperatingRoom = (data) => request.post('/api/room', data)
export const updateOperatingRoom = (data) => request.put('/api/room', data)
export const deleteOperatingRoom = (id) => request.delete(`/api/room/${id}`)
export const processOperatingRoom = (id) => request.put(`/api/room/process/${id}`)
export const finishOperatingRoom = (id) => request.put(`/api/room/finish/${id}`)

export const getInstrumentPackPage = (params) => request.get('/api/pack/page', { params })
export const addInstrumentPack = (data) => request.post('/api/pack', data)
export const updateInstrumentPack = (data) => request.put('/api/pack', data)
export const deleteInstrumentPack = (id) => request.delete(`/api/pack/${id}`)
export const processInstrumentPack = (id) => request.put(`/api/pack/process/${id}`)
export const finishInstrumentPack = (id) => request.put(`/api/pack/finish/${id}`)

export const getInstrumentItemPage = (params) => request.get('/api/item/page', { params })
export const addInstrumentItem = (data) => request.post('/api/item', data)
export const updateInstrumentItem = (data) => request.put('/api/item', data)
export const deleteInstrumentItem = (id) => request.delete(`/api/item/${id}`)
export const processInstrumentItem = (id) => request.put(`/api/item/process/${id}`)
export const finishInstrumentItem = (id) => request.put(`/api/item/finish/${id}`)

export const getPackTracePage = (params) => request.get('/api/trace/page', { params })
export const addPackTrace = (data) => request.post('/api/trace', data)
export const updatePackTrace = (data) => request.put('/api/trace', data)
export const deletePackTrace = (id) => request.delete(`/api/trace/${id}`)
export const processPackTrace = (id) => request.put(`/api/trace/process/${id}`)
export const finishPackTrace = (id) => request.put(`/api/trace/finish/${id}`)

export const getSterilizationBatchPage = (params) => request.get('/api/batch/page', { params })
export const addSterilizationBatch = (data) => request.post('/api/batch', data)
export const updateSterilizationBatch = (data) => request.put('/api/batch', data)
export const deleteSterilizationBatch = (id) => request.delete(`/api/batch/${id}`)
export const processSterilizationBatch = (id) => request.put(`/api/batch/process/${id}`)
export const finishSterilizationBatch = (id) => request.put(`/api/batch/finish/${id}`)

export const getSterilizationRecordPage = (params) => request.get('/api/sterilization/page', { params })
export const addSterilizationRecord = (data) => request.post('/api/sterilization', data)
export const updateSterilizationRecord = (data) => request.put('/api/sterilization', data)
export const deleteSterilizationRecord = (id) => request.delete(`/api/sterilization/${id}`)
export const processSterilizationRecord = (id) => request.put(`/api/sterilization/process/${id}`)
export const finishSterilizationRecord = (id) => request.put(`/api/sterilization/finish/${id}`)

export const getReleaseApprovalPage = (params) => request.get('/api/release/page', { params })
export const addReleaseApproval = (data) => request.post('/api/release', data)
export const updateReleaseApproval = (data) => request.put('/api/release', data)
export const deleteReleaseApproval = (id) => request.delete(`/api/release/${id}`)
export const processReleaseApproval = (id) => request.put(`/api/release/process/${id}`)
export const finishReleaseApproval = (id) => request.put(`/api/release/finish/${id}`)

export const getSurgeryUsePage = (params) => request.get('/api/surgery/page', { params })
export const addSurgeryUse = (data) => request.post('/api/surgery', data)
export const updateSurgeryUse = (data) => request.put('/api/surgery', data)
export const deleteSurgeryUse = (id) => request.delete(`/api/surgery/${id}`)
export const processSurgeryUse = (id) => request.put(`/api/surgery/process/${id}`)
export const finishSurgeryUse = (id) => request.put(`/api/surgery/finish/${id}`)

export const getReturnCheckinPage = (params) => request.get('/api/return/page', { params })
export const addReturnCheckin = (data) => request.post('/api/return', data)
export const updateReturnCheckin = (data) => request.put('/api/return', data)
export const deleteReturnCheckin = (id) => request.delete(`/api/return/${id}`)
export const processReturnCheckin = (id) => request.put(`/api/return/process/${id}`)
export const finishReturnCheckin = (id) => request.put(`/api/return/finish/${id}`)

export const getDefectReportPage = (params) => request.get('/api/defect/page', { params })
export const addDefectReport = (data) => request.post('/api/defect', data)
export const updateDefectReport = (data) => request.put('/api/defect', data)
export const deleteDefectReport = (id) => request.delete(`/api/defect/${id}`)
export const processDefectReport = (id) => request.put(`/api/defect/process/${id}`)
export const finishDefectReport = (id) => request.put(`/api/defect/finish/${id}`)

export const getRecallEventPage = (params) => request.get('/api/recall/page', { params })
export const addRecallEvent = (data) => request.post('/api/recall', data)
export const updateRecallEvent = (data) => request.put('/api/recall', data)
export const deleteRecallEvent = (id) => request.delete(`/api/recall/${id}`)
export const processRecallEvent = (id) => request.put(`/api/recall/process/${id}`)
export const finishRecallEvent = (id) => request.put(`/api/recall/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
