import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getWarehouseNodePage = (params) => request.get('/api/warehouse/page', { params })
export const addWarehouseNode = (data) => request.post('/api/warehouse', data)
export const updateWarehouseNode = (data) => request.put('/api/warehouse', data)
export const deleteWarehouseNode = (id) => request.delete(`/api/warehouse/${id}`)
export const enableWarehouseNode = (id) => request.put(`/api/warehouse/enable/${id}`)
export const disableWarehouseNode = (id) => request.put(`/api/warehouse/disable/${id}`)
export const getCarrierCompanyPage = (params) => request.get('/api/carrier/page', { params })
export const addCarrierCompany = (data) => request.post('/api/carrier', data)
export const updateCarrierCompany = (data) => request.put('/api/carrier', data)
export const deleteCarrierCompany = (id) => request.delete(`/api/carrier/${id}`)
export const approveCarrierCompany = (id) => request.put(`/api/carrier/approve/${id}`)
export const suspendCarrierCompany = (id) => request.put(`/api/carrier/suspend/${id}`)
export const getColdDevicePage = (params) => request.get('/api/device/page', { params })
export const addColdDevice = (data) => request.post('/api/device', data)
export const updateColdDevice = (data) => request.put('/api/device', data)
export const deleteColdDevice = (id) => request.delete(`/api/device/${id}`)
export const onlineColdDevice = (id) => request.put(`/api/device/online/${id}`)
export const offlineColdDevice = (id) => request.put(`/api/device/offline/${id}`)
export const repairColdDevice = (id) => request.put(`/api/device/repair/${id}`)
export const getProductCargoPage = (params) => request.get('/api/cargo/page', { params })
export const addProductCargo = (data) => request.post('/api/cargo', data)
export const updateProductCargo = (data) => request.put('/api/cargo', data)
export const deleteProductCargo = (id) => request.delete(`/api/cargo/${id}`)
export const shipProductCargo = (id) => request.put(`/api/cargo/ship/${id}`)
export const arriveProductCargo = (id) => request.put(`/api/cargo/arrive/${id}`)
export const getTransportOrderPage = (params) => request.get('/api/order/page', { params })
export const addTransportOrder = (data) => request.post('/api/order', data)
export const updateTransportOrder = (data) => request.put('/api/order', data)
export const deleteTransportOrder = (id) => request.delete(`/api/order/${id}`)
export const dispatchTransportOrder = (id) => request.put(`/api/order/dispatch/${id}`)
export const startTransportOrder = (id) => request.put(`/api/order/start/${id}`)
export const finishTransportOrder = (id) => request.put(`/api/order/finish/${id}`)
export const getTemperatureRecordPage = (params) => request.get('/api/temperature/page', { params })
export const addTemperatureRecord = (data) => request.post('/api/temperature', data)
export const updateTemperatureRecord = (data) => request.put('/api/temperature', data)
export const deleteTemperatureRecord = (id) => request.delete(`/api/temperature/${id}`)
export const normalTemperatureRecord = (id) => request.put(`/api/temperature/normal/${id}`)
export const warnTemperatureRecord = (id) => request.put(`/api/temperature/warn/${id}`)
export const alarmTemperatureRecord = (id) => request.put(`/api/temperature/alarm/${id}`)
export const getGpsTrackPage = (params) => request.get('/api/track/page', { params })
export const addGpsTrack = (data) => request.post('/api/track', data)
export const updateGpsTrack = (data) => request.put('/api/track', data)
export const deleteGpsTrack = (id) => request.delete(`/api/track/${id}`)
export const getAlertRulePage = (params) => request.get('/api/rule/page', { params })
export const addAlertRule = (data) => request.post('/api/rule', data)
export const updateAlertRule = (data) => request.put('/api/rule', data)
export const deleteAlertRule = (id) => request.delete(`/api/rule/${id}`)
export const enableAlertRule = (id) => request.put(`/api/rule/enable/${id}`)
export const disableAlertRule = (id) => request.put(`/api/rule/disable/${id}`)
export const getExceptionAlertPage = (params) => request.get('/api/alert/page', { params })
export const addExceptionAlert = (data) => request.post('/api/alert', data)
export const updateExceptionAlert = (data) => request.put('/api/alert', data)
export const deleteExceptionAlert = (id) => request.delete(`/api/alert/${id}`)
export const ackExceptionAlert = (id) => request.put(`/api/alert/ack/${id}`)
export const resolveExceptionAlert = (id) => request.put(`/api/alert/resolve/${id}`)
export const closeExceptionAlert = (id) => request.put(`/api/alert/close/${id}`)
export const getDisposalTaskPage = (params) => request.get('/api/task/page', { params })
export const addDisposalTask = (data) => request.post('/api/task', data)
export const updateDisposalTask = (data) => request.put('/api/task', data)
export const deleteDisposalTask = (id) => request.delete(`/api/task/${id}`)
export const startDisposalTask = (id) => request.put(`/api/task/start/${id}`)
export const finishDisposalTask = (id) => request.put(`/api/task/finish/${id}`)
export const closeDisposalTask = (id) => request.put(`/api/task/close/${id}`)
export const getResponsibilityTracePage = (params) => request.get('/api/responsibility/page', { params })
export const addResponsibilityTrace = (data) => request.post('/api/responsibility', data)
export const updateResponsibilityTrace = (data) => request.put('/api/responsibility', data)
export const deleteResponsibilityTrace = (id) => request.delete(`/api/responsibility/${id}`)
export const reviewResponsibilityTrace = (id) => request.put(`/api/responsibility/review/${id}`)
export const confirmResponsibilityTrace = (id) => request.put(`/api/responsibility/confirm/${id}`)
export const closeResponsibilityTrace = (id) => request.put(`/api/responsibility/close/${id}`)
export const getMaintenanceRecordPage = (params) => request.get('/api/maintenance/page', { params })
export const addMaintenanceRecord = (data) => request.post('/api/maintenance', data)
export const updateMaintenanceRecord = (data) => request.put('/api/maintenance', data)
export const deleteMaintenanceRecord = (id) => request.delete(`/api/maintenance/${id}`)
export const submitMaintenanceRecord = (id) => request.put(`/api/maintenance/submit/${id}`)
export const finishMaintenanceRecord = (id) => request.put(`/api/maintenance/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
