import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getIncubationProjectPage = (params) => request.get('/api/project/page', { params })
export const addIncubationProject = (data) => request.post('/api/project', data)
export const updateIncubationProject = (data) => request.put('/api/project', data)
export const deleteIncubationProject = (id) => request.delete(`/api/project/${id}`)
export const activateIncubationProject = (id) => request.put(`/api/project/activate/${id}`)
export const finishIncubationProject = (id) => request.put(`/api/project/finish/${id}`)
export const getMentorProfilePage = (params) => request.get('/api/mentor/page', { params })
export const addMentorProfile = (data) => request.post('/api/mentor', data)
export const updateMentorProfile = (data) => request.put('/api/mentor', data)
export const deleteMentorProfile = (id) => request.delete(`/api/mentor/${id}`)
export const activateMentorProfile = (id) => request.put(`/api/mentor/activate/${id}`)
export const finishMentorProfile = (id) => request.put(`/api/mentor/finish/${id}`)
export const getTeamProfilePage = (params) => request.get('/api/team/page', { params })
export const addTeamProfile = (data) => request.post('/api/team', data)
export const updateTeamProfile = (data) => request.put('/api/team', data)
export const deleteTeamProfile = (id) => request.delete(`/api/team/${id}`)
export const activateTeamProfile = (id) => request.put(`/api/team/activate/${id}`)
export const finishTeamProfile = (id) => request.put(`/api/team/finish/${id}`)
export const getProjectApplicationPage = (params) => request.get('/api/application/page', { params })
export const addProjectApplication = (data) => request.post('/api/application', data)
export const updateProjectApplication = (data) => request.put('/api/application', data)
export const deleteProjectApplication = (id) => request.delete(`/api/application/${id}`)
export const processProjectApplication = (id) => request.put(`/api/application/process/${id}`)
export const finishProjectApplication = (id) => request.put(`/api/application/finish/${id}`)
export const getIncubationPlanPage = (params) => request.get('/api/plan/page', { params })
export const addIncubationPlan = (data) => request.post('/api/plan', data)
export const updateIncubationPlan = (data) => request.put('/api/plan', data)
export const deleteIncubationPlan = (id) => request.delete(`/api/plan/${id}`)
export const submitIncubationPlan = (id) => request.put(`/api/plan/submit/${id}`)
export const approveIncubationPlan = (id) => request.put(`/api/plan/approve/${id}`)
export const getMentorCoachingPage = (params) => request.get('/api/coaching/page', { params })
export const addMentorCoaching = (data) => request.post('/api/coaching', data)
export const updateMentorCoaching = (data) => request.put('/api/coaching', data)
export const deleteMentorCoaching = (id) => request.delete(`/api/coaching/${id}`)
export const submitMentorCoaching = (id) => request.put(`/api/coaching/submit/${id}`)
export const approveMentorCoaching = (id) => request.put(`/api/coaching/approve/${id}`)
export const getRoadshowEventPage = (params) => request.get('/api/roadshow/page', { params })
export const addRoadshowEvent = (data) => request.post('/api/roadshow', data)
export const updateRoadshowEvent = (data) => request.put('/api/roadshow', data)
export const deleteRoadshowEvent = (id) => request.delete(`/api/roadshow/${id}`)
export const processRoadshowEvent = (id) => request.put(`/api/roadshow/process/${id}`)
export const finishRoadshowEvent = (id) => request.put(`/api/roadshow/finish/${id}`)
export const getRoadshowScorePage = (params) => request.get('/api/score/page', { params })
export const addRoadshowScore = (data) => request.post('/api/score', data)
export const updateRoadshowScore = (data) => request.put('/api/score', data)
export const deleteRoadshowScore = (id) => request.delete(`/api/score/${id}`)
export const submitRoadshowScore = (id) => request.put(`/api/score/submit/${id}`)
export const approveRoadshowScore = (id) => request.put(`/api/score/approve/${id}`)
export const getFundingRecordPage = (params) => request.get('/api/funding/page', { params })
export const addFundingRecord = (data) => request.post('/api/funding', data)
export const updateFundingRecord = (data) => request.put('/api/funding', data)
export const deleteFundingRecord = (id) => request.delete(`/api/funding/${id}`)
export const submitFundingRecord = (id) => request.put(`/api/funding/submit/${id}`)
export const approveFundingRecord = (id) => request.put(`/api/funding/approve/${id}`)
export const getMilestoneTaskPage = (params) => request.get('/api/milestone/page', { params })
export const addMilestoneTask = (data) => request.post('/api/milestone', data)
export const updateMilestoneTask = (data) => request.put('/api/milestone', data)
export const deleteMilestoneTask = (id) => request.delete(`/api/milestone/${id}`)
export const processMilestoneTask = (id) => request.put(`/api/milestone/process/${id}`)
export const finishMilestoneTask = (id) => request.put(`/api/milestone/finish/${id}`)
export const getAchievementShowcasePage = (params) => request.get('/api/achievement/page', { params })
export const addAchievementShowcase = (data) => request.post('/api/achievement', data)
export const updateAchievementShowcase = (data) => request.put('/api/achievement', data)
export const deleteAchievementShowcase = (id) => request.delete(`/api/achievement/${id}`)
export const activateAchievementShowcase = (id) => request.put(`/api/achievement/activate/${id}`)
export const finishAchievementShowcase = (id) => request.put(`/api/achievement/finish/${id}`)
export const getIncubationNoticePage = (params) => request.get('/api/notice/page', { params })
export const addIncubationNotice = (data) => request.post('/api/notice', data)
export const updateIncubationNotice = (data) => request.put('/api/notice', data)
export const deleteIncubationNotice = (id) => request.delete(`/api/notice/${id}`)
export const processIncubationNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishIncubationNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)


