import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getDriftShelfPage = (params) => request.get('/api/shelf/page', { params })
export const addDriftShelf = (data) => request.post('/api/shelf', data)
export const updateDriftShelf = (data) => request.put('/api/shelf', data)
export const deleteDriftShelf = (id) => request.delete(`/api/shelf/${id}`)
export const processDriftShelf = (id) => request.put(`/api/shelf/process/${id}`)
export const finishDriftShelf = (id) => request.put(`/api/shelf/finish/${id}`)

export const getBookProfilePage = (params) => request.get('/api/book/page', { params })
export const addBookProfile = (data) => request.post('/api/book', data)
export const updateBookProfile = (data) => request.put('/api/book', data)
export const deleteBookProfile = (id) => request.delete(`/api/book/${id}`)
export const processBookProfile = (id) => request.put(`/api/book/process/${id}`)
export const finishBookProfile = (id) => request.put(`/api/book/finish/${id}`)

export const getReaderProfilePage = (params) => request.get('/api/reader/page', { params })
export const addReaderProfile = (data) => request.post('/api/reader', data)
export const updateReaderProfile = (data) => request.put('/api/reader', data)
export const deleteReaderProfile = (id) => request.delete(`/api/reader/${id}`)
export const processReaderProfile = (id) => request.put(`/api/reader/process/${id}`)
export const finishReaderProfile = (id) => request.put(`/api/reader/finish/${id}`)

export const getBookDonationPage = (params) => request.get('/api/donation/page', { params })
export const addBookDonation = (data) => request.post('/api/donation', data)
export const updateBookDonation = (data) => request.put('/api/donation', data)
export const deleteBookDonation = (id) => request.delete(`/api/donation/${id}`)
export const processBookDonation = (id) => request.put(`/api/donation/process/${id}`)
export const finishBookDonation = (id) => request.put(`/api/donation/finish/${id}`)

export const getBorrowRecordPage = (params) => request.get('/api/borrow/page', { params })
export const addBorrowRecord = (data) => request.post('/api/borrow', data)
export const updateBorrowRecord = (data) => request.put('/api/borrow', data)
export const deleteBorrowRecord = (id) => request.delete(`/api/borrow/${id}`)
export const processBorrowRecord = (id) => request.put(`/api/borrow/process/${id}`)
export const finishBorrowRecord = (id) => request.put(`/api/borrow/finish/${id}`)

export const getReturnExchangePage = (params) => request.get('/api/return/page', { params })
export const addReturnExchange = (data) => request.post('/api/return', data)
export const updateReturnExchange = (data) => request.put('/api/return', data)
export const deleteReturnExchange = (id) => request.delete(`/api/return/${id}`)
export const processReturnExchange = (id) => request.put(`/api/return/process/${id}`)
export const finishReturnExchange = (id) => request.put(`/api/return/finish/${id}`)

export const getReadingCheckinPage = (params) => request.get('/api/checkin/page', { params })
export const addReadingCheckin = (data) => request.post('/api/checkin', data)
export const updateReadingCheckin = (data) => request.put('/api/checkin', data)
export const deleteReadingCheckin = (id) => request.delete(`/api/checkin/${id}`)
export const processReadingCheckin = (id) => request.put(`/api/checkin/process/${id}`)
export const finishReadingCheckin = (id) => request.put(`/api/checkin/finish/${id}`)

export const getReadingNotePage = (params) => request.get('/api/note/page', { params })
export const addReadingNote = (data) => request.post('/api/note', data)
export const updateReadingNote = (data) => request.put('/api/note', data)
export const deleteReadingNote = (id) => request.delete(`/api/note/${id}`)
export const processReadingNote = (id) => request.put(`/api/note/process/${id}`)
export const finishReadingNote = (id) => request.put(`/api/note/finish/${id}`)

export const getPointsMedalPage = (params) => request.get('/api/medal/page', { params })
export const addPointsMedal = (data) => request.post('/api/medal', data)
export const updatePointsMedal = (data) => request.put('/api/medal', data)
export const deletePointsMedal = (id) => request.delete(`/api/medal/${id}`)
export const processPointsMedal = (id) => request.put(`/api/medal/process/${id}`)
export const finishPointsMedal = (id) => request.put(`/api/medal/finish/${id}`)

export const getReadingActivityPage = (params) => request.get('/api/activity/page', { params })
export const addReadingActivity = (data) => request.post('/api/activity', data)
export const updateReadingActivity = (data) => request.put('/api/activity', data)
export const deleteReadingActivity = (id) => request.delete(`/api/activity/${id}`)
export const processReadingActivity = (id) => request.put(`/api/activity/process/${id}`)
export const finishReadingActivity = (id) => request.put(`/api/activity/finish/${id}`)

export const getMessageNoticePage = (params) => request.get('/api/notice/page', { params })
export const addMessageNotice = (data) => request.post('/api/notice', data)
export const updateMessageNotice = (data) => request.put('/api/notice', data)
export const deleteMessageNotice = (id) => request.delete(`/api/notice/${id}`)
export const processMessageNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishMessageNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
