server:
  port: 8069

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teacher_eval_069?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  sql:
    init:
      mode: never
      encoding: UTF-8
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 500ms

app:
  redis:
    enabled: true
  mybatis-plus:
    db-type: mysql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
