import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getStoreProfilePage = (params) => request.get('/api/store/page', { params })
export const addStoreProfile = (data) => request.post('/api/store', data)
export const updateStoreProfile = (data) => request.put('/api/store', data)
export const deleteStoreProfile = (id) => request.delete(`/api/store/${id}`)
export const processStoreProfile = (id) => request.put(`/api/store/process/${id}`)
export const finishStoreProfile = (id) => request.put(`/api/store/finish/${id}`)

export const getSupplierProfilePage = (params) => request.get('/api/supplier/page', { params })
export const addSupplierProfile = (data) => request.post('/api/supplier', data)
export const updateSupplierProfile = (data) => request.put('/api/supplier', data)
export const deleteSupplierProfile = (id) => request.delete(`/api/supplier/${id}`)
export const processSupplierProfile = (id) => request.put(`/api/supplier/process/${id}`)
export const finishSupplierProfile = (id) => request.put(`/api/supplier/finish/${id}`)

export const getFreshCategoryPage = (params) => request.get('/api/category/page', { params })
export const addFreshCategory = (data) => request.post('/api/category', data)
export const updateFreshCategory = (data) => request.put('/api/category', data)
export const deleteFreshCategory = (id) => request.delete(`/api/category/${id}`)
export const processFreshCategory = (id) => request.put(`/api/category/process/${id}`)
export const finishFreshCategory = (id) => request.put(`/api/category/finish/${id}`)

export const getProductBatchPage = (params) => request.get('/api/batch/page', { params })
export const addProductBatch = (data) => request.post('/api/batch', data)
export const updateProductBatch = (data) => request.put('/api/batch', data)
export const deleteProductBatch = (id) => request.delete(`/api/batch/${id}`)
export const processProductBatch = (id) => request.put(`/api/batch/process/${id}`)
export const finishProductBatch = (id) => request.put(`/api/batch/finish/${id}`)

export const getShelfLifeRulePage = (params) => request.get('/api/rule/page', { params })
export const addShelfLifeRule = (data) => request.post('/api/rule', data)
export const updateShelfLifeRule = (data) => request.put('/api/rule', data)
export const deleteShelfLifeRule = (id) => request.delete(`/api/rule/${id}`)
export const processShelfLifeRule = (id) => request.put(`/api/rule/process/${id}`)
export const finishShelfLifeRule = (id) => request.put(`/api/rule/finish/${id}`)

export const getExpiryWarningPage = (params) => request.get('/api/warning/page', { params })
export const addExpiryWarning = (data) => request.post('/api/warning', data)
export const updateExpiryWarning = (data) => request.put('/api/warning', data)
export const deleteExpiryWarning = (id) => request.delete(`/api/warning/${id}`)
export const processExpiryWarning = (id) => request.put(`/api/warning/process/${id}`)
export const finishExpiryWarning = (id) => request.put(`/api/warning/finish/${id}`)

export const getPromotionStrategyPage = (params) => request.get('/api/promotion/page', { params })
export const addPromotionStrategy = (data) => request.post('/api/promotion', data)
export const updatePromotionStrategy = (data) => request.put('/api/promotion', data)
export const deletePromotionStrategy = (id) => request.delete(`/api/promotion/${id}`)
export const processPromotionStrategy = (id) => request.put(`/api/promotion/process/${id}`)
export const finishPromotionStrategy = (id) => request.put(`/api/promotion/finish/${id}`)

export const getDiscountExecutionPage = (params) => request.get('/api/discount/page', { params })
export const addDiscountExecution = (data) => request.post('/api/discount', data)
export const updateDiscountExecution = (data) => request.put('/api/discount', data)
export const deleteDiscountExecution = (id) => request.delete(`/api/discount/${id}`)
export const processDiscountExecution = (id) => request.put(`/api/discount/process/${id}`)
export const finishDiscountExecution = (id) => request.put(`/api/discount/finish/${id}`)

export const getLossReportPage = (params) => request.get('/api/loss/page', { params })
export const addLossReport = (data) => request.post('/api/loss', data)
export const updateLossReport = (data) => request.put('/api/loss', data)
export const deleteLossReport = (id) => request.delete(`/api/loss/${id}`)
export const processLossReport = (id) => request.put(`/api/loss/process/${id}`)
export const finishLossReport = (id) => request.put(`/api/loss/finish/${id}`)

export const getInventoryTurnoverPage = (params) => request.get('/api/turnover/page', { params })
export const addInventoryTurnover = (data) => request.post('/api/turnover', data)
export const updateInventoryTurnover = (data) => request.put('/api/turnover', data)
export const deleteInventoryTurnover = (id) => request.delete(`/api/turnover/${id}`)
export const processInventoryTurnover = (id) => request.put(`/api/turnover/process/${id}`)
export const finishInventoryTurnover = (id) => request.put(`/api/turnover/finish/${id}`)

export const getStoreAnalysisPage = (params) => request.get('/api/analysis/page', { params })
export const addStoreAnalysis = (data) => request.post('/api/analysis', data)
export const updateStoreAnalysis = (data) => request.put('/api/analysis', data)
export const deleteStoreAnalysis = (id) => request.delete(`/api/analysis/${id}`)
export const processStoreAnalysis = (id) => request.put(`/api/analysis/process/${id}`)
export const finishStoreAnalysis = (id) => request.put(`/api/analysis/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
