server:
  port: 8012

spring:
  application:
    name: collab-board
  
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/collab_board?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 5000ms
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

file:
  upload:
    path: D:/collab-board-files/
    attachment-path: ${file.upload.path}attachments/
    avatar-path: ${file.upload.path}avatars/
    cover-path: ${file.upload.path}covers/
    export-path: ${file.upload.path}exports/

jwt:
  secret: collab-board-platform-jwt-secret-key-for-token-generation-and-validation-2025
  expiration: 86400000

websocket:
  path: /ws/collab
  allowed-origins: http://localhost:5173,http://localhost:5174

