import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getToiletSitePage = (params) => request.get('/api/site/page', { params })
export const addToiletSite = (data) => request.post('/api/site', data)
export const updateToiletSite = (data) => request.put('/api/site', data)
export const deleteToiletSite = (id) => request.delete(`/api/site/${id}`)
export const processToiletSite = (id) => request.put(`/api/site/process/${id}`)
export const finishToiletSite = (id) => request.put(`/api/site/finish/${id}`)

export const getCleaningRoutePage = (params) => request.get('/api/route/page', { params })
export const addCleaningRoute = (data) => request.post('/api/route', data)
export const updateCleaningRoute = (data) => request.put('/api/route', data)
export const deleteCleaningRoute = (id) => request.delete(`/api/route/${id}`)
export const processCleaningRoute = (id) => request.put(`/api/route/process/${id}`)
export const finishCleaningRoute = (id) => request.put(`/api/route/finish/${id}`)

export const getCleaningTaskPage = (params) => request.get('/api/task/page', { params })
export const addCleaningTask = (data) => request.post('/api/task', data)
export const updateCleaningTask = (data) => request.put('/api/task', data)
export const deleteCleaningTask = (id) => request.delete(`/api/task/${id}`)
export const processCleaningTask = (id) => request.put(`/api/task/process/${id}`)
export const finishCleaningTask = (id) => request.put(`/api/task/finish/${id}`)

export const getCleaningRecordPage = (params) => request.get('/api/record/page', { params })
export const addCleaningRecord = (data) => request.post('/api/record', data)
export const updateCleaningRecord = (data) => request.put('/api/record', data)
export const deleteCleaningRecord = (id) => request.delete(`/api/record/${id}`)
export const processCleaningRecord = (id) => request.put(`/api/record/process/${id}`)
export const finishCleaningRecord = (id) => request.put(`/api/record/finish/${id}`)

export const getInspectionPlanPage = (params) => request.get('/api/plan/page', { params })
export const addInspectionPlan = (data) => request.post('/api/plan', data)
export const updateInspectionPlan = (data) => request.put('/api/plan', data)
export const deleteInspectionPlan = (id) => request.delete(`/api/plan/${id}`)
export const processInspectionPlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishInspectionPlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getInspectionRecordPage = (params) => request.get('/api/inspection/page', { params })
export const addInspectionRecord = (data) => request.post('/api/inspection', data)
export const updateInspectionRecord = (data) => request.put('/api/inspection', data)
export const deleteInspectionRecord = (id) => request.delete(`/api/inspection/${id}`)
export const processInspectionRecord = (id) => request.put(`/api/inspection/process/${id}`)
export const finishInspectionRecord = (id) => request.put(`/api/inspection/finish/${id}`)

export const getConsumableStockPage = (params) => request.get('/api/stock/page', { params })
export const addConsumableStock = (data) => request.post('/api/stock', data)
export const updateConsumableStock = (data) => request.put('/api/stock', data)
export const deleteConsumableStock = (id) => request.delete(`/api/stock/${id}`)
export const processConsumableStock = (id) => request.put(`/api/stock/process/${id}`)
export const finishConsumableStock = (id) => request.put(`/api/stock/finish/${id}`)

export const getSupplyRequestPage = (params) => request.get('/api/request/page', { params })
export const addSupplyRequest = (data) => request.post('/api/request', data)
export const updateSupplyRequest = (data) => request.put('/api/request', data)
export const deleteSupplyRequest = (id) => request.delete(`/api/request/${id}`)
export const processSupplyRequest = (id) => request.put(`/api/request/process/${id}`)
export const finishSupplyRequest = (id) => request.put(`/api/request/finish/${id}`)

export const getSupplyDispatchPage = (params) => request.get('/api/dispatch/page', { params })
export const addSupplyDispatch = (data) => request.post('/api/dispatch', data)
export const updateSupplyDispatch = (data) => request.put('/api/dispatch', data)
export const deleteSupplyDispatch = (id) => request.delete(`/api/dispatch/${id}`)
export const processSupplyDispatch = (id) => request.put(`/api/dispatch/process/${id}`)
export const finishSupplyDispatch = (id) => request.put(`/api/dispatch/finish/${id}`)

export const getComplaintReportPage = (params) => request.get('/api/complaint/page', { params })
export const addComplaintReport = (data) => request.post('/api/complaint', data)
export const updateComplaintReport = (data) => request.put('/api/complaint', data)
export const deleteComplaintReport = (id) => request.delete(`/api/complaint/${id}`)
export const processComplaintReport = (id) => request.put(`/api/complaint/process/${id}`)
export const finishComplaintReport = (id) => request.put(`/api/complaint/finish/${id}`)

export const getIssueRectificationPage = (params) => request.get('/api/rectification/page', { params })
export const addIssueRectification = (data) => request.post('/api/rectification', data)
export const updateIssueRectification = (data) => request.put('/api/rectification', data)
export const deleteIssueRectification = (id) => request.delete(`/api/rectification/${id}`)
export const processIssueRectification = (id) => request.put(`/api/rectification/process/${id}`)
export const finishIssueRectification = (id) => request.put(`/api/rectification/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
