import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getTeachingClassPage = (params) => request.get('/api/teaching/page', { params })
export const addTeachingClass = (data) => request.post('/api/teaching', data)
export const updateTeachingClass = (data) => request.put('/api/teaching', data)
export const deleteTeachingClass = (id) => request.delete(`/api/teaching/${id}`)
export const processTeachingClass = (id) => request.put(`/api/teaching/process/${id}`)
export const finishTeachingClass = (id) => request.put(`/api/teaching/finish/${id}`)

export const getStudentProfilePage = (params) => request.get('/api/student/page', { params })
export const addStudentProfile = (data) => request.post('/api/student', data)
export const updateStudentProfile = (data) => request.put('/api/student', data)
export const deleteStudentProfile = (id) => request.delete(`/api/student/${id}`)
export const processStudentProfile = (id) => request.put(`/api/student/process/${id}`)
export const finishStudentProfile = (id) => request.put(`/api/student/finish/${id}`)

export const getTeacherProfilePage = (params) => request.get('/api/teacher/page', { params })
export const addTeacherProfile = (data) => request.post('/api/teacher', data)
export const updateTeacherProfile = (data) => request.put('/api/teacher', data)
export const deleteTeacherProfile = (id) => request.delete(`/api/teacher/${id}`)
export const processTeacherProfile = (id) => request.put(`/api/teacher/process/${id}`)
export const finishTeacherProfile = (id) => request.put(`/api/teacher/finish/${id}`)

export const getCourseSchedulePage = (params) => request.get('/api/schedule/page', { params })
export const addCourseSchedule = (data) => request.post('/api/schedule', data)
export const updateCourseSchedule = (data) => request.put('/api/schedule', data)
export const deleteCourseSchedule = (id) => request.delete(`/api/schedule/${id}`)
export const processCourseSchedule = (id) => request.put(`/api/schedule/process/${id}`)
export const finishCourseSchedule = (id) => request.put(`/api/schedule/finish/${id}`)

export const getAttendanceRecordPage = (params) => request.get('/api/attendance/page', { params })
export const addAttendanceRecord = (data) => request.post('/api/attendance', data)
export const updateAttendanceRecord = (data) => request.put('/api/attendance', data)
export const deleteAttendanceRecord = (id) => request.delete(`/api/attendance/${id}`)
export const processAttendanceRecord = (id) => request.put(`/api/attendance/process/${id}`)
export const finishAttendanceRecord = (id) => request.put(`/api/attendance/finish/${id}`)

export const getExceptionAppealPage = (params) => request.get('/api/appeal/page', { params })
export const addExceptionAppeal = (data) => request.post('/api/appeal', data)
export const updateExceptionAppeal = (data) => request.put('/api/appeal', data)
export const deleteExceptionAppeal = (id) => request.delete(`/api/appeal/${id}`)
export const processExceptionAppeal = (id) => request.put(`/api/appeal/process/${id}`)
export const finishExceptionAppeal = (id) => request.put(`/api/appeal/finish/${id}`)

export const getAppealReviewPage = (params) => request.get('/api/review/page', { params })
export const addAppealReview = (data) => request.post('/api/review', data)
export const updateAppealReview = (data) => request.put('/api/review', data)
export const deleteAppealReview = (id) => request.delete(`/api/review/${id}`)
export const processAppealReview = (id) => request.put(`/api/review/process/${id}`)
export const finishAppealReview = (id) => request.put(`/api/review/finish/${id}`)

export const getClassroomInspectionPage = (params) => request.get('/api/inspection/page', { params })
export const addClassroomInspection = (data) => request.post('/api/inspection', data)
export const updateClassroomInspection = (data) => request.put('/api/inspection', data)
export const deleteClassroomInspection = (id) => request.delete(`/api/inspection/${id}`)
export const processClassroomInspection = (id) => request.put(`/api/inspection/process/${id}`)
export const finishClassroomInspection = (id) => request.put(`/api/inspection/finish/${id}`)

export const getInspectionIssuePage = (params) => request.get('/api/issue/page', { params })
export const addInspectionIssue = (data) => request.post('/api/issue', data)
export const updateInspectionIssue = (data) => request.put('/api/issue', data)
export const deleteInspectionIssue = (id) => request.delete(`/api/issue/${id}`)
export const processInspectionIssue = (id) => request.put(`/api/issue/process/${id}`)
export const finishInspectionIssue = (id) => request.put(`/api/issue/finish/${id}`)

export const getRectificationTaskPage = (params) => request.get('/api/rectification/page', { params })
export const addRectificationTask = (data) => request.post('/api/rectification', data)
export const updateRectificationTask = (data) => request.put('/api/rectification', data)
export const deleteRectificationTask = (id) => request.delete(`/api/rectification/${id}`)
export const processRectificationTask = (id) => request.put(`/api/rectification/process/${id}`)
export const finishRectificationTask = (id) => request.put(`/api/rectification/finish/${id}`)

export const getRectificationFeedbackPage = (params) => request.get('/api/feedback/page', { params })
export const addRectificationFeedback = (data) => request.post('/api/feedback', data)
export const updateRectificationFeedback = (data) => request.put('/api/feedback', data)
export const deleteRectificationFeedback = (id) => request.delete(`/api/feedback/${id}`)
export const processRectificationFeedback = (id) => request.put(`/api/feedback/process/${id}`)
export const finishRectificationFeedback = (id) => request.put(`/api/feedback/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
