import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getCloudRegionPage = (params) => request.get('/api/region/page', { params })
export const addCloudRegion = (data) => request.post('/api/region', data)
export const updateCloudRegion = (data) => request.put('/api/region', data)
export const deleteCloudRegion = (id) => request.delete(`/api/region/${id}`)
export const getServerAssetPage = (params) => request.get('/api/asset/page', { params })
export const addServerAsset = (data) => request.post('/api/asset', data)
export const updateServerAsset = (data) => request.put('/api/asset', data)
export const deleteServerAsset = (id) => request.delete(`/api/asset/${id}`)
export const onlineServerAsset = (id) => request.put(`/api/asset/online/${id}`)
export const offlineServerAsset = (id) => request.put(`/api/asset/offline/${id}`)
export const getResourceGroupPage = (params) => request.get('/api/group/page', { params })
export const addResourceGroup = (data) => request.post('/api/group', data)
export const updateResourceGroup = (data) => request.put('/api/group', data)
export const deleteResourceGroup = (id) => request.delete(`/api/group/${id}`)
export const getMetricDefinitionPage = (params) => request.get('/api/metric/page', { params })
export const addMetricDefinition = (data) => request.post('/api/metric', data)
export const updateMetricDefinition = (data) => request.put('/api/metric', data)
export const deleteMetricDefinition = (id) => request.delete(`/api/metric/${id}`)
export const getMetricSamplePage = (params) => request.get('/api/sample/page', { params })
export const addMetricSample = (data) => request.post('/api/sample', data)
export const updateMetricSample = (data) => request.put('/api/sample', data)
export const deleteMetricSample = (id) => request.delete(`/api/sample/${id}`)
export const getAlertRulePage = (params) => request.get('/api/rule/page', { params })
export const addAlertRule = (data) => request.post('/api/rule', data)
export const updateAlertRule = (data) => request.put('/api/rule', data)
export const deleteAlertRule = (id) => request.delete(`/api/rule/${id}`)
export const enableAlertRule = (id) => request.put(`/api/rule/enable/${id}`)
export const disableAlertRule = (id) => request.put(`/api/rule/disable/${id}`)
export const getAlertEventPage = (params) => request.get('/api/event/page', { params })
export const addAlertEvent = (data) => request.post('/api/event', data)
export const updateAlertEvent = (data) => request.put('/api/event', data)
export const deleteAlertEvent = (id) => request.delete(`/api/event/${id}`)
export const ackAlertEvent = (id) => request.put(`/api/event/ack/${id}`)
export const resolveAlertEvent = (id) => request.put(`/api/event/resolve/${id}`)
export const closeAlertEvent = (id) => request.put(`/api/event/close/${id}`)
export const getAlertNotifyPage = (params) => request.get('/api/notify/page', { params })
export const addAlertNotify = (data) => request.post('/api/notify', data)
export const updateAlertNotify = (data) => request.put('/api/notify', data)
export const deleteAlertNotify = (id) => request.delete(`/api/notify/${id}`)
export const getIncidentTicketPage = (params) => request.get('/api/ticket/page', { params })
export const addIncidentTicket = (data) => request.post('/api/ticket', data)
export const updateIncidentTicket = (data) => request.put('/api/ticket', data)
export const deleteIncidentTicket = (id) => request.delete(`/api/ticket/${id}`)
export const assignIncidentTicket = (id) => request.put(`/api/ticket/assign/${id}`)
export const resolveIncidentTicket = (id) => request.put(`/api/ticket/resolve/${id}`)
export const closeIncidentTicket = (id) => request.put(`/api/ticket/close/${id}`)
export const getMaintenanceWindowPage = (params) => request.get('/api/maintenance/page', { params })
export const addMaintenanceWindow = (data) => request.post('/api/maintenance', data)
export const updateMaintenanceWindow = (data) => request.put('/api/maintenance', data)
export const deleteMaintenanceWindow = (id) => request.delete(`/api/maintenance/${id}`)
export const startMaintenanceWindow = (id) => request.put(`/api/maintenance/start/${id}`)
export const finishMaintenanceWindow = (id) => request.put(`/api/maintenance/finish/${id}`)
export const getCapacityPlanPage = (params) => request.get('/api/capacity/page', { params })
export const addCapacityPlan = (data) => request.post('/api/capacity', data)
export const updateCapacityPlan = (data) => request.put('/api/capacity', data)
export const deleteCapacityPlan = (id) => request.delete(`/api/capacity/${id}`)
export const publishCapacityPlan = (id) => request.put(`/api/capacity/publish/${id}`)
export const archiveCapacityPlan = (id) => request.put(`/api/capacity/archive/${id}`)
export const getDashboardWidgetPage = (params) => request.get('/api/widget/page', { params })
export const addDashboardWidget = (data) => request.post('/api/widget', data)
export const updateDashboardWidget = (data) => request.put('/api/widget', data)
export const deleteDashboardWidget = (id) => request.delete(`/api/widget/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
