import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getContractTemplatePage = (params) => request.get('/api/template/page', { params })
export const addContractTemplate = (data) => request.post('/api/template', data)
export const updateContractTemplate = (data) => request.put('/api/template', data)
export const deleteContractTemplate = (id) => request.delete(`/api/template/${id}`)
export const activateContractTemplate = (id) => request.put(`/api/template/activate/${id}`)
export const finishContractTemplate = (id) => request.put(`/api/template/finish/${id}`)
export const getCounterpartyProfilePage = (params) => request.get('/api/counterparty/page', { params })
export const addCounterpartyProfile = (data) => request.post('/api/counterparty', data)
export const updateCounterpartyProfile = (data) => request.put('/api/counterparty', data)
export const deleteCounterpartyProfile = (id) => request.delete(`/api/counterparty/${id}`)
export const activateCounterpartyProfile = (id) => request.put(`/api/counterparty/activate/${id}`)
export const finishCounterpartyProfile = (id) => request.put(`/api/counterparty/finish/${id}`)
export const getSignerProfilePage = (params) => request.get('/api/signer/page', { params })
export const addSignerProfile = (data) => request.post('/api/signer', data)
export const updateSignerProfile = (data) => request.put('/api/signer', data)
export const deleteSignerProfile = (id) => request.delete(`/api/signer/${id}`)
export const processSignerProfile = (id) => request.put(`/api/signer/process/${id}`)
export const finishSignerProfile = (id) => request.put(`/api/signer/finish/${id}`)
export const getContractDraftPage = (params) => request.get('/api/draft/page', { params })
export const addContractDraft = (data) => request.post('/api/draft', data)
export const updateContractDraft = (data) => request.put('/api/draft', data)
export const deleteContractDraft = (id) => request.delete(`/api/draft/${id}`)
export const submitContractDraft = (id) => request.put(`/api/draft/submit/${id}`)
export const approveContractDraft = (id) => request.put(`/api/draft/approve/${id}`)
export const getSealApplicationPage = (params) => request.get('/api/seal-apply/page', { params })
export const addSealApplication = (data) => request.post('/api/seal-apply', data)
export const updateSealApplication = (data) => request.put('/api/seal-apply', data)
export const deleteSealApplication = (id) => request.delete(`/api/seal-apply/${id}`)
export const submitSealApplication = (id) => request.put(`/api/seal-apply/submit/${id}`)
export const approveSealApplication = (id) => request.put(`/api/seal-apply/approve/${id}`)
export const getApprovalFlowPage = (params) => request.get('/api/approval/page', { params })
export const addApprovalFlow = (data) => request.post('/api/approval', data)
export const updateApprovalFlow = (data) => request.put('/api/approval', data)
export const deleteApprovalFlow = (id) => request.delete(`/api/approval/${id}`)
export const submitApprovalFlow = (id) => request.put(`/api/approval/submit/${id}`)
export const approveApprovalFlow = (id) => request.put(`/api/approval/approve/${id}`)
export const getContractSigningPage = (params) => request.get('/api/signing/page', { params })
export const addContractSigning = (data) => request.post('/api/signing', data)
export const updateContractSigning = (data) => request.put('/api/signing', data)
export const deleteContractSigning = (id) => request.delete(`/api/signing/${id}`)
export const processContractSigning = (id) => request.put(`/api/signing/process/${id}`)
export const finishContractSigning = (id) => request.put(`/api/signing/finish/${id}`)
export const getSealRecordPage = (params) => request.get('/api/seal-record/page', { params })
export const addSealRecord = (data) => request.post('/api/seal-record', data)
export const updateSealRecord = (data) => request.put('/api/seal-record', data)
export const deleteSealRecord = (id) => request.delete(`/api/seal-record/${id}`)
export const activateSealRecord = (id) => request.put(`/api/seal-record/activate/${id}`)
export const finishSealRecord = (id) => request.put(`/api/seal-record/finish/${id}`)
export const getArchiveRecordPage = (params) => request.get('/api/archive/page', { params })
export const addArchiveRecord = (data) => request.post('/api/archive', data)
export const updateArchiveRecord = (data) => request.put('/api/archive', data)
export const deleteArchiveRecord = (id) => request.delete(`/api/archive/${id}`)
export const activateArchiveRecord = (id) => request.put(`/api/archive/activate/${id}`)
export const finishArchiveRecord = (id) => request.put(`/api/archive/finish/${id}`)
export const getExpirationReminderPage = (params) => request.get('/api/reminder/page', { params })
export const addExpirationReminder = (data) => request.post('/api/reminder', data)
export const updateExpirationReminder = (data) => request.put('/api/reminder', data)
export const deleteExpirationReminder = (id) => request.delete(`/api/reminder/${id}`)
export const activateExpirationReminder = (id) => request.put(`/api/reminder/activate/${id}`)
export const finishExpirationReminder = (id) => request.put(`/api/reminder/finish/${id}`)
export const getRiskClausePage = (params) => request.get('/api/risk/page', { params })
export const addRiskClause = (data) => request.post('/api/risk', data)
export const updateRiskClause = (data) => request.put('/api/risk', data)
export const deleteRiskClause = (id) => request.delete(`/api/risk/${id}`)
export const processRiskClause = (id) => request.put(`/api/risk/process/${id}`)
export const finishRiskClause = (id) => request.put(`/api/risk/finish/${id}`)
export const getContractNoticePage = (params) => request.get('/api/notice/page', { params })
export const addContractNotice = (data) => request.post('/api/notice', data)
export const updateContractNotice = (data) => request.put('/api/notice', data)
export const deleteContractNotice = (id) => request.delete(`/api/notice/${id}`)
export const processContractNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishContractNotice = (id) => request.put(`/api/notice/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)




