import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getItemCategoryPage = (params) => request.get('/api/category/page', { params })
export const addItemCategory = (data) => request.post('/api/category', data)
export const updateItemCategory = (data) => request.put('/api/category', data)
export const deleteItemCategory = (id) => request.delete(`/api/category/${id}`)
export const processItemCategory = (id) => request.put(`/api/category/process/${id}`)
export const finishItemCategory = (id) => request.put(`/api/category/finish/${id}`)

export const getStudentProfilePage = (params) => request.get('/api/student/page', { params })
export const addStudentProfile = (data) => request.post('/api/student', data)
export const updateStudentProfile = (data) => request.put('/api/student', data)
export const deleteStudentProfile = (id) => request.delete(`/api/student/${id}`)
export const processStudentProfile = (id) => request.put(`/api/student/process/${id}`)
export const finishStudentProfile = (id) => request.put(`/api/student/finish/${id}`)

export const getConsignmentItemPage = (params) => request.get('/api/consignment/page', { params })
export const addConsignmentItem = (data) => request.post('/api/consignment', data)
export const updateConsignmentItem = (data) => request.put('/api/consignment', data)
export const deleteConsignmentItem = (id) => request.delete(`/api/consignment/${id}`)
export const processConsignmentItem = (id) => request.put(`/api/consignment/process/${id}`)
export const finishConsignmentItem = (id) => request.put(`/api/consignment/finish/${id}`)

export const getItemAuditPage = (params) => request.get('/api/audit/page', { params })
export const addItemAudit = (data) => request.post('/api/audit', data)
export const updateItemAudit = (data) => request.put('/api/audit', data)
export const deleteItemAudit = (id) => request.delete(`/api/audit/${id}`)
export const processItemAudit = (id) => request.put(`/api/audit/process/${id}`)
export const finishItemAudit = (id) => request.put(`/api/audit/finish/${id}`)

export const getEscrowOrderPage = (params) => request.get('/api/order/page', { params })
export const addEscrowOrder = (data) => request.post('/api/order', data)
export const updateEscrowOrder = (data) => request.put('/api/order', data)
export const deleteEscrowOrder = (id) => request.delete(`/api/order/${id}`)
export const processEscrowOrder = (id) => request.put(`/api/order/process/${id}`)
export const finishEscrowOrder = (id) => request.put(`/api/order/finish/${id}`)

export const getPaymentRecordPage = (params) => request.get('/api/payment/page', { params })
export const addPaymentRecord = (data) => request.post('/api/payment', data)
export const updatePaymentRecord = (data) => request.put('/api/payment', data)
export const deletePaymentRecord = (id) => request.delete(`/api/payment/${id}`)
export const processPaymentRecord = (id) => request.put(`/api/payment/process/${id}`)
export const finishPaymentRecord = (id) => request.put(`/api/payment/finish/${id}`)

export const getHandoverRecordPage = (params) => request.get('/api/handover/page', { params })
export const addHandoverRecord = (data) => request.post('/api/handover', data)
export const updateHandoverRecord = (data) => request.put('/api/handover', data)
export const deleteHandoverRecord = (id) => request.delete(`/api/handover/${id}`)
export const processHandoverRecord = (id) => request.put(`/api/handover/process/${id}`)
export const finishHandoverRecord = (id) => request.put(`/api/handover/finish/${id}`)

export const getCreditEvaluationPage = (params) => request.get('/api/credit/page', { params })
export const addCreditEvaluation = (data) => request.post('/api/credit', data)
export const updateCreditEvaluation = (data) => request.put('/api/credit', data)
export const deleteCreditEvaluation = (id) => request.delete(`/api/credit/${id}`)
export const processCreditEvaluation = (id) => request.put(`/api/credit/process/${id}`)
export const finishCreditEvaluation = (id) => request.put(`/api/credit/finish/${id}`)

export const getBreachRecordPage = (params) => request.get('/api/breach/page', { params })
export const addBreachRecord = (data) => request.post('/api/breach', data)
export const updateBreachRecord = (data) => request.put('/api/breach', data)
export const deleteBreachRecord = (id) => request.delete(`/api/breach/${id}`)
export const processBreachRecord = (id) => request.put(`/api/breach/process/${id}`)
export const finishBreachRecord = (id) => request.put(`/api/breach/finish/${id}`)

export const getComplaintTicketPage = (params) => request.get('/api/complaint/page', { params })
export const addComplaintTicket = (data) => request.post('/api/complaint', data)
export const updateComplaintTicket = (data) => request.put('/api/complaint', data)
export const deleteComplaintTicket = (id) => request.delete(`/api/complaint/${id}`)
export const processComplaintTicket = (id) => request.put(`/api/complaint/process/${id}`)
export const finishComplaintTicket = (id) => request.put(`/api/complaint/finish/${id}`)

export const getPlatformNoticePage = (params) => request.get('/api/notice/page', { params })
export const addPlatformNotice = (data) => request.post('/api/notice', data)
export const updatePlatformNotice = (data) => request.put('/api/notice', data)
export const deletePlatformNotice = (id) => request.delete(`/api/notice/${id}`)
export const processPlatformNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishPlatformNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
