import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getSportEventPage = (params) => request.get('/api/event/page', { params })
export const addSportEvent = (data) => request.post('/api/event', data)
export const updateSportEvent = (data) => request.put('/api/event', data)
export const deleteSportEvent = (id) => request.delete(`/api/event/${id}`)
export const processSportEvent = (id) => request.put(`/api/event/process/${id}`)
export const finishSportEvent = (id) => request.put(`/api/event/finish/${id}`)

export const getTeamProfilePage = (params) => request.get('/api/team/page', { params })
export const addTeamProfile = (data) => request.post('/api/team', data)
export const updateTeamProfile = (data) => request.put('/api/team', data)
export const deleteTeamProfile = (id) => request.delete(`/api/team/${id}`)
export const processTeamProfile = (id) => request.put(`/api/team/process/${id}`)
export const finishTeamProfile = (id) => request.put(`/api/team/finish/${id}`)

export const getAthleteProfilePage = (params) => request.get('/api/athlete/page', { params })
export const addAthleteProfile = (data) => request.post('/api/athlete', data)
export const updateAthleteProfile = (data) => request.put('/api/athlete', data)
export const deleteAthleteProfile = (id) => request.delete(`/api/athlete/${id}`)
export const processAthleteProfile = (id) => request.put(`/api/athlete/process/${id}`)
export const finishAthleteProfile = (id) => request.put(`/api/athlete/finish/${id}`)

export const getEventRegistrationPage = (params) => request.get('/api/registration/page', { params })
export const addEventRegistration = (data) => request.post('/api/registration', data)
export const updateEventRegistration = (data) => request.put('/api/registration', data)
export const deleteEventRegistration = (id) => request.delete(`/api/registration/${id}`)
export const processEventRegistration = (id) => request.put(`/api/registration/process/${id}`)
export const finishEventRegistration = (id) => request.put(`/api/registration/finish/${id}`)

export const getGroupDrawPage = (params) => request.get('/api/group/page', { params })
export const addGroupDraw = (data) => request.post('/api/group', data)
export const updateGroupDraw = (data) => request.put('/api/group', data)
export const deleteGroupDraw = (id) => request.delete(`/api/group/${id}`)
export const processGroupDraw = (id) => request.put(`/api/group/process/${id}`)
export const finishGroupDraw = (id) => request.put(`/api/group/finish/${id}`)

export const getScheduleMatchPage = (params) => request.get('/api/schedule/page', { params })
export const addScheduleMatch = (data) => request.post('/api/schedule', data)
export const updateScheduleMatch = (data) => request.put('/api/schedule', data)
export const deleteScheduleMatch = (id) => request.delete(`/api/schedule/${id}`)
export const processScheduleMatch = (id) => request.put(`/api/schedule/process/${id}`)
export const finishScheduleMatch = (id) => request.put(`/api/schedule/finish/${id}`)

export const getVenueResourcePage = (params) => request.get('/api/venue/page', { params })
export const addVenueResource = (data) => request.post('/api/venue', data)
export const updateVenueResource = (data) => request.put('/api/venue', data)
export const deleteVenueResource = (id) => request.delete(`/api/venue/${id}`)
export const processVenueResource = (id) => request.put(`/api/venue/process/${id}`)
export const finishVenueResource = (id) => request.put(`/api/venue/finish/${id}`)

export const getRefereeAssignmentPage = (params) => request.get('/api/referee/page', { params })
export const addRefereeAssignment = (data) => request.post('/api/referee', data)
export const updateRefereeAssignment = (data) => request.put('/api/referee', data)
export const deleteRefereeAssignment = (id) => request.delete(`/api/referee/${id}`)
export const processRefereeAssignment = (id) => request.put(`/api/referee/process/${id}`)
export const finishRefereeAssignment = (id) => request.put(`/api/referee/finish/${id}`)

export const getScoreRecordPage = (params) => request.get('/api/score/page', { params })
export const addScoreRecord = (data) => request.post('/api/score', data)
export const updateScoreRecord = (data) => request.put('/api/score', data)
export const deleteScoreRecord = (id) => request.delete(`/api/score/${id}`)
export const processScoreRecord = (id) => request.put(`/api/score/process/${id}`)
export const finishScoreRecord = (id) => request.put(`/api/score/finish/${id}`)

export const getResultPublishPage = (params) => request.get('/api/result/page', { params })
export const addResultPublish = (data) => request.post('/api/result', data)
export const updateResultPublish = (data) => request.put('/api/result', data)
export const deleteResultPublish = (id) => request.delete(`/api/result/${id}`)
export const processResultPublish = (id) => request.put(`/api/result/process/${id}`)
export const finishResultPublish = (id) => request.put(`/api/result/finish/${id}`)

export const getAppealReviewPage = (params) => request.get('/api/appeal/page', { params })
export const addAppealReview = (data) => request.post('/api/appeal', data)
export const updateAppealReview = (data) => request.put('/api/appeal', data)
export const deleteAppealReview = (id) => request.delete(`/api/appeal/${id}`)
export const processAppealReview = (id) => request.put(`/api/appeal/process/${id}`)
export const finishAppealReview = (id) => request.put(`/api/appeal/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
