import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getEmployeeProfilePage = (params) => request.get('/api/employee/page', { params })
export const addEmployeeProfile = (data) => request.post('/api/employee', data)
export const updateEmployeeProfile = (data) => request.put('/api/employee', data)
export const deleteEmployeeProfile = (id) => request.delete(`/api/employee/${id}`)
export const activateEmployeeProfile = (id) => request.put(`/api/employee/activate/${id}`)
export const freezeEmployeeProfile = (id) => request.put(`/api/employee/freeze/${id}`)
export const getDepartmentGroupPage = (params) => request.get('/api/department/page', { params })
export const addDepartmentGroup = (data) => request.post('/api/department', data)
export const updateDepartmentGroup = (data) => request.put('/api/department', data)
export const deleteDepartmentGroup = (id) => request.delete(`/api/department/${id}`)
export const getMailTemplatePage = (params) => request.get('/api/template/page', { params })
export const addMailTemplate = (data) => request.post('/api/template', data)
export const updateMailTemplate = (data) => request.put('/api/template', data)
export const deleteMailTemplate = (id) => request.delete(`/api/template/${id}`)
export const publishMailTemplate = (id) => request.put(`/api/template/publish/${id}`)
export const archiveMailTemplate = (id) => request.put(`/api/template/archive/${id}`)
export const getPhishingCampaignPage = (params) => request.get('/api/campaign/page', { params })
export const addPhishingCampaign = (data) => request.post('/api/campaign', data)
export const updatePhishingCampaign = (data) => request.put('/api/campaign', data)
export const deletePhishingCampaign = (id) => request.delete(`/api/campaign/${id}`)
export const submitPhishingCampaign = (id) => request.put(`/api/campaign/submit/${id}`)
export const startPhishingCampaign = (id) => request.put(`/api/campaign/start/${id}`)
export const finishPhishingCampaign = (id) => request.put(`/api/campaign/finish/${id}`)
export const getCampaignTargetPage = (params) => request.get('/api/target/page', { params })
export const addCampaignTarget = (data) => request.post('/api/target', data)
export const updateCampaignTarget = (data) => request.put('/api/target', data)
export const deleteCampaignTarget = (id) => request.delete(`/api/target/${id}`)
export const getMailSendRecordPage = (params) => request.get('/api/send-record/page', { params })
export const addMailSendRecord = (data) => request.post('/api/send-record', data)
export const updateMailSendRecord = (data) => request.put('/api/send-record', data)
export const deleteMailSendRecord = (id) => request.delete(`/api/send-record/${id}`)
export const sentMailSendRecord = (id) => request.put(`/api/send-record/sent/${id}`)
export const openMailSendRecord = (id) => request.put(`/api/send-record/open/${id}`)
export const failMailSendRecord = (id) => request.put(`/api/send-record/fail/${id}`)
export const getClickTrackingPage = (params) => request.get('/api/click/page', { params })
export const addClickTracking = (data) => request.post('/api/click', data)
export const updateClickTracking = (data) => request.put('/api/click', data)
export const deleteClickTracking = (id) => request.delete(`/api/click/${id}`)
export const confirmClickTracking = (id) => request.put(`/api/click/confirm/${id}`)
export const educateClickTracking = (id) => request.put(`/api/click/educate/${id}`)
export const ignoreClickTracking = (id) => request.put(`/api/click/ignore/${id}`)
export const getTrainingCoursePage = (params) => request.get('/api/course/page', { params })
export const addTrainingCourse = (data) => request.post('/api/course', data)
export const updateTrainingCourse = (data) => request.put('/api/course', data)
export const deleteTrainingCourse = (id) => request.delete(`/api/course/${id}`)
export const publishTrainingCourse = (id) => request.put(`/api/course/publish/${id}`)
export const archiveTrainingCourse = (id) => request.put(`/api/course/archive/${id}`)
export const getTrainingExamPage = (params) => request.get('/api/exam/page', { params })
export const addTrainingExam = (data) => request.post('/api/exam', data)
export const updateTrainingExam = (data) => request.put('/api/exam', data)
export const deleteTrainingExam = (id) => request.delete(`/api/exam/${id}`)
export const publishTrainingExam = (id) => request.put(`/api/exam/publish/${id}`)
export const closeTrainingExam = (id) => request.put(`/api/exam/close/${id}`)
export const getExamQuestionPage = (params) => request.get('/api/question/page', { params })
export const addExamQuestion = (data) => request.post('/api/question', data)
export const updateExamQuestion = (data) => request.put('/api/question', data)
export const deleteExamQuestion = (id) => request.delete(`/api/question/${id}`)
export const getExamAttemptPage = (params) => request.get('/api/attempt/page', { params })
export const addExamAttempt = (data) => request.post('/api/attempt', data)
export const updateExamAttempt = (data) => request.put('/api/attempt', data)
export const deleteExamAttempt = (id) => request.delete(`/api/attempt/${id}`)
export const passExamAttempt = (id) => request.put(`/api/attempt/pass/${id}`)
export const failExamAttempt = (id) => request.put(`/api/attempt/fail/${id}`)
export const retrainExamAttempt = (id) => request.put(`/api/attempt/retrain/${id}`)
export const getRiskScorePage = (params) => request.get('/api/risk-score/page', { params })
export const addRiskScore = (data) => request.post('/api/risk-score', data)
export const updateRiskScore = (data) => request.put('/api/risk-score', data)
export const deleteRiskScore = (id) => request.delete(`/api/risk-score/${id}`)
export const reviewRiskScore = (id) => request.put(`/api/risk-score/review/${id}`)
export const remediateRiskScore = (id) => request.put(`/api/risk-score/remediate/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
