import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getPatientProfilePage = (params) => request.get('/api/patient/page', { params })
export const addPatientProfile = (data) => request.post('/api/patient', data)
export const updatePatientProfile = (data) => request.put('/api/patient', data)
export const deletePatientProfile = (id) => request.delete(`/api/patient/${id}`)
export const activatePatientProfile = (id) => request.put(`/api/patient/activate/${id}`)
export const finishPatientProfile = (id) => request.put(`/api/patient/finish/${id}`)
export const getDrugCatalogPage = (params) => request.get('/api/drug/page', { params })
export const addDrugCatalog = (data) => request.post('/api/drug', data)
export const updateDrugCatalog = (data) => request.put('/api/drug', data)
export const deleteDrugCatalog = (id) => request.delete(`/api/drug/${id}`)
export const activateDrugCatalog = (id) => request.put(`/api/drug/activate/${id}`)
export const finishDrugCatalog = (id) => request.put(`/api/drug/finish/${id}`)
export const getReporterProfilePage = (params) => request.get('/api/reporter/page', { params })
export const addReporterProfile = (data) => request.post('/api/reporter', data)
export const updateReporterProfile = (data) => request.put('/api/reporter', data)
export const deleteReporterProfile = (id) => request.delete(`/api/reporter/${id}`)
export const activateReporterProfile = (id) => request.put(`/api/reporter/activate/${id}`)
export const finishReporterProfile = (id) => request.put(`/api/reporter/finish/${id}`)
export const getAdverseReportPage = (params) => request.get('/api/report/page', { params })
export const addAdverseReport = (data) => request.post('/api/report', data)
export const updateAdverseReport = (data) => request.put('/api/report', data)
export const deleteAdverseReport = (id) => request.delete(`/api/report/${id}`)
export const submitAdverseReport = (id) => request.put(`/api/report/submit/${id}`)
export const approveAdverseReport = (id) => request.put(`/api/report/approve/${id}`)
export const getReactionSymptomPage = (params) => request.get('/api/symptom/page', { params })
export const addReactionSymptom = (data) => request.post('/api/symptom', data)
export const updateReactionSymptom = (data) => request.put('/api/symptom', data)
export const deleteReactionSymptom = (id) => request.delete(`/api/symptom/${id}`)
export const processReactionSymptom = (id) => request.put(`/api/symptom/process/${id}`)
export const finishReactionSymptom = (id) => request.put(`/api/symptom/finish/${id}`)
export const getRiskAssessmentPage = (params) => request.get('/api/risk/page', { params })
export const addRiskAssessment = (data) => request.post('/api/risk', data)
export const updateRiskAssessment = (data) => request.put('/api/risk', data)
export const deleteRiskAssessment = (id) => request.delete(`/api/risk/${id}`)
export const submitRiskAssessment = (id) => request.put(`/api/risk/submit/${id}`)
export const approveRiskAssessment = (id) => request.put(`/api/risk/approve/${id}`)
export const getFollowupPlanPage = (params) => request.get('/api/plan/page', { params })
export const addFollowupPlan = (data) => request.post('/api/plan', data)
export const updateFollowupPlan = (data) => request.put('/api/plan', data)
export const deleteFollowupPlan = (id) => request.delete(`/api/plan/${id}`)
export const processFollowupPlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishFollowupPlan = (id) => request.put(`/api/plan/finish/${id}`)
export const getFollowupRecordPage = (params) => request.get('/api/followup/page', { params })
export const addFollowupRecord = (data) => request.post('/api/followup', data)
export const updateFollowupRecord = (data) => request.put('/api/followup', data)
export const deleteFollowupRecord = (id) => request.delete(`/api/followup/${id}`)
export const submitFollowupRecord = (id) => request.put(`/api/followup/submit/${id}`)
export const approveFollowupRecord = (id) => request.put(`/api/followup/approve/${id}`)
export const getCaseReviewPage = (params) => request.get('/api/review/page', { params })
export const addCaseReview = (data) => request.post('/api/review', data)
export const updateCaseReview = (data) => request.put('/api/review', data)
export const deleteCaseReview = (id) => request.delete(`/api/review/${id}`)
export const submitCaseReview = (id) => request.put(`/api/review/submit/${id}`)
export const approveCaseReview = (id) => request.put(`/api/review/approve/${id}`)
export const getTreatmentAdvicePage = (params) => request.get('/api/advice/page', { params })
export const addTreatmentAdvice = (data) => request.post('/api/advice', data)
export const updateTreatmentAdvice = (data) => request.put('/api/advice', data)
export const deleteTreatmentAdvice = (id) => request.delete(`/api/advice/${id}`)
export const activateTreatmentAdvice = (id) => request.put(`/api/advice/activate/${id}`)
export const finishTreatmentAdvice = (id) => request.put(`/api/advice/finish/${id}`)
export const getDepartmentInfoPage = (params) => request.get('/api/department/page', { params })
export const addDepartmentInfo = (data) => request.post('/api/department', data)
export const updateDepartmentInfo = (data) => request.put('/api/department', data)
export const deleteDepartmentInfo = (id) => request.delete(`/api/department/${id}`)
export const activateDepartmentInfo = (id) => request.put(`/api/department/activate/${id}`)
export const finishDepartmentInfo = (id) => request.put(`/api/department/finish/${id}`)
export const getStatisticsReportPage = (params) => request.get('/api/statistic/page', { params })
export const addStatisticsReport = (data) => request.post('/api/statistic', data)
export const updateStatisticsReport = (data) => request.put('/api/statistic', data)
export const deleteStatisticsReport = (id) => request.delete(`/api/statistic/${id}`)
export const activateStatisticsReport = (id) => request.put(`/api/statistic/activate/${id}`)
export const finishStatisticsReport = (id) => request.put(`/api/statistic/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
