import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getTrainingProgramPage = (params) => request.get('/api/program/page', { params })
export const addTrainingProgram = (data) => request.post('/api/program', data)
export const updateTrainingProgram = (data) => request.put('/api/program', data)
export const deleteTrainingProgram = (id) => request.delete(`/api/program/${id}`)
export const processTrainingProgram = (id) => request.put(`/api/program/process/${id}`)
export const finishTrainingProgram = (id) => request.put(`/api/program/finish/${id}`)

export const getNurseProfilePage = (params) => request.get('/api/nurse/page', { params })
export const addNurseProfile = (data) => request.post('/api/nurse', data)
export const updateNurseProfile = (data) => request.put('/api/nurse', data)
export const deleteNurseProfile = (id) => request.delete(`/api/nurse/${id}`)
export const processNurseProfile = (id) => request.put(`/api/nurse/process/${id}`)
export const finishNurseProfile = (id) => request.put(`/api/nurse/finish/${id}`)

export const getTrainingClassPage = (params) => request.get('/api/class/page', { params })
export const addTrainingClass = (data) => request.post('/api/class', data)
export const updateTrainingClass = (data) => request.put('/api/class', data)
export const deleteTrainingClass = (id) => request.delete(`/api/class/${id}`)
export const processTrainingClass = (id) => request.put(`/api/class/process/${id}`)
export const finishTrainingClass = (id) => request.put(`/api/class/finish/${id}`)

export const getTrainingCheckinPage = (params) => request.get('/api/checkin/page', { params })
export const addTrainingCheckin = (data) => request.post('/api/checkin', data)
export const updateTrainingCheckin = (data) => request.put('/api/checkin', data)
export const deleteTrainingCheckin = (id) => request.delete(`/api/checkin/${id}`)
export const processTrainingCheckin = (id) => request.put(`/api/checkin/process/${id}`)
export const finishTrainingCheckin = (id) => request.put(`/api/checkin/finish/${id}`)

export const getSkillItemPage = (params) => request.get('/api/skill/page', { params })
export const addSkillItem = (data) => request.post('/api/skill', data)
export const updateSkillItem = (data) => request.put('/api/skill', data)
export const deleteSkillItem = (id) => request.delete(`/api/skill/${id}`)
export const processSkillItem = (id) => request.put(`/api/skill/process/${id}`)
export const finishSkillItem = (id) => request.put(`/api/skill/finish/${id}`)

export const getSkillAssessmentPage = (params) => request.get('/api/assessment/page', { params })
export const addSkillAssessment = (data) => request.post('/api/assessment', data)
export const updateSkillAssessment = (data) => request.put('/api/assessment', data)
export const deleteSkillAssessment = (id) => request.delete(`/api/assessment/${id}`)
export const processSkillAssessment = (id) => request.put(`/api/assessment/process/${id}`)
export const finishSkillAssessment = (id) => request.put(`/api/assessment/finish/${id}`)

export const getCertificateArchivePage = (params) => request.get('/api/certificate/page', { params })
export const addCertificateArchive = (data) => request.post('/api/certificate', data)
export const updateCertificateArchive = (data) => request.put('/api/certificate', data)
export const deleteCertificateArchive = (id) => request.delete(`/api/certificate/${id}`)
export const processCertificateArchive = (id) => request.put(`/api/certificate/process/${id}`)
export const finishCertificateArchive = (id) => request.put(`/api/certificate/finish/${id}`)

export const getRetrainingReminderPage = (params) => request.get('/api/retraining/page', { params })
export const addRetrainingReminder = (data) => request.post('/api/retraining', data)
export const updateRetrainingReminder = (data) => request.put('/api/retraining', data)
export const deleteRetrainingReminder = (id) => request.delete(`/api/retraining/${id}`)
export const processRetrainingReminder = (id) => request.put(`/api/retraining/process/${id}`)
export const finishRetrainingReminder = (id) => request.put(`/api/retraining/finish/${id}`)

export const getPracticeRecordPage = (params) => request.get('/api/practice/page', { params })
export const addPracticeRecord = (data) => request.post('/api/practice', data)
export const updatePracticeRecord = (data) => request.put('/api/practice', data)
export const deletePracticeRecord = (id) => request.delete(`/api/practice/${id}`)
export const processPracticeRecord = (id) => request.put(`/api/practice/process/${id}`)
export const finishPracticeRecord = (id) => request.put(`/api/practice/finish/${id}`)

export const getAssessmentAppealPage = (params) => request.get('/api/appeal/page', { params })
export const addAssessmentAppeal = (data) => request.post('/api/appeal', data)
export const updateAssessmentAppeal = (data) => request.put('/api/appeal', data)
export const deleteAssessmentAppeal = (id) => request.delete(`/api/appeal/${id}`)
export const processAssessmentAppeal = (id) => request.put(`/api/appeal/process/${id}`)
export const finishAssessmentAppeal = (id) => request.put(`/api/appeal/finish/${id}`)

export const getTrainingNoticePage = (params) => request.get('/api/notice/page', { params })
export const addTrainingNotice = (data) => request.post('/api/notice', data)
export const updateTrainingNotice = (data) => request.put('/api/notice', data)
export const deleteTrainingNotice = (id) => request.delete(`/api/notice/${id}`)
export const processTrainingNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishTrainingNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
