import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getGreenhouseProfilePage = (params) => request.get('/api/greenhouse/page', { params })
export const addGreenhouseProfile = (data) => request.post('/api/greenhouse', data)
export const updateGreenhouseProfile = (data) => request.put('/api/greenhouse', data)
export const deleteGreenhouseProfile = (id) => request.delete(`/api/greenhouse/${id}`)
export const activateGreenhouseProfile = (id) => request.put(`/api/greenhouse/activate/${id}`)
export const finishGreenhouseProfile = (id) => request.put(`/api/greenhouse/finish/${id}`)
export const getCropBatchPage = (params) => request.get('/api/crop/page', { params })
export const addCropBatch = (data) => request.post('/api/crop', data)
export const updateCropBatch = (data) => request.put('/api/crop', data)
export const deleteCropBatch = (id) => request.delete(`/api/crop/${id}`)
export const activateCropBatch = (id) => request.put(`/api/crop/activate/${id}`)
export const finishCropBatch = (id) => request.put(`/api/crop/finish/${id}`)
export const getEnvironmentSensorPage = (params) => request.get('/api/sensor/page', { params })
export const addEnvironmentSensor = (data) => request.post('/api/sensor', data)
export const updateEnvironmentSensor = (data) => request.put('/api/sensor', data)
export const deleteEnvironmentSensor = (id) => request.delete(`/api/sensor/${id}`)
export const activateEnvironmentSensor = (id) => request.put(`/api/sensor/activate/${id}`)
export const finishEnvironmentSensor = (id) => request.put(`/api/sensor/finish/${id}`)
export const getEnvironmentReadingPage = (params) => request.get('/api/reading/page', { params })
export const addEnvironmentReading = (data) => request.post('/api/reading', data)
export const updateEnvironmentReading = (data) => request.put('/api/reading', data)
export const deleteEnvironmentReading = (id) => request.delete(`/api/reading/${id}`)
export const processEnvironmentReading = (id) => request.put(`/api/reading/process/${id}`)
export const finishEnvironmentReading = (id) => request.put(`/api/reading/finish/${id}`)
export const getIrrigationTaskPage = (params) => request.get('/api/irrigation/page', { params })
export const addIrrigationTask = (data) => request.post('/api/irrigation', data)
export const updateIrrigationTask = (data) => request.put('/api/irrigation', data)
export const deleteIrrigationTask = (id) => request.delete(`/api/irrigation/${id}`)
export const processIrrigationTask = (id) => request.put(`/api/irrigation/process/${id}`)
export const finishIrrigationTask = (id) => request.put(`/api/irrigation/finish/${id}`)
export const getFertilizerPlanPage = (params) => request.get('/api/fertilizer/page', { params })
export const addFertilizerPlan = (data) => request.post('/api/fertilizer', data)
export const updateFertilizerPlan = (data) => request.put('/api/fertilizer', data)
export const deleteFertilizerPlan = (id) => request.delete(`/api/fertilizer/${id}`)
export const activateFertilizerPlan = (id) => request.put(`/api/fertilizer/activate/${id}`)
export const finishFertilizerPlan = (id) => request.put(`/api/fertilizer/finish/${id}`)
export const getPestWarningPage = (params) => request.get('/api/pest/page', { params })
export const addPestWarning = (data) => request.post('/api/pest', data)
export const updatePestWarning = (data) => request.put('/api/pest', data)
export const deletePestWarning = (id) => request.delete(`/api/pest/${id}`)
export const processPestWarning = (id) => request.put(`/api/pest/process/${id}`)
export const finishPestWarning = (id) => request.put(`/api/pest/finish/${id}`)
export const getDiseaseDiagnosisPage = (params) => request.get('/api/diagnosis/page', { params })
export const addDiseaseDiagnosis = (data) => request.post('/api/diagnosis', data)
export const updateDiseaseDiagnosis = (data) => request.put('/api/diagnosis', data)
export const deleteDiseaseDiagnosis = (id) => request.delete(`/api/diagnosis/${id}`)
export const submitDiseaseDiagnosis = (id) => request.put(`/api/diagnosis/submit/${id}`)
export const approveDiseaseDiagnosis = (id) => request.put(`/api/diagnosis/approve/${id}`)
export const getControlDevicePage = (params) => request.get('/api/device/page', { params })
export const addControlDevice = (data) => request.post('/api/device', data)
export const updateControlDevice = (data) => request.put('/api/device', data)
export const deleteControlDevice = (id) => request.delete(`/api/device/${id}`)
export const activateControlDevice = (id) => request.put(`/api/device/activate/${id}`)
export const finishControlDevice = (id) => request.put(`/api/device/finish/${id}`)
export const getRemoteCommandPage = (params) => request.get('/api/command/page', { params })
export const addRemoteCommand = (data) => request.post('/api/command', data)
export const updateRemoteCommand = (data) => request.put('/api/command', data)
export const deleteRemoteCommand = (id) => request.delete(`/api/command/${id}`)
export const processRemoteCommand = (id) => request.put(`/api/command/process/${id}`)
export const finishRemoteCommand = (id) => request.put(`/api/command/finish/${id}`)
export const getHarvestRecordPage = (params) => request.get('/api/harvest/page', { params })
export const addHarvestRecord = (data) => request.post('/api/harvest', data)
export const updateHarvestRecord = (data) => request.put('/api/harvest', data)
export const deleteHarvestRecord = (id) => request.delete(`/api/harvest/${id}`)
export const activateHarvestRecord = (id) => request.put(`/api/harvest/activate/${id}`)
export const finishHarvestRecord = (id) => request.put(`/api/harvest/finish/${id}`)
export const getMaintenanceTicketPage = (params) => request.get('/api/ticket/page', { params })
export const addMaintenanceTicket = (data) => request.post('/api/ticket', data)
export const updateMaintenanceTicket = (data) => request.put('/api/ticket', data)
export const deleteMaintenanceTicket = (id) => request.delete(`/api/ticket/${id}`)
export const processMaintenanceTicket = (id) => request.put(`/api/ticket/process/${id}`)
export const finishMaintenanceTicket = (id) => request.put(`/api/ticket/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
