import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getApiProjectPage = (params) => request.get('/api/project/page', { params })
export const addApiProject = (data) => request.post('/api/project', data)
export const updateApiProject = (data) => request.put('/api/project', data)
export const deleteApiProject = (id) => request.delete(`/api/project/${id}`)
export const archiveApiProject = (id) => request.put(`/api/project/archive/${id}`)
export const activateApiProject = (id) => request.put(`/api/project/activate/${id}`)
export const getApiGroupPage = (params) => request.get('/api/group/page', { params })
export const addApiGroup = (data) => request.post('/api/group', data)
export const updateApiGroup = (data) => request.put('/api/group', data)
export const deleteApiGroup = (id) => request.delete(`/api/group/${id}`)
export const getApiEndpointPage = (params) => request.get('/api/endpoint/page', { params })
export const addApiEndpoint = (data) => request.post('/api/endpoint', data)
export const updateApiEndpoint = (data) => request.put('/api/endpoint', data)
export const deleteApiEndpoint = (id) => request.delete(`/api/endpoint/${id}`)
export const publishApiEndpoint = (id) => request.put(`/api/endpoint/publish/${id}`)
export const offlineApiEndpoint = (id) => request.put(`/api/endpoint/offline/${id}`)
export const getRequestParamPage = (params) => request.get('/api/request-param/page', { params })
export const addRequestParam = (data) => request.post('/api/request-param', data)
export const updateRequestParam = (data) => request.put('/api/request-param', data)
export const deleteRequestParam = (id) => request.delete(`/api/request-param/${id}`)
export const getResponseFieldPage = (params) => request.get('/api/response-field/page', { params })
export const addResponseField = (data) => request.post('/api/response-field', data)
export const updateResponseField = (data) => request.put('/api/response-field', data)
export const deleteResponseField = (id) => request.delete(`/api/response-field/${id}`)
export const getMockRulePage = (params) => request.get('/api/mock-rule/page', { params })
export const addMockRule = (data) => request.post('/api/mock-rule', data)
export const updateMockRule = (data) => request.put('/api/mock-rule', data)
export const deleteMockRule = (id) => request.delete(`/api/mock-rule/${id}`)
export const getTestCasePage = (params) => request.get('/api/test-case/page', { params })
export const addTestCase = (data) => request.post('/api/test-case', data)
export const updateTestCase = (data) => request.put('/api/test-case', data)
export const deleteTestCase = (id) => request.delete(`/api/test-case/${id}`)
export const enableTestCase = (id) => request.put(`/api/test-case/enable/${id}`)
export const disableTestCase = (id) => request.put(`/api/test-case/disable/${id}`)
export const getTestStepPage = (params) => request.get('/api/test-step/page', { params })
export const addTestStep = (data) => request.post('/api/test-step', data)
export const updateTestStep = (data) => request.put('/api/test-step', data)
export const deleteTestStep = (id) => request.delete(`/api/test-step/${id}`)
export const getEnvironmentConfigPage = (params) => request.get('/api/environment/page', { params })
export const addEnvironmentConfig = (data) => request.post('/api/environment', data)
export const updateEnvironmentConfig = (data) => request.put('/api/environment', data)
export const deleteEnvironmentConfig = (id) => request.delete(`/api/environment/${id}`)
export const getTestExecutionPage = (params) => request.get('/api/execution/page', { params })
export const addTestExecution = (data) => request.post('/api/execution', data)
export const updateTestExecution = (data) => request.put('/api/execution', data)
export const deleteTestExecution = (id) => request.delete(`/api/execution/${id}`)
export const startTestExecution = (id) => request.put(`/api/execution/start/${id}`)
export const finishTestExecution = (id) => request.put(`/api/execution/finish/${id}`)
export const failTestExecution = (id) => request.put(`/api/execution/fail/${id}`)
export const getExecutionResultPage = (params) => request.get('/api/execution-result/page', { params })
export const addExecutionResult = (data) => request.post('/api/execution-result', data)
export const updateExecutionResult = (data) => request.put('/api/execution-result', data)
export const deleteExecutionResult = (id) => request.delete(`/api/execution-result/${id}`)
export const confirmExecutionResult = (id) => request.put(`/api/execution-result/confirm/${id}`)
export const rejectExecutionResult = (id) => request.put(`/api/execution-result/reject/${id}`)
export const getDocumentSnapshotPage = (params) => request.get('/api/document/page', { params })
export const addDocumentSnapshot = (data) => request.post('/api/document', data)
export const updateDocumentSnapshot = (data) => request.put('/api/document', data)
export const deleteDocumentSnapshot = (id) => request.delete(`/api/document/${id}`)
export const publishDocumentSnapshot = (id) => request.put(`/api/document/publish/${id}`)
export const archiveDocumentSnapshot = (id) => request.put(`/api/document/archive/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
