DROP TABLE IF EXISTS evaluation_appeal;
DROP TABLE IF EXISTS evaluation_record;
DROP TABLE IF EXISTS evaluation_task;
DROP TABLE IF EXISTS evaluation_notice;
DROP TABLE IF EXISTS evaluation_indicator;
DROP TABLE IF EXISTS teacher_profile;
DROP TABLE IF EXISTS teaching_class;
DROP TABLE IF EXISTS subject_info;
DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  phone VARCHAR(20) DEFAULT '',
  email VARCHAR(100) DEFAULT '',
  role VARCHAR(20) NOT NULL,
  class_id BIGINT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  last_login_time DATETIME NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_username UNIQUE (username)
);

CREATE INDEX idx_user_class_id ON sys_user (class_id);

CREATE TABLE subject_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_name VARCHAR(50) NOT NULL,
  subject_code VARCHAR(30) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_subject_code UNIQUE (subject_code)
);

CREATE TABLE teaching_class (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grade_name VARCHAR(30) NOT NULL,
  class_name VARCHAR(30) NOT NULL,
  head_teacher VARCHAR(50) DEFAULT '',
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_grade_class UNIQUE (grade_name, class_name)
);

CREATE TABLE teacher_profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  teacher_no VARCHAR(30) NOT NULL,
  subject_id BIGINT NOT NULL,
  title_name VARCHAR(30) DEFAULT '教师',
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_teacher_user UNIQUE (user_id),
  CONSTRAINT uk_teacher_no UNIQUE (teacher_no)
);

CREATE INDEX idx_teacher_subject_id ON teacher_profile (subject_id);

CREATE TABLE evaluation_indicator (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indicator_name VARCHAR(50) NOT NULL,
  dimension_name VARCHAR(50) NOT NULL,
  weight_value DECIMAL(5,2) NOT NULL,
  sort_no INT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_indicator_dimension ON evaluation_indicator (dimension_name);
CREATE INDEX idx_indicator_sort ON evaluation_indicator (sort_no);

CREATE TABLE evaluation_task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_name VARCHAR(100) NOT NULL,
  term_name VARCHAR(30) NOT NULL,
  class_id BIGINT NOT NULL,
  teacher_id BIGINT NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  creator_id BIGINT NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_task_class_id ON evaluation_task (class_id);
CREATE INDEX idx_task_teacher_id ON evaluation_task (teacher_id);
CREATE INDEX idx_task_status ON evaluation_task (status);

CREATE TABLE evaluation_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  evaluator_id BIGINT NOT NULL,
  teacher_id BIGINT NOT NULL,
  class_id BIGINT NOT NULL,
  attitude_score DECIMAL(5,2) NOT NULL,
  content_score DECIMAL(5,2) NOT NULL,
  method_score DECIMAL(5,2) NOT NULL,
  manage_score DECIMAL(5,2) NOT NULL,
  homework_score DECIMAL(5,2) NOT NULL,
  total_score DECIMAL(6,2) NOT NULL,
  comment_text VARCHAR(1000) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_task_evaluator UNIQUE (task_id, evaluator_id)
);

CREATE INDEX idx_record_teacher_id ON evaluation_record (teacher_id);
CREATE INDEX idx_record_class_id ON evaluation_record (class_id);

CREATE TABLE evaluation_appeal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  teacher_id BIGINT NOT NULL,
  reason_text VARCHAR(1000) NOT NULL,
  reply_text VARCHAR(1000) DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'WAITING',
  handle_by BIGINT NULL,
  handle_time DATETIME NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_appeal_teacher_id ON evaluation_appeal (teacher_id);
CREATE INDEX idx_appeal_status ON evaluation_appeal (status);

CREATE TABLE evaluation_notice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  content_text VARCHAR(2000) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  publish_time DATETIME NULL,
  creator_id BIGINT NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notice_status ON evaluation_notice (status);
CREATE INDEX idx_notice_publish_time ON evaluation_notice (publish_time);
