import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getCarrierCompanyPage = (params) => request.get('/api/carrier/page', { params })
export const addCarrierCompany = (data) => request.post('/api/carrier', data)
export const updateCarrierCompany = (data) => request.put('/api/carrier', data)
export const deleteCarrierCompany = (id) => request.delete(`/api/carrier/${id}`)
export const processCarrierCompany = (id) => request.put(`/api/carrier/process/${id}`)
export const finishCarrierCompany = (id) => request.put(`/api/carrier/finish/${id}`)

export const getVehicleProfilePage = (params) => request.get('/api/vehicle/page', { params })
export const addVehicleProfile = (data) => request.post('/api/vehicle', data)
export const updateVehicleProfile = (data) => request.put('/api/vehicle', data)
export const deleteVehicleProfile = (id) => request.delete(`/api/vehicle/${id}`)
export const processVehicleProfile = (id) => request.put(`/api/vehicle/process/${id}`)
export const finishVehicleProfile = (id) => request.put(`/api/vehicle/finish/${id}`)

export const getDriverProfilePage = (params) => request.get('/api/driver/page', { params })
export const addDriverProfile = (data) => request.post('/api/driver', data)
export const updateDriverProfile = (data) => request.put('/api/driver', data)
export const deleteDriverProfile = (id) => request.delete(`/api/driver/${id}`)
export const processDriverProfile = (id) => request.put(`/api/driver/process/${id}`)
export const finishDriverProfile = (id) => request.put(`/api/driver/finish/${id}`)

export const getGateAppointmentPage = (params) => request.get('/api/appointment/page', { params })
export const addGateAppointment = (data) => request.post('/api/appointment', data)
export const updateGateAppointment = (data) => request.put('/api/appointment', data)
export const deleteGateAppointment = (id) => request.delete(`/api/appointment/${id}`)
export const processGateAppointment = (id) => request.put(`/api/appointment/process/${id}`)
export const finishGateAppointment = (id) => request.put(`/api/appointment/finish/${id}`)

export const getTimeSlotPlanPage = (params) => request.get('/api/slot/page', { params })
export const addTimeSlotPlan = (data) => request.post('/api/slot', data)
export const updateTimeSlotPlan = (data) => request.put('/api/slot', data)
export const deleteTimeSlotPlan = (id) => request.delete(`/api/slot/${id}`)
export const processTimeSlotPlan = (id) => request.put(`/api/slot/process/${id}`)
export const finishTimeSlotPlan = (id) => request.put(`/api/slot/finish/${id}`)

export const getGateCheckinPage = (params) => request.get('/api/checkin/page', { params })
export const addGateCheckin = (data) => request.post('/api/checkin', data)
export const updateGateCheckin = (data) => request.put('/api/checkin', data)
export const deleteGateCheckin = (id) => request.delete(`/api/checkin/${id}`)
export const processGateCheckin = (id) => request.put(`/api/checkin/process/${id}`)
export const finishGateCheckin = (id) => request.put(`/api/checkin/finish/${id}`)

export const getQueueTicketPage = (params) => request.get('/api/queue/page', { params })
export const addQueueTicket = (data) => request.post('/api/queue', data)
export const updateQueueTicket = (data) => request.put('/api/queue', data)
export const deleteQueueTicket = (id) => request.delete(`/api/queue/${id}`)
export const processQueueTicket = (id) => request.put(`/api/queue/process/${id}`)
export const finishQueueTicket = (id) => request.put(`/api/queue/finish/${id}`)

export const getDockDoorPage = (params) => request.get('/api/dock/page', { params })
export const addDockDoor = (data) => request.post('/api/dock', data)
export const updateDockDoor = (data) => request.put('/api/dock', data)
export const deleteDockDoor = (id) => request.delete(`/api/dock/${id}`)
export const processDockDoor = (id) => request.put(`/api/dock/process/${id}`)
export const finishDockDoor = (id) => request.put(`/api/dock/finish/${id}`)

export const getDockAssignmentPage = (params) => request.get('/api/assignment/page', { params })
export const addDockAssignment = (data) => request.post('/api/assignment', data)
export const updateDockAssignment = (data) => request.put('/api/assignment', data)
export const deleteDockAssignment = (id) => request.delete(`/api/assignment/${id}`)
export const processDockAssignment = (id) => request.put(`/api/assignment/process/${id}`)
export const finishDockAssignment = (id) => request.put(`/api/assignment/finish/${id}`)

export const getLoadingTaskPage = (params) => request.get('/api/loading/page', { params })
export const addLoadingTask = (data) => request.post('/api/loading', data)
export const updateLoadingTask = (data) => request.put('/api/loading', data)
export const deleteLoadingTask = (id) => request.delete(`/api/loading/${id}`)
export const processLoadingTask = (id) => request.put(`/api/loading/process/${id}`)
export const finishLoadingTask = (id) => request.put(`/api/loading/finish/${id}`)

export const getTurnaroundRecordPage = (params) => request.get('/api/turnaround/page', { params })
export const addTurnaroundRecord = (data) => request.post('/api/turnaround', data)
export const updateTurnaroundRecord = (data) => request.put('/api/turnaround', data)
export const deleteTurnaroundRecord = (id) => request.delete(`/api/turnaround/${id}`)
export const processTurnaroundRecord = (id) => request.put(`/api/turnaround/process/${id}`)
export const finishTurnaroundRecord = (id) => request.put(`/api/turnaround/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
