import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getCommunityAreaPage = (params) => request.get('/api/area/page', { params })
export const addCommunityArea = (data) => request.post('/api/area', data)
export const updateCommunityArea = (data) => request.put('/api/area', data)
export const deleteCommunityArea = (id) => request.delete(`/api/area/${id}`)
export const processCommunityArea = (id) => request.put(`/api/area/process/${id}`)
export const finishCommunityArea = (id) => request.put(`/api/area/finish/${id}`)

export const getBuildingProfilePage = (params) => request.get('/api/building/page', { params })
export const addBuildingProfile = (data) => request.post('/api/building', data)
export const updateBuildingProfile = (data) => request.put('/api/building', data)
export const deleteBuildingProfile = (id) => request.delete(`/api/building/${id}`)
export const processBuildingProfile = (id) => request.put(`/api/building/process/${id}`)
export const finishBuildingProfile = (id) => request.put(`/api/building/finish/${id}`)

export const getResidentProfilePage = (params) => request.get('/api/resident/page', { params })
export const addResidentProfile = (data) => request.post('/api/resident', data)
export const updateResidentProfile = (data) => request.put('/api/resident', data)
export const deleteResidentProfile = (id) => request.delete(`/api/resident/${id}`)
export const processResidentProfile = (id) => request.put(`/api/resident/process/${id}`)
export const finishResidentProfile = (id) => request.put(`/api/resident/finish/${id}`)

export const getSortingCategoryPage = (params) => request.get('/api/category/page', { params })
export const addSortingCategory = (data) => request.post('/api/category', data)
export const updateSortingCategory = (data) => request.put('/api/category', data)
export const deleteSortingCategory = (id) => request.delete(`/api/category/${id}`)
export const processSortingCategory = (id) => request.put(`/api/category/process/${id}`)
export const finishSortingCategory = (id) => request.put(`/api/category/finish/${id}`)

export const getSortingCheckinPage = (params) => request.get('/api/checkin/page', { params })
export const addSortingCheckin = (data) => request.post('/api/checkin', data)
export const updateSortingCheckin = (data) => request.put('/api/checkin', data)
export const deleteSortingCheckin = (id) => request.delete(`/api/checkin/${id}`)
export const processSortingCheckin = (id) => request.put(`/api/checkin/process/${id}`)
export const finishSortingCheckin = (id) => request.put(`/api/checkin/finish/${id}`)

export const getSupervisionRecordPage = (params) => request.get('/api/supervision/page', { params })
export const addSupervisionRecord = (data) => request.post('/api/supervision', data)
export const updateSupervisionRecord = (data) => request.put('/api/supervision', data)
export const deleteSupervisionRecord = (id) => request.delete(`/api/supervision/${id}`)
export const processSupervisionRecord = (id) => request.put(`/api/supervision/process/${id}`)
export const finishSupervisionRecord = (id) => request.put(`/api/supervision/finish/${id}`)

export const getCorrectionTaskPage = (params) => request.get('/api/correction/page', { params })
export const addCorrectionTask = (data) => request.post('/api/correction', data)
export const updateCorrectionTask = (data) => request.put('/api/correction', data)
export const deleteCorrectionTask = (id) => request.delete(`/api/correction/${id}`)
export const processCorrectionTask = (id) => request.put(`/api/correction/process/${id}`)
export const finishCorrectionTask = (id) => request.put(`/api/correction/finish/${id}`)

export const getPointsLedgerPage = (params) => request.get('/api/points/page', { params })
export const addPointsLedger = (data) => request.post('/api/points', data)
export const updatePointsLedger = (data) => request.put('/api/points', data)
export const deletePointsLedger = (id) => request.delete(`/api/points/${id}`)
export const processPointsLedger = (id) => request.put(`/api/points/process/${id}`)
export const finishPointsLedger = (id) => request.put(`/api/points/finish/${id}`)

export const getRewardCatalogPage = (params) => request.get('/api/reward/page', { params })
export const addRewardCatalog = (data) => request.post('/api/reward', data)
export const updateRewardCatalog = (data) => request.put('/api/reward', data)
export const deleteRewardCatalog = (id) => request.delete(`/api/reward/${id}`)
export const processRewardCatalog = (id) => request.put(`/api/reward/process/${id}`)
export const finishRewardCatalog = (id) => request.put(`/api/reward/finish/${id}`)

export const getExchangeOrderPage = (params) => request.get('/api/exchange/page', { params })
export const addExchangeOrder = (data) => request.post('/api/exchange', data)
export const updateExchangeOrder = (data) => request.put('/api/exchange', data)
export const deleteExchangeOrder = (id) => request.delete(`/api/exchange/${id}`)
export const processExchangeOrder = (id) => request.put(`/api/exchange/process/${id}`)
export const finishExchangeOrder = (id) => request.put(`/api/exchange/finish/${id}`)

export const getBuildingRankingPage = (params) => request.get('/api/ranking/page', { params })
export const addBuildingRanking = (data) => request.post('/api/ranking', data)
export const updateBuildingRanking = (data) => request.put('/api/ranking', data)
export const deleteBuildingRanking = (id) => request.delete(`/api/ranking/${id}`)
export const processBuildingRanking = (id) => request.put(`/api/ranking/process/${id}`)
export const finishBuildingRanking = (id) => request.put(`/api/ranking/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
