import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getDeviceProfilePage = (params) => request.get('/api/device/page', { params })
export const addDeviceProfile = (data) => request.post('/api/device', data)
export const updateDeviceProfile = (data) => request.put('/api/device', data)
export const deleteDeviceProfile = (id) => request.delete(`/api/device/${id}`)
export const activateDeviceProfile = (id) => request.put(`/api/device/activate/${id}`)
export const finishDeviceProfile = (id) => request.put(`/api/device/finish/${id}`)
export const getDeviceCategoryPage = (params) => request.get('/api/category/page', { params })
export const addDeviceCategory = (data) => request.post('/api/category', data)
export const updateDeviceCategory = (data) => request.put('/api/category', data)
export const deleteDeviceCategory = (id) => request.delete(`/api/category/${id}`)
export const activateDeviceCategory = (id) => request.put(`/api/category/activate/${id}`)
export const finishDeviceCategory = (id) => request.put(`/api/category/finish/${id}`)
export const getDepartmentInfoPage = (params) => request.get('/api/department/page', { params })
export const addDepartmentInfo = (data) => request.post('/api/department', data)
export const updateDepartmentInfo = (data) => request.put('/api/department', data)
export const deleteDepartmentInfo = (id) => request.delete(`/api/department/${id}`)
export const activateDepartmentInfo = (id) => request.put(`/api/department/activate/${id}`)
export const finishDepartmentInfo = (id) => request.put(`/api/department/finish/${id}`)
export const getBorrowRequestPage = (params) => request.get('/api/request/page', { params })
export const addBorrowRequest = (data) => request.post('/api/request', data)
export const updateBorrowRequest = (data) => request.put('/api/request', data)
export const deleteBorrowRequest = (id) => request.delete(`/api/request/${id}`)
export const submitBorrowRequest = (id) => request.put(`/api/request/submit/${id}`)
export const approveBorrowRequest = (id) => request.put(`/api/request/approve/${id}`)
export const getBorrowRecordPage = (params) => request.get('/api/borrow/page', { params })
export const addBorrowRecord = (data) => request.post('/api/borrow', data)
export const updateBorrowRecord = (data) => request.put('/api/borrow', data)
export const deleteBorrowRecord = (id) => request.delete(`/api/borrow/${id}`)
export const processBorrowRecord = (id) => request.put(`/api/borrow/process/${id}`)
export const finishBorrowRecord = (id) => request.put(`/api/borrow/finish/${id}`)
export const getReturnRecordPage = (params) => request.get('/api/return/page', { params })
export const addReturnRecord = (data) => request.post('/api/return', data)
export const updateReturnRecord = (data) => request.put('/api/return', data)
export const deleteReturnRecord = (id) => request.delete(`/api/return/${id}`)
export const submitReturnRecord = (id) => request.put(`/api/return/submit/${id}`)
export const approveReturnRecord = (id) => request.put(`/api/return/approve/${id}`)
export const getSterilizationBatchPage = (params) => request.get('/api/batch/page', { params })
export const addSterilizationBatch = (data) => request.post('/api/batch', data)
export const updateSterilizationBatch = (data) => request.put('/api/batch', data)
export const deleteSterilizationBatch = (id) => request.delete(`/api/batch/${id}`)
export const processSterilizationBatch = (id) => request.put(`/api/batch/process/${id}`)
export const finishSterilizationBatch = (id) => request.put(`/api/batch/finish/${id}`)
export const getSterilizationRecordPage = (params) => request.get('/api/sterilization/page', { params })
export const addSterilizationRecord = (data) => request.post('/api/sterilization', data)
export const updateSterilizationRecord = (data) => request.put('/api/sterilization', data)
export const deleteSterilizationRecord = (id) => request.delete(`/api/sterilization/${id}`)
export const submitSterilizationRecord = (id) => request.put(`/api/sterilization/submit/${id}`)
export const approveSterilizationRecord = (id) => request.put(`/api/sterilization/approve/${id}`)
export const getQrTracePage = (params) => request.get('/api/trace/page', { params })
export const addQrTrace = (data) => request.post('/api/trace', data)
export const updateQrTrace = (data) => request.put('/api/trace', data)
export const deleteQrTrace = (id) => request.delete(`/api/trace/${id}`)
export const activateQrTrace = (id) => request.put(`/api/trace/activate/${id}`)
export const finishQrTrace = (id) => request.put(`/api/trace/finish/${id}`)
export const getMaintenanceRecordPage = (params) => request.get('/api/maintenance/page', { params })
export const addMaintenanceRecord = (data) => request.post('/api/maintenance', data)
export const updateMaintenanceRecord = (data) => request.put('/api/maintenance', data)
export const deleteMaintenanceRecord = (id) => request.delete(`/api/maintenance/${id}`)
export const submitMaintenanceRecord = (id) => request.put(`/api/maintenance/submit/${id}`)
export const approveMaintenanceRecord = (id) => request.put(`/api/maintenance/approve/${id}`)
export const getInspectionTaskPage = (params) => request.get('/api/inspection/page', { params })
export const addInspectionTask = (data) => request.post('/api/inspection', data)
export const updateInspectionTask = (data) => request.put('/api/inspection', data)
export const deleteInspectionTask = (id) => request.delete(`/api/inspection/${id}`)
export const processInspectionTask = (id) => request.put(`/api/inspection/process/${id}`)
export const finishInspectionTask = (id) => request.put(`/api/inspection/finish/${id}`)
export const getRiskAlertPage = (params) => request.get('/api/alert/page', { params })
export const addRiskAlert = (data) => request.post('/api/alert', data)
export const updateRiskAlert = (data) => request.put('/api/alert', data)
export const deleteRiskAlert = (id) => request.delete(`/api/alert/${id}`)
export const processRiskAlert = (id) => request.put(`/api/alert/process/${id}`)
export const finishRiskAlert = (id) => request.put(`/api/alert/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
