import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getCanteenInfoPage = (params) => request.get('/api/canteen/page', { params })
export const addCanteenInfo = (data) => request.post('/api/canteen', data)
export const updateCanteenInfo = (data) => request.put('/api/canteen', data)
export const deleteCanteenInfo = (id) => request.delete(`/api/canteen/${id}`)
export const processCanteenInfo = (id) => request.put(`/api/canteen/process/${id}`)
export const finishCanteenInfo = (id) => request.put(`/api/canteen/finish/${id}`)

export const getKitchenAreaPage = (params) => request.get('/api/area/page', { params })
export const addKitchenArea = (data) => request.post('/api/area', data)
export const updateKitchenArea = (data) => request.put('/api/area', data)
export const deleteKitchenArea = (id) => request.delete(`/api/area/${id}`)
export const processKitchenArea = (id) => request.put(`/api/area/process/${id}`)
export const finishKitchenArea = (id) => request.put(`/api/area/finish/${id}`)

export const getDishMenuPage = (params) => request.get('/api/dish/page', { params })
export const addDishMenu = (data) => request.post('/api/dish', data)
export const updateDishMenu = (data) => request.put('/api/dish', data)
export const deleteDishMenu = (id) => request.delete(`/api/dish/${id}`)
export const processDishMenu = (id) => request.put(`/api/dish/process/${id}`)
export const finishDishMenu = (id) => request.put(`/api/dish/finish/${id}`)

export const getSampleRetentionPage = (params) => request.get('/api/sample/page', { params })
export const addSampleRetention = (data) => request.post('/api/sample', data)
export const updateSampleRetention = (data) => request.put('/api/sample', data)
export const deleteSampleRetention = (id) => request.delete(`/api/sample/${id}`)
export const processSampleRetention = (id) => request.put(`/api/sample/process/${id}`)
export const finishSampleRetention = (id) => request.put(`/api/sample/finish/${id}`)

export const getSampleStoragePage = (params) => request.get('/api/storage/page', { params })
export const addSampleStorage = (data) => request.post('/api/storage', data)
export const updateSampleStorage = (data) => request.put('/api/storage', data)
export const deleteSampleStorage = (id) => request.delete(`/api/storage/${id}`)
export const processSampleStorage = (id) => request.put(`/api/storage/process/${id}`)
export const finishSampleStorage = (id) => request.put(`/api/storage/finish/${id}`)

export const getIngredientAcceptancePage = (params) => request.get('/api/ingredient/page', { params })
export const addIngredientAcceptance = (data) => request.post('/api/ingredient', data)
export const updateIngredientAcceptance = (data) => request.put('/api/ingredient', data)
export const deleteIngredientAcceptance = (id) => request.delete(`/api/ingredient/${id}`)
export const processIngredientAcceptance = (id) => request.put(`/api/ingredient/process/${id}`)
export const finishIngredientAcceptance = (id) => request.put(`/api/ingredient/finish/${id}`)

export const getDisinfectionRecordPage = (params) => request.get('/api/disinfection/page', { params })
export const addDisinfectionRecord = (data) => request.post('/api/disinfection', data)
export const updateDisinfectionRecord = (data) => request.put('/api/disinfection', data)
export const deleteDisinfectionRecord = (id) => request.delete(`/api/disinfection/${id}`)
export const processDisinfectionRecord = (id) => request.put(`/api/disinfection/process/${id}`)
export const finishDisinfectionRecord = (id) => request.put(`/api/disinfection/finish/${id}`)

export const getHygieneInspectionPage = (params) => request.get('/api/inspection/page', { params })
export const addHygieneInspection = (data) => request.post('/api/inspection', data)
export const updateHygieneInspection = (data) => request.put('/api/inspection', data)
export const deleteHygieneInspection = (id) => request.delete(`/api/inspection/${id}`)
export const processHygieneInspection = (id) => request.put(`/api/inspection/process/${id}`)
export const finishHygieneInspection = (id) => request.put(`/api/inspection/finish/${id}`)

export const getIssueRectificationPage = (params) => request.get('/api/rectification/page', { params })
export const addIssueRectification = (data) => request.post('/api/rectification', data)
export const updateIssueRectification = (data) => request.put('/api/rectification', data)
export const deleteIssueRectification = (id) => request.delete(`/api/rectification/${id}`)
export const processIssueRectification = (id) => request.put(`/api/rectification/process/${id}`)
export const finishIssueRectification = (id) => request.put(`/api/rectification/finish/${id}`)

export const getRiskWarningPage = (params) => request.get('/api/risk/page', { params })
export const addRiskWarning = (data) => request.post('/api/risk', data)
export const updateRiskWarning = (data) => request.put('/api/risk', data)
export const deleteRiskWarning = (id) => request.delete(`/api/risk/${id}`)
export const processRiskWarning = (id) => request.put(`/api/risk/process/${id}`)
export const finishRiskWarning = (id) => request.put(`/api/risk/finish/${id}`)

export const getWasteDisposalPage = (params) => request.get('/api/waste/page', { params })
export const addWasteDisposal = (data) => request.post('/api/waste', data)
export const updateWasteDisposal = (data) => request.put('/api/waste', data)
export const deleteWasteDisposal = (id) => request.delete(`/api/waste/${id}`)
export const processWasteDisposal = (id) => request.put(`/api/waste/process/${id}`)
export const finishWasteDisposal = (id) => request.put(`/api/waste/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
