import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getWaterStationPage = (params) => request.get('/api/station/page', { params })
export const addWaterStation = (data) => request.post('/api/station', data)
export const updateWaterStation = (data) => request.put('/api/station', data)
export const deleteWaterStation = (id) => request.delete(`/api/station/${id}`)
export const processWaterStation = (id) => request.put(`/api/station/process/${id}`)
export const finishWaterStation = (id) => request.put(`/api/station/finish/${id}`)

export const getPipelineSectionPage = (params) => request.get('/api/section/page', { params })
export const addPipelineSection = (data) => request.post('/api/section', data)
export const updatePipelineSection = (data) => request.put('/api/section', data)
export const deletePipelineSection = (id) => request.delete(`/api/section/${id}`)
export const processPipelineSection = (id) => request.put(`/api/section/process/${id}`)
export const finishPipelineSection = (id) => request.put(`/api/section/finish/${id}`)

export const getPatrolRoutePage = (params) => request.get('/api/route/page', { params })
export const addPatrolRoute = (data) => request.post('/api/route', data)
export const updatePatrolRoute = (data) => request.put('/api/route', data)
export const deletePatrolRoute = (id) => request.delete(`/api/route/${id}`)
export const processPatrolRoute = (id) => request.put(`/api/route/process/${id}`)
export const finishPatrolRoute = (id) => request.put(`/api/route/finish/${id}`)

export const getValveLedgerPage = (params) => request.get('/api/valve/page', { params })
export const addValveLedger = (data) => request.post('/api/valve', data)
export const updateValveLedger = (data) => request.put('/api/valve', data)
export const deleteValveLedger = (id) => request.delete(`/api/valve/${id}`)
export const processValveLedger = (id) => request.put(`/api/valve/process/${id}`)
export const finishValveLedger = (id) => request.put(`/api/valve/finish/${id}`)

export const getPatrolTaskPage = (params) => request.get('/api/task/page', { params })
export const addPatrolTask = (data) => request.post('/api/task', data)
export const updatePatrolTask = (data) => request.put('/api/task', data)
export const deletePatrolTask = (id) => request.delete(`/api/task/${id}`)
export const processPatrolTask = (id) => request.put(`/api/task/process/${id}`)
export const finishPatrolTask = (id) => request.put(`/api/task/finish/${id}`)

export const getPatrolRecordPage = (params) => request.get('/api/record/page', { params })
export const addPatrolRecord = (data) => request.post('/api/record', data)
export const updatePatrolRecord = (data) => request.put('/api/record', data)
export const deletePatrolRecord = (id) => request.delete(`/api/record/${id}`)
export const processPatrolRecord = (id) => request.put(`/api/record/process/${id}`)
export const finishPatrolRecord = (id) => request.put(`/api/record/finish/${id}`)

export const getFaultReportPage = (params) => request.get('/api/fault/page', { params })
export const addFaultReport = (data) => request.post('/api/fault', data)
export const updateFaultReport = (data) => request.put('/api/fault', data)
export const deleteFaultReport = (id) => request.delete(`/api/fault/${id}`)
export const processFaultReport = (id) => request.put(`/api/fault/process/${id}`)
export const finishFaultReport = (id) => request.put(`/api/fault/finish/${id}`)

export const getDispatchOrderPage = (params) => request.get('/api/dispatch/page', { params })
export const addDispatchOrder = (data) => request.post('/api/dispatch', data)
export const updateDispatchOrder = (data) => request.put('/api/dispatch', data)
export const deleteDispatchOrder = (id) => request.delete(`/api/dispatch/${id}`)
export const processDispatchOrder = (id) => request.put(`/api/dispatch/process/${id}`)
export const finishDispatchOrder = (id) => request.put(`/api/dispatch/finish/${id}`)

export const getMaintenanceReceiptPage = (params) => request.get('/api/receipt/page', { params })
export const addMaintenanceReceipt = (data) => request.post('/api/receipt', data)
export const updateMaintenanceReceipt = (data) => request.put('/api/receipt', data)
export const deleteMaintenanceReceipt = (id) => request.delete(`/api/receipt/${id}`)
export const processMaintenanceReceipt = (id) => request.put(`/api/receipt/process/${id}`)
export const finishMaintenanceReceipt = (id) => request.put(`/api/receipt/finish/${id}`)

export const getSparePartLedgerPage = (params) => request.get('/api/spare/page', { params })
export const addSparePartLedger = (data) => request.post('/api/spare', data)
export const updateSparePartLedger = (data) => request.put('/api/spare', data)
export const deleteSparePartLedger = (id) => request.delete(`/api/spare/${id}`)
export const processSparePartLedger = (id) => request.put(`/api/spare/process/${id}`)
export const finishSparePartLedger = (id) => request.put(`/api/spare/finish/${id}`)

export const getRiskWarningPage = (params) => request.get('/api/warning/page', { params })
export const addRiskWarning = (data) => request.post('/api/warning', data)
export const updateRiskWarning = (data) => request.put('/api/warning', data)
export const deleteRiskWarning = (id) => request.delete(`/api/warning/${id}`)
export const processRiskWarning = (id) => request.put(`/api/warning/process/${id}`)
export const finishRiskWarning = (id) => request.put(`/api/warning/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
