DROP TABLE IF EXISTS user_coupon;
DROP TABLE IF EXISTS coupon;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS ticket_order;
DROP TABLE IF EXISTS seat;
DROP TABLE IF EXISTS showtime;
DROP TABLE IF EXISTS hall;
DROP TABLE IF EXISTS cinema;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  nickname VARCHAR(50),
  phone VARCHAR(20),
  email VARCHAR(100),
  avatar VARCHAR(255),
  balance DECIMAL(10,2) DEFAULT 0,
  role VARCHAR(20) DEFAULT 'USER',
  status TINYINT DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_username UNIQUE (username),
  CONSTRAINT uk_user_phone UNIQUE (phone)
);

CREATE INDEX idx_user_role ON user (role);
CREATE INDEX idx_user_status ON user (status);

CREATE TABLE movie (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  type VARCHAR(20),
  category VARCHAR(50),
  duration INT,
  director VARCHAR(100),
  actors CLOB,
  poster VARCHAR(255),
  description CLOB,
  rating DECIMAL(3,1) DEFAULT 0,
  comment_count INT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'ON',
  is_recommend TINYINT DEFAULT 0,
  release_date DATE,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_movie_title ON movie (title);
CREATE INDEX idx_movie_status ON movie (status);
CREATE INDEX idx_movie_recommend ON movie (is_recommend);

CREATE TABLE cinema (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  address VARCHAR(255),
  phone VARCHAR(20),
  business_hours VARCHAR(50),
  facilities CLOB,
  status TINYINT DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cinema_name ON cinema (name);
CREATE INDEX idx_cinema_status ON cinema (status);

CREATE TABLE hall (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cinema_id BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL,
  type VARCHAR(20),
  total_seats INT,
  seat_rows INT DEFAULT 8,
  seat_cols INT DEFAULT 10,
  seat_layout CLOB,
  status TINYINT DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_hall_cinema ON hall (cinema_id);
CREATE INDEX idx_hall_status ON hall (status);

CREATE TABLE showtime (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id BIGINT NOT NULL,
  hall_id BIGINT NOT NULL,
  cinema_id BIGINT NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  status VARCHAR(20) DEFAULT 'SELLING',
  available_seats INT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_showtime_movie ON showtime (movie_id);
CREATE INDEX idx_showtime_hall ON showtime (hall_id);
CREATE INDEX idx_showtime_cinema ON showtime (cinema_id);
CREATE INDEX idx_showtime_start ON showtime (start_time);
CREATE INDEX idx_showtime_status ON showtime (status);

CREATE TABLE seat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  showtime_id BIGINT NOT NULL,
  row_num INT NOT NULL,
  col_num INT NOT NULL,
  seat_type VARCHAR(20) DEFAULT 'NORMAL',
  price DECIMAL(10,2),
  status VARCHAR(20) DEFAULT 'AVAILABLE',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_showtime_position UNIQUE (showtime_id, row_num, col_num)
);

CREATE INDEX idx_seat_showtime ON seat (showtime_id);
CREATE INDEX idx_seat_status ON seat (status);

CREATE TABLE ticket_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no VARCHAR(50) NOT NULL,
  user_id BIGINT NOT NULL,
  showtime_id BIGINT NOT NULL,
  movie_title VARCHAR(100),
  cinema_name VARCHAR(100),
  hall_name VARCHAR(50),
  show_time DATETIME,
  seat_info VARCHAR(255),
  total_amount DECIMAL(10,2),
  discount_amount DECIMAL(10,2) DEFAULT 0,
  pay_amount DECIMAL(10,2),
  coupon_id BIGINT,
  status VARCHAR(20) DEFAULT 'WAIT_PAY',
  pay_time DATETIME,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_order_no UNIQUE (order_no)
);

CREATE INDEX idx_order_user ON ticket_order (user_id);
CREATE INDEX idx_order_status ON ticket_order (status);
CREATE INDEX idx_order_create ON ticket_order (create_time);

CREATE TABLE ticket (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  ticket_no VARCHAR(50) NOT NULL,
  qr_code VARCHAR(255),
  status VARCHAR(20) DEFAULT 'UNUSED',
  use_time DATETIME,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_ticket_no UNIQUE (ticket_no)
);

CREATE INDEX idx_ticket_order ON ticket (order_id);
CREATE INDEX idx_ticket_status ON ticket (status);

CREATE TABLE payment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT,
  pay_no VARCHAR(50) NOT NULL,
  pay_type VARCHAR(20),
  pay_amount DECIMAL(10,2),
  status VARCHAR(20) DEFAULT 'WAIT',
  pay_time DATETIME,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_pay_no UNIQUE (pay_no)
);

CREATE INDEX idx_payment_order ON payment (order_id);
CREATE INDEX idx_payment_status ON payment (status);

CREATE TABLE comment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  order_id BIGINT,
  rating INT,
  content CLOB,
  status VARCHAR(20) DEFAULT 'PENDING',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_comment_movie ON comment (movie_id);
CREATE INDEX idx_comment_user ON comment (user_id);
CREATE INDEX idx_comment_status ON comment (status);

CREATE TABLE coupon (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(20),
  discount_type VARCHAR(20),
  discount_value DECIMAL(10,2),
  min_amount DECIMAL(10,2) DEFAULT 0,
  total_count INT DEFAULT 0,
  used_count INT DEFAULT 0,
  start_time DATETIME,
  end_time DATETIME,
  status TINYINT DEFAULT 1,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_coupon_status ON coupon (status);
CREATE INDEX idx_coupon_type ON coupon (type);

CREATE TABLE user_coupon (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  coupon_id BIGINT NOT NULL,
  status VARCHAR(20) DEFAULT 'UNUSED',
  use_time DATETIME,
  expire_time DATETIME,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_coupon_user ON user_coupon (user_id);
CREATE INDEX idx_user_coupon_coupon ON user_coupon (coupon_id);
CREATE INDEX idx_user_coupon_status ON user_coupon (status);
