import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getBusRoutePage = (params) => request.get('/api/route/page', { params })
export const addBusRoute = (data) => request.post('/api/route', data)
export const updateBusRoute = (data) => request.put('/api/route', data)
export const deleteBusRoute = (id) => request.delete(`/api/route/${id}`)
export const processBusRoute = (id) => request.put(`/api/route/process/${id}`)
export const finishBusRoute = (id) => request.put(`/api/route/finish/${id}`)

export const getBusStopPage = (params) => request.get('/api/stop/page', { params })
export const addBusStop = (data) => request.post('/api/stop', data)
export const updateBusStop = (data) => request.put('/api/stop', data)
export const deleteBusStop = (id) => request.delete(`/api/stop/${id}`)
export const processBusStop = (id) => request.put(`/api/stop/process/${id}`)
export const finishBusStop = (id) => request.put(`/api/stop/finish/${id}`)

export const getVehicleProfilePage = (params) => request.get('/api/vehicle/page', { params })
export const addVehicleProfile = (data) => request.post('/api/vehicle', data)
export const updateVehicleProfile = (data) => request.put('/api/vehicle', data)
export const deleteVehicleProfile = (id) => request.delete(`/api/vehicle/${id}`)
export const processVehicleProfile = (id) => request.put(`/api/vehicle/process/${id}`)
export const finishVehicleProfile = (id) => request.put(`/api/vehicle/finish/${id}`)

export const getDriverProfilePage = (params) => request.get('/api/driver/page', { params })
export const addDriverProfile = (data) => request.post('/api/driver', data)
export const updateDriverProfile = (data) => request.put('/api/driver', data)
export const deleteDriverProfile = (id) => request.delete(`/api/driver/${id}`)
export const processDriverProfile = (id) => request.put(`/api/driver/process/${id}`)
export const finishDriverProfile = (id) => request.put(`/api/driver/finish/${id}`)

export const getStudentProfilePage = (params) => request.get('/api/student/page', { params })
export const addStudentProfile = (data) => request.post('/api/student', data)
export const updateStudentProfile = (data) => request.put('/api/student', data)
export const deleteStudentProfile = (id) => request.delete(`/api/student/${id}`)
export const processStudentProfile = (id) => request.put(`/api/student/process/${id}`)
export const finishStudentProfile = (id) => request.put(`/api/student/finish/${id}`)

export const getGuardianProfilePage = (params) => request.get('/api/guardian/page', { params })
export const addGuardianProfile = (data) => request.post('/api/guardian', data)
export const updateGuardianProfile = (data) => request.put('/api/guardian', data)
export const deleteGuardianProfile = (id) => request.delete(`/api/guardian/${id}`)
export const processGuardianProfile = (id) => request.put(`/api/guardian/process/${id}`)
export const finishGuardianProfile = (id) => request.put(`/api/guardian/finish/${id}`)

export const getRideReservationPage = (params) => request.get('/api/reservation/page', { params })
export const addRideReservation = (data) => request.post('/api/reservation', data)
export const updateRideReservation = (data) => request.put('/api/reservation', data)
export const deleteRideReservation = (id) => request.delete(`/api/reservation/${id}`)
export const processRideReservation = (id) => request.put(`/api/reservation/process/${id}`)
export const finishRideReservation = (id) => request.put(`/api/reservation/finish/${id}`)

export const getBoardingCheckinPage = (params) => request.get('/api/boarding/page', { params })
export const addBoardingCheckin = (data) => request.post('/api/boarding', data)
export const updateBoardingCheckin = (data) => request.put('/api/boarding', data)
export const deleteBoardingCheckin = (id) => request.delete(`/api/boarding/${id}`)
export const processBoardingCheckin = (id) => request.put(`/api/boarding/process/${id}`)
export const finishBoardingCheckin = (id) => request.put(`/api/boarding/finish/${id}`)

export const getDropoffCheckinPage = (params) => request.get('/api/dropoff/page', { params })
export const addDropoffCheckin = (data) => request.post('/api/dropoff', data)
export const updateDropoffCheckin = (data) => request.put('/api/dropoff', data)
export const deleteDropoffCheckin = (id) => request.delete(`/api/dropoff/${id}`)
export const processDropoffCheckin = (id) => request.put(`/api/dropoff/process/${id}`)
export const finishDropoffCheckin = (id) => request.put(`/api/dropoff/finish/${id}`)

export const getExceptionAlertPage = (params) => request.get('/api/exception/page', { params })
export const addExceptionAlert = (data) => request.post('/api/exception', data)
export const updateExceptionAlert = (data) => request.put('/api/exception', data)
export const deleteExceptionAlert = (id) => request.delete(`/api/exception/${id}`)
export const processExceptionAlert = (id) => request.put(`/api/exception/process/${id}`)
export const finishExceptionAlert = (id) => request.put(`/api/exception/finish/${id}`)

export const getParentNoticePage = (params) => request.get('/api/notice/page', { params })
export const addParentNotice = (data) => request.post('/api/notice', data)
export const updateParentNotice = (data) => request.put('/api/notice', data)
export const deleteParentNotice = (id) => request.delete(`/api/notice/${id}`)
export const processParentNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishParentNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
