import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getVenueInfoPage = (params) => request.get('/api/venue/page', { params })
export const addVenueInfo = (data) => request.post('/api/venue', data)
export const updateVenueInfo = (data) => request.put('/api/venue', data)
export const deleteVenueInfo = (id) => request.delete(`/api/venue/${id}`)
export const processVenueInfo = (id) => request.put(`/api/venue/process/${id}`)
export const finishVenueInfo = (id) => request.put(`/api/venue/finish/${id}`)

export const getTicketProductPage = (params) => request.get('/api/ticket/page', { params })
export const addTicketProduct = (data) => request.post('/api/ticket', data)
export const updateTicketProduct = (data) => request.put('/api/ticket', data)
export const deleteTicketProduct = (id) => request.delete(`/api/ticket/${id}`)
export const processTicketProduct = (id) => request.put(`/api/ticket/process/${id}`)
export const finishTicketProduct = (id) => request.put(`/api/ticket/finish/${id}`)

export const getTicketOrderPage = (params) => request.get('/api/ticket-order/page', { params })
export const addTicketOrder = (data) => request.post('/api/ticket-order', data)
export const updateTicketOrder = (data) => request.put('/api/ticket-order', data)
export const deleteTicketOrder = (id) => request.delete(`/api/ticket-order/${id}`)
export const processTicketOrder = (id) => request.put(`/api/ticket-order/process/${id}`)
export const finishTicketOrder = (id) => request.put(`/api/ticket-order/finish/${id}`)

export const getGuideProfilePage = (params) => request.get('/api/guide/page', { params })
export const addGuideProfile = (data) => request.post('/api/guide', data)
export const updateGuideProfile = (data) => request.put('/api/guide', data)
export const deleteGuideProfile = (id) => request.delete(`/api/guide/${id}`)
export const processGuideProfile = (id) => request.put(`/api/guide/process/${id}`)
export const finishGuideProfile = (id) => request.put(`/api/guide/finish/${id}`)

export const getGuideSchedulePage = (params) => request.get('/api/schedule/page', { params })
export const addGuideSchedule = (data) => request.post('/api/schedule', data)
export const updateGuideSchedule = (data) => request.put('/api/schedule', data)
export const deleteGuideSchedule = (id) => request.delete(`/api/schedule/${id}`)
export const processGuideSchedule = (id) => request.put(`/api/schedule/process/${id}`)
export const finishGuideSchedule = (id) => request.put(`/api/schedule/finish/${id}`)

export const getGuideBookingPage = (params) => request.get('/api/booking/page', { params })
export const addGuideBooking = (data) => request.post('/api/booking', data)
export const updateGuideBooking = (data) => request.put('/api/booking', data)
export const deleteGuideBooking = (id) => request.delete(`/api/booking/${id}`)
export const processGuideBooking = (id) => request.put(`/api/booking/process/${id}`)
export const finishGuideBooking = (id) => request.put(`/api/booking/finish/${id}`)

export const getTicketVerificationPage = (params) => request.get('/api/verification/page', { params })
export const addTicketVerification = (data) => request.post('/api/verification', data)
export const updateTicketVerification = (data) => request.put('/api/verification', data)
export const deleteTicketVerification = (id) => request.delete(`/api/verification/${id}`)
export const processTicketVerification = (id) => request.put(`/api/verification/process/${id}`)
export const finishTicketVerification = (id) => request.put(`/api/verification/finish/${id}`)

export const getCrowdFlowRecordPage = (params) => request.get('/api/crowd-flow/page', { params })
export const addCrowdFlowRecord = (data) => request.post('/api/crowd-flow', data)
export const updateCrowdFlowRecord = (data) => request.put('/api/crowd-flow', data)
export const deleteCrowdFlowRecord = (id) => request.delete(`/api/crowd-flow/${id}`)
export const processCrowdFlowRecord = (id) => request.put(`/api/crowd-flow/process/${id}`)
export const finishCrowdFlowRecord = (id) => request.put(`/api/crowd-flow/finish/${id}`)

export const getVisitorFeedbackPage = (params) => request.get('/api/feedback/page', { params })
export const addVisitorFeedback = (data) => request.post('/api/feedback', data)
export const updateVisitorFeedback = (data) => request.put('/api/feedback', data)
export const deleteVisitorFeedback = (id) => request.delete(`/api/feedback/${id}`)
export const processVisitorFeedback = (id) => request.put(`/api/feedback/process/${id}`)
export const finishVisitorFeedback = (id) => request.put(`/api/feedback/finish/${id}`)

export const getMarketingActivityPage = (params) => request.get('/api/activity/page', { params })
export const addMarketingActivity = (data) => request.post('/api/activity', data)
export const updateMarketingActivity = (data) => request.put('/api/activity', data)
export const deleteMarketingActivity = (id) => request.delete(`/api/activity/${id}`)
export const processMarketingActivity = (id) => request.put(`/api/activity/process/${id}`)
export const finishMarketingActivity = (id) => request.put(`/api/activity/finish/${id}`)

export const getVenueNoticePage = (params) => request.get('/api/notice/page', { params })
export const addVenueNotice = (data) => request.post('/api/notice', data)
export const updateVenueNotice = (data) => request.put('/api/notice', data)
export const deleteVenueNotice = (id) => request.delete(`/api/notice/${id}`)
export const processVenueNotice = (id) => request.put(`/api/notice/process/${id}`)
export const finishVenueNotice = (id) => request.put(`/api/notice/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
