import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getCompanyProfilePage = (params) => request.get('/api/company/page', { params })
export const addCompanyProfile = (data) => request.post('/api/company', data)
export const updateCompanyProfile = (data) => request.put('/api/company', data)
export const deleteCompanyProfile = (id) => request.delete(`/api/company/${id}`)
export const activateCompanyProfile = (id) => request.put(`/api/company/activate/${id}`)
export const finishCompanyProfile = (id) => request.put(`/api/company/finish/${id}`)
export const getEmissionFactorPage = (params) => request.get('/api/factor/page', { params })
export const addEmissionFactor = (data) => request.post('/api/factor', data)
export const updateEmissionFactor = (data) => request.put('/api/factor', data)
export const deleteEmissionFactor = (id) => request.delete(`/api/factor/${id}`)
export const activateEmissionFactor = (id) => request.put(`/api/factor/activate/${id}`)
export const finishEmissionFactor = (id) => request.put(`/api/factor/finish/${id}`)
export const getAccountingPeriodPage = (params) => request.get('/api/period/page', { params })
export const addAccountingPeriod = (data) => request.post('/api/period', data)
export const updateAccountingPeriod = (data) => request.put('/api/period', data)
export const deleteAccountingPeriod = (id) => request.delete(`/api/period/${id}`)
export const submitAccountingPeriod = (id) => request.put(`/api/period/submit/${id}`)
export const approveAccountingPeriod = (id) => request.put(`/api/period/approve/${id}`)
export const getEnergyConsumptionPage = (params) => request.get('/api/consumption/page', { params })
export const addEnergyConsumption = (data) => request.post('/api/consumption', data)
export const updateEnergyConsumption = (data) => request.put('/api/consumption', data)
export const deleteEnergyConsumption = (id) => request.delete(`/api/consumption/${id}`)
export const submitEnergyConsumption = (id) => request.put(`/api/consumption/submit/${id}`)
export const approveEnergyConsumption = (id) => request.put(`/api/consumption/approve/${id}`)
export const getEmissionRecordPage = (params) => request.get('/api/emission/page', { params })
export const addEmissionRecord = (data) => request.post('/api/emission', data)
export const updateEmissionRecord = (data) => request.put('/api/emission', data)
export const deleteEmissionRecord = (id) => request.delete(`/api/emission/${id}`)
export const submitEmissionRecord = (id) => request.put(`/api/emission/submit/${id}`)
export const approveEmissionRecord = (id) => request.put(`/api/emission/approve/${id}`)
export const getReductionTaskPage = (params) => request.get('/api/task/page', { params })
export const addReductionTask = (data) => request.post('/api/task', data)
export const updateReductionTask = (data) => request.put('/api/task', data)
export const deleteReductionTask = (id) => request.delete(`/api/task/${id}`)
export const processReductionTask = (id) => request.put(`/api/task/process/${id}`)
export const finishReductionTask = (id) => request.put(`/api/task/finish/${id}`)
export const getReductionMeasurePage = (params) => request.get('/api/measure/page', { params })
export const addReductionMeasure = (data) => request.post('/api/measure', data)
export const updateReductionMeasure = (data) => request.put('/api/measure', data)
export const deleteReductionMeasure = (id) => request.delete(`/api/measure/${id}`)
export const processReductionMeasure = (id) => request.put(`/api/measure/process/${id}`)
export const finishReductionMeasure = (id) => request.put(`/api/measure/finish/${id}`)
export const getCarbonQuotaPage = (params) => request.get('/api/quota/page', { params })
export const addCarbonQuota = (data) => request.post('/api/quota', data)
export const updateCarbonQuota = (data) => request.put('/api/quota', data)
export const deleteCarbonQuota = (id) => request.delete(`/api/quota/${id}`)
export const activateCarbonQuota = (id) => request.put(`/api/quota/activate/${id}`)
export const finishCarbonQuota = (id) => request.put(`/api/quota/finish/${id}`)
export const getVerificationReportPage = (params) => request.get('/api/report/page', { params })
export const addVerificationReport = (data) => request.post('/api/report', data)
export const updateVerificationReport = (data) => request.put('/api/report', data)
export const deleteVerificationReport = (id) => request.delete(`/api/report/${id}`)
export const submitVerificationReport = (id) => request.put(`/api/report/submit/${id}`)
export const approveVerificationReport = (id) => request.put(`/api/report/approve/${id}`)
export const getDataAttachmentPage = (params) => request.get('/api/attachment/page', { params })
export const addDataAttachment = (data) => request.post('/api/attachment', data)
export const updateDataAttachment = (data) => request.put('/api/attachment', data)
export const deleteDataAttachment = (id) => request.delete(`/api/attachment/${id}`)
export const submitDataAttachment = (id) => request.put(`/api/attachment/submit/${id}`)
export const approveDataAttachment = (id) => request.put(`/api/attachment/approve/${id}`)
export const getAlertRulePage = (params) => request.get('/api/rule/page', { params })
export const addAlertRule = (data) => request.post('/api/rule', data)
export const updateAlertRule = (data) => request.put('/api/rule', data)
export const deleteAlertRule = (id) => request.delete(`/api/rule/${id}`)
export const activateAlertRule = (id) => request.put(`/api/rule/activate/${id}`)
export const finishAlertRule = (id) => request.put(`/api/rule/finish/${id}`)
export const getCarbonWarningPage = (params) => request.get('/api/warning/page', { params })
export const addCarbonWarning = (data) => request.post('/api/warning', data)
export const updateCarbonWarning = (data) => request.put('/api/warning', data)
export const deleteCarbonWarning = (id) => request.delete(`/api/warning/${id}`)
export const processCarbonWarning = (id) => request.put(`/api/warning/process/${id}`)
export const finishCarbonWarning = (id) => request.put(`/api/warning/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
