import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const getDataSourceConfigPage = (params) => request.get('/api/source/page', { params })
export const addDataSourceConfig = (data) => request.post('/api/source', data)
export const updateDataSourceConfig = (data) => request.put('/api/source', data)
export const deleteDataSourceConfig = (id) => request.delete(`/api/source/${id}`)
export const enableDataSourceConfig = (id) => request.put(`/api/source/enable/${id}`)
export const disableDataSourceConfig = (id) => request.put(`/api/source/disable/${id}`)
export const getDataSetCatalogPage = (params) => request.get('/api/dataset/page', { params })
export const addDataSetCatalog = (data) => request.post('/api/dataset', data)
export const updateDataSetCatalog = (data) => request.put('/api/dataset', data)
export const deleteDataSetCatalog = (id) => request.delete(`/api/dataset/${id}`)
export const publishDataSetCatalog = (id) => request.put(`/api/dataset/publish/${id}`)
export const archiveDataSetCatalog = (id) => request.put(`/api/dataset/archive/${id}`)
export const getSensitiveRulePage = (params) => request.get('/api/rule/page', { params })
export const addSensitiveRule = (data) => request.post('/api/rule', data)
export const updateSensitiveRule = (data) => request.put('/api/rule', data)
export const deleteSensitiveRule = (id) => request.delete(`/api/rule/${id}`)
export const enableSensitiveRule = (id) => request.put(`/api/rule/enable/${id}`)
export const disableSensitiveRule = (id) => request.put(`/api/rule/disable/${id}`)
export const getRecognitionTaskPage = (params) => request.get('/api/recognition-task/page', { params })
export const addRecognitionTask = (data) => request.post('/api/recognition-task', data)
export const updateRecognitionTask = (data) => request.put('/api/recognition-task', data)
export const deleteRecognitionTask = (id) => request.delete(`/api/recognition-task/${id}`)
export const startRecognitionTask = (id) => request.put(`/api/recognition-task/start/${id}`)
export const finishRecognitionTask = (id) => request.put(`/api/recognition-task/finish/${id}`)
export const failRecognitionTask = (id) => request.put(`/api/recognition-task/fail/${id}`)
export const getRecognitionResultPage = (params) => request.get('/api/recognition-result/page', { params })
export const addRecognitionResult = (data) => request.post('/api/recognition-result', data)
export const updateRecognitionResult = (data) => request.put('/api/recognition-result', data)
export const deleteRecognitionResult = (id) => request.delete(`/api/recognition-result/${id}`)
export const confirmRecognitionResult = (id) => request.put(`/api/recognition-result/confirm/${id}`)
export const ignoreRecognitionResult = (id) => request.put(`/api/recognition-result/ignore/${id}`)
export const getMaskingStrategyPage = (params) => request.get('/api/strategy/page', { params })
export const addMaskingStrategy = (data) => request.post('/api/strategy', data)
export const updateMaskingStrategy = (data) => request.put('/api/strategy', data)
export const deleteMaskingStrategy = (id) => request.delete(`/api/strategy/${id}`)
export const enableMaskingStrategy = (id) => request.put(`/api/strategy/enable/${id}`)
export const disableMaskingStrategy = (id) => request.put(`/api/strategy/disable/${id}`)
export const getMaskingTaskPage = (params) => request.get('/api/masking-task/page', { params })
export const addMaskingTask = (data) => request.post('/api/masking-task', data)
export const updateMaskingTask = (data) => request.put('/api/masking-task', data)
export const deleteMaskingTask = (id) => request.delete(`/api/masking-task/${id}`)
export const submitMaskingTask = (id) => request.put(`/api/masking-task/submit/${id}`)
export const startMaskingTask = (id) => request.put(`/api/masking-task/start/${id}`)
export const finishMaskingTask = (id) => request.put(`/api/masking-task/finish/${id}`)
export const failMaskingTask = (id) => request.put(`/api/masking-task/fail/${id}`)
export const getMaskingRecordPage = (params) => request.get('/api/masking-record/page', { params })
export const addMaskingRecord = (data) => request.post('/api/masking-record', data)
export const updateMaskingRecord = (data) => request.put('/api/masking-record', data)
export const deleteMaskingRecord = (id) => request.delete(`/api/masking-record/${id}`)
export const getFieldLineagePage = (params) => request.get('/api/lineage/page', { params })
export const addFieldLineage = (data) => request.post('/api/lineage', data)
export const updateFieldLineage = (data) => request.put('/api/lineage', data)
export const deleteFieldLineage = (id) => request.delete(`/api/lineage/${id}`)
export const getAccessRequestPage = (params) => request.get('/api/access-request/page', { params })
export const addAccessRequest = (data) => request.post('/api/access-request', data)
export const updateAccessRequest = (data) => request.put('/api/access-request', data)
export const deleteAccessRequest = (id) => request.delete(`/api/access-request/${id}`)
export const submitAccessRequest = (id) => request.put(`/api/access-request/submit/${id}`)
export const approveAccessRequest = (id) => request.put(`/api/access-request/approve/${id}`)
export const rejectAccessRequest = (id) => request.put(`/api/access-request/reject/${id}`)
export const revokeAccessRequest = (id) => request.put(`/api/access-request/revoke/${id}`)
export const getExportApprovalPage = (params) => request.get('/api/export-approval/page', { params })
export const addExportApproval = (data) => request.post('/api/export-approval', data)
export const updateExportApproval = (data) => request.put('/api/export-approval', data)
export const deleteExportApproval = (id) => request.delete(`/api/export-approval/${id}`)
export const approveExportApproval = (id) => request.put(`/api/export-approval/approve/${id}`)
export const rejectExportApproval = (id) => request.put(`/api/export-approval/reject/${id}`)
export const finishExportApproval = (id) => request.put(`/api/export-approval/finish/${id}`)
export const getRiskAlertPage = (params) => request.get('/api/risk-alert/page', { params })
export const addRiskAlert = (data) => request.post('/api/risk-alert', data)
export const updateRiskAlert = (data) => request.put('/api/risk-alert', data)
export const deleteRiskAlert = (id) => request.delete(`/api/risk-alert/${id}`)
export const ackRiskAlert = (id) => request.put(`/api/risk-alert/ack/${id}`)
export const resolveRiskAlert = (id) => request.put(`/api/risk-alert/resolve/${id}`)
export const closeRiskAlert = (id) => request.put(`/api/risk-alert/close/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
