import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getReserveWarehousePage = (params) => request.get('/api/warehouse/page', { params })
export const addReserveWarehouse = (data) => request.post('/api/warehouse', data)
export const updateReserveWarehouse = (data) => request.put('/api/warehouse', data)
export const deleteReserveWarehouse = (id) => request.delete(`/api/warehouse/${id}`)
export const processReserveWarehouse = (id) => request.put(`/api/warehouse/process/${id}`)
export const finishReserveWarehouse = (id) => request.put(`/api/warehouse/finish/${id}`)

export const getMaterialCategoryPage = (params) => request.get('/api/category/page', { params })
export const addMaterialCategory = (data) => request.post('/api/category', data)
export const updateMaterialCategory = (data) => request.put('/api/category', data)
export const deleteMaterialCategory = (id) => request.delete(`/api/category/${id}`)
export const processMaterialCategory = (id) => request.put(`/api/category/process/${id}`)
export const finishMaterialCategory = (id) => request.put(`/api/category/finish/${id}`)

export const getMaterialLedgerPage = (params) => request.get('/api/material/page', { params })
export const addMaterialLedger = (data) => request.post('/api/material', data)
export const updateMaterialLedger = (data) => request.put('/api/material', data)
export const deleteMaterialLedger = (id) => request.delete(`/api/material/${id}`)
export const processMaterialLedger = (id) => request.put(`/api/material/process/${id}`)
export const finishMaterialLedger = (id) => request.put(`/api/material/finish/${id}`)

export const getStockBatchPage = (params) => request.get('/api/batch/page', { params })
export const addStockBatch = (data) => request.post('/api/batch', data)
export const updateStockBatch = (data) => request.put('/api/batch', data)
export const deleteStockBatch = (id) => request.delete(`/api/batch/${id}`)
export const processStockBatch = (id) => request.put(`/api/batch/process/${id}`)
export const finishStockBatch = (id) => request.put(`/api/batch/finish/${id}`)

export const getInventoryCheckPage = (params) => request.get('/api/check/page', { params })
export const addInventoryCheck = (data) => request.post('/api/check', data)
export const updateInventoryCheck = (data) => request.put('/api/check', data)
export const deleteInventoryCheck = (id) => request.delete(`/api/check/${id}`)
export const processInventoryCheck = (id) => request.put(`/api/check/process/${id}`)
export const finishInventoryCheck = (id) => request.put(`/api/check/finish/${id}`)

export const getCheckDifferencePage = (params) => request.get('/api/difference/page', { params })
export const addCheckDifference = (data) => request.post('/api/difference', data)
export const updateCheckDifference = (data) => request.put('/api/difference', data)
export const deleteCheckDifference = (id) => request.delete(`/api/difference/${id}`)
export const processCheckDifference = (id) => request.put(`/api/difference/process/${id}`)
export const finishCheckDifference = (id) => request.put(`/api/difference/finish/${id}`)

export const getRequisitionOrderPage = (params) => request.get('/api/requisition/page', { params })
export const addRequisitionOrder = (data) => request.post('/api/requisition', data)
export const updateRequisitionOrder = (data) => request.put('/api/requisition', data)
export const deleteRequisitionOrder = (id) => request.delete(`/api/requisition/${id}`)
export const processRequisitionOrder = (id) => request.put(`/api/requisition/process/${id}`)
export const finishRequisitionOrder = (id) => request.put(`/api/requisition/finish/${id}`)

export const getAllocationApprovalPage = (params) => request.get('/api/approval/page', { params })
export const addAllocationApproval = (data) => request.post('/api/approval', data)
export const updateAllocationApproval = (data) => request.put('/api/approval', data)
export const deleteAllocationApproval = (id) => request.delete(`/api/approval/${id}`)
export const processAllocationApproval = (id) => request.put(`/api/approval/process/${id}`)
export const finishAllocationApproval = (id) => request.put(`/api/approval/finish/${id}`)

export const getDispatchTaskPage = (params) => request.get('/api/dispatch/page', { params })
export const addDispatchTask = (data) => request.post('/api/dispatch', data)
export const updateDispatchTask = (data) => request.put('/api/dispatch', data)
export const deleteDispatchTask = (id) => request.delete(`/api/dispatch/${id}`)
export const processDispatchTask = (id) => request.put(`/api/dispatch/process/${id}`)
export const finishDispatchTask = (id) => request.put(`/api/dispatch/finish/${id}`)

export const getOutboundRecordPage = (params) => request.get('/api/outbound/page', { params })
export const addOutboundRecord = (data) => request.post('/api/outbound', data)
export const updateOutboundRecord = (data) => request.put('/api/outbound', data)
export const deleteOutboundRecord = (id) => request.delete(`/api/outbound/${id}`)
export const processOutboundRecord = (id) => request.put(`/api/outbound/process/${id}`)
export const finishOutboundRecord = (id) => request.put(`/api/outbound/finish/${id}`)

export const getStockWarningPage = (params) => request.get('/api/warning/page', { params })
export const addStockWarning = (data) => request.post('/api/warning', data)
export const updateStockWarning = (data) => request.put('/api/warning', data)
export const deleteStockWarning = (id) => request.delete(`/api/warning/${id}`)
export const processStockWarning = (id) => request.put(`/api/warning/process/${id}`)
export const finishStockWarning = (id) => request.put(`/api/warning/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
