import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getDroneDevicePage = (params) => request.get('/api/drone/page', { params })
export const addDroneDevice = (data) => request.post('/api/drone', data)
export const updateDroneDevice = (data) => request.put('/api/drone', data)
export const deleteDroneDevice = (id) => request.delete(`/api/drone/${id}`)
export const onlineDroneDevice = (id) => request.put(`/api/drone/online/${id}`)
export const offlineDroneDevice = (id) => request.put(`/api/drone/offline/${id}`)
export const getPilotProfilePage = (params) => request.get('/api/pilot/page', { params })
export const addPilotProfile = (data) => request.post('/api/pilot', data)
export const updatePilotProfile = (data) => request.put('/api/pilot', data)
export const deletePilotProfile = (id) => request.delete(`/api/pilot/${id}`)
export const enablePilotProfile = (id) => request.put(`/api/pilot/enable/${id}`)
export const disablePilotProfile = (id) => request.put(`/api/pilot/disable/${id}`)
export const getInspectionZonePage = (params) => request.get('/api/zone/page', { params })
export const addInspectionZone = (data) => request.post('/api/zone', data)
export const updateInspectionZone = (data) => request.put('/api/zone', data)
export const deleteInspectionZone = (id) => request.delete(`/api/zone/${id}`)
export const enableInspectionZone = (id) => request.put(`/api/zone/enable/${id}`)
export const disableInspectionZone = (id) => request.put(`/api/zone/disable/${id}`)
export const getFlightRoutePage = (params) => request.get('/api/route/page', { params })
export const addFlightRoute = (data) => request.post('/api/route', data)
export const updateFlightRoute = (data) => request.put('/api/route', data)
export const deleteFlightRoute = (id) => request.delete(`/api/route/${id}`)
export const publishFlightRoute = (id) => request.put(`/api/route/publish/${id}`)
export const disableFlightRoute = (id) => request.put(`/api/route/disable/${id}`)
export const getInspectionTaskPage = (params) => request.get('/api/task/page', { params })
export const addInspectionTask = (data) => request.post('/api/task', data)
export const updateInspectionTask = (data) => request.put('/api/task', data)
export const deleteInspectionTask = (id) => request.delete(`/api/task/${id}`)
export const assignInspectionTask = (id) => request.put(`/api/task/assign/${id}`)
export const finishInspectionTask = (id) => request.put(`/api/task/finish/${id}`)
export const getFlightRecordPage = (params) => request.get('/api/flight/page', { params })
export const addFlightRecord = (data) => request.post('/api/flight', data)
export const updateFlightRecord = (data) => request.put('/api/flight', data)
export const deleteFlightRecord = (id) => request.delete(`/api/flight/${id}`)
export const finishFlightRecord = (id) => request.put(`/api/flight/finish/${id}`)
export const warnFlightRecord = (id) => request.put(`/api/flight/warn/${id}`)
export const getDefectReportPage = (params) => request.get('/api/defect/page', { params })
export const addDefectReport = (data) => request.post('/api/defect', data)
export const updateDefectReport = (data) => request.put('/api/defect', data)
export const deleteDefectReport = (id) => request.delete(`/api/defect/${id}`)
export const confirmDefectReport = (id) => request.put(`/api/defect/confirm/${id}`)
export const closeDefectReport = (id) => request.put(`/api/defect/close/${id}`)
export const getDefectImagePage = (params) => request.get('/api/image/page', { params })
export const addDefectImage = (data) => request.post('/api/image', data)
export const updateDefectImage = (data) => request.put('/api/image', data)
export const deleteDefectImage = (id) => request.delete(`/api/image/${id}`)
export const confirmDefectImage = (id) => request.put(`/api/image/confirm/${id}`)
export const rejectDefectImage = (id) => request.put(`/api/image/reject/${id}`)
export const getRectificationOrderPage = (params) => request.get('/api/rectify/page', { params })
export const addRectificationOrder = (data) => request.post('/api/rectify', data)
export const updateRectificationOrder = (data) => request.put('/api/rectify', data)
export const deleteRectificationOrder = (id) => request.delete(`/api/rectify/${id}`)
export const submitRectificationOrder = (id) => request.put(`/api/rectify/submit/${id}`)
export const closeRectificationOrder = (id) => request.put(`/api/rectify/close/${id}`)
export const getBatteryStationPage = (params) => request.get('/api/station/page', { params })
export const addBatteryStation = (data) => request.post('/api/station', data)
export const updateBatteryStation = (data) => request.put('/api/station', data)
export const deleteBatteryStation = (id) => request.delete(`/api/station/${id}`)
export const enableBatteryStation = (id) => request.put(`/api/station/enable/${id}`)
export const warnBatteryStation = (id) => request.put(`/api/station/warn/${id}`)
export const getMaintenanceRecordPage = (params) => request.get('/api/maintenance/page', { params })
export const addMaintenanceRecord = (data) => request.post('/api/maintenance', data)
export const updateMaintenanceRecord = (data) => request.put('/api/maintenance', data)
export const deleteMaintenanceRecord = (id) => request.delete(`/api/maintenance/${id}`)
export const finishMaintenanceRecord = (id) => request.put(`/api/maintenance/finish/${id}`)
export const closeMaintenanceRecord = (id) => request.put(`/api/maintenance/close/${id}`)
export const getRiskWarningPage = (params) => request.get('/api/warning/page', { params })
export const addRiskWarning = (data) => request.post('/api/warning', data)
export const updateRiskWarning = (data) => request.put('/api/warning', data)
export const deleteRiskWarning = (id) => request.delete(`/api/warning/${id}`)
export const assignRiskWarning = (id) => request.put(`/api/warning/assign/${id}`)
export const closeRiskWarning = (id) => request.put(`/api/warning/close/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
