import request from './request'

export const login = data => request.post('/api/auth/login', data)
export const register = data => request.post('/api/auth/register', data)
export const getInfo = () => request.get('/api/auth/info')
export const updatePassword = data => request.put('/api/auth/password', data)
export const updateUserInfo = data => request.put('/api/auth/info', data)

export const getUserList = params => request.get('/api/user/list', { params })
export const auditUser = (id, data) => request.put(`/api/user/audit/${id}`, data)
export const updateUserStatus = (id, data) => request.put(`/api/user/status/${id}`, data)
export const deleteUser = id => request.delete(`/api/user/${id}`)

export const getAlumniList = params => request.get('/api/alumni/list', { params })
export const getAlumniById = id => request.get(`/api/alumni/${id}`)
export const getMyAlumni = () => request.get('/api/alumni/my')
export const updateAlumni = data => request.put('/api/alumni', data)
export const getAlumniContacts = params => request.get('/api/alumni/contacts', { params })
export const getAlumniDistribution = () => request.get('/api/alumni/distribution')

export const getGradeList = () => request.get('/api/grade/list')
export const addGrade = data => request.post('/api/grade', data)
export const updateGrade = data => request.put('/api/grade', data)
export const deleteGrade = id => request.delete(`/api/grade/${id}`)

export const getClassList = params => request.get('/api/class/list', { params })
export const addClass = data => request.post('/api/class', data)
export const updateClass = data => request.put('/api/class', data)
export const deleteClass = id => request.delete(`/api/class/${id}`)

export const getNewsList = params => request.get('/api/news/list', { params })
export const getNewsById = id => request.get(`/api/news/${id}`)
export const addNews = data => request.post('/api/news', data)
export const updateNews = data => request.put('/api/news', data)
export const deleteNews = id => request.delete(`/api/news/${id}`)
export const getNewsComments = id => request.get(`/api/news/${id}/comments`)
export const addNewsComment = (id, data) => request.post(`/api/news/${id}/comment`, data)

export const getActivityList = params => request.get('/api/activity/list', { params })
export const getActivityById = id => request.get(`/api/activity/${id}`)
export const addActivity = data => request.post('/api/activity', data)
export const updateActivity = data => request.put('/api/activity', data)
export const deleteActivity = id => request.delete(`/api/activity/${id}`)
export const signActivity = id => request.post(`/api/activity/${id}/sign`)
export const cancelSignActivity = id => request.delete(`/api/activity/${id}/sign`)
export const checkActivity = id => request.post(`/api/activity/${id}/check`)
export const getActivitySigns = id => request.get(`/api/activity/${id}/signs`)
export const getActivityPhotos = id => request.get(`/api/activity/${id}/photos`)
export const addActivityPhoto = (id, data) => request.post(`/api/activity/${id}/photo`, data)

export const getDonationProjects = params => request.get('/api/donation/project/list', { params })
export const getDonationProjectById = id => request.get(`/api/donation/project/${id}`)
export const addDonationProject = data => request.post('/api/donation/project', data)
export const updateDonationProject = data => request.put('/api/donation/project', data)
export const deleteDonationProject = id => request.delete(`/api/donation/project/${id}`)
export const donate = data => request.post('/api/donation/donate', data)
export const getDonationRecords = params => request.get('/api/donation/record/list', { params })
export const confirmDonation = id => request.put(`/api/donation/record/${id}/confirm`)

export const getCompanyList = params => request.get('/api/company/list', { params })
export const getCompanyById = id => request.get(`/api/company/${id}`)
export const addCompany = data => request.post('/api/company', data)
export const updateCompany = data => request.put('/api/company', data)
export const deleteCompany = id => request.delete(`/api/company/${id}`)
export const auditCompany = (id, data) => request.put(`/api/company/${id}/audit`, data)

export const getJobList = params => request.get('/api/job/list', { params })
export const getJobById = id => request.get(`/api/job/${id}`)
export const addJob = data => request.post('/api/job', data)
export const updateJob = data => request.put('/api/job', data)
export const deleteJob = id => request.delete(`/api/job/${id}`)
export const auditJob = (id, data) => request.put(`/api/job/${id}/audit`, data)

export const getForumCategories = () => request.get('/api/forum/category/list')
export const addForumCategory = data => request.post('/api/forum/category', data)
export const updateForumCategory = data => request.put('/api/forum/category', data)
export const deleteForumCategory = id => request.delete(`/api/forum/category/${id}`)
export const getForumPosts = params => request.get('/api/forum/post/list', { params })
export const getForumPostById = id => request.get(`/api/forum/post/${id}`)
export const addForumPost = data => request.post('/api/forum/post', data)
export const deleteForumPost = id => request.delete(`/api/forum/post/${id}`)
export const getForumReplies = id => request.get(`/api/forum/post/${id}/replies`)
export const addForumReply = (id, data) => request.post(`/api/forum/post/${id}/reply`, data)
export const likeForumPost = id => request.post(`/api/forum/post/${id}/like`)
export const unlikeForumPost = id => request.delete(`/api/forum/post/${id}/like`)

export const getBannerList = () => request.get('/api/banner/list')
export const getBannerAll = () => request.get('/api/banner/all')
export const addBanner = data => request.post('/api/banner', data)
export const updateBanner = data => request.put('/api/banner', data)
export const deleteBanner = id => request.delete(`/api/banner/${id}`)

export const getLogList = params => request.get('/api/log/list', { params })
export const clearLog = () => request.delete('/api/log/clear')

export const getStats = () => request.get('/api/stats/overview')

export const uploadFile = file => {
  const formData = new FormData()
  formData.append('file', file)
  return request.post('/api/upload', formData)
}
