import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getChargingStationPage = (params) => request.get('/api/station/page', { params })
export const addChargingStation = (data) => request.post('/api/station', data)
export const updateChargingStation = (data) => request.put('/api/station', data)
export const deleteChargingStation = (id) => request.delete(`/api/station/${id}`)
export const enableChargingStation = (id) => request.put(`/api/station/enable/${id}`)
export const disableChargingStation = (id) => request.put(`/api/station/disable/${id}`)
export const getChargingPilePage = (params) => request.get('/api/pile/page', { params })
export const addChargingPile = (data) => request.post('/api/pile', data)
export const updateChargingPile = (data) => request.put('/api/pile', data)
export const deleteChargingPile = (id) => request.delete(`/api/pile/${id}`)
export const availableChargingPile = (id) => request.put(`/api/pile/available/${id}`)
export const disableChargingPile = (id) => request.put(`/api/pile/disable/${id}`)
export const getUserVehiclePage = (params) => request.get('/api/vehicle/page', { params })
export const addUserVehicle = (data) => request.post('/api/vehicle', data)
export const updateUserVehicle = (data) => request.put('/api/vehicle', data)
export const deleteUserVehicle = (id) => request.delete(`/api/vehicle/${id}`)
export const enableUserVehicle = (id) => request.put(`/api/vehicle/enable/${id}`)
export const disableUserVehicle = (id) => request.put(`/api/vehicle/disable/${id}`)
export const getAppointmentOrderPage = (params) => request.get('/api/appointment/page', { params })
export const addAppointmentOrder = (data) => request.post('/api/appointment', data)
export const updateAppointmentOrder = (data) => request.put('/api/appointment', data)
export const deleteAppointmentOrder = (id) => request.delete(`/api/appointment/${id}`)
export const reserveAppointmentOrder = (id) => request.put(`/api/appointment/reserve/${id}`)
export const finishAppointmentOrder = (id) => request.put(`/api/appointment/finish/${id}`)
export const getChargingSessionPage = (params) => request.get('/api/session/page', { params })
export const addChargingSession = (data) => request.post('/api/session', data)
export const updateChargingSession = (data) => request.put('/api/session', data)
export const deleteChargingSession = (id) => request.delete(`/api/session/${id}`)
export const finishChargingSession = (id) => request.put(`/api/session/finish/${id}`)
export const closeChargingSession = (id) => request.put(`/api/session/close/${id}`)
export const getFaultReportPage = (params) => request.get('/api/fault/page', { params })
export const addFaultReport = (data) => request.post('/api/fault', data)
export const updateFaultReport = (data) => request.put('/api/fault', data)
export const deleteFaultReport = (id) => request.delete(`/api/fault/${id}`)
export const confirmFaultReport = (id) => request.put(`/api/fault/confirm/${id}`)
export const closeFaultReport = (id) => request.put(`/api/fault/close/${id}`)
export const getRepairWorkOrderPage = (params) => request.get('/api/repair/page', { params })
export const addRepairWorkOrder = (data) => request.post('/api/repair', data)
export const updateRepairWorkOrder = (data) => request.put('/api/repair', data)
export const deleteRepairWorkOrder = (id) => request.delete(`/api/repair/${id}`)
export const assignRepairWorkOrder = (id) => request.put(`/api/repair/assign/${id}`)
export const finishRepairWorkOrder = (id) => request.put(`/api/repair/finish/${id}`)
export const getMaintenancePlanPage = (params) => request.get('/api/plan/page', { params })
export const addMaintenancePlan = (data) => request.post('/api/plan', data)
export const updateMaintenancePlan = (data) => request.put('/api/plan', data)
export const deleteMaintenancePlan = (id) => request.delete(`/api/plan/${id}`)
export const publishMaintenancePlan = (id) => request.put(`/api/plan/publish/${id}`)
export const finishMaintenancePlan = (id) => request.put(`/api/plan/finish/${id}`)
export const getElectricityPricePage = (params) => request.get('/api/price/page', { params })
export const addElectricityPrice = (data) => request.post('/api/price', data)
export const updateElectricityPrice = (data) => request.put('/api/price', data)
export const deleteElectricityPrice = (id) => request.delete(`/api/price/${id}`)
export const enableElectricityPrice = (id) => request.put(`/api/price/enable/${id}`)
export const disableElectricityPrice = (id) => request.put(`/api/price/disable/${id}`)
export const getPaymentRecordPage = (params) => request.get('/api/payment/page', { params })
export const addPaymentRecord = (data) => request.post('/api/payment', data)
export const updatePaymentRecord = (data) => request.put('/api/payment', data)
export const deletePaymentRecord = (id) => request.delete(`/api/payment/${id}`)
export const refundPaymentRecord = (id) => request.put(`/api/payment/refund/${id}`)
export const finishPaymentRecord = (id) => request.put(`/api/payment/finish/${id}`)
export const getRevenueStatisticPage = (params) => request.get('/api/revenue/page', { params })
export const addRevenueStatistic = (data) => request.post('/api/revenue', data)
export const updateRevenueStatistic = (data) => request.put('/api/revenue', data)
export const deleteRevenueStatistic = (id) => request.delete(`/api/revenue/${id}`)
export const confirmRevenueStatistic = (id) => request.put(`/api/revenue/confirm/${id}`)
export const closeRevenueStatistic = (id) => request.put(`/api/revenue/close/${id}`)
export const getEnergyMonitorPage = (params) => request.get('/api/energy/page', { params })
export const addEnergyMonitor = (data) => request.post('/api/energy', data)
export const updateEnergyMonitor = (data) => request.put('/api/energy', data)
export const deleteEnergyMonitor = (id) => request.delete(`/api/energy/${id}`)
export const warnEnergyMonitor = (id) => request.put(`/api/energy/warn/${id}`)
export const recoverEnergyMonitor = (id) => request.put(`/api/energy/recover/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
