import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getLiveStudioPage = (params) => request.get('/api/studio/page', { params })
export const addLiveStudio = (data) => request.post('/api/studio', data)
export const updateLiveStudio = (data) => request.put('/api/studio', data)
export const deleteLiveStudio = (id) => request.delete(`/api/studio/${id}`)
export const processLiveStudio = (id) => request.put(`/api/studio/process/${id}`)
export const finishLiveStudio = (id) => request.put(`/api/studio/finish/${id}`)

export const getAnchorProfilePage = (params) => request.get('/api/anchor/page', { params })
export const addAnchorProfile = (data) => request.post('/api/anchor', data)
export const updateAnchorProfile = (data) => request.put('/api/anchor', data)
export const deleteAnchorProfile = (id) => request.delete(`/api/anchor/${id}`)
export const processAnchorProfile = (id) => request.put(`/api/anchor/process/${id}`)
export const finishAnchorProfile = (id) => request.put(`/api/anchor/finish/${id}`)

export const getMerchantProfilePage = (params) => request.get('/api/merchant/page', { params })
export const addMerchantProfile = (data) => request.post('/api/merchant', data)
export const updateMerchantProfile = (data) => request.put('/api/merchant', data)
export const deleteMerchantProfile = (id) => request.delete(`/api/merchant/${id}`)
export const processMerchantProfile = (id) => request.put(`/api/merchant/process/${id}`)
export const finishMerchantProfile = (id) => request.put(`/api/merchant/finish/${id}`)

export const getProductCatalogPage = (params) => request.get('/api/product/page', { params })
export const addProductCatalog = (data) => request.post('/api/product', data)
export const updateProductCatalog = (data) => request.put('/api/product', data)
export const deleteProductCatalog = (id) => request.delete(`/api/product/${id}`)
export const processProductCatalog = (id) => request.put(`/api/product/process/${id}`)
export const finishProductCatalog = (id) => request.put(`/api/product/finish/${id}`)

export const getSampleLedgerPage = (params) => request.get('/api/sample/page', { params })
export const addSampleLedger = (data) => request.post('/api/sample', data)
export const updateSampleLedger = (data) => request.put('/api/sample', data)
export const deleteSampleLedger = (id) => request.delete(`/api/sample/${id}`)
export const processSampleLedger = (id) => request.put(`/api/sample/process/${id}`)
export const finishSampleLedger = (id) => request.put(`/api/sample/finish/${id}`)

export const getSampleLoanPage = (params) => request.get('/api/loan/page', { params })
export const addSampleLoan = (data) => request.post('/api/loan', data)
export const updateSampleLoan = (data) => request.put('/api/loan', data)
export const deleteSampleLoan = (id) => request.delete(`/api/loan/${id}`)
export const processSampleLoan = (id) => request.put(`/api/loan/process/${id}`)
export const finishSampleLoan = (id) => request.put(`/api/loan/finish/${id}`)

export const getAnchorSchedulePage = (params) => request.get('/api/schedule/page', { params })
export const addAnchorSchedule = (data) => request.post('/api/schedule', data)
export const updateAnchorSchedule = (data) => request.put('/api/schedule', data)
export const deleteAnchorSchedule = (id) => request.delete(`/api/schedule/${id}`)
export const processAnchorSchedule = (id) => request.put(`/api/schedule/process/${id}`)
export const finishAnchorSchedule = (id) => request.put(`/api/schedule/finish/${id}`)

export const getSelectionReviewPage = (params) => request.get('/api/review/page', { params })
export const addSelectionReview = (data) => request.post('/api/review', data)
export const updateSelectionReview = (data) => request.put('/api/review', data)
export const deleteSelectionReview = (id) => request.delete(`/api/review/${id}`)
export const processSelectionReview = (id) => request.put(`/api/review/process/${id}`)
export const finishSelectionReview = (id) => request.put(`/api/review/finish/${id}`)

export const getLivePlanPage = (params) => request.get('/api/plan/page', { params })
export const addLivePlan = (data) => request.post('/api/plan', data)
export const updateLivePlan = (data) => request.put('/api/plan', data)
export const deleteLivePlan = (id) => request.delete(`/api/plan/${id}`)
export const processLivePlan = (id) => request.put(`/api/plan/process/${id}`)
export const finishLivePlan = (id) => request.put(`/api/plan/finish/${id}`)

export const getLiveSessionPage = (params) => request.get('/api/session/page', { params })
export const addLiveSession = (data) => request.post('/api/session', data)
export const updateLiveSession = (data) => request.put('/api/session', data)
export const deleteLiveSession = (id) => request.delete(`/api/session/${id}`)
export const processLiveSession = (id) => request.put(`/api/session/process/${id}`)
export const finishLiveSession = (id) => request.put(`/api/session/finish/${id}`)

export const getLiveReplayPage = (params) => request.get('/api/replay/page', { params })
export const addLiveReplay = (data) => request.post('/api/replay', data)
export const updateLiveReplay = (data) => request.put('/api/replay', data)
export const deleteLiveReplay = (id) => request.delete(`/api/replay/${id}`)
export const processLiveReplay = (id) => request.put(`/api/replay/process/${id}`)
export const finishLiveReplay = (id) => request.put(`/api/replay/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
