import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getHospitalWardPage = (params) => request.get('/api/ward/page', { params })
export const addHospitalWard = (data) => request.post('/api/ward', data)
export const updateHospitalWard = (data) => request.put('/api/ward', data)
export const deleteHospitalWard = (id) => request.delete(`/api/ward/${id}`)
export const processHospitalWard = (id) => request.put(`/api/ward/process/${id}`)
export const finishHospitalWard = (id) => request.put(`/api/ward/finish/${id}`)

export const getPatientProfilePage = (params) => request.get('/api/patient/page', { params })
export const addPatientProfile = (data) => request.post('/api/patient', data)
export const updatePatientProfile = (data) => request.put('/api/patient', data)
export const deletePatientProfile = (id) => request.delete(`/api/patient/${id}`)
export const processPatientProfile = (id) => request.put(`/api/patient/process/${id}`)
export const finishPatientProfile = (id) => request.put(`/api/patient/finish/${id}`)

export const getCaregiverProfilePage = (params) => request.get('/api/caregiver/page', { params })
export const addCaregiverProfile = (data) => request.post('/api/caregiver', data)
export const updateCaregiverProfile = (data) => request.put('/api/caregiver', data)
export const deleteCaregiverProfile = (id) => request.delete(`/api/caregiver/${id}`)
export const processCaregiverProfile = (id) => request.put(`/api/caregiver/process/${id}`)
export const finishCaregiverProfile = (id) => request.put(`/api/caregiver/finish/${id}`)

export const getCareAppointmentPage = (params) => request.get('/api/appointment/page', { params })
export const addCareAppointment = (data) => request.post('/api/appointment', data)
export const updateCareAppointment = (data) => request.put('/api/appointment', data)
export const deleteCareAppointment = (id) => request.delete(`/api/appointment/${id}`)
export const processCareAppointment = (id) => request.put(`/api/appointment/process/${id}`)
export const finishCareAppointment = (id) => request.put(`/api/appointment/finish/${id}`)

export const getAppointmentReviewPage = (params) => request.get('/api/review/page', { params })
export const addAppointmentReview = (data) => request.post('/api/review', data)
export const updateAppointmentReview = (data) => request.put('/api/review', data)
export const deleteAppointmentReview = (id) => request.delete(`/api/review/${id}`)
export const processAppointmentReview = (id) => request.put(`/api/review/process/${id}`)
export const finishAppointmentReview = (id) => request.put(`/api/review/finish/${id}`)

export const getCaregiverSchedulePage = (params) => request.get('/api/schedule/page', { params })
export const addCaregiverSchedule = (data) => request.post('/api/schedule', data)
export const updateCaregiverSchedule = (data) => request.put('/api/schedule', data)
export const deleteCaregiverSchedule = (id) => request.delete(`/api/schedule/${id}`)
export const processCaregiverSchedule = (id) => request.put(`/api/schedule/process/${id}`)
export const finishCaregiverSchedule = (id) => request.put(`/api/schedule/finish/${id}`)

export const getServiceAssignmentPage = (params) => request.get('/api/assignment/page', { params })
export const addServiceAssignment = (data) => request.post('/api/assignment', data)
export const updateServiceAssignment = (data) => request.put('/api/assignment', data)
export const deleteServiceAssignment = (id) => request.delete(`/api/assignment/${id}`)
export const processServiceAssignment = (id) => request.put(`/api/assignment/process/${id}`)
export const finishServiceAssignment = (id) => request.put(`/api/assignment/finish/${id}`)

export const getCareServiceRecordPage = (params) => request.get('/api/service/page', { params })
export const addCareServiceRecord = (data) => request.post('/api/service', data)
export const updateCareServiceRecord = (data) => request.put('/api/service', data)
export const deleteCareServiceRecord = (id) => request.delete(`/api/service/${id}`)
export const processCareServiceRecord = (id) => request.put(`/api/service/process/${id}`)
export const finishCareServiceRecord = (id) => request.put(`/api/service/finish/${id}`)

export const getFamilyCommunicationPage = (params) => request.get('/api/communication/page', { params })
export const addFamilyCommunication = (data) => request.post('/api/communication', data)
export const updateFamilyCommunication = (data) => request.put('/api/communication', data)
export const deleteFamilyCommunication = (id) => request.delete(`/api/communication/${id}`)
export const processFamilyCommunication = (id) => request.put(`/api/communication/process/${id}`)
export const finishFamilyCommunication = (id) => request.put(`/api/communication/finish/${id}`)

export const getCareEvaluationPage = (params) => request.get('/api/evaluation/page', { params })
export const addCareEvaluation = (data) => request.post('/api/evaluation', data)
export const updateCareEvaluation = (data) => request.put('/api/evaluation', data)
export const deleteCareEvaluation = (id) => request.delete(`/api/evaluation/${id}`)
export const processCareEvaluation = (id) => request.put(`/api/evaluation/process/${id}`)
export const finishCareEvaluation = (id) => request.put(`/api/evaluation/finish/${id}`)

export const getSettlementRecordPage = (params) => request.get('/api/settlement/page', { params })
export const addSettlementRecord = (data) => request.post('/api/settlement', data)
export const updateSettlementRecord = (data) => request.put('/api/settlement', data)
export const deleteSettlementRecord = (id) => request.delete(`/api/settlement/${id}`)
export const processSettlementRecord = (id) => request.put(`/api/settlement/process/${id}`)
export const finishSettlementRecord = (id) => request.put(`/api/settlement/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
