DROP TABLE IF EXISTS operation_log;
DROP TABLE IF EXISTS order_appeal;
DROP TABLE IF EXISTS credit_record;
DROP TABLE IF EXISTS fault_report;
DROP TABLE IF EXISTS consumption_record;
DROP TABLE IF EXISTS recharge_record;
DROP TABLE IF EXISTS user_wallet;
DROP TABLE IF EXISTS rental_order;
DROP TABLE IF EXISTS bicycle;
DROP TABLE IF EXISTS station;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS system_config;

CREATE TABLE user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(50),
    phone VARCHAR(20),
    student_id VARCHAR(30),
    id_card VARCHAR(30),
    avatar VARCHAR(255),
    gender TINYINT DEFAULT 0,
    email VARCHAR(100),
    credit_score INT DEFAULT 100,
    status TINYINT DEFAULT 1,
    auth_status TINYINT DEFAULT 0,
    auth_image VARCHAR(255),
    deleted TINYINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(50),
    phone VARCHAR(20),
    avatar VARCHAR(255),
    role TINYINT DEFAULT 1,
    status TINYINT DEFAULT 1,
    deleted TINYINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE station (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_name VARCHAR(100) NOT NULL,
    address VARCHAR(255),
    longitude DECIMAL(10, 7),
    latitude DECIMAL(10, 7),
    capacity INT DEFAULT 50,
    current_count INT DEFAULT 0,
    status TINYINT DEFAULT 1,
    description VARCHAR(500),
    image VARCHAR(255),
    deleted TINYINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bicycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bike_no VARCHAR(30) NOT NULL UNIQUE,
    qr_code VARCHAR(255),
    bike_type TINYINT DEFAULT 1,
    status TINYINT DEFAULT 0,
    station_id BIGINT,
    longitude DECIMAL(10, 7),
    latitude DECIMAL(10, 7),
    total_mileage DECIMAL(10, 2) DEFAULT 0.00,
    total_orders INT DEFAULT 0,
    last_maintenance TIMESTAMP,
    purchase_date DATE,
    deleted TINYINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rental_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    bike_id BIGINT NOT NULL,
    start_station_id BIGINT,
    end_station_id BIGINT,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    duration INT DEFAULT 0,
    distance DECIMAL(10, 2) DEFAULT 0.00,
    amount DECIMAL(10, 2) DEFAULT 0.00,
    status TINYINT DEFAULT 0,
    pay_status TINYINT DEFAULT 0,
    return_photo VARCHAR(255),
    remark VARCHAR(500),
    deleted TINYINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_wallet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    balance DECIMAL(10, 2) DEFAULT 0.00,
    deposit DECIMAL(10, 2) DEFAULT 0.00,
    deposit_status TINYINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recharge_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    type TINYINT DEFAULT 1,
    pay_method TINYINT DEFAULT 1,
    status TINYINT DEFAULT 1,
    transaction_no VARCHAR(50),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE consumption_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_id BIGINT,
    amount DECIMAL(10, 2) NOT NULL,
    type TINYINT DEFAULT 1,
    balance_after DECIMAL(10, 2),
    description VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fault_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bike_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    fault_type TINYINT NOT NULL,
    description VARCHAR(500),
    images VARCHAR(1000),
    status TINYINT DEFAULT 0,
    handler_id BIGINT,
    handle_time TIMESTAMP,
    handle_result VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE credit_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    change_value INT NOT NULL,
    change_type TINYINT NOT NULL,
    reason VARCHAR(255),
    order_id BIGINT,
    score_after INT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_appeal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    appeal_type TINYINT DEFAULT 1,
    content VARCHAR(500) NOT NULL,
    images VARCHAR(1000),
    status TINYINT DEFAULT 0,
    handler_id BIGINT,
    handle_time TIMESTAMP,
    handle_result VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE system_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL UNIQUE,
    config_value VARCHAR(500),
    description VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT,
    admin_name VARCHAR(50),
    module VARCHAR(50),
    operation VARCHAR(100),
    method VARCHAR(200),
    params CLOB,
    ip VARCHAR(50),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_phone ON user (phone);
CREATE INDEX idx_user_student_id ON user (student_id);
CREATE INDEX idx_station_status ON station (status);
CREATE INDEX idx_bicycle_station ON bicycle (station_id);
CREATE INDEX idx_bicycle_status ON bicycle (status);
CREATE INDEX idx_rental_order_user ON rental_order (user_id);
CREATE INDEX idx_rental_order_bike ON rental_order (bike_id);
CREATE INDEX idx_rental_order_status ON rental_order (status);
CREATE INDEX idx_recharge_record_user ON recharge_record (user_id);
CREATE INDEX idx_consumption_record_user ON consumption_record (user_id);
CREATE INDEX idx_fault_report_user ON fault_report (user_id);
CREATE INDEX idx_fault_report_bike ON fault_report (bike_id);
CREATE INDEX idx_fault_report_status ON fault_report (status);
CREATE INDEX idx_credit_record_user ON credit_record (user_id);
CREATE INDEX idx_order_appeal_user ON order_appeal (user_id);
CREATE INDEX idx_operation_log_admin ON operation_log (admin_id);
