import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getPetOwnerPage = (params) => request.get('/api/owner/page', { params })
export const addPetOwner = (data) => request.post('/api/owner', data)
export const updatePetOwner = (data) => request.put('/api/owner', data)
export const deletePetOwner = (id) => request.delete(`/api/owner/${id}`)
export const processPetOwner = (id) => request.put(`/api/owner/process/${id}`)
export const finishPetOwner = (id) => request.put(`/api/owner/finish/${id}`)

export const getPetProfilePage = (params) => request.get('/api/pet/page', { params })
export const addPetProfile = (data) => request.post('/api/pet', data)
export const updatePetProfile = (data) => request.put('/api/pet', data)
export const deletePetProfile = (id) => request.delete(`/api/pet/${id}`)
export const processPetProfile = (id) => request.put(`/api/pet/process/${id}`)
export const finishPetProfile = (id) => request.put(`/api/pet/finish/${id}`)

export const getDoctorProfilePage = (params) => request.get('/api/doctor/page', { params })
export const addDoctorProfile = (data) => request.post('/api/doctor', data)
export const updateDoctorProfile = (data) => request.put('/api/doctor', data)
export const deleteDoctorProfile = (id) => request.delete(`/api/doctor/${id}`)
export const processDoctorProfile = (id) => request.put(`/api/doctor/process/${id}`)
export const finishDoctorProfile = (id) => request.put(`/api/doctor/finish/${id}`)

export const getClinicSchedulePage = (params) => request.get('/api/schedule/page', { params })
export const addClinicSchedule = (data) => request.post('/api/schedule', data)
export const updateClinicSchedule = (data) => request.put('/api/schedule', data)
export const deleteClinicSchedule = (id) => request.delete(`/api/schedule/${id}`)
export const processClinicSchedule = (id) => request.put(`/api/schedule/process/${id}`)
export const finishClinicSchedule = (id) => request.put(`/api/schedule/finish/${id}`)

export const getVisitAppointmentPage = (params) => request.get('/api/appointment/page', { params })
export const addVisitAppointment = (data) => request.post('/api/appointment', data)
export const updateVisitAppointment = (data) => request.put('/api/appointment', data)
export const deleteVisitAppointment = (id) => request.delete(`/api/appointment/${id}`)
export const processVisitAppointment = (id) => request.put(`/api/appointment/process/${id}`)
export const finishVisitAppointment = (id) => request.put(`/api/appointment/finish/${id}`)

export const getVisitRecordPage = (params) => request.get('/api/visit/page', { params })
export const addVisitRecord = (data) => request.post('/api/visit', data)
export const updateVisitRecord = (data) => request.put('/api/visit', data)
export const deleteVisitRecord = (id) => request.delete(`/api/visit/${id}`)
export const processVisitRecord = (id) => request.put(`/api/visit/process/${id}`)
export const finishVisitRecord = (id) => request.put(`/api/visit/finish/${id}`)

export const getVaccinePlanPage = (params) => request.get('/api/vaccine-plan/page', { params })
export const addVaccinePlan = (data) => request.post('/api/vaccine-plan', data)
export const updateVaccinePlan = (data) => request.put('/api/vaccine-plan', data)
export const deleteVaccinePlan = (id) => request.delete(`/api/vaccine-plan/${id}`)
export const processVaccinePlan = (id) => request.put(`/api/vaccine-plan/process/${id}`)
export const finishVaccinePlan = (id) => request.put(`/api/vaccine-plan/finish/${id}`)

export const getVaccineRecordPage = (params) => request.get('/api/vaccine-record/page', { params })
export const addVaccineRecord = (data) => request.post('/api/vaccine-record', data)
export const updateVaccineRecord = (data) => request.put('/api/vaccine-record', data)
export const deleteVaccineRecord = (id) => request.delete(`/api/vaccine-record/${id}`)
export const processVaccineRecord = (id) => request.put(`/api/vaccine-record/process/${id}`)
export const finishVaccineRecord = (id) => request.put(`/api/vaccine-record/finish/${id}`)

export const getFollowUpRecordPage = (params) => request.get('/api/follow-up/page', { params })
export const addFollowUpRecord = (data) => request.post('/api/follow-up', data)
export const updateFollowUpRecord = (data) => request.put('/api/follow-up', data)
export const deleteFollowUpRecord = (id) => request.delete(`/api/follow-up/${id}`)
export const processFollowUpRecord = (id) => request.put(`/api/follow-up/process/${id}`)
export const finishFollowUpRecord = (id) => request.put(`/api/follow-up/finish/${id}`)

export const getMedicineStockPage = (params) => request.get('/api/medicine/page', { params })
export const addMedicineStock = (data) => request.post('/api/medicine', data)
export const updateMedicineStock = (data) => request.put('/api/medicine', data)
export const deleteMedicineStock = (id) => request.delete(`/api/medicine/${id}`)
export const processMedicineStock = (id) => request.put(`/api/medicine/process/${id}`)
export const finishMedicineStock = (id) => request.put(`/api/medicine/finish/${id}`)

export const getBillingRecordPage = (params) => request.get('/api/billing/page', { params })
export const addBillingRecord = (data) => request.post('/api/billing', data)
export const updateBillingRecord = (data) => request.put('/api/billing', data)
export const deleteBillingRecord = (id) => request.delete(`/api/billing/${id}`)
export const processBillingRecord = (id) => request.put(`/api/billing/process/${id}`)
export const finishBillingRecord = (id) => request.put(`/api/billing/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
