import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getMerchantInfoPage = (params) => request.get('/api/merchant/page', { params })
export const addMerchantInfo = (data) => request.post('/api/merchant', data)
export const updateMerchantInfo = (data) => request.put('/api/merchant', data)
export const deleteMerchantInfo = (id) => request.delete(`/api/merchant/${id}`)
export const approveMerchantInfo = (id) => request.put(`/api/merchant/approve/${id}`)
export const suspendMerchantInfo = (id) => request.put(`/api/merchant/suspend/${id}`)
export const getStoreBranchPage = (params) => request.get('/api/store/page', { params })
export const addStoreBranch = (data) => request.post('/api/store', data)
export const updateStoreBranch = (data) => request.put('/api/store', data)
export const deleteStoreBranch = (id) => request.delete(`/api/store/${id}`)
export const openStoreBranch = (id) => request.put(`/api/store/open/${id}`)
export const closeStoreBranch = (id) => request.put(`/api/store/close/${id}`)
export const getConsumerProfilePage = (params) => request.get('/api/consumer/page', { params })
export const addConsumerProfile = (data) => request.post('/api/consumer', data)
export const updateConsumerProfile = (data) => request.put('/api/consumer', data)
export const deleteConsumerProfile = (id) => request.delete(`/api/consumer/${id}`)
export const activateConsumerProfile = (id) => request.put(`/api/consumer/activate/${id}`)
export const freezeConsumerProfile = (id) => request.put(`/api/consumer/freeze/${id}`)
export const getCouponTemplatePage = (params) => request.get('/api/template/page', { params })
export const addCouponTemplate = (data) => request.post('/api/template', data)
export const updateCouponTemplate = (data) => request.put('/api/template', data)
export const deleteCouponTemplate = (id) => request.delete(`/api/template/${id}`)
export const publishCouponTemplate = (id) => request.put(`/api/template/publish/${id}`)
export const offlineCouponTemplate = (id) => request.put(`/api/template/offline/${id}`)
export const getCouponActivityPage = (params) => request.get('/api/activity/page', { params })
export const addCouponActivity = (data) => request.post('/api/activity', data)
export const updateCouponActivity = (data) => request.put('/api/activity', data)
export const deleteCouponActivity = (id) => request.delete(`/api/activity/${id}`)
export const startCouponActivity = (id) => request.put(`/api/activity/start/${id}`)
export const pauseCouponActivity = (id) => request.put(`/api/activity/pause/${id}`)
export const finishCouponActivity = (id) => request.put(`/api/activity/finish/${id}`)
export const getUserCouponPage = (params) => request.get('/api/coupon/page', { params })
export const addUserCoupon = (data) => request.post('/api/coupon', data)
export const updateUserCoupon = (data) => request.put('/api/coupon', data)
export const deleteUserCoupon = (id) => request.delete(`/api/coupon/${id}`)
export const lockUserCoupon = (id) => request.put(`/api/coupon/lock/${id}`)
export const useUserCoupon = (id) => request.put(`/api/coupon/use/${id}`)
export const expireUserCoupon = (id) => request.put(`/api/coupon/expire/${id}`)
export const getVerificationRecordPage = (params) => request.get('/api/verification/page', { params })
export const addVerificationRecord = (data) => request.post('/api/verification', data)
export const updateVerificationRecord = (data) => request.put('/api/verification', data)
export const deleteVerificationRecord = (id) => request.delete(`/api/verification/${id}`)
export const confirmVerificationRecord = (id) => request.put(`/api/verification/confirm/${id}`)
export const revokeVerificationRecord = (id) => request.put(`/api/verification/revoke/${id}`)
export const getMerchantSettlementPage = (params) => request.get('/api/settlement/page', { params })
export const addMerchantSettlement = (data) => request.post('/api/settlement', data)
export const updateMerchantSettlement = (data) => request.put('/api/settlement', data)
export const deleteMerchantSettlement = (id) => request.delete(`/api/settlement/${id}`)
export const calculateMerchantSettlement = (id) => request.put(`/api/settlement/calculate/${id}`)
export const settleMerchantSettlement = (id) => request.put(`/api/settlement/settle/${id}`)
export const getSettlementDetailPage = (params) => request.get('/api/detail/page', { params })
export const addSettlementDetail = (data) => request.post('/api/detail', data)
export const updateSettlementDetail = (data) => request.put('/api/detail', data)
export const deleteSettlementDetail = (id) => request.delete(`/api/detail/${id}`)
export const confirmSettlementDetail = (id) => request.put(`/api/detail/confirm/${id}`)
export const adjustSettlementDetail = (id) => request.put(`/api/detail/adjust/${id}`)
export const getPaymentTransferPage = (params) => request.get('/api/transfer/page', { params })
export const addPaymentTransfer = (data) => request.post('/api/transfer', data)
export const updatePaymentTransfer = (data) => request.put('/api/transfer', data)
export const deletePaymentTransfer = (id) => request.delete(`/api/transfer/${id}`)
export const submitPaymentTransfer = (id) => request.put(`/api/transfer/submit/${id}`)
export const successPaymentTransfer = (id) => request.put(`/api/transfer/success/${id}`)
export const failPaymentTransfer = (id) => request.put(`/api/transfer/fail/${id}`)
export const getComplaintTicketPage = (params) => request.get('/api/complaint/page', { params })
export const addComplaintTicket = (data) => request.post('/api/complaint', data)
export const updateComplaintTicket = (data) => request.put('/api/complaint', data)
export const deleteComplaintTicket = (id) => request.delete(`/api/complaint/${id}`)
export const assignComplaintTicket = (id) => request.put(`/api/complaint/assign/${id}`)
export const resolveComplaintTicket = (id) => request.put(`/api/complaint/resolve/${id}`)
export const closeComplaintTicket = (id) => request.put(`/api/complaint/close/${id}`)
export const getActivityStatRecordPage = (params) => request.get('/api/statRecord/page', { params })
export const addActivityStatRecord = (data) => request.post('/api/statRecord', data)
export const updateActivityStatRecord = (data) => request.put('/api/statRecord', data)
export const deleteActivityStatRecord = (id) => request.delete(`/api/statRecord/${id}`)
export const publishActivityStatRecord = (id) => request.put(`/api/statRecord/publish/${id}`)
export const archiveActivityStatRecord = (id) => request.put(`/api/statRecord/archive/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
