import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getParkingLotPage = (params) => request.get('/api/lot/page', { params })
export const addParkingLot = (data) => request.post('/api/lot', data)
export const updateParkingLot = (data) => request.put('/api/lot', data)
export const deleteParkingLot = (id) => request.delete(`/api/lot/${id}`)
export const processParkingLot = (id) => request.put(`/api/lot/process/${id}`)
export const finishParkingLot = (id) => request.put(`/api/lot/finish/${id}`)

export const getParkingSpacePage = (params) => request.get('/api/space/page', { params })
export const addParkingSpace = (data) => request.post('/api/space', data)
export const updateParkingSpace = (data) => request.put('/api/space', data)
export const deleteParkingSpace = (id) => request.delete(`/api/space/${id}`)
export const processParkingSpace = (id) => request.put(`/api/space/process/${id}`)
export const finishParkingSpace = (id) => request.put(`/api/space/finish/${id}`)

export const getTenantProfilePage = (params) => request.get('/api/tenant/page', { params })
export const addTenantProfile = (data) => request.post('/api/tenant', data)
export const updateTenantProfile = (data) => request.put('/api/tenant', data)
export const deleteTenantProfile = (id) => request.delete(`/api/tenant/${id}`)
export const processTenantProfile = (id) => request.put(`/api/tenant/process/${id}`)
export const finishTenantProfile = (id) => request.put(`/api/tenant/finish/${id}`)

export const getLeaseContractPage = (params) => request.get('/api/contract/page', { params })
export const addLeaseContract = (data) => request.post('/api/contract', data)
export const updateLeaseContract = (data) => request.put('/api/contract', data)
export const deleteLeaseContract = (id) => request.delete(`/api/contract/${id}`)
export const processLeaseContract = (id) => request.put(`/api/contract/process/${id}`)
export const finishLeaseContract = (id) => request.put(`/api/contract/finish/${id}`)

export const getRenewalReminderPage = (params) => request.get('/api/reminder/page', { params })
export const addRenewalReminder = (data) => request.post('/api/reminder', data)
export const updateRenewalReminder = (data) => request.put('/api/reminder', data)
export const deleteRenewalReminder = (id) => request.delete(`/api/reminder/${id}`)
export const processRenewalReminder = (id) => request.put(`/api/reminder/process/${id}`)
export const finishRenewalReminder = (id) => request.put(`/api/reminder/finish/${id}`)

export const getRenewalPaymentPage = (params) => request.get('/api/payment/page', { params })
export const addRenewalPayment = (data) => request.post('/api/payment', data)
export const updateRenewalPayment = (data) => request.put('/api/payment', data)
export const deleteRenewalPayment = (id) => request.delete(`/api/payment/${id}`)
export const processRenewalPayment = (id) => request.put(`/api/payment/process/${id}`)
export const finishRenewalPayment = (id) => request.put(`/api/payment/finish/${id}`)

export const getVehicleBindPage = (params) => request.get('/api/vehicle/page', { params })
export const addVehicleBind = (data) => request.post('/api/vehicle', data)
export const updateVehicleBind = (data) => request.put('/api/vehicle', data)
export const deleteVehicleBind = (id) => request.delete(`/api/vehicle/${id}`)
export const processVehicleBind = (id) => request.put(`/api/vehicle/process/${id}`)
export const finishVehicleBind = (id) => request.put(`/api/vehicle/finish/${id}`)

export const getOccupancyCheckPage = (params) => request.get('/api/check/page', { params })
export const addOccupancyCheck = (data) => request.post('/api/check', data)
export const updateOccupancyCheck = (data) => request.put('/api/check', data)
export const deleteOccupancyCheck = (id) => request.delete(`/api/check/${id}`)
export const processOccupancyCheck = (id) => request.put(`/api/check/process/${id}`)
export const finishOccupancyCheck = (id) => request.put(`/api/check/finish/${id}`)

export const getAbnormalOccupancyPage = (params) => request.get('/api/abnormal/page', { params })
export const addAbnormalOccupancy = (data) => request.post('/api/abnormal', data)
export const updateAbnormalOccupancy = (data) => request.put('/api/abnormal', data)
export const deleteAbnormalOccupancy = (id) => request.delete(`/api/abnormal/${id}`)
export const processAbnormalOccupancy = (id) => request.put(`/api/abnormal/process/${id}`)
export const finishAbnormalOccupancy = (id) => request.put(`/api/abnormal/finish/${id}`)

export const getViolationHandlingPage = (params) => request.get('/api/handling/page', { params })
export const addViolationHandling = (data) => request.post('/api/handling', data)
export const updateViolationHandling = (data) => request.put('/api/handling', data)
export const deleteViolationHandling = (id) => request.delete(`/api/handling/${id}`)
export const processViolationHandling = (id) => request.put(`/api/handling/process/${id}`)
export const finishViolationHandling = (id) => request.put(`/api/handling/finish/${id}`)

export const getServiceTicketPage = (params) => request.get('/api/ticket/page', { params })
export const addServiceTicket = (data) => request.post('/api/ticket', data)
export const updateServiceTicket = (data) => request.put('/api/ticket', data)
export const deleteServiceTicket = (id) => request.delete(`/api/ticket/${id}`)
export const processServiceTicket = (id) => request.put(`/api/ticket/process/${id}`)
export const finishServiceTicket = (id) => request.put(`/api/ticket/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
