spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parking_management?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

file:
  upload-dir: D:/upload/parking
  access-url: http://localhost:8040/files
