DROP TABLE IF EXISTS chapters;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT NOT NULL AUTO_INCREMENT,
  open_id VARCHAR(100),
  union_id VARCHAR(100),
  nickname VARCHAR(50) NOT NULL,
  avatar VARCHAR(255),
  phone VARCHAR(20),
  email VARCHAR(100),
  role VARCHAR(20) NOT NULL DEFAULT 'USER',
  status VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  score INT NOT NULL DEFAULT 0,
  level INT NOT NULL DEFAULT 1,
  bio VARCHAR(500),
  last_login_time DATETIME,
  last_login_ip VARCHAR(50),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_open_id (open_id),
  UNIQUE KEY uk_phone (phone)
);

CREATE TABLE courses (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  cover VARCHAR(255),
  description CLOB,
  category VARCHAR(50) NOT NULL,
  level VARCHAR(20) NOT NULL DEFAULT 'BEGINNER',
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  teacher_id BIGINT NOT NULL,
  teacher_name VARCHAR(50) NOT NULL,
  student_count INT NOT NULL DEFAULT 0,
  chapter_count INT NOT NULL DEFAULT 0,
  duration INT NOT NULL DEFAULT 0,
  view_count INT NOT NULL DEFAULT 0,
  like_count INT NOT NULL DEFAULT 0,
  favorite_count INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE chapters (
  id BIGINT NOT NULL AUTO_INCREMENT,
  course_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  content CLOB,
  duration INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  is_free BOOLEAN NOT NULL DEFAULT FALSE,
  view_count INT NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
