import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')

export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)

export const getWorkshopProfilePage = (params) => request.get('/api/workshop/page', { params })
export const addWorkshopProfile = (data) => request.post('/api/workshop', data)
export const updateWorkshopProfile = (data) => request.put('/api/workshop', data)
export const deleteWorkshopProfile = (id) => request.delete(`/api/workshop/${id}`)
export const processWorkshopProfile = (id) => request.put(`/api/workshop/process/${id}`)
export const finishWorkshopProfile = (id) => request.put(`/api/workshop/finish/${id}`)

export const getInheritorProfilePage = (params) => request.get('/api/inheritor/page', { params })
export const addInheritorProfile = (data) => request.post('/api/inheritor', data)
export const updateInheritorProfile = (data) => request.put('/api/inheritor', data)
export const deleteInheritorProfile = (id) => request.delete(`/api/inheritor/${id}`)
export const processInheritorProfile = (id) => request.put(`/api/inheritor/process/${id}`)
export const finishInheritorProfile = (id) => request.put(`/api/inheritor/finish/${id}`)

export const getCourseCatalogPage = (params) => request.get('/api/course/page', { params })
export const addCourseCatalog = (data) => request.post('/api/course', data)
export const updateCourseCatalog = (data) => request.put('/api/course', data)
export const deleteCourseCatalog = (id) => request.delete(`/api/course/${id}`)
export const processCourseCatalog = (id) => request.put(`/api/course/process/${id}`)
export const finishCourseCatalog = (id) => request.put(`/api/course/finish/${id}`)

export const getCourseSchedulePage = (params) => request.get('/api/schedule/page', { params })
export const addCourseSchedule = (data) => request.post('/api/schedule', data)
export const updateCourseSchedule = (data) => request.put('/api/schedule', data)
export const deleteCourseSchedule = (id) => request.delete(`/api/schedule/${id}`)
export const processCourseSchedule = (id) => request.put(`/api/schedule/process/${id}`)
export const finishCourseSchedule = (id) => request.put(`/api/schedule/finish/${id}`)

export const getCourseBookingPage = (params) => request.get('/api/booking/page', { params })
export const addCourseBooking = (data) => request.post('/api/booking', data)
export const updateCourseBooking = (data) => request.put('/api/booking', data)
export const deleteCourseBooking = (id) => request.delete(`/api/booking/${id}`)
export const processCourseBooking = (id) => request.put(`/api/booking/process/${id}`)
export const finishCourseBooking = (id) => request.put(`/api/booking/finish/${id}`)

export const getBookingReviewPage = (params) => request.get('/api/review/page', { params })
export const addBookingReview = (data) => request.post('/api/review', data)
export const updateBookingReview = (data) => request.put('/api/review', data)
export const deleteBookingReview = (id) => request.delete(`/api/review/${id}`)
export const processBookingReview = (id) => request.put(`/api/review/process/${id}`)
export const finishBookingReview = (id) => request.put(`/api/review/finish/${id}`)

export const getClassCheckinPage = (params) => request.get('/api/checkin/page', { params })
export const addClassCheckin = (data) => request.post('/api/checkin', data)
export const updateClassCheckin = (data) => request.put('/api/checkin', data)
export const deleteClassCheckin = (id) => request.delete(`/api/checkin/${id}`)
export const processClassCheckin = (id) => request.put(`/api/checkin/process/${id}`)
export const finishClassCheckin = (id) => request.put(`/api/checkin/finish/${id}`)

export const getArtworkCatalogPage = (params) => request.get('/api/artwork/page', { params })
export const addArtworkCatalog = (data) => request.post('/api/artwork', data)
export const updateArtworkCatalog = (data) => request.put('/api/artwork', data)
export const deleteArtworkCatalog = (id) => request.delete(`/api/artwork/${id}`)
export const processArtworkCatalog = (id) => request.put(`/api/artwork/process/${id}`)
export const finishArtworkCatalog = (id) => request.put(`/api/artwork/finish/${id}`)

export const getExhibitionShowcasePage = (params) => request.get('/api/showcase/page', { params })
export const addExhibitionShowcase = (data) => request.post('/api/showcase', data)
export const updateExhibitionShowcase = (data) => request.put('/api/showcase', data)
export const deleteExhibitionShowcase = (id) => request.delete(`/api/showcase/${id}`)
export const processExhibitionShowcase = (id) => request.put(`/api/showcase/process/${id}`)
export const finishExhibitionShowcase = (id) => request.put(`/api/showcase/finish/${id}`)

export const getProductOrderPage = (params) => request.get('/api/order/page', { params })
export const addProductOrder = (data) => request.post('/api/order', data)
export const updateProductOrder = (data) => request.put('/api/order', data)
export const deleteProductOrder = (id) => request.delete(`/api/order/${id}`)
export const processProductOrder = (id) => request.put(`/api/order/process/${id}`)
export const finishProductOrder = (id) => request.put(`/api/order/finish/${id}`)

export const getSalesSettlementPage = (params) => request.get('/api/settlement/page', { params })
export const addSalesSettlement = (data) => request.post('/api/settlement', data)
export const updateSalesSettlement = (data) => request.put('/api/settlement', data)
export const deleteSalesSettlement = (id) => request.delete(`/api/settlement/${id}`)
export const processSalesSettlement = (id) => request.put(`/api/settlement/process/${id}`)
export const finishSalesSettlement = (id) => request.put(`/api/settlement/finish/${id}`)

export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
export const processOperationLog = (id) => request.put(`/api/log/process/${id}`)
export const finishOperationLog = (id) => request.put(`/api/log/finish/${id}`)
