import request from './request'

export const login = (data) => request.post('/api/auth/login', data)
export const logout = () => request.post('/api/auth/logout')
export const getDashboard = () => request.get('/api/statistics/dashboard')
export const getSysUserPage = (params) => request.get('/api/user/page', { params })
export const addSysUser = (data) => request.post('/api/user', data)
export const updateSysUser = (data) => request.put('/api/user', data)
export const deleteSysUser = (id) => request.delete(`/api/user/${id}`)
export const enableSysUser = (id) => request.put(`/api/user/enable/${id}`)
export const disableSysUser = (id) => request.put(`/api/user/disable/${id}`)
export const getPondProfilePage = (params) => request.get('/api/pond/page', { params })
export const addPondProfile = (data) => request.post('/api/pond', data)
export const updatePondProfile = (data) => request.put('/api/pond', data)
export const deletePondProfile = (id) => request.delete(`/api/pond/${id}`)
export const activatePondProfile = (id) => request.put(`/api/pond/activate/${id}`)
export const finishPondProfile = (id) => request.put(`/api/pond/finish/${id}`)
export const getSensorDevicePage = (params) => request.get('/api/sensor/page', { params })
export const addSensorDevice = (data) => request.post('/api/sensor', data)
export const updateSensorDevice = (data) => request.put('/api/sensor', data)
export const deleteSensorDevice = (id) => request.delete(`/api/sensor/${id}`)
export const activateSensorDevice = (id) => request.put(`/api/sensor/activate/${id}`)
export const finishSensorDevice = (id) => request.put(`/api/sensor/finish/${id}`)
export const getWaterQualityReadingPage = (params) => request.get('/api/reading/page', { params })
export const addWaterQualityReading = (data) => request.post('/api/reading', data)
export const updateWaterQualityReading = (data) => request.put('/api/reading', data)
export const deleteWaterQualityReading = (id) => request.delete(`/api/reading/${id}`)
export const processWaterQualityReading = (id) => request.put(`/api/reading/process/${id}`)
export const finishWaterQualityReading = (id) => request.put(`/api/reading/finish/${id}`)
export const getFeedingPlanPage = (params) => request.get('/api/plan/page', { params })
export const addFeedingPlan = (data) => request.post('/api/plan', data)
export const updateFeedingPlan = (data) => request.put('/api/plan', data)
export const deleteFeedingPlan = (id) => request.delete(`/api/plan/${id}`)
export const activateFeedingPlan = (id) => request.put(`/api/plan/activate/${id}`)
export const finishFeedingPlan = (id) => request.put(`/api/plan/finish/${id}`)
export const getFeedingRecordPage = (params) => request.get('/api/feeding/page', { params })
export const addFeedingRecord = (data) => request.post('/api/feeding', data)
export const updateFeedingRecord = (data) => request.put('/api/feeding', data)
export const deleteFeedingRecord = (id) => request.delete(`/api/feeding/${id}`)
export const submitFeedingRecord = (id) => request.put(`/api/feeding/submit/${id}`)
export const approveFeedingRecord = (id) => request.put(`/api/feeding/approve/${id}`)
export const getFishBatchPage = (params) => request.get('/api/batch/page', { params })
export const addFishBatch = (data) => request.post('/api/batch', data)
export const updateFishBatch = (data) => request.put('/api/batch', data)
export const deleteFishBatch = (id) => request.delete(`/api/batch/${id}`)
export const activateFishBatch = (id) => request.put(`/api/batch/activate/${id}`)
export const finishFishBatch = (id) => request.put(`/api/batch/finish/${id}`)
export const getGrowthSamplingPage = (params) => request.get('/api/sampling/page', { params })
export const addGrowthSampling = (data) => request.post('/api/sampling', data)
export const updateGrowthSampling = (data) => request.put('/api/sampling', data)
export const deleteGrowthSampling = (id) => request.delete(`/api/sampling/${id}`)
export const submitGrowthSampling = (id) => request.put(`/api/sampling/submit/${id}`)
export const approveGrowthSampling = (id) => request.put(`/api/sampling/approve/${id}`)
export const getDiseaseWarningPage = (params) => request.get('/api/disease/page', { params })
export const addDiseaseWarning = (data) => request.post('/api/disease', data)
export const updateDiseaseWarning = (data) => request.put('/api/disease', data)
export const deleteDiseaseWarning = (id) => request.delete(`/api/disease/${id}`)
export const processDiseaseWarning = (id) => request.put(`/api/disease/process/${id}`)
export const finishDiseaseWarning = (id) => request.put(`/api/disease/finish/${id}`)
export const getMedicationRecordPage = (params) => request.get('/api/medication/page', { params })
export const addMedicationRecord = (data) => request.post('/api/medication', data)
export const updateMedicationRecord = (data) => request.put('/api/medication', data)
export const deleteMedicationRecord = (id) => request.delete(`/api/medication/${id}`)
export const submitMedicationRecord = (id) => request.put(`/api/medication/submit/${id}`)
export const approveMedicationRecord = (id) => request.put(`/api/medication/approve/${id}`)
export const getEquipmentDevicePage = (params) => request.get('/api/equipment/page', { params })
export const addEquipmentDevice = (data) => request.post('/api/equipment', data)
export const updateEquipmentDevice = (data) => request.put('/api/equipment', data)
export const deleteEquipmentDevice = (id) => request.delete(`/api/equipment/${id}`)
export const activateEquipmentDevice = (id) => request.put(`/api/equipment/activate/${id}`)
export const finishEquipmentDevice = (id) => request.put(`/api/equipment/finish/${id}`)
export const getWaterAlertRulePage = (params) => request.get('/api/rule/page', { params })
export const addWaterAlertRule = (data) => request.post('/api/rule', data)
export const updateWaterAlertRule = (data) => request.put('/api/rule', data)
export const deleteWaterAlertRule = (id) => request.delete(`/api/rule/${id}`)
export const activateWaterAlertRule = (id) => request.put(`/api/rule/activate/${id}`)
export const finishWaterAlertRule = (id) => request.put(`/api/rule/finish/${id}`)
export const getProductionStatisticPage = (params) => request.get('/api/statistic/page', { params })
export const addProductionStatistic = (data) => request.post('/api/statistic', data)
export const updateProductionStatistic = (data) => request.put('/api/statistic', data)
export const deleteProductionStatistic = (id) => request.delete(`/api/statistic/${id}`)
export const activateProductionStatistic = (id) => request.put(`/api/statistic/activate/${id}`)
export const finishProductionStatistic = (id) => request.put(`/api/statistic/finish/${id}`)
export const getOperationLogPage = (params) => request.get('/api/log/page', { params })
export const addOperationLog = (data) => request.post('/api/log', data)
export const updateOperationLog = (data) => request.put('/api/log', data)
export const deleteOperationLog = (id) => request.delete(`/api/log/${id}`)
